### ISSUE TITLE
Maximum of repeatable group is 29 ?

### ISSUE THREAD

**Issue by Aqsathemes** [CMB2/CMB2#1000]
I create a WordPress plugin, when i create more than 29 repeatable group fields, the plugin just saves 29 item (repeatable group) !!!!

**Comment by tw2113** [comment]
This may more of a server configuration limitation issue than a CMB2 issue.

http://diywpblog.com/how-to-increase-max-input-vars/

**Comment by Aqsathemes** [comment]
Thank you tw2113, i think you are right.
