### ISSUE TITLE
composer install inside plugin dir puts cmb2 in wp-content dir instead of vendor

### ISSUE THREAD

**Issue by sandrodz** [CMB2/CMB2#1004]
Consider following composer.json

```
{
    "name": "test",
    "require": {
        "webdevstudios/cmb2": "^2.2",
        "madcoda/php-youtube-api": "^1.2",
        "johnbillion/extended-cpts": "^3.2",
        "johnbillion/extended-taxos": "^2.0"
    }
}
```

Do this in an empty dir, do `composer install` few times. You will notice that `cmb2` is placed inside `wp-content` dir instead of `vendor`.

Notice composer.json files lives inside a plugin and not wp root dir. So this makes no sense.

<img width="653" alt="screen shot 2017-07-29 at 3 12 24 pm" src="https://user-images.githubusercontent.com/8479569/28744364-5ee914e4-7470-11e7-97bd-04d573717713.png">

**Comment by sandrodz** [comment]
I realized this was due to composer installers, fix was simple
<img width="1280" alt="screen shot 2017-08-19 at 2 23 10 pm" src="https://user-images.githubusercontent.com/8479569/29485824-fd50ff8c-84e9-11e7-9102-3d16cf450f4a.png">

**Comment by mostafasoufi** [comment]
I think is better use the library instead `wordpress-plugin` for composer type.
