### ISSUE TITLE
select_all_button => false not working for taxonomy multicheck

### ISSUE THREAD

**Issue by arkytn** [CMB2/CMB2#1005]
select_all_button => false not working for taxonomy multicheck. Reason is it needs a space added in front of the 'no-select-all. Otherwise the class concatenation runs together
Line 70 of \cmb2\includes\types\CMB2_Type_Taxonomy_Multicheck.php should be:

$classes .= ' no-select-all';

(space in front of no-select-all

**Comment by tw2113** [comment]
Can you provide the config code you're using for this, so we can confirm it's a legitimate bug or possibly something from the config only or the site in question. Thanks.

**Comment by arkytn** [comment]
Real simple 

$cmb->add_field( array(
	'name'     => $taxonomy->label,
	'id'       => "submitted_{$taxonomy->name}",
	'type'     => $taxonomy->hierarchical ? 'taxonomy_multicheck' : 'taxonomy_select' ,
	'select_all_button' => false,
	'taxonomy' => $taxonomy->name, // Taxonomy Slug
) );
Doesn't turn off the select all button.

If you look at the code  at line 67 of cmb2\includes\types\CMB2_Type_Taxonomy_Multicheck.php:

	protected function get_wrapper_classes() {
		$classes = 'cmb2-checkbox-list cmb2-list';
		if ( false === $this->field->args( 'select_all_button' ) ) {
			$classes .= 'no-select-all';
		}
		return $classes;
	}

You are concating 'cmb2-checkbox-list cmb2-list' with  'no-select-all' resulting in
 
'cmb2-checkbox-list cmb2-listno-select-all' 

which kills the meaning of both 'cmb2-list' and 'no-select-all'
You need to add the space so you get

'cmb2-checkbox-list cmb2-list no-select-all' 

which works properly.
Nothing to do with setting or sites.

**Comment by tw2113** [comment]
Can confirm this in trunk, it's not in the release version of the plugin yet.

**Comment by arkytn** [comment]
Thank you

**Comment by allysonsouza** [comment]
I'm having the same problem, CMB2 version 2.2.5.3

**Comment by jtsternberg** [comment]
Thank you for reporting @allysonsouza. Fixed in trunk and will be in the next release.
