### ISSUE TITLE
Missing wp_unslash() for money values

### ISSUE THREAD

**Issue by ocean90** [CMB2/CMB2#1014]
In Swiss German the thousand separator is an apostrophe so a money value can be `2'180.00`. But if it gets sanitized the value of `$this->value` is actually `2\'180.00` which breaks the replacements and you get `2.00`.

This seems to be introduced by c325d63aee8c36095c66564d56d24c40f96ccd99.

**Comment by jtsternberg** [comment]
Would you be able to add a test to supplement the [existing slashes test](https://github.com/CMB2/CMB2/blob/trunk/tests/test-cmb-field.php#L522-L543)?

**Comment by jtsternberg** [comment]
Can you provide your box/field config which causes this issue for you?

**Comment by jtsternberg** [comment]
Specifically wondering which object type this is registered for.

**Comment by jtsternberg** [comment]
Nevermind, got it sorted, and tests added. Thank you for the PR.

**Comment by ocean90** [comment]
@jtsternberg Any chance for another hotfix release, 2.2.5.3?

**Comment by jtsternberg** [comment]
@ocean90 done.
