### ISSUE TITLE
Setting First Day of Week to Date Picker

### ISSUE THREAD

**Issue by bitstarr** [CMB2/CMB2#1017]
For the date picker I wanted to set Monday the first day of the week, like it is common in most euoprean countries. There is documented option in CMB2 and as I investigated, I found out that the lib beeing used (https://github.com/trentrichardson/jQuery-Timepicker-Addon) doesn't support this.

I also noticed that the last commit to this lib was in April 2016, so it is kind of abandoned. 

I would suggest to refactor the pickers and use something like https://github.com/amsul/pickadate.js

Thanks.

**Comment by jtsternberg** [comment]
The timepicker addon only handles the timepicker. It is an addon to the jQuery datepicker and has nothing to do with the month view (including the first day of the week). There is almost no chance we will be changing the datepicker. Also, you can definitely change the start day. You can modify the datepicker attributes [as documented here](https://github.com/CMB2/CMB2/wiki/Field-Types#additional-field-options).

You would use the `firstDay` option:

```php
$cmb_demo->add_field( array(
	'name' => __( 'Test Date Picker', 'cmb2' ),
	'id'   => '_yourprefix_demo_textdate',
	'type' => 'text_date',
	'attributes' => array(
		'data-datepicker' => json_encode( array(
			'firstDay' => 1,
		) ),
	),
) );
```

**Comment by bitstarr** [comment]
@tw2113 I didn't notice the maintainer search, but yes this situation would be the same.

@jtsternberg Indeed I have mistaken the time picker script the date picker integration. After taking a deeper look I can understand not to change the date picker, because it uses the WP build in Jquery UI which is comfortable.

I wasn't awaiting a ``data-datepicker`` attribute because there is ``date_format``. Now I know better.

Nonetheless thanks for your help and the great work you do with this helpful plugin!
