### ISSUE TITLE
Tabbed navigation for options pages

### ISSUE THREAD

**Issue by MapSteps** [CMB2/CMB2#1022]
### Expected Behavior:
Hey guys,

I've seen you have updated the way we can create options pages that's great! Now, how can i still create tabs using the new method? 

https://github.com/CMB2/CMB2-Snippet-Library/blob/master/options-and-settings-pages/theme-options-cmb.php

Best,
David

**Comment by taunoha** [comment]
Maybe this plugin is helpfull: https://github.com/taunoha/cmb-theme-options-tabs

**Comment by MapSteps** [comment]
That looks great, thanks @taunoha!

Best,
David
