### ISSUE TITLE
Time 12:00 AM Doesn't Populate; Can't set 11:59 PM

### ISSUE THREAD

**Issue by lepittenger** [CMB2/CMB2#1027]
### Expected Behavior:
When setting the time on a time field, clicking "Done" should populate time to "12:00 AM". Manually setting the time at 11:59 PM should be allowed.
https://www.dropbox.com/s/9pr0l6lk8ldfzvu/Screenshot%202017-09-15%2012.36.33.png?dl=0

### Actual Behavior:
When clicking "Done" for setting the time to 12:00 AM, time field is not set at all and is blank. 
When setting time manually to 11:59 PM, the field sets it self to 11:00 PM.

### CMB2 Field Registration Code:

Just using a copy of the example-functions.php code from within the plugin.

**Comment by tw2113** [comment]
Not quite sure if this is going to be on the jQuery Datepicker side or the CMB2/PHP side, but both the hour and the minute options for "12" and "00" have values of string "0". Curious if it's getting evaluated to boolean false as a result.

**Comment by tw2113** [comment]
Alternatively, if you select anything else first, and then re-select the 12:00 combination, it works the 2nd time.

**Comment by jtsternberg** [comment]
For the manual setting of the timepicker to 11:59, you can override the default CMB2 `'stepMinute'` value (which is 5), by doing something like this:

```php
$cmb_demo->add_field( array(
	'name' => __( 'Test Time', 'cmb2' ),
	'desc' => __( 'field description (optional)', 'cmb2' ),
	'id'   => '_yourprefix_demo_time',
	'type' => 'text_time',
	'attributes' => array(
		'data-timepicker' => json_encode( array(
			'stepMinute' => 1,
		) ),
	),
) );
```

**Comment by jtsternberg** [comment]
Ok with https://github.com/CMB2/CMB2/commit/0b010a0a69777d94df310f0e02a348c8fac07c95, clicking "done" now will set the field to the default value.
