### ISSUE TITLE
if tag in cmb2_output_file_list

### ISSUE THREAD

**Issue by wptricks** [CMB2/CMB2#1028]
hi my friends

I can add a if `!empty` tag in the following function 
```php
function cmb2_output_file_list( $file_list_meta_key, $img_size = 'medium' ) {

	// Get the list of files
	$files = get_post_meta( get_the_ID(), $file_list_meta_key, 1 );

	echo '<div class="file-list-wrap">';
	// Loop through them and output an image
	foreach ( (array) $files as $attachment_id => $attachment_url ) {
		echo '<div class="file-list-image">';
		echo wp_get_attachment_image( $attachment_id, $img_size );
		echo '</div>';
	}
	echo '</div>';
}
```

**Comment by tw2113** [comment]
Closing for the time being until someone can provide some better context for this issue/support request.

**Comment by planetcappe** [comment]
I know it's a very old issue, but maybe someone else will find it useful.
`function cmb2_output_file_list( $file_list_meta_key, $img_size = 'medium' ) {

	// Get the list of files
	$files = get_post_meta( get_the_ID(), $file_list_meta_key, 1 );

	if (!empty($files)) {

	echo '<div class="file-list-wrap">';
	// Loop through them and output an image
	foreach ( (array) $files as $attachment_id => $attachment_url ) {
		echo '<div class="file-list-image">';
		echo wp_get_attachment_image( $attachment_id, $img_size );
		echo '</div>';
	}
	echo '</div>';
	}
}`
