### ISSUE TITLE
Radio Image Option not working: Images not appearing in the back-end to choose.

### ISSUE THREAD

**Issue by fastmarketo** [CMB2/CMB2#1029]
![2017-09-25 06_21_51-global - - filezilla](https://user-images.githubusercontent.com/6827222/30788444-f976b31a-a1b9-11e7-8f84-66aa57f715e6.png)
```
add_action( 'cmb2_admin_init', 'radio_template' );
function radio_template(){
    $cmb = new_cmb2_box( array(
		'id'            => $prefix . 'metabox',
		'title'         => __( 'Select The template for you Post Page', 'cmb2' ),
		'object_types'  => array( 'page', 'post' ), // Post type
		// 'show_on_cb' => 'yourprefix_show_if_front_page', // function should return a bool value
		// 'context'    => 'normal',
		// 'priority'   => 'high',
		// 'show_names' => true, // Show field names on the left
		// 'cmb_styles' => false, // false to disable the CMB stylesheet
		// 'closed'     => true, // true to keep the metabox closed by default
	) );

   $cmb->add_field( array(
    		'name'             => __( 'Select Template', 'cmb2' ),
    		'desc'             => __( 'field description (optional)', 'cmb2' ),
    		'id'               => $prefix . 'template_selector',
    		'type'             => 'radio_image',
    		'options'          => array(
    			'full-width'    => __('Full Width', 'cmb2'),
    			'sidebar-left'  => __('Left Sidebar', 'cmb2'),
    			'sidebar-right' => __('Right Sidebar', 'cmb2'),
    		),
    		'images_path'      => get_template_directory_uri(),
    		'images'           => array(
    			'full-width'    => 'images/full-width.png',
    			'sidebar-left'  => 'images/sidebar-left.png',
    			'sidebar-right' => 'images/sidebar-right.png',
    		)
    	) );
}
```
Images are not appearing in the backend. I have added just one image:     			'sidebar-right' => 'images/sidebar-right.png',
but that too is not coming in the backend.
![2017-09-25 06_20_12-edit post puck theme wordpress](https://user-images.githubusercontent.com/6827222/30788405-a5defb86-a1b9-11e7-84a8-8b3074a03324.png)

what is the cause?
![sidebar-right](https://user-images.githubusercontent.com/6827222/30788457-09f06006-a1ba-11e7-8e6f-7dda682c8aaa.png)

**Comment by tw2113** [comment]
Not familiar with a "radio_image" field type. Is it coming from some CMB2 extension you have installed? If yes, the GitHub/Support page for that extension would be the best place to go to. The only two radio field types that come with CMB2 core, are "radio" and "radio_inline"

**Comment by fastmarketo** [comment]
I have simple CMB2 plugin installed. I used this → https://github.com/satwinderrathore/CMB2-radio-image
![2017-09-25 06_50_20-plugins puck theme wordpress](https://user-images.githubusercontent.com/6827222/30788759-d6d2bdfa-a1bd-11e7-83f9-6a8abeae1bb8.png)

**Comment by tw2113** [comment]
You'll want to open up an issue over at https://github.com/satwinderrathore/CMB2-radio-image/issues or perhaps have @satwinderrathore step in here.

Closing this issue as it's not directly related to CMB2 core, but feel free for potential discussion beyond that.

**Comment by fastmarketo** [comment]
thanks. do you think that w/o using any extension we can achieve what I am trying to achieve? It is not easy to trust new extensions.

**Comment by tw2113** [comment]
I imagine you could, that type of effect is heavily CSS.

**Comment by fastmarketo** [comment]
sir, I have a humble request I hope you do not feel offended. As a plugin maker can you please include this feature in the (primary) plugin itself. I am distributing your plugin in a  commercial theme; that way it will look more professional if everything(all meta's) is coming via one plugin.

**Comment by satwinderrathore** [comment]
Please make sure you are using the proper template tag for path.

**Comment by fastmarketo** [comment]
this is the theme setup → https://www.screencast.com/t/A4iy5GYPZo and this the code →  Can you identify if I am going wrong anywhere→ https://www.screencast.com/t/wGdWbdCkfPdE?

**Comment by fastmarketo** [comment]
this is the image → 
![sidebar-right](https://user-images.githubusercontent.com/6827222/30793165-af501f64-a1dd-11e7-894b-e7b25b187528.png)

**Comment by satwinderrathore** [comment]
Your code is okay, Please make sure images exists in the folder and you are using the main theme(parent theme)

**Comment by fastmarketo** [comment]
I think everything is in place → https://www.screencast.com/t/kvXj3snq that's what is astonishing me a lot why things are not working; the only image is not appearing. https://www.screencast.com/t/k80OIpegC

**Comment by tw2113** [comment]
Just wanted to step in and say...it doesn't look like you have the Radio Image plugin installed at all. I just see CMB2 core. See the screenshot at https://github.com/CMB2/CMB2/issues/1029#issuecomment-331754577

**Comment by jtsternberg** [comment]
> can you please include this feature in the (primary) plugin itself

I'm not sure the issue, but this is fairly trivial to do. E.g.
```php
$cmb_demo->add_field( array(
	'name'    => __( 'Test Radio', 'cmb2' ),
	'desc'    => __( 'field description (optional)', 'cmb2' ),
	'id'      => '_yourprefix_demo_radio',
	'type'    => 'radio',
	'options' => array(
		'img1' => '<img src="http://via.placeholder.com/350x150/E8117F/ffffff?text=Image%201">',
		'img2' => '<img src="http://via.placeholder.com/350x150/f9a82f/ffffff?text=Image%202">',
		'img3' => '<img src="http://via.placeholder.com/350x150/49aed7/ffffff?text=Image%203">',
	),
) );
```

**Comment by fastmarketo** [comment]
Actually, the template selection through images is quite a common thing in today's premium theme. This feature should be included in the plugin in its entirety, including the CSS because as soon as we dive too much into customizing a plugin than the purpose of using a plugin is defied. Secondly, it will look just unprofessional in a premium/commercial theme to add extensions of a plugin, which itself is bundled with TMG. The sole idea of the discussion is to convey that this should be a useful feature already built-in the main plugin w/o requiring any CSS writing as in the case of the example suggested by you.

**Comment by bnecreative** [comment]
Hi, hope you don't mind me chiming in. I actually use cmb2 within my theme and also the radio image extension that @tw2113 referenced.

@fastmarketo, if CMB2 is a requirement of your theme, then you could just include it as a core file then add the extension on top of it like I have done. Or if you pref to have CMB2 be installed with TMG, you could instead include only the extension in your core theme and have it check if CMB2 exist before being used.

**Comment by tw2113** [comment]
Let's not delve into the topic of what plugins should do what and where sources.

@fastmarketo the biggest issue I saw, after looking things over a bit closer last night is that while CMB2 core plugin is installed and active, the Radio Images plugin is not. Until both are installed and active, you're not going to have a populated metabox. I copy/pasted your CMB2 code for the radio image box into a local install and images were showing for me, selectable, and everything. So the plugin pair is working, at least when properly paired up.

Once you get that detail taken care of and tested, we can work from there.

**Comment by fastmarketo** [comment]
I am now using this, but this is not simple HTML, but coming through code and dynamic array →

https://github.com/CMB2/CMB2/issues/1029#issuecomment-331876878

The solution to make it image selective lies here →
https://codepen.io/paulobrien/pen/xbJjs?editors=1010

But how to implement this in terms of CSS and specially structured HTML to render this all.

**Comment by tw2113** [comment]
If it's coming through as an array, then you'll want to do a foreach loop on that variable and output that way, instead of just trying to echo the variable holding the data.

**Comment by fastmarketo** [comment]
can you show me how with a sample sir?

**Comment by fastmarketo** [comment]
```
$cmb->add_field( array(
	'name'    => __( 'Image Radio', 'blewspaper' ),
	'desc'    => __( 'Use images for the radio button labels', 'text_domain' ),
	'id'      => '_yourprefix_demo_radio_images',
	'type'    => 'radio_inline',
	'options' => array(
		'img1' => '<img src="<?php echo get_template_directory_uri(); ?>/inc/admin/images/layout_one.png" alt="Image 1" title="Image 1">',
		'img2' => '<img src="<?php echo get_template_directory_uri(); ?>/inc/admin/images/layout_one.png" alt="Image 2" title="Image 2">',
		'img3' => '<img src="<?php echo get_template_directory_uri(); ?>/inc/admin/images/layout_one.png" alt="Image 3" title="Image 3">',
		'img1' => '<img src="<?php echo get_template_directory_uri(); ?>/inc/admin/images/layout_one.png" alt="Image 1" title="Image 1">',
		'img2' => '<img src="<?php echo get_template_directory_uri(); ?>/inc/admin/images/layout_one.png" alt="Image 2" title="Image 2">',
		'img3' => '<img src="<?php echo get_template_directory_uri(); ?>/inc/admin/images/layout_one.png" alt="Image 3" title="Image 3">',
		'img1' => '<img src="<?php echo get_template_directory_uri(); ?>/inc/admin/images/layout_one.png" alt="Image 1" title="Image 1">',
		'img2' => '<img src="<?php echo get_template_directory_uri(); ?>/inc/admin/images/layout_one.png" alt="Image 2" title="Image 2">',
		'img3' => '<img src="<?php echo get_template_directory_uri(); ?>/inc/admin/images/layout_one.png" alt="Image 3" title="Image 3">',
	),
) );
```

<?php echo get_template_directory_uri(); ?>/inc/admin/images/layout_one.png → Is this not the correct method to include images in the post backend page meta?

**Comment by tw2113** [comment]
I see nothing wrong with the method above, as long as the images are in that location and the generated url is complete and accurate

**Comment by Zaanmedia** [comment]
> I see nothing wrong with the method above, as long as the images are in that location and the generated url is complete and accurate.

'img1' => '<img src="<?php echo get_template_directory_uri(); ?>/inc/admin/images/layout_one.png" alt="Image 1" title="Image 1">',

Shouldn't it be something like this:

'img1' => '<img src="' . echo get_template_directory_uri(); . '/inc/admin/images/layout_one.png" alt="Image 1" title="Image 1">',

**Comment by tw2113** [comment]
i stand corrected :D but @Zaanmedia doesn't quite have it right either.

Try below:
```
$cmb->add_field( array(
	'name'    => __( 'Image Radio', 'text_domain' ),
	'desc'    => __( 'Use images for the radio button labels', 'text_domain' ),
	'id'      => '_yourprefix_demo_radio_images',
	'type'    => 'radio_inline',
	'options' => array(
		'img1' => '<img src="' . get_template_directory_uri() . '/inc/admin/images/layout_one.png" alt="Image 1" title="Image 1">',
		'img2' => '<img src="' . get_template_directory_uri() . '/inc/admin/images/layout_one.png" alt="Image 2" title="Image 2">',
		'img3' => '<img src="' . get_template_directory_uri() . '/inc/admin/images/layout_one.png" alt="Image 3" title="Image 3">',
		'img1' => '<img src="' . get_template_directory_uri() . '/inc/admin/images/layout_one.png" alt="Image 1" title="Image 1">',
		'img2' => '<img src="' . get_template_directory_uri() . '/inc/admin/images/layout_one.png" alt="Image 2" title="Image 2">',
		'img3' => '<img src="' . get_template_directory_uri() . '/inc/admin/images/layout_one.png" alt="Image 3" title="Image 3">',
		'img1' => '<img src="' . get_template_directory_uri() . '/inc/admin/images/layout_one.png" alt="Image 1" title="Image 1">',
		'img2' => '<img src="' . get_template_directory_uri() . '/inc/admin/images/layout_one.png" alt="Image 2" title="Image 2">',
		'img3' => '<img src="' . get_template_directory_uri() . '/inc/admin/images/layout_one.png" alt="Image 3" title="Image 3">',
	),
) );
```

**Comment by Zaanmedia** [comment]
@tw2113 was pretty close... 😂 but that looks more like it!

**Comment by fastmarketo** [comment]
Thanks.

**Comment by fastmarketo** [comment]
How to make one among these as the default layout?

**Comment by tw2113** [comment]
Don't know personally, that'd be a question more for @satwinderrathore at the moment

**Comment by fastmarketo** [comment]
I am not using his plugin I have styled it myself with the basis of CSS. I think it is a basic question related to meta.

**Comment by tw2113** [comment]
if you're rendering your own radio buttons and whatnot, you could see about using something like the WP `selected` function.

If you're using the radio field type, try setting a default like shown at https://github.com/CMB2/CMB2/wiki/Field-Types#radio_inline

**Comment by fastmarketo** [comment]
I am using this for selecting the layout. How should I pick the condition?

I mean →
If certain condition {echo class1;}

**Comment by tw2113** [comment]
That looks like it'd be good for conditionally showing classes for CSS purposes, but it doesn't do anything for filling in the form to be saved for the post saving process and resulting post meta data.

**Comment by fastmarketo** [comment]
I dont know what you are saying, but all these images are created and loaded in teh post meta. the user can select the post layout based on the image selected, but I need correct If condition for that.

**Comment by tw2113** [comment]
You need to make sure you're actually be saving a value for what they chose too.

From the looks of things, some sort of value should be getting saved to a meta key of `_yourprefix_demo_radio_images`

You can use `get_post_meta()` in your code, using the current post ID and that meta key knowledge to fetch what you currently have saved if anything, and determine which to highlight based on that returned value. Chances are high that what's going to get returned is the html for the selected image, based on what I'm seeing in previous code snippets.

**Comment by fastmarketo** [comment]
If we add this CSS then radio_inline option can be used for images also →

```
input.cmb2-option[type=radio]{
  position:absolute;
  left :-999em
}
input.cmb2-option[type=radio] + label img{
  border:2px solid transparent;
}
input.cmb2-option[type=radio]:checked + label img{
  border:2px solid #000000;
}

```
