### ISSUE TITLE
wysiwyg editor in group causes JS error

### ISSUE THREAD

**Issue by mclblock** [CMB2/CMB2#1031]
### Expected Behavior:
When a WYSIWYG editor is embedded in a repeatable-group field, it should just repeat and be available to the editor

### Actual Behavior:
The editor displays as a textarea and does not initialise sa a WYSIWYG editor. In the console, the following error appears:

```
cmb2-wysiwyg.js?ver=2.2.5.3:284 Uncaught TypeError: Cannot read property 'init' of undefined
    at Object.wysiwyg.init (cmb2-wysiwyg.js?ver=2.2.5.3:284)
    at HTMLTextAreaElement.<anonymous> (cmb2-wysiwyg.js?ver=2.2.5.3:144)
    at Function.each (jquery.js?ver=1.12.4:2)
    at jQuery.fn.init.each (jquery.js?ver=1.12.4:2)
    at HTMLDocument.wysiwyg.initAll (cmb2-wysiwyg.js?ver=2.2.5.3:134)
    at HTMLDocument.dispatch (jquery.js?ver=1.12.4:3)
    at HTMLDocument.r.handle (jquery.js?ver=1.12.4:3)
    at Object.trigger (jquery.js?ver=1.12.4:3)
    at Object.jQuery.event.trigger (jquery-migrate.js?ver=1.4.1:633)
    at HTMLDocument.<anonymous> (jquery.js?ver=1.12.4:3)
```
I am using CMB2 as a PHP include and I'm on version 2.2.5.3

### Steps to reproduce:

1. Create a new Metabox
2.Add a repeatable group to all pages
3. Add a WYSIWYG editor into the group.
4. Go onto a page and look at the meta box
5. observe the WYSIWYG not initialising.

### CMB2 Field Registration Code:

```php

namespace com\company\wordpress;


add_action('cmb2_admin_init', 'com\company\wordpress\custom_meta_box');
function custom_meta_box()
{
    $prefix = 'wp_custom_metabox';

    $cmb = new_cmb2_box(array(
        'id' => $prefix . 'metabox',
        'title' => esc_html__('CMB2 WYSIWYG issue', 'cmb2'),
        'object_types' => array('page'), // Post type
        'context' => 'normal',
        'priority' => 'high',
        'show_names' => true, // Show field names on the left
    ));

    $cmb_group = $cmb->add_field(array(
        'id' => $prefix . 'group',
        'type' => 'group',
        'description' => __('Generates reusable form entries', 'cmb2'),
        // 'repeatable'  => false, // use false if you want non-repeatable group
        'options' => array(
            'group_title' => __('Entry {#}', 'cmb2'), // since version 1.1.4, {#} gets replaced by row number
            'add_button' => __('Add Another Entry', 'cmb2'),
            'remove_button' => __('Remove Entry', 'cmb2'),
            'sortable' => true, // beta
        ),
    ));

    $cmb->add_group_field($cmb_group, array(
        'name' => esc_html__('Title', 'cmb2'),
        'id' => 'title',
        'type' => 'wysiwyg',
    ));

}```

**Comment by tw2113** [comment]
One thing I want to point out is that WYSIWYG field types are denoted as not available as repeatable fields, as shown at https://github.com/CMB2/CMB2/wiki/Field-Types. Likely for reasons like this.

**Comment by jtsternberg** [comment]
@tw2113 `wysiwyg` field types will not work with the `repeatable` flag, but they should work fine in a repeatable group.

**Comment by jtsternberg** [comment]
@mclblock are you trying to use on a post-type that does not have `editor` in the `supports` array? It's possible that is the cause of the problem.

**Comment by tw2113** [comment]
Noted on the clarification, thanks Justin

**Comment by mclblock** [comment]
Thanks @tw2113 and @jtsternberg  for the information. Just confirming that I am using wysiwyg in a repeatable group and that I'm not using the `repeatable` flag. It looks like the "Disable the visual editor when writing" option was enabled which in turn caused an error in the tinyMCE initialisation.  I've re-enabled the visual editor and this has brought back the WYSIWYG in the repeatable group.
Is there a way to avoid the JS error so that other scripts can execute correctly?

**Comment by jtsternberg** [comment]
I'm still not able to replicate the issue. Can you test after disabling other plugins?

**Comment by jtsternberg** [comment]
I lied. Pushing up a fix shortly.

**Comment by Scorpio256** [comment]
Hi I have same error. To replicate it all you need to do is move block more than once.
