### ISSUE TITLE
Number field type default value

### ISSUE THREAD

**Issue by chrisdrake** [CMB2/CMB2#1032]
Hi Justin,

Another quick problem for you here. I've added a number field as follows:

```
$cmb_options->add_field( array(
	'name'				=> __( 'Booking Duration', 'srpt' ),
	'desc'				=> __( 'The minimum duration of a booking in days.', 'srpt' ),
	'id'				=> 'booking_duration',
	'type'				=> 'text_small',
	'default'			=> '1',
	'attributes'		=> array(
		'type'				=> 'number',
		'pattern'			=> '\d*',
		'min'				=> '1',
	),
) );
```

My problem is that it does not respect the default value of '1' and instead shows '0'. Is there any way around this?

Thanks!

**Comment by tw2113** [comment]
"0" and "1" are hard values to use for this type of thing because they can tend to be used in conjunction with boolean true/false. Just a quick thought for the moment.

**Comment by jtsternberg** [comment]
I copy/pasted your code, and I see `1` as the default value:
![](http://b.ustin.co/RpJhPy+)

**Comment by chrisdrake** [comment]
Hmm, strange.

I should add that I'm using CMB2 for an options page, as described at https://github.com/CMB2/CMB2-Snippet-Library/blob/master/options-and-settings-pages/theme-options-cmb.php

**Comment by chrisdrake** [comment]
I have found my problem. It's my own fault. I have an escape_cb filter which was causing the issue.

Thanks, and sorry for wasting your time.
