### ISSUE TITLE
Change the display of group of fields

### ISSUE THREAD

**Issue by bomsn** [CMB2/CMB2#1033]
Hi guys, is there anyway to change the display of repeatable group of fields to look something like this
https://i.imgur.com/6DUnlao.png

as it may make the page really long if you have a big number of group fields with many fields in them, which is not good UX.

It would be great if you can show me where I can start to make this possible.

**Comment by jtsternberg** [comment]
Sorry that is a custom/display/implementation question, and is not suited for a Github issue. I suggest going to Stackoverflow or WordPress stack exchange.
