### ISSUE TITLE
How to add theme options

### ISSUE THREAD

**Issue by bitstarr** [CMB2/CMB2#1037]
Normally i use ``add_options_page()`` and ``add_settings_section()``/``add_settings_field``. But i need to add a repeatable group to a theme/custom options page in WP-Admin.

I was trying to use https://github.com/CMB2/CMB2-Snippet-Library/blob/master/options-and-settings-pages/theme-options-cmb.php but i absolutely don't know how?!

There is no documentation but this kind of a bad joke:
https://github.com/CMB2/CMB2/wiki/Using-CMB-to-create-an-Admin-Theme-Options-Page

Nothing happens using the snippet. Is there a trick, or some undocumented function i have to call on any point, or do i need another plugin?

OR: is there simply no possibility to use CMB2 for my idea? So i can free up my time for looking for other solutions.

Hope there will be an answer...

**Comment by tw2113** [comment]
Hey @bitstarr Can you provide the exact code you're using for your attempts? I know you point to example snippets, but I am hoping to debug what you've actually used thus far.

Not having any issues yet for an options page and repeatable fields:
https://cloudup.com/cl0o4PB5gRS

**Comment by bitstarr** [comment]
@tw2113 I'm using CMB2 as plugin. Also there is no theme framework or something else.
I simply added https://github.com/CMB2/CMB2-Snippet-Library/blob/master/options-and-settings-pages/theme-options-cmb.php to my theme and required it. What else do I have to do?

BTW nice styling in the screenshot.

**Comment by tw2113** [comment]
How you're using CMB2 the library isn't a huge deal, all that matters is that your configuration is loaded at some point, and the rest will be taken care of. I've often set up my config in a mu-plugin file, but it can also be run from your theme's functions.php file or a standard activate-able plugin.

As you say above, you saved the example file and loaded it. All that would be left is marking what fields you want to be, as being repeatable. The styling is default with the latest release of CMB2.

**Comment by bitstarr** [comment]
Now it works. Maybe i forgot acivating CMB2 or something last time. I was in a hurry when trying the first time :(

Thanks for your kind help and patience!

**Comment by tw2113** [comment]
Welcome, and have a good rest of your day.
