### ISSUE TITLE
wysiwyg - wp is not defined

### ISSUE THREAD

**Issue by mclblock** [CMB2/CMB2#1038]
Hi

I think I am doing something obviously wrong but the wysiwyg editor doesn't seem to work for me anymore. I've added a simple wysiwyg editor to a custom post type but it throws a javascript exception on the edit-post screen. It doesn't seem to stem from the post type definition, nor plugins or themes. I have gone through and disabled all of them and tried it on the vanilla Twenty-Seventeen theme. I'm not using a repeatable group or field. I've also checked the FAQs but couldn't spot any known issues around this (Sorry if it is noted somewhere and I missed it!). 

### Expected Behavior:
The Edit-Post screen should have show an extra TinyMCE field.

### Actual Behavior:
The TinyMCE field does not appear in the WP-Admin. The label of the field appears but the input textarea does not. An error appear in the browser console:
```
Uncaught ReferenceError: wp is not defined
    at HTMLDocument.<anonymous> (default.js?ver=1.0.0:5)
    at i (jquery.js?ver=1.12.4:2)
    at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4:2)
    at Function.ready (jquery.js?ver=1.12.4:2)
    at HTMLDocument.K (jquery.js?ver=1.12.4:2)
(anonymous) @ default.js?ver=1.0.0:5
i @ jquery.js?ver=1.12.4:2
fireWith @ jquery.js?ver=1.12.4:2
ready @ jquery.js?ver=1.12.4:2
K @ jquery.js?ver=1.12.4:2
```

### Steps to reproduce (I have confirmed I can reproduce this issue on the trunk branch):

1. Add a new metabox to an existing post type and a dd a wysiwyg field to the metabox (you may use the code below)
2. Observe a javascript error in the console.

### CMB2 Field Registration Code:

```php
<?php
namespace com\test\wordpress;

add_action('init', 'com\test\wordpress\create_test_post_type');
function create_test_post_type()
{

    $args = array(
        'public' => true,
        'supports' => array('title','thumbnail','editor'),
        'menu_icon' => 'dashicons-businessman'
    );
    
    register_post_type('Test', $args);
}


/* DESCRIPTION META BOX*/
add_action('cmb2_admin_init', 'com\test\wordpress\register_test_metabox');
function register_test_metabox()
{
    $prefix = 'mc_test_';

    $cmb = new_cmb2_box(array(
        'id' => $prefix . 'description_metabox',
        'title' => esc_html__('Test info', 'cmb2'),
        'object_types' => array('test'), // Post type
    ));
    $cmb->add_field( array(
        'name'    => 'Test wysiwyg',
        'desc'    => 'field description (optional)',
        'id'      => 'wiki_test_wysiwyg',
        'type'    => 'wysiwyg',
        'options' => array(),
    ) );
}
```

**Comment by tw2113** [comment]
Just on a hunch, can you see if it still occurs without the PHP namespacing?

**Comment by mclblock** [comment]
Sure!

Not sure why but of all of a sudden I am getting a PHP error:
```
Fatal error: Declaration of CMB2_Type_Wysiwyg::render() must be compatible with CMB2_Type_Textarea::render($args = Array) in D:\sandboxes\sites\mc-bridge-corporate\public_html\wp-content\plugins\cmb2\includes\types\CMB2_Type_Wysiwyg.php on line 16
```

I've tried downgrading CMB2 to 2.2.4 but that didn't do anything so probably isn't something that has changed recently. Must be something really obvious that I'm missing...

This is the code I am now using (I'm attaching a wysiwyg to a regular post without namespacing in my theme.

```php
add_action('cmb2_admin_init', 'register_test_metabox');
function register_test_metabox()
{
    $prefix = 'mc_test_';

    $cmb = new_cmb2_box(array(
        'id' => $prefix . 'description_metabox',
        'title' => esc_html__('Test info', 'cmb2'),
        'object_types' => array('post'), // Post type
    ));
    $cmb->add_field( array(
        'name'    => 'Test wysiwyg',
        'desc'    => 'field description (optional)',
        'id'      => 'wiki_test_wysiwyg',
        'type'    => 'wysiwyg',
        'options' => array(),
    ) );
}
```

**Comment by tw2113** [comment]
Not sure why that error started springing up unless something at that level got changed.

Not managing to recreate myself, with both the original namespaced version, as well as the non-namespaced one in the last reply. Has to be something in regards to your current install, at this point.

**Comment by tivnet** [comment]
class CMB2_Type_Wysiwyg extends CMB2_Type_Textarea {

	/**
	 * Handles outputting a 'wysiwyg' element
	 * @since  1.1.0
	 * @return string Form wysiwyg element
	 */
	public function render() {


should be written as

`public function render( $args = array() ) {`

to match the parent class' method declaration.

**Comment by tivnet** [comment]
(already fixed in https://github.com/CMB2/CMB2/commit/66b56ffba01ace1da1d649157619147777d43a99)

**Comment by jtsternberg** [comment]
Closing as this should be fixed in the most recent release.
