### ISSUE TITLE
Date picker doesn't show correctly when change the Wordpress language to Simplified Chinese

### ISSUE THREAD

**Issue by williamjieh** [CMB2/CMB2#1044]
### Expected Behavior:
text_date show calendar correctly 

### Actual Behavior:
text_date show calendar strangely when change wordpress language to Simplified Chinese

### Steps to reproduce (I have confirmed I can reproduce this issue on the trunk branch):

1. At wordpress admin Settings -> General page, change the language to Simplified Chinese
2. use date picker, the calendar doesn't show correctly

### CMB2 Field Registration Code:

```php
add_action( 'cmb2_admin_init', 'yourprefix_register_demo_metabox' );
function yourprefix_register_demo_metabox() {

	$cmb = new_cmb2_box( array(
		// Box Config...
	) );

	$cmb->add_field( array(
		// Field Config...
	) );

	// Additional fields...
}
```
![screen shot 2017-10-31 at 5 05 37 pm](https://user-images.githubusercontent.com/16261025/32254415-d32ab466-be5d-11e7-9791-8a65b485e7e9.png)

**Comment by tw2113** [comment]
Looks like a number of places where for whatever reason, it's trying to refer to a bunch of undefined javascript variables. This one may bubble its way from jQuery UI more than CMB2 specifically, but I won't claim that as for sure fact.

**Comment by EyesX** [comment]
The same issue occurs when using Swedish. Setting the language to English renders the date picker correctly. 

CMB2 2.2.6.1 and WP 4.9

![cmb2_datepicker](https://user-images.githubusercontent.com/4299787/33238025-2f0622b8-d284-11e7-8c09-5c724a337fec.png)

**Comment by uicestone** [comment]
For the Chinese language, I believe it's the cmb2/languages/cmb2-zh_CN.po contains Chinese comma "，" rather than ', '
for example the '一月，二月，三月，四月，五月，六月，七月，八月，九月，十月，十一月，十二月'
should be: '一月, 二月, 三月, 四月, 五月, 六月, 七月, 八月, 九月, 十月, 十一月, 十二月'.

I fixed this by replacing all "，" in the .po file to ', ' and compile to .mo using [Poedit](https://poedit.net/).

**Comment by jtsternberg** [comment]
@uicestone care to submit your updated .mo and .po files as a pull request?
