### ISSUE TITLE
Error: The frameborder attribute on the iframe element is obsolete. Use CSS instead.

### ISSUE THREAD

**Issue by fastmarketo** [CMB2/CMB2#1048]
```
Error: The frameborder attribute on the iframe element is obsolete. Use CSS instead.
From line 186, column 28; to line 186, column 172
           <iframe width="600" height="338" src="https://www.youtube.com/embed/jynQQcn2NJk?feature=oembed" frameborder="0" gesture="media" allowfullscreen></ifra
```
https://www.screencast.com/t/FxxAiFqPCb

what is the fix? I believe that this could be fixed by making certain changes in the CMB2 plugin.

**Comment by tw2113** [comment]
Not finding any place in CMB2's code that sets frameborder. The only instance I can find is in the unit tests, which is going to end up specifying to match incoming values. My hunch is that it's coming from WordPress core and the oEmbed functionality, and is out of our control.

**Comment by jtsternberg** [comment]
Yes, this is the oembed that youtube itself provides to WordPress. CMB2 does not generate this.
