### ISSUE TITLE
Let users rename group_title of repeatable group row

### ISSUE THREAD

**Issue by manzoorwanijk** [CMB2/CMB2#1062]
Hi,
It would be nice to let users edit/change the title of every entry of a repeatable group instead of setting it as `Entry {#}` kind of stuff. Currently the group title is rendered as `h3` tag with no filter/hook to change the behaviour. As an example, you can see the different pricing rules of [WooCommerce Dynamic Pricing & Discounts](https://codecanyon.net/item/woocommerce-dynamic-pricing-discounts/7119279) renamed.
Thanks :)

**Comment by jtsternberg** [comment]
Thanks for reporting. Already tracking here: #706. Please note, in that issue there is a documented snippet for accomplishing this.
