### ISSUE TITLE
Repeatable multiple field

### ISSUE THREAD

**Issue by breth84** [CMB2/CMB2#1065]
How can I repeat more fields in the product row? 

an examples 

![schermata 2017-11-29 alle 14 00 09](https://user-images.githubusercontent.com/2384410/33376351-a7b9f1c2-d50d-11e7-8b04-4ba9ae8d0f88.png)

Now the code is this:

  ```
 $cmb = new_cmb2_box(array(
        'id' => $prefix . 'menu',
        'title' => __('Menu', 'classeitalia'),
        'object_types' => array('page'),
        'show_on' => array('key' => 'page-template', 'value' => 'template-kitchen.php'),
        'context' => 'normal',
        'priority' => 'default',
    ));

    $block_id = $cmb->add_field(array(
        'id' => $prefix . 'menu_block',
        'type' => 'group',
        'options' => array(
            'group_title' => esc_html__('Menu {#}', 'classeitalia'),
            'add_button' => esc_html__('Add Another Menu', 'classeitalia'),
            'remove_button' => esc_html__('Remove Menu', 'classeitalia'),
            'sortable' => true,
        ),
    ));

    $cmb->add_group_field($block_id, array(
        'name' => __('Menu Title', 'classeitalia'),
        'id' => $prefix . 'menu_title',
        'type' => 'text',
    ));

    $cmb->add_group_field($block_id, array(
        'name' => __('Menu Subtitle', 'classeitalia'),
        'id' => $prefix . 'menu_subtitle',
        'type' => 'text',
    ));

    $cmb->add_group_field($block_id, array(
        'name' => __('Add a Product of Menu', 'classeitalia'),
        'id' => $prefix . 'menu_products',
        'type' => 'textarea_code',
        'repeatable' => true,
        'text' => array(
                'add_row_text' => 'Add Another Products',
           ),
        'desc' => __('Add a products of this menu', 'classeitalia'),

    ));
```

**Comment by jtsternberg** [comment]
If I understand correctly from your screenshot, you are looking to do nested repeatable groups? That is not currently possible (see #565), however you can build a custom-field that contains multiple fields/inputs within it, and put _that_ in a repeatable group. See the address field type for an example: https://github.com/CMB2/CMB2-Snippet-Library/tree/master/custom-field-types/address-field-type

**Comment by breth84** [comment]
Yes, thanks

**Comment by jtsternberg** [comment]
Ok, closing as a duplicate.

**Comment by rray524** [comment]
<?php
/*
Template Name: whatever you want
*/
get_header();
$products = get_post_meta(get_the_ID(),"your-prefix_menu_block",true);
?>

<div class="container">
	<div class="row">
	    <?php
		 foreach ($products  as $product): 
		?>
					  <ul>
					    <?php foreach($product['menu_products'] as $pdts) : ?>
					        <li><?php echo esc_html($pdts); ?></li>
					    <?php endforeach; ?>					    
					  </ul>
					</div>
	    <?php endforeach; ?>
	</div>
</div>


<?php get_footer(); ?>

**Comment by rray524** [comment]
`<?php
/*
Template Name: whatever you want
*/
get_header();
$products = get_post_meta(get_the_ID(),"your-prefix_menu_block",true);
?>

<div class="container">
	<div class="row">
	    <?php
		 foreach ($products  as $product): 
		?>
					  <ul>
					    <?php foreach($product['menu_products'] as $pdts) : ?>
					        <li><?php echo esc_html($pdts); ?></li>
					    <?php endforeach; ?>					    
					  </ul>
					</div>
	    <?php endforeach; ?>
	</div>
</div>


<?php get_footer(); ?>`

**Comment by rray524** [comment]
<?php
/*
Template Name: whatever you want
*/
get_header();
$products = get_post_meta(get_the_ID(),"your-prefix_menu_block",true);
?>

<div class="container">
	<div class="row">
	    <?php
		 foreach ($products  as $product): 
		?>
					  <ul>
					    <?php foreach($product['menu_products'] as $pdts) : ?>
					        <li><?php echo esc_html($pdts); ?></li>
					    <?php endforeach; ?>					    
					  </ul>
					</div>
	    <?php endforeach; ?>
	</div>
</div>
<?php get_footer(); ?>

**Comment by AsafAzoulay** [comment]
do you have full example of how to do custom fields + repeatable + save data correctly?
