### ISSUE TITLE
How create Taxonomy   custom fields??

### ISSUE THREAD

**Issue by johndiego** [CMB2/CMB2#1066]
How i can custom fields taxonomy example?
Thanks guys.

**Comment by jtsternberg** [comment]
Please clarify what you're asking. Have you looked at the wiki? https://github.com/CMB2/CMB2/wiki/Field-Types#taxonomy_radio

**Comment by johndiego** [comment]
I would like to create custom fields in a taxonomy and not in a post_type.,
Sorry my english!!
Thanks for repply @jtsternberg

**Comment by jtsternberg** [comment]
Examples for registering fields for each type of data can be found here: https://github.com/CMB2/CMB2/wiki/Examples
For terms (taxonomies), specifically here: https://github.com/CMB2/CMB2/blob/b1a7e8fb9f0634337b390a098f0a1f70f0f64085/example-functions.php#L601-L641

**Comment by johndiego** [comment]
veryyyyyy thanks , save my live  :+1:

**Comment by jtsternberg** [comment]
I don't understand the question. That is a taxonomy field type. To define the post-type, you have to do it at the metabox registration.

**Comment by GitaStreet** [comment]
If I understand correctly, orobably wanting to use Custom Post Type powered WordPress taxonomies. Like this plugin:
https://wordpress.org/plugins/cpt-onomies/

**Comment by johndiego** [comment]
I solved my problems , Thanks @GitaStreet  @jtsternberg !!
I wiill search how i can display custom fields in my vew!
thanks!!

**Comment by mehmetsarr** [comment]
> Sorunlarımı çözdüm , teşekkürler @GitaStreet @jtsternberg !!
> Vew'de özel alanları nasıl görüntüleyebileceğimi araştıracağım!
> Teşekkürler!!

How did you do the viewing? I could not do it somehow

**Comment by ahamed-sojib** [comment]
> Examples for registering fields for each type of data can be found here: https://github.com/CMB2/CMB2/wiki/Examples
> For terms (taxonomies), specifically here:
> 
> https://github.com/CMB2/CMB2/blob/b1a7e8fb9f0634337b390a098f0a1f70f0f64085/example-functions.php#L601-L641

How can I show added filed output in frontend?

**Comment by tw2113** [comment]
@ahamed-sojib You'll want to use something like https://developer.wordpress.org/reference/functions/get_term_meta/ to start fetching these fields. Do note that you'll want to use the TERM ID, as opposed to POST ID. So you'll need to get term objects for the terms assigned to the given post.

**Comment by ahamed-sojib** [comment]
> @ahamed-sojib You'll want to use something like https://developer.wordpress.org/reference/functions/get_term_meta/ to start fetching these fields. Do note that you'll want to use the TERM ID, as opposed to POST ID. So you'll need to get term objects for the terms assigned to the given post.

but why it is not working can you help me ?
<?php $cat_thumbnail = wp_get_attachment_image( get_term_meta( get_the_ID(), 'categories_thumbnail_metabox', 1 ), 'full' );
 ?>
 <?php echo esc_url($cat_thumbnail); ?>

**Comment by tw2113** [comment]
the `get_the_ID()` usage is passing the post ID, not term ID. See my previous comment about that part. Something like https://developer.wordpress.org/reference/functions/get_the_terms/ would get you the terms on the post, to then use with what you're doing here.

**Comment by ahamed-sojib** [comment]
> the `get_the_ID()` usage is passing the post ID, not term ID. See my previous comment about that part. Something like https://developer.wordpress.org/reference/functions/get_the_terms/ would get you the terms on the post, to then use with what you're doing here.

Thanks, Man! It is working now.
