### ISSUE TITLE
Incompatible with PHP 7.2 

### ISSUE THREAD

**Issue by anhskohbo** [CMB2/CMB2#1070]
Some bugs like this:

```
( ! ) Fatal error: Declaration of CMB2_Type_File_List::render() must be compatible with CMB2_Type_Text::render($args = Array) in webdevstudios/cmb2/includes/types/CMB2_Type_File_List.php on line 13
```

**Comment by johnnymat** [comment]
Hello

Ive tried a quick test too on new php 7.2 to update a personal project. A lot of [Types](https://github.com/CMB2/CMB2/wiki/Field-Types) works well but [text_datetime_timestamp](https://github.com/CMB2/CMB2/wiki/Field-Types#text_datetime_timestamp) is problematic (doesnt work at all with php 7.2, until 7.1 branch) .


text_datetime_timestamp

**Comment by tw2113** [comment]
So just to help with this.

`CMB2_Type_File_List` extends `CMB2_Type_File_Base`
`CMB2_Type_File_Base` extends `CMB2_Type_Text`

`CMB2_Type_Text` has a `render()` method with a signature of `public function render( $args = array() ) {`

`CMB2_Type_File_Base` does not implement its own `render` method, but `CMB2_Type_File_List` does but it does not pass a default `$args` of empty array.

Changing that should clear up the original error reported. Apparently it's also going to cause fatal errors, so we should get this taken care of soon, as PHP7.2 is officially released and will begin getting updated to with more frequency.

**Comment by jtsternberg** [comment]
Just a heads up, 2.3.0 has been released and contains the php 7.2 compatibility fix.

**Comment by salientroot** [comment]
Hi, I got the same issue now.
Please help me as soon as possible.

**Comment by tw2113** [comment]
@salientroot can you confirm if you're already using CMB2 version 2.3.0 or are your errors coming up with that version already updated to?

**Comment by salientroot** [comment]
sorry, I am using the wp real estate plugin now and got the issue

**Comment by tw2113** [comment]
Sounds like they've bundled CMB2 in with their plugin, and will need to get that updated as part of an overall update for their plugin.

**Comment by salientroot** [comment]
yeah, i think so, but the plugin is just the latest version.

**Comment by tw2113** [comment]
Yes, you may have the latest version of WP Real Estate, but that version doesn't have the latest version of CMB2 with the PHP 7.2 compatibility fixes. Their devs need to update the copy of CMB2 that ships with their plugin and release an update that includes that.

Do you have a link to where one can download a copy of WP Real Estate? or is it a premium plugin?

**Comment by jtsternberg** [comment]
Unless the wp real estate plugin bundled CMB2 incorrectly, you should be able to install the [CMB2 plugin](https://wordpress.org/plugins/cmb2/) separately to override their bundled version and fix the issue.

**Comment by salientroot** [comment]
hmm, I think it's not good way

**Comment by salientroot** [comment]
ok, anyway this is not your problem. thanks for your help :)

**Comment by droidmanspace** [comment]
Does downgrade of php fix it?

**Comment by tw2113** [comment]
technically, but ideally whatever is bundling CMB2 should get upgraded to 2.3.x to address the compatibility issues. As more and more trickle up to PHP7.2, it's going to become more apparent that the bundlers need to act.

**Comment by jtsternberg** [comment]
Added a section to the troubleshooting wiki: https://github.com/CMB2/CMB2/wiki/Troubleshooting#fatal-error-declaration-of-cmb2_type_colorpickerrender-or-similar

**Comment by facepalmua** [comment]
To anyone who's looking how to resolve the issue, I changed two files to fix the error. You can find those files in:
/wp-content/plugins/Ebor-Framework-master/metaboxes/includes/types/


CMB2_Type_Checkbox.php
```
<?php
/**
 * CMB checkbox field type
 *
 * @since  2.2.2
 *
 * @category  WordPress_Plugin
 * @package   CMB2
 * @author    WebDevStudios
 * @license   GPL-2.0+
 * @link      http://webdevstudios.com
 */
class CMB2_Type_Checkbox extends CMB2_Type_Text {

    /**
     * If checkbox is checked
     *
     * @var mixed
     */
    public $is_checked = null;

    /**
     * Constructor
     *
     * @since 2.2.2
     *
     * @param CMB2_Types $types
     * @param array      $args
     * @param bool|null  $is_checked
     */
    public function __construct( CMB2_Types $types, $args = array(), $is_checked = null ) {
        parent::__construct( $types, $args );
        $this->is_checked = $is_checked;
    }

    /**
     * Render the checkbox field
     *
     * @param array $args Optional render arguments.
     * @return string
     */
    public function render( $args = array() ) {
        $defaults = array(
            'type'  => 'checkbox',
            'class' => 'cmb2-option cmb2-list',
            'value' => 'on',
            'desc'  => '',
        );

        $meta_value = $this->field->escaped_value();

        $is_checked = null === $this->is_checked
            ? ! empty( $meta_value )
            : $this->is_checked;

        if ( $is_checked ) {
            $defaults['checked'] = 'checked';
        }

        $args = $this->parse_args( 'checkbox', $defaults );

        return $this->rendered(
            sprintf(
                '%s <label for="%s">%s</label>',
                parent::render( $args ),
                $this->_id(),
                $this->_desc()
            )
        );
    }

}
```


and CMB2_Type_Oembed.php

```
<?php
/**
 * CMB oembed field type
 *
 * @since  2.2.2
 *
 * @category  WordPress_Plugin
 * @package   CMB2
 * @author    WebDevStudios
 * @license   GPL-2.0+
 * @link      http://webdevstudios.com
 */
class CMB2_Type_Oembed extends CMB2_Type_Text {

    /**
     * Render the oEmbed field
     *
     * @param array $args Optional render arguments.
     * @return string
     */
    public function render( $args = array() ) {
        $field = $this->field;

        $meta_value = trim( $field->escaped_value() );

        $oembed = ! empty( $meta_value )
            ? cmb2_ajax()->get_oembed( array(
                'url'         => $field->escaped_value(),
                'object_id'   => $field->object_id,
                'object_type' => $field->object_type,
                'oembed_args' => array( 'width' => '640' ),
                'field_id'    => $this->_id(),
            ) )
            : '';

        return parent::render( array(
            'class'           => 'cmb2-oembed regular-text',
            'data-objectid'   => $field->object_id,
            'data-objecttype' => $field->object_type,
        ) )
        . '<p class="cmb-spinner spinner" style="display:none;"></p>'
        . '<div id="'. $this->_id( '-status' ). '" class="cmb2-media-status ui-helper-clearfix embed_wrap">' . $oembed . '</div>';
    }

}
```

**Comment by tw2113** [comment]
For what it's worth, it looks like the developer(s) of Ebor-Framework-master needs to look into making sure they've upgraded their bundled CMB2 library copy with the latest release, as I suspect we've had this error handled in the core version for awhile.
