### ISSUE TITLE
The Compatibility issue with PHP 7.2

### ISSUE THREAD

**Issue by themevan** [CMB2/CMB2#1075]
Just report a compatibility issue with PHP 7.2, it's not important, just when I tried PHP 7.2, then found this error:

`Fatal error: Declaration of CMB2_Type_Colorpicker::render() must be compatible with CMB2_Type_Text::render($args = Array)`

Thanks

**Comment by jtsternberg** [comment]
Closing as duplicate. https://github.com/CMB2/CMB2/issues/1070
