### ISSUE TITLE
show_on_cb inside a group based on another value inside same group

### ISSUE THREAD

**Issue by sandrodz** [CMB2/CMB2#1076]
I'd like to conditionally display another field inside the group based on select dropdown value.

e.g. on `hr` nothing happens, on `3col` new field is displayed.

<img width="1135" alt="screen shot 2017-12-17 at 11 39 12 pm" src="https://user-images.githubusercontent.com/8479569/34083066-83c9b00c-e383-11e7-8e49-82323e1e5148.png">

This is what I got so far:
<img width="1354" alt="screen shot 2017-12-17 at 11 40 34 pm" src="https://user-images.githubusercontent.com/8479569/34083082-c7f3f35a-e383-11e7-930a-82ff375c0f42.png">

I'm planning to look into $cmb variable and see if I can find `template` value for the current group and return true/false based on that.

Problem is that I don't know currently in which nested group I am inside that `at_cmb2_only_show_for_3col`

any ideas?

my solution, I hope there is a better way ^_^

<img width="760" alt="screen shot 2017-12-18 at 8 29 26 am" src="https://user-images.githubusercontent.com/8479569/34090074-d79f90e4-e3cd-11e7-90fd-397fb139ab48.png">

**Comment by tw2113** [comment]
Have you looked over https://github.com/CMB2/CMB2/wiki/Adding-your-own-show_on-filters much? This may help you as it documents what type of things are passed to each callback for the `show_on_cb` field.

Specifically each callback receive:

**Comment by jtsternberg** [comment]
A couple things:
1) He is not talking about conditionally showing a box, but a field, in which case, he has [the right parameter](https://github.com/CMB2/CMB2/wiki/Field-Parameters#show_on_cb), though the argument passed in to the field's `show_on_cb` is the `CMB2_Field` (`$field`) object, not the `CMB2` object.
2) He is talking about conditionally showing based on another field's value. @sandrodz if you're looking at changing based on the field's dynamic value (e.g. detecting when another field changes via Javascript), you'll probably want to try the [CMB2 Conditionals](https://github.com/jcchavezs/cmb2-conditionals) extension, unless you're comfortable writing some custom JS.

**Comment by sandrodz** [comment]
Hi, thanks for looking in! I had to scratch the use of cmb2 because of this bug: https://github.com/CMB2/cmb2-attached-posts/issues/51

Unfortunately I'm short on time to experiment and debug this issues, but I will look into it more closely later on. I've looked at issues on https://github.com/jcchavezs/cmb2-conditionals and it seems that plugin has trouble with groups, which is my use case.

**Comment by jtsternberg** [comment]
Thanks, added a todo to #1055.
