### ISSUE TITLE
Show selected taxonomy_multicheck_inline in other taxonomy

### ISSUE THREAD

**Issue by johndiego** [CMB2/CMB2#1077]
<b>How i can values in selected in other taxonomy with  IDS ?   </b>

![deepinscreenshot_20171221191809](https://user-images.githubusercontent.com/18476845/34275440-74e461f0-e684-11e7-9ce6-b6978cca12cf.png)
![deepinscreenshot_20171221192137](https://user-images.githubusercontent.com/18476845/34275441-7506d3de-e684-11e7-9f59-ca801780dced.png)
![deepinscreenshot_20171221192525](https://user-images.githubusercontent.com/18476845/34275489-ba44ed3c-e684-11e7-80cc-6f21aeabb290.png)

**Comment by tw2113** [comment]
So you're needing to get taxonomy information for some taxonomy associated with terms stored as term meta on a different taxonomy term?

Just as a hunch, have you looked at get_term_by() to get term info for the items in that foreach loop?

**Comment by johndiego** [comment]
How can I save the selected taxonomies and retrieve the IDS?

**Comment by tw2113** [comment]
get_term_by will return WP_Term objects that include term IDs.

https://codex.wordpress.org/Function_Reference/get_term_by

**Comment by johndiego** [comment]
![deepinscreenshot_20171222101014](https://user-images.githubusercontent.com/18476845/34297621-57b27140-e700-11e7-901b-7ecb8d067f1e.png)

this dont save my field!!

How i can save selected with ids?

**Comment by tw2113** [comment]
Planning to try and recreate the best I can so that I can see what exactly may be getting saved and where, to provide a more concrete answer for you.

**Comment by tw2113** [comment]
Alright, Justin has some fixes regarding this :D

**Comment by jtsternberg** [comment]
WordPress does not have the infrastructure to associate two taxonomies, so I have updated CMB2 to store the associated taxonomy term id to term meta. If you need this functionality right now, your best bet would be to update your CMB2 to the trunk branch and use that.

**Comment by johndiego** [comment]
@jtsternberg  Thanks!!!!
