### ISSUE TITLE
sort post based on metabox

### ISSUE THREAD

**Issue by numerosept** [CMB2/CMB2#1084]
Hello i'm getting trouble to sort posts based on metabox text_date.
I want to sort posts ascending from today's date.

The query is working, i got it sorted for days and months but it does not include the year. 

So for example if a post has : january  2nd 2019 set in the metabox it will be sorted before every posts set for march 2018 .

Below you will find my code, hope someone can help 

### CMB2 Field Registration Code:
```php
add_filter( 'cmb2_admin_init', 'agenda_settings' );
function agenda_settings( ) {

	// Start with an underscore to hide fields from custom fields list
	$prefix = '_agenda_';

	$cmb = new_cmb2_box( array(
		'id'            => $prefix . 'settings',
		'title'         => __( 'date', 'compassion' ),
		'object_types'  => array( 'agendas' ),
	) );
	$cmb->add_field( array(
		'name'      => __( 'Datum hinzufügen', 'compassion' ),
		'id'        => $prefix . 'date_agenda',
		'type'      => 'text_date',
	) );
}
```
### Frontend template query code:
``` 
    $posts_per_page = 15;

    $paged = ( get_query_var( 'paged' ) ) ? get_query_var( 'paged' ) : 1;

    $args = array(
      'post_type'       =>  'agendas',
      'posts_per_page'  =>  $posts_per_page,
      'paged'           =>  $paged,
      'meta_key' => '_agenda_date_agenda',
      'order'  			=> 'ASC',
      'orderby' => 'meta_value',
      'meta_query' => array(
       array(
           'key' => '_agenda_date_agenda',
           'value' => time(),
           'compare' => '<',
       )
   )
      
    );

```

**Comment by tw2113** [comment]
See my reply here: https://wordpress.org/support/topic/2018-date-sorting-not-working/#post-9857365 which deals very much with the same type of problem.

For what it's worth, this isn't a fault with CMB2 by any means, it's a fault with dealing with dates in general and at least to some degree, WordPress core.
