### ISSUE TITLE
Enhancement: for options page - ability to autoload=false for options

### ISSUE THREAD

**Issue by slaFFik** [CMB2/CMB2#1093]
### Expected Behavior:

When creating an options page using `\new_cmb2_box()` give ability to define the `autoloader`, so devs could define that those options should NOT be autoloaded.

As a developer, you know the drawbacks of `autoload=yes`.

### Actual Behavior:

currently it defaults to `yes`

### Steps to reproduce (I have confirmed I can reproduce this issue on the trunk branch):

Use the https://github.com/CMB2/CMB2-Snippet-Library/blob/master/options-and-settings-pages/options-pages-with-tabs-and-submenus.php snippet and save options.

**Comment by slaFFik** [comment]
`CMB2_Options::set()` which has this:

```php
// If no override, update the option
return update_option( $this->key, $this->options );
```

**Comment by jtsternberg** [comment]
Added a filter, and parameter on options-page boxes toggles the filter. Please test: https://github.com/CMB2/CMB2/compare/options-autoload-feature

**Comment by slaFFik** [comment]
@jtsternberg I've tested the PR.

Switching from `yes` to `no` via both filter and param work.
Swithcing back from `no` to `yes` doesn't work, it always stays the same `no`.

**Comment by jtsternberg** [comment]
@slaFFik can you provide your code that you tested with?

**Comment by jtsternberg** [comment]
Also, you are right. It will not switch the autoload value in the DB after the first time it is inserted. If you want to test switching, you will need to actually delete the option from the database first.

**Comment by slaFFik** [comment]
Default code from https://github.com/CMB2/CMB2-Snippet-Library/blob/master/options-and-settings-pages/options-pages-with-tabs-and-submenus.php snippet (100% the same) + 
```php
add_filter( 'cmb2_should_autoload_test_main_options', '__return_true' ); //_false
```
or 
```
'autoload'     => 'yes', // 'no'
```

**Comment by slaFFik** [comment]
Using this
```php
update_option( 'test_main_options', 'a:1:{s:8:"bg_color";s:7:"#602415";}', 'yes' );
```

Actually udpates autoload `no` to `yes`. So you don't need to remove option and udpate it again to change this value.

**Comment by slaFFik** [comment]
Using this
```php
update_option( 'test_test', time(), true ); // false
```

actually udpates autoload `no` to `yes`. So you don't need to remove option and udpate it again to change this value.

**Comment by slaFFik** [comment]
Just remember, that `update_option()` doesn't fire `$wpdb->update()` to save data if old/new values are the same. 

So the bug in the commit is that you default to `null`, which in case of already saved `no` uses `null` as default that later omits the `$update_args['autoload']` completely and don't pass the updated value to `-`->update()`. In short, you need to always pass the boolean no matter what, instead of a `null`.

**Comment by jtsternberg** [comment]
Ok, good feedback, thank you. [Updated](https://github.com/CMB2/CMB2/pull/1098/commits/1dc107bb8b16a5d1d44d7e2b43fd19ee2ce7038b). Please test again?

**Comment by slaFFik** [comment]
Looks good, tests for both filter and param for al lscenarios passed fine when `true`/`false` is used. 

There will be a problem with `'no'` string, but I'm not sure something should be done here, at your discretion.

Thank you for this feature!
