### ISSUE TITLE
Fatal error in WordPress 3.8

### ISSUE THREAD

**Issue by manzoorwanijk** [CMB2/CMB2#1095]
Since it's mentioned in the plugin readme that WP 3.8 is supported, so I set the required version for my plugin to be 3.8. But, when I tested it on that version, it crashed.
**Fatal Error: Call to undefined function register_setting() in `/public_html/wp-content/plugins/cmb2/includes/CMB2_Options_Hookup.php on line 49`**

**Comment by grappler** [comment]
That is strange as `register_setting()` was introduced in WP 2.7. https://developer.wordpress.org/reference/functions/register_setting/

**Comment by tw2113** [comment]
@manzoorwanijk can you provide an exact copy of the code you're trying to use? My hunches are that you have stuff being run before parts of WP core are loaded, however I can't prove that quite yet.

**Comment by manzoorwanijk** [comment]
@tw2113 I tried [this](https://github.com/CMB2/CMB2-Snippet-Library/blob/master/options-and-settings-pages/theme-options-cmb.php) snippet in `functions.php` of the child theme as well as in the plugin file, but the result is the same.

`register_setting()` is in [plugin.php](https://core.trac.wordpress.org/browser/tags/3.8/src/wp-admin/includes/plugin.php#L1712) in WP 3.8 and in WP 4.9, it's in [option.php](https://core.trac.wordpress.org/browser/tags/4.9/src/wp-includes/option.php#L1969)

**Comment by tw2113** [comment]
Will need to create a dev site that has 3.8 installed on it to really debug what may be going on, so it may be a little bit for me to circle back. I will do what I can to help though.

**Comment by tw2113** [comment]
Does definitely feel like the loading order has changed since 3.8.x and the example is catered towards the new order.

That said, I have to say it's extremely hard for us to consider supporting such an old version of WordPress, especially one that was released at the end of 2013. We do say that we support 3.8 still, and as an overall case, we probably do, with this options page setup being an edge case. This lends itself to be a case of bumping the minimum requirement more than anything.

@jtsternberg what are your thoughts on this and possibly bumping the minimum version number now that we have an example that for sure is breaking with 3.8?

**Comment by tw2113** [comment]
I'm not as worried about 4.6 or higher, because I have to believe the snippets wouldn't have been committed and pushed if was failing. Regardless, let us know what you experience and we can do what we can with those newer versions.

**Comment by manzoorwanijk** [comment]
Yes! My fear came out to be true! It's the same in WP 4.6 and works perfectly in WP >= 4.7
![image](https://user-images.githubusercontent.com/18226415/36419742-cc706654-1658-11e8-91ee-8acb743a2c3e.png)

**Comment by tw2113** [comment]
Some extra thoughts on this, I just noticed this comment at the top of the original snippet linked to: https://github.com/CMB2/CMB2-Snippet-Library/blob/master/options-and-settings-pages/theme-options-cmb.php#L2-L8

This lends to my belief that this was still not something tested on 4.6 or earlier. It may be worth noting in the snippet that WP requirement to avoid headaches for others. I'm curious how well the version shown at https://github.com/CMB2/CMB2-Snippet-Library/blob/59166b81693f4ab8651868e70cb29702576bd055/options-and-settings-pages/theme-options-cmb.php will do for you, as it's the version right before it got updated
