### ISSUE TITLE
Add a WordPress Code Editor field type

### ISSUE THREAD

**Issue by garretmh** [CMB2/CMB2#1096]
WordPress 4.9 added the Code Editor API (https://make.wordpress.org/core/2017/10/22/code-editing-improvements-in-wordpress-4-9/) to generate CodeMirror editors. It requires a bit of JavaScript hookup but would allow for much nicer WordPress-official alternative to textarea_code.

**Comment by jtsternberg** [comment]
This is a great idea.

**Comment by jtsternberg** [comment]
This should probably replace the default behavior for the `textarea_code` field type, with an options opt-out, e.g. `'options' => array( 'formatted' => false )`.
