### ISSUE TITLE
Add group entries dynamically

### ISSUE THREAD

**Issue by efoula** [CMB2/CMB2#1097]
Is there a way to add/edit entries of an existing group dynamically?
same as (update_post_meta or add_post_meta).
```
add_action('cmb2_init', 'prem_tbles_metaboxes');
function prem_tbles_metaboxes() {
	$prefix           = '_premtb_';
	$prcestble_groups = new_cmb2_box(array(
			'id'           => 'prm_metabox',
			'title'        => __('Pricing Tables', 'cmb2'),
			'object_types' => array('page'), // Post type
			'context'      => 'normal',
			'priority'     => 'high',
			'show_on'      => array('key'      => 'id', 'value'      => '19993'),
			'show_names'   => true, // Show field names on the left
			'closed'       => true, // Keep the metabox closed by default
		));
	$prcestble_groups_id = $prcestble_groups->add_field(array(
			'id'             => $prefix.'repeat_group',
			'type'           => 'group',
			'options'        => array(
				'group_title'   => __('Plan {#}', 'cmb'),
				'add_button'    => __('Add Another Plan', 'cmb'),
				'remove_button' => __('Remove Plan', 'cmb'),
				'sortable'      => true,
				'closed'        => true,
			),
		));
	$prcestble_groups->add_group_field($prcestble_groups_id, array(
			'name' => 'Title',
			'id'   => 'pln_title',
			'type' => 'text',
		));
}

```

**Comment by tw2113** [comment]
Unless I'm mistaken, you could grab your entry, `_premtb_repeat_group` from the looks of it, via get_post_meta() and then append indexes into it, matching the structure that the UI saves to.

Just eyeballing this but:

```
$group = get_post_meta( get_the_ID(), '_premtb_repeat_group', true );
$group[] = array( 'pln_title' => 'new value' );
update_post_meta( get_the_ID(), '_premtb_repeat_group', $group );
```
This would grab what you already have saved, insert a new index at the end of the array, and then re-save back into the meta. I may or may no have the structure 100% right, so you'd need to double check that spot.

**Comment by efoula** [comment]
Your solution makes sense, but I still don't know how to change a "specific" entry of the group?
Is each entry in the same group has an id?

**Comment by tw2113** [comment]
You would need to find a way to locate it in the data that is being saved, for which we don't, to my knowledge, have a built in way to do. Really depends on exactly how the content is saved.

**Comment by efoula** [comment]
Sounds good. Let us say I will provide an ID for each entry, then how to update the entry content by its ID?

**Comment by efoula** [comment]
For example, if I have 2 entries:

Group (_premtb_repeat_group)

Entry(1)
field (id) = 1
field (title) = Apple

Entry(2)
field (id) = 2
field (title) = Orange

--
How could I update Entry(1)-> title?

**Comment by efoula** [comment]
This is what I found when I inspect the fields on the backend
`<input type="text" class="regular-text" name="_premtb_repeat_group[1][pln_title_en]" id="_premtb_repeat_group_1_pln_title_en" value="1 Month">`
(1) is the key of the entry.

And this is how it is saved in the DB meta value:
i:1;a:8:{s:12:\"pln_title_en\";s:7:\"1 Month\";

**Comment by tw2113** [comment]
Yeah, there's not really much for unique ID being saved for each repeated field in there. the `field (id)` items are likely going to be incremental and not unique to each item. That more than likely is just the array index.

Perhaps a good question is going to be what exactly are you trying to work out how to do, where you're encountering the need to update in this way?

**Comment by efoula** [comment]
Actually, I have a website more like "linkedin", and what am trying to do is to allow the users to add their work experiences "Company name, position, date, etc.", and I give the users the ability to add/edit/delete any work experience. So, coz I used to use cmb2 which I found very easy to use, I was thinking of using a group cmb to add these user's work experiences, and that's it.

**Comment by tw2113** [comment]
Noted. That said, have you looked over the wiki and the frontend posting topics? It's possible to display CMB2 fields on the frontend, and that would take care of the need to dynamically update things yourself.

https://github.com/CMB2/CMB2/wiki/Bringing-Metaboxes-to-the-Front-end

https://webdevstudios.com/2015/03/30/use-cmb2-to-create-a-new-post-submission-form/

https://github.com/CMB2/CMB2-Snippet-Library/tree/master/front-end

**Comment by efoula** [comment]
Thank you for your response, appreciate it.
I still have the same problem, coz I want to edit/update the group entries separately, and I cannot reach that result by using the frontend forms, and also I am using AJAX to submit the forms.

I hope anyone can help on this issue, the group entry already has a key, so why not I couldn't update it dynamically by using "update_post_meta"?

**Comment by efoula** [comment]
Look I made a workaround by using find and replace in an array, I hope this could help anyone who is facing the same problem.

```
$entries = get_post_meta(19993, '_premtb_repeat_group', true);
$array   = $entries;
$count = 0;
foreach ((array) $entries as $key => $entry) {
	$count++;
	if ($count == 2) {
		if (isset($entry['pln_title_en'])) {
			$pln_title_en = esc_html($entry['pln_title_en']);
		}
		if (isset($entry['pln_price_en'])) {
			$pln_price_en = esc_html($entry['pln_price_en']);
		}
		if (isset($entry['pln_feats_en'])) {
			$pln_feats_en = esc_html($entry['pln_feats_en']);
		}
		$search  = array($pln_title_en, $pln_price_en, $pln_feats_en);
		$replace = array('Replace Title', 'Replace Price', 'Replace Features');
	}
}
array_walk($array,
	function (&$v) use ($search, $replace) {
		$v = str_replace($search, $replace, $v);
	}
);
update_post_meta(19993, '_premtb_repeat_group', $array);
```

**Comment by tw2113** [comment]
The arrays have indexes though, not named keys, at least in terms of each item in the group. The individual items have their own arrays that have named keys that you can target a bit easier with, but from what I've seen with the data above, there's no real way to tell if that's a Facbebook item, an Instagram item, or what have you. Thus the issue with updating individual items the way aimed for.

If they're going to have a consistent order each time, no matter who's saving the data, then you may be able to get by with things like I believe I'm reading with your snippet above. With that said, I could see `$entries[2]` being possible to use to target the 3rd item.

```
if ( isset( $entry[2]['pln_title_en'] ) ) {
    $pln_title_en = esc_html( $entry[2]['pln_title_en'] );
}
```
and so on.

**Comment by efoula** [comment]
Your solution rocksss. Thank you so much :)

```
$entries = get_post_meta(get_the_id(), '_premtb_repeat_group', true);
$entries[$key]['pln_title_en'] = 'Replace Title';
update_post_meta(get_the_id(), '_premtb_repeat_group', $entries);
```

**Comment by tw2113** [comment]
Welcome.

**Comment by efoula** [comment]
Hey, I still have one issue, when I use your solution to add a new entry if there is the default empty entry in the group, then your code is not working (500 interval server error).
Otherwise, if there is a filled in entry, then the code works perfectly.

```
$group = get_post_meta( get_the_ID(), '_premtb_repeat_group', true );
$group[] = array( 'pln_title' => 'new value' );
update_post_meta( get_the_ID(), '_premtb_repeat_group', $group );
```
