### ISSUE TITLE
"File" field type and white images with transparent backgrounds

### ISSUE THREAD

**Issue by chrisgherbert** [CMB2/CMB2#1103]
### Expected Behavior:

When uploading an image using the "file" field type, it should be visible even if the image is all-white with a transparent background.  These kinds are images are very common when dealing with logos or icons.

### Actual Behavior:

All-white images are not visible because the preview box has a white background:
![screen shot 2018-03-07 at 12 43 35 am](https://user-images.githubusercontent.com/2541849/37075774-619dd7c2-21a1-11e8-90ca-cbfa8d7cecb8.png)

Standard WordPress image UI elements use a checkerboard background or a light gray background:

#### Featured Image Example

![screen shot 2018-03-07 at 12 49 55 am](https://user-images.githubusercontent.com/2541849/37075788-79272344-21a1-11e8-9c02-227cbd239f44.png)

#### Media Library Example

![screen shot 2018-03-07 at 12 50 25 am](https://user-images.githubusercontent.com/2541849/37075804-9145febe-21a1-11e8-90e0-4748c8b5e405.png)

**Comment by jtsternberg** [comment]
I like it. Added.

![](http://b.ustin.co/nekNuG+)
