### ISSUE TITLE
UX of the wysiwyg field - fullscreen mode / adjust to content

### ISSUE THREAD

**Issue by vollyimnetz** [CMB2/CMB2#1104]
### Expected Behavior:
If i click on fullscreenmode in an cmb2-wysiwyg-field i expect that the backend-sidebar get hidden like in the normal editor-field.

### Actual Behavior:
The backend sidebar overlaps the editor-field, so editing is not possible.

### CMB2 Field Registration Code:
Standard code from this website.

----------------
Alternative: it would be cool if the cmb2-wysiwyg-field grow as the normal editor-field do.

**Comment by jtsternberg** [comment]
I'm not seeing the sidebar issue: 

![](http://b.ustin.co/LAryPG+)

**Comment by vollyimnetz** [comment]
hi, thank you for your quick response. You are right. The problem is caused by the plugin "SiteOrigin Widgets Bundle" (which i do not even use on this page).
I will create a ticket on there issue page.
----
But, you may want to think about the feature request (auto grow of the wysiwyg-field).

can be closed
