### ISSUE TITLE
Revolution slider compatibility

### ISSUE THREAD

**Issue by andrejarh** [CMB2/CMB2#1110]
Latest development version causes Revolution slider plugin not to work. The WordPress.org version of CMB2 works fine.  When i updated to the latest version, this is the error the slider reports:
![screen shot 2018-03-21 at 09 27 46](https://user-images.githubusercontent.com/10053621/37699987-358d29cc-2cea-11e8-8fb1-bccc6e3b56bb.png)

Rev slider is not really a codebeauty masterpice, so it is quite possible the problem is on their end. 
As soon as I switch to the old CMB2, this error is gone.

Anyway, I just wanted to let you know about this issue.

**Comment by jtsternberg** [comment]
Do you have a `textarea_code` field type on this page?

**Comment by jtsternberg** [comment]
What is the full url to the `css_editor.js` file? It looks like Revolution slider is likely using an old version of CodeMirror. WordPress now bundles CodeMirror in core, so they should update their plugin to work with that version.

**Comment by andrejarh** [comment]
Hi, you are probably right. They are using their own version of CodeMirror ( ver. 2.35 ) packed with their plugin. I haven't seen the textarea_code field on this site though.

**Comment by pareshsojitra** [comment]
Hi,

I'm also getting the same issue, is there any suggestion on where is the problem ? Either Revolution or CMB2 Need to fix the problem ?

Thank you.

**Comment by tw2113** [comment]
@pareshsojitra can you confirm questions asked by justin in https://github.com/CMB2/CMB2/issues/1110#issuecomment-374925395 ?

**Comment by wayheming** [comment]
+1 http://prntscr.com/jnhy4y

**Comment by tw2113** [comment]
I realize i'm going to come off pointing fingers, but unless CMB2 is somehow using this function wrong, or storing the return results wrong, then it's more an issue coming from these other plugins. They need to also be made aware of the errors coming up from someone potentially using a core WordPress function in these various screens. Specifically `wp_enqueue_code_editor`.

I'm willing to be wrong though, don't get me wrong, but the found "solution" is just removing a newly added feature for CMB2.

**Comment by pareshsojitra** [comment]
- I think the problem is : codemirror library is getting loaded in all pages in WP admin and because of that its affecting other plugin pages/features like WP import, Revolution Slider etc.

- To avoid conflict it should be load in CMB Page/Features only.

**Comment by tw2113** [comment]
Logically, limiting where possible makes total sense, but the question ends up being how to do that successfully, when CMB2 can be added to both post editor screens as well as term editor screens. All of which may have these other libraries/plugins included as well.

We could check, if not done already, if there's a field type that uses this codemirror lib before adding, however once there is, the same conflict is potentially going to show up. There still needs to be compatibility resolution from these other items as well.

**Comment by jtsternberg** [comment]
[2.4.2](https://github.com/CMB2/CMB2/releases/tag/v2.4.2) addresses this issue and only enqueues WP's code editor functionality if a `textarea_code` field is found on the page.

**Comment by pareshsojitra** [comment]
Thank you so much for your fixes

**Comment by jtsternberg** [comment]
That being said, this conflict only partially mitigates the issue.. The version of code mirror in core is the one that all plugins need to be using to avoid conflicts. Please spread the word to those other plugins.
