### ISSUE TITLE
show_on_cb overridden by show_on

### ISSUE THREAD

**Issue by JBCSU** [CMB2/CMB2#1111]
I'm defining a metabox that I want to show only on one specific page template AND only for admins. My code to create the metabox therefore includes both the `show_on` and `show_on_cb` options, as follows:

### CMB2 Metabox Code:

```php
    $subscribe = new_cmb2_box( [
        'id'           => 'subscribe'
      , 'title'        => __( 'Subscribe', 'stanford-text-domain' )
      , 'object_types' => [ 'page' ]
      , 'show_on'      => [
            'key'      => 'page-template'
          , 'value'    => 'page-mailchimp-archive.php'
        ]
      , 'show_on_cb'   => [ $this, 'show_for_admins_only' ]
      , 'context'      => 'normal'
      , 'priority'     => 'high'
      , 'show_names'   => TRUE
    ] );

  /**
   * @param  CMB2 $param - ignored
   * @return bool
   */
  public function show_for_admins_only( $cmb ) {
    return current_user_can( 'manage_options' );
  }
```

### Expected Behavior:

I've confirmed that, when I'm logged is an editor, the `show_for_admins_only()` function returns `FALSE`. I therefore expect that the metabox will not display for editors.

### Actual Behavior:

The metabox displays for everyone who edits a page with the `page-mailchimp-archive.php` page template. The `show_on_cb` is effectively ignored.

It appears that the `show_on` logic, which tests for the correct the page template, occurs after invoking the `show_on_cb` callback, and the last Boolean wins. I think as soon as a `FALSE` is seen, testing for whether or not to display a metabox should stop, and the metabox should be not be displayed.

### Versions
WordPress: 4.9.4
CMB2: 2.3.0

**Comment by tw2113** [comment]
Not sure exactly the workflow logic intended, but It'd probably be best to use one or the other. At least that's what I'd end up doing. The "show on" for template value is just grabbing the meta key/value pair for the template selected, so you could easily do that in the callback you create.
