### ISSUE TITLE
wysiwyg field on widgets don't render editor tabs

### ISSUE THREAD

**Issue by rubengc** [CMB2/CMB2#1112]
### Expected Behavior:

See Visual and Text tabs wysiwyg field on widgets screen, as WordPress Text widget

### Actual Behavior:

The editor is rendered in "Text mode" and tabs aren't rendered, so there is no way to change to visual mode

Also, the HTML for this tabs isn't rendered too, so the .wp-editor-tabs element is completely empty

### Steps to reproduce (I have confirmed I can reproduce this issue on the trunk branch):

1. Add the wiget-example.php provided by @jtsternberg here:
https://github.com/CMB2/CMB2-Snippet-Library/blob/master/widgets/widget-example.php

2. Register a widget with a wysiwyg field (behavior not changes adding more fields)

**Comment by jtsternberg** [comment]
Thanks for reporting. That snippet definitley needs work before it can be considered "supported" ([see description](https://github.com/CMB2/CMB2-Snippet-Library/blob/master/widgets/widget-example.php#L4)), and I also don't usually accept issues for the snippet library in this repo. The snippet library is meant to be a community dropbox for CMB2 code, with no support/warranties, and likely will need tweaking to make work for each person's' setup.

If you'd like, please feel free to submit a PR to that repo for any suggested improvements.

**Comment by rubengc** [comment]
Ok no problem, anyway, do you know why this issue happens? or how editor tabs are instanced?

**Comment by rubengc** [comment]
It looks that issue comes from how CMB2 renders wysiwyg field

The textarea has an id like: `{widget_prefix}[{widget_instance}][{field_id}]`

and switchEditor from WordPress editor.js will try to get the editor textarea by his id attribute with a selector like: `$('#'+id)`

and how textarea has as id the characters `[` and `]` it causes an selector error on jQuery

Probably thats why editor tabs isn't rendered

**Comment by rubengc** [comment]
Ha! Get it working, wp_editor() id args requires sanitization, just adding this changes on class [CMB2_Type_Wysiwyg line 57](https://github.com/CMB2/CMB2/blob/trunk/includes/types/CMB2_Type_Wysiwyg.php#L57) get it working!

Current code:
`wp_editor( $args['value'], $args['id'], $args['options'] );`

Change that fix the issue:
`wp_editor( $args['value'], sanitize_html_class( $args['id'] ), $args['options'] );`
