### ISSUE TITLE
Submenu options page doesn't populate input fields once saved!

### ISSUE THREAD

**Issue by dameer** [CMB2/CMB2#1113]
When options-page registered out of existing parent (admin page) everything works just fine. However, when you register a submenu options page for the custom post type menu the following issue pops up. Registered fields do not get populated with values saved, they rather remain empty.

Expected Behavior:
Input fields should be saved and show inserted values on admin page reload.

Actual Behavior:
Input fields ARE saved but remain empty as if nothing is saved. 
`var_dump( get_option( PREFIX . 'some_page' ) )` indicates that values are saved.

```
add_action( 'cmb2_admin_init', 'func_create_required_metaboxes' );
function func_create_required_metaboxes() {

	$test = new_cmb2_box( array(
	
		'id'           => PREFIX . 'prefixed',
		'title'        => esc_html__( 'TEST', 'dc' ),
		'object_types' => array( 'options-page' ),
		'option_key'      => PREFIX . 'some_page', // The option key and admin menu page slug.
		'parent_slug'     => 'edit.php?post_type=some_post_type', // Make options page a submenu item of the themes menu.
	
	) );
	
	$group_test = $test->add_field( array(
	
		'name' => esc_attr__( 'Group', 'dc' ),
		'id'          => PREFIX . 'group_id',
		'type'        => 'group',
		'repeatable'  => false, // EITHER false OR true, options do not get populated
		'description' =>  esc_attr__( 'Testing options', 'dc' ),
		'options'     => array(
			'group_title'   => esc_attr__( 'Feature {#}', 'dc' ), // since version 1.1.4, {#} gets replaced by row number
			'add_button'    => esc_attr__( 'Add New', 'dc' ),
			'remove_button' => esc_attr__( 'Remove', 'dc' ),
			'sortable'      => true, // beta
		),
		
	) );
	
	$test->add_group_field( $group_test, array(
	
		'name' => esc_attr__( 'Input', 'dc' ),
		'description' =>  esc_attr__( 'Description', 'dc' ),
		'id'   => 'input_id',
		'type' => 'text',
		
	) );
	
	$test->add_group_field( $group_test, array(
	
		'name' => esc_attr__( 'Input 2', 'dc' ),
		'description' =>  esc_attr__( 'Description 2', 'dc' ),
		'id'   => 'input_id_2',
		'type' => 'text',
		
	) );

}
```

**Comment by tw2113** [comment]
Not managing to recreate the issue with fields not displaying at the moment.

https://cloudup.com/cgyAHqUdvlH

Only things I changed from the code used above is setting the post type to be a submenu of, and removing the PREFIX usage, as it was throwing PHP notices. Even with those in place though, values were persisting for me.

That's not to say you're not experiencing issues with it still, just indicating it may be a detail coming from other parts of the current site.

**Comment by dameer** [comment]
After long long run, I finally spotted troublemaker. Believe it or not it's SiteOrigin Page Builder plugin. I still can't figure out how come and why so I guess there's another long run ahead of me.
Thanks for a hint buddy, I appreciate your efforts!

**Comment by tw2113** [comment]
Welcome.

Nope, sadly I don't know what conflict may be coming from that bundle that could be causing conflict here. It'd be something that'd need investigation.
