### ISSUE TITLE
taxonomy_radio_inline don't work  with group field!!

### ISSUE THREAD

**Issue by johndiego** [CMB2/CMB2#1114]
```
$group_field_id = $posts->add_field( array(
		'id'          => $prefix . 'grupo_detalhes',
		'type'        => 'group',
		'description' => __( 'DETALHES DO IMOVEL', PROJETO ),
		'repeatable'  => false,
		'options'     => array(
			'group_title'   => __( 'DETALHES  {#}', PROJETO ), 
			'add_button'    => __( 'ADICIONAR NOVO DETALHE', 'cmb2' ),
			'remove_button' => __( 'REMOVER', 'cmb2' ),
			'sortable'      => false, // beta
			// 'closed'     => true, // true to have the groups closed by default
		),
	) );
	$posts->add_group_field($group_field_id, array(
		'name' => 'COMPOSICAO',
		'id'   => $prefix . 'composicao',
		'taxonomy'       => 'myyaxno',
		'type'           => 'taxonomy_radio_inline',
		'remove_default' => 'true'
	) );

	$posts->add_group_field( $group_field_id, array(
		'id'   => $prefix . 'quantidade_composicao',
		'name' => __( 'QUANTIDADE', PROJETO ),
		'title' => esc_html__( 'Quantidade', PROJETO), 
		'type' => 'text',
		'attributes' => array(
			'type' => 'number',
			'pattern' => '\d*',
		),
		'sanitization_cb' => 'absint',
			'escape_cb'       => 'absint',
	) );
````

Group field don't save values corretly.!! 
Just save defaults  values.

**Comment by tw2113** [comment]
I want to point out the note that's right after the "taxonomy_radio_inline" item in the list at https://github.com/CMB2/CMB2/wiki/Field-Types#types

"* Default Category/Tag/Taxonomy metaboxes replacement."

Basically this field type does not save anything as post meta, it instead is meant to replace the default metabox that gets rendered for the given taxonomy type.

If you want a metabox section that saves term information as post meta, I recommend checking out and adapting https://github.com/CMB2/CMB2/wiki/Tips-&-Tricks#a-dropdown-for-taxonomy-terms-which-does-not-set-the-term-on-the-post to fit your needs.

**Comment by johndiego** [comment]
Thanks! @tw2113  work for -me!!
