### ISSUE TITLE
Anyone using wp-multilang to translate CMB2 (groups) metaboxes?

### ISSUE THREAD

**Issue by sandrodz** [CMB2/CMB2#1121]
https://github.com/VaLeXaR/wp-multilang/issues/48

**Comment by tw2113** [comment]
I haven't personally.

Which part are you intending to translate in this case? The generated UI or the data entered and saved when editing the post?

**Comment by sandrodz** [comment]
I had trouble with groups, but going through miltilang files I've found `wpm_each ` - solution is detailed in this issue: https://github.com/VaLeXaR/wp-multilang/issues/48
