### ISSUE TITLE
Rename "trunk" branch to "develop"

### ISSUE THREAD

**Issue by slaFFik** [CMB2/CMB2#1122]
I'm installing and using CMB2 via composer.
I need some changes from trunk, that will be avail in a next minor release (2.4).
To do that, I write `"webdevstudios/cmb2": "dev-trunk"` in `require` section of my `composer.json` file.
But composer installs `master` branch instead. 

I know, that this is a composer issue (due to its compatibility with SVN and its default trunk branch). But that doesn't help me to have a real `trunk` branch locally.

Could you please rename `trunk` branch to something what is more or less considered a standard: `develop` branch?

**Comment by jtsternberg** [comment]
That is an excellent question. What do you think could be some potential negative implications?

**Comment by slaFFik** [comment]
Current PRs against trunk may need a branch change. I don't know whether GitHub provides UI for that.
Docs and `.github` templates should be updated.

**Comment by slaFFik** [comment]
@jtsternberg 
Are there any plans to actually do that?
Packagist doesn't support `trunk` branch name, you can see that there is no `dev-trunk` branch here https://packagist.org/packages/cmb2/cmb2 in sidebar.

**Comment by jtsternberg** [comment]
Ok, [`develop`](https://github.com/CMB2/CMB2/tree/develop) has been created, and will be used from now on. PRs to trunk we'll leave as-is and can merge into `develop` if we get them merged.
