### ISSUE TITLE
Field data is not storing in database after save.

### ISSUE THREAD

**Issue by byananta** [CMB2/CMB2#1124]
I am using cmb2 group fields in custom post type. But the data is not storing after save the post type from yesterday before that it was working.

**Comment by tw2113** [comment]
Any changes to any part of the website since it was last working? Any updates applied?

**Comment by byananta** [comment]
Hi, Many many thanks for your prompt reply. I have found the problem. The problem was max_input_vars problem. Now it is working fine. Thanks again

**Comment by tw2113** [comment]
Welcome, glad you got this figured out :D
