### ISSUE TITLE
Taxonomy_Multicheck + Taxonomy_Select 

### ISSUE THREAD

**Issue by AntonioBodean** [CMB2/CMB2#1126]
Sorry for translation ...

How to assemble two categories together? For example, if you choose a user to be absent, and separate a right column to choose what type of absence, for example, vacation or travel leave ...

Can you help me how to add taxonomy select "Type of absence" in after mutickeck taxonomy? Thank you!

![taxonomy_multickeck- -taxonomy_select](https://user-images.githubusercontent.com/12821898/39385972-ccd4ca08-4a48-11e8-9e17-8eefba2729fc.png)

**Comment by tw2113** [comment]
As far as I'm aware, this is going to end up being a custom solution. I am familiar with any field types that do this.

Also, I must note that the taxonomy_* field types aren't going to save the values to post meta. They're going to assign as taxonomy terms. The types are meant to act as replacements for the default taxonomy metaboxes.

**Comment by AntonioBodean** [comment]
Already create the categories and personalized input from metabox.

![posts ausencia y permisos](https://user-images.githubusercontent.com/12821898/39395883-b2b3e83a-4aba-11e8-917f-3371e36e5cf6.JPG)

How is it now in public on the intranet:

![posts ausencia y permisos 2](https://user-images.githubusercontent.com/12821898/39395915-5a34ebfe-4abb-11e8-8912-95263691c99d.JPG)

Now I need to post the type of absence ... Can you explain me as a personalized solution?

Thanks for answering!

**Comment by tw2113** [comment]
Closing as not a core bug, until proven otherwise.
