### ISSUE TITLE
meta in taxonomy

### ISSUE THREAD

**Issue by ashkankiani** [CMB2/CMB2#1127]
post type: product
best load page: taxonomy-{product-category}
Products also have a taxonomy colors
(taxonomy colors have a term Color) and
(term Color also have a metabox text), ID metaBox Text => text-color

load loop :

<?php if ( have_posts() ) : ?>
    <?php while ( have_posts() ) : the_post(); ?>

    
    <?php $name = get_post_meta( get_the_ID(), 'name', true ); ?>

    

    <?php endwhile; else : ?>
    <p><?php _e( 'no posts.' ); ?></p>
<?php endif; ?>

in here => How can I have all the meta boxes of posts(product) and all term taxonomic colors of posts(product) with text values(text-color)?

**Comment by tw2113** [comment]
Hard to say for sure where the data you're wanting is stored without seeing your CMB2 config code. However, if it's for sure saving as term meta, then you're not using the correct functions in your loop to get the data.

You're going to need to get the IDs for the terms associated with the post, and use those term IDs with `get_term_meta()`, not `get_post_meta()`.

**Comment by tw2113** [comment]
Closing for the time being. If @ashkankiani or someone else comes back with more information, we can address at that time.
