### ISSUE TITLE
file_list file download button not downloading file

### ISSUE THREAD

**Issue by cggit** [CMB2/CMB2#1130]
When uploading a PDF or Doc as a field type of "file_list" the resulting Download button from (Download/Remove) opens a media modal instead of downloading.

My fix is
js/cmb2.js line 77 to
`.on( 'click', '.cmb2-media-status .img-status, .cmb2-media-status .file-status > span', cmb.handleFileClick )`

and 

js/cmb2.js line 169 to
`var $el    = $( this ).hasClass('cmb2-media-item') ? $(this) : $(this).closest('.cmb2-media-item');`

Can someone else confirm the problem and solution?

**Comment by jtsternberg** [comment]
Can you paste the before/after code or open a PR, or link to the related lines in github? The lines you are referencing do not make sense.

https://github.com/CMB2/CMB2/blob/trunk/js/cmb2.js#L77 
https://github.com/CMB2/CMB2/blob/trunk/js/cmb2.js#L169

**Comment by jtsternberg** [comment]
I think it should be good now. Please test the trunk branch.

**Comment by cggit** [comment]
Great. That works too and is most slick! I updated my comment just so I know how to properly reference next time
