### ISSUE TITLE
Colorpicker field doesn't load its js/css if bring a form to the front-end

### ISSUE THREAD

**Issue by aposidelov** [CMB2/CMB2#1131]
After exposing cmb2 form as a shortcode on a custom frontend page it seems that colorpicker doesn't load its js/css and only its text field is shown. 

### Expected Behavior:
Colorpicker field is shown and works normally.

### Actual Behavior:
Only colorpicker text field is shown. No colorpicker js/css is applied.
https://www.screencast.com/t/r6H0PPjyC6D

### Steps to reproduce

1. Go to 'Add Page' form (Pages > Add new)
2. Page Title: Custom page
3. Page Content: [cmb_frontend_form]
4. Click Publish button and go to (/custom-page) to see a form

### CMB2 Field Registration Code:

```php
add_action( 'cmb2_init', 'bt_cmb2_frontend_form_metabox' );
add_shortcode( 'cmb_frontend_form', 'bt_cmb2_frontend_form_shortcode' );

function bt_cmb2_frontend_form_metabox() {
  $cmb = new_cmb2_box( array(
    'id'           => 'bt_frontend_form',
    'title'        => esc_html__( 'Frontend form', 'cmb2' ),
    'object_types' => array( 'post' ),     
    'hookup'        => false,
    'save_fields' => false,    
  ) );  

  $cmb->add_field( array(
    'name'    => 'Text 1',        
    'id'      => 'text1',    
    'type'    => 'text',
  ) );
  $cmb->add_field( array(
    'name'    => 'BG',
    'id'      => 'bg',
    'type'    => 'colorpicker',
    'default' => '#ff0f00',    
  ) );
}

function bt_cmb2_frontend_form_shortcode( $atts = array() ) {
  $output = '';
  $cmb = cmb2_get_metabox( 'bt_frontend_form', 'custom' );
  $output .= cmb2_get_metabox_form( $cmb, 'custom', array( 'save_button' => __( 'Save', 'cmb2' ) ) );
  return $output;
}
```

**Comment by tw2113** [comment]
Probably just not enqueuing them like needed, especially since those resources may be more an admin-side resource that WordPress uses. You would need to determine their resource handles and enqueue them manually alongside the rest of your code above.

For what it's worth, we don't have any sort of flags or ways to know where these items are being loaded, so we don't have any way to predict when they should be loaded for you.

**Comment by tw2113** [comment]
Closing as not an issue with CMB2 core itself, but feel free to continue commenting as needed.
