### ISSUE TITLE
Tabbed navigation for options-page without submenus - with single option_key

### ISSUE THREAD

**Issue by manzoorwanijk** [CMB2/CMB2#1139]
As version 2.4.0 introduces tabbed navigation for options-pages. Is there a simple way to create those tabbed pages without creating the submenus? Preferably with single option_key

Example
![image](https://user-images.githubusercontent.com/18226415/40554826-9952822e-6064-11e8-9117-26925d7539c5.png)

**Comment by manzoorwanijk** [comment]
@taunoha, that looks close enough but I wanted all the tab fields in single option key. The tab navigation should be JavaScript based without page reload.
I have now myself built something cool on those lines, just finishing it up :)

**Comment by JiveDig** [comment]
I'm looking to do the same thing. Using the same option key, but breaking up the fields into tabs would be a great addition. I'll beed to roll something up myself as well I think.

**Comment by taunoha** [comment]
Could you please explain why you need to use the same option key? What is the use case?

**Comment by tw2113** [comment]
Using the same option key makes sense in my head at least, since it's still all one set of options, it's just visually separated out and organized via some tab sections.

**Comment by manzoorwanijk** [comment]
@taunoha for example if there is a theme/plugin which has too many options to customise, it makes the page too long. It can easily be divided (visually into tabs). Creating separate menus and thus different option keys doesn't make sense in such case.

**Comment by tw2113** [comment]
At least in regards to the submenu items getting added, I have whipped up this quick snippet which will feel really straightforward.

```
function wpcodex_adjust_the_wp_menu() {
	remove_submenu_page( 'MY-MENU-SLUG', 'MY-SUBMENU-SLUG' );
}
add_action( 'admin_menu', 'wpcodex_adjust_the_wp_menu', 999 );
```

Only downside thus far is that the Options page i'm doing this for loses menu highlight on the secondary tabs.

**Comment by tw2113** [comment]
Perhaps a `show_submenu` parameter could be added for `options_page_menu_hooks()`

**Comment by tw2113** [comment]
Any settings moved to new tabs will need to have option fallbacks for sake of fetching current settings for new setting.

Perhaps check for our current/new option first, and if that doesn't exist yet, check the original option name/value for a setting to use or save.

Also would be awesome to wire up the same idea above for when loading the new tab pages, and pre-populate. Utilize the filters in CMB2 for altering where to check for values.

**Comment by pgroot91** [comment]
@tw2113 came also up with the same solution. I didn't came up with a solution to keep the main menu item highlighted/active when navigation to the other pages.

**Comment by tw2113** [comment]
I hadn't delved into it last night, but my mind was thinking see if there's some way to fake it with some admin css and jquery or so. Will need exploring there.

**Comment by tw2113** [comment]
At least from my testing/tinkering last night, it was still showing the fields/tab content and saving it. It's the secondary tabs that i'm hiding, not the primary one, which gets specified as the parent.

I won't say this is a for-sure solution cause I still need to keep tinkering, but I presently feel it'll work for my needs in the long term.

**Comment by pgroot91** [comment]
Just wanted to let you guys know that i have finally found a solution that works!

This is not my solution but i found this on stackoverflow and edited it based on the CMB2 demo provided: 

```
function yourprefix_remove_submenus_and_highlight_first_submenu_item( $submenu_file ) {

    global $plugin_page;

    $hidden_submenus = array(
	
		// Uncomment "yourprefix_main_options" for removing all submenus
		//'yourprefix_main_options' => true,
        'yourprefix_secondary_options' => true,
		'yourprefix_tertiary_options' => true,
    );

    // Select another submenu item to highlight (optional).
    if ( $plugin_page && isset( $hidden_submenus[ $plugin_page ] ) ) {
        $submenu_file = 'yourprefix_main_options';
    }

    // Hide the submenu.
    foreach ( $hidden_submenus as $submenu => $unused ) {
        remove_submenu_page( 'yourprefix_main_options', $submenu );
    }

    return $submenu_file;
}
add_filter( 'submenu_file', 'yourprefix_remove_submenus_and_highlight_first_submenu_item' );
```
