### ISSUE TITLE
TinyMCE missing word count

### ISSUE THREAD

**Issue by andrewatduckpin** [CMB2/CMB2#1141]
### Expected Behavior:
When using the WYSIWYG field type, tinyMCE is loaded via wp-includes, just like on a default page content box. The expected behavior is that CMB2 WYSIWYG fields powered by tinyMCE would include the word count feature found on standard WP visual editor.

### Actual Behavior:
There is no word count on the CMB2 WYSIWYG field.

### Steps to reproduce (I have confirmed I can reproduce this issue on the trunk branch):

1. Create WYSIWYG field in CMB2 config
2. Go to page or post that uses the above field
3. Start typing
4. In the bottom left, the word count is not present

To see the word count in action, go to any WP page on the default template and type in the standard visual editor.

**Comment by tw2113** [comment]
At least based on https://wordpress.stackexchange.com/questions/196101/embed-and-word-count-not-working-for-wp-editor-instance it may not be a feature made available outside of the primary editor for the editor screen. Given that we'd be working with post meta for this, it wouldn't work.

**Comment by jtsternberg** [comment]
As @tw2113 said, this is not a CMB2 issue. However, looking at the WordPress core code, it was easy enough to swipe it and replace with a CMB2 `wysiwyg` field id. I'll get something in the snippet library shortly.

**Comment by jtsternberg** [comment]
Snippet added: https://github.com/CMB2/CMB2-Snippet-Library/blob/master/misc/adding-wordcount-to-cmb2-wysiwyg-field.php
