### ISSUE TITLE
Meta box content is pulled through to front end but stripped of all formatting

### ISSUE THREAD

**Issue by chr0s** [CMB2/CMB2#1144]
Hi, I've followed video tutorials and used code given in the basic usage section, and am encountering an issue. I have three meta boxes: a text, a wysiwyg, a file list. All are displaying properly in the back-end; all are being pulled through to the front end.

The problem is that they are being pulled through incorrectly. The wysiwyg file just displays the code, rather than rendering it (so '`<strong>example</strong>`' rather than '**example**'). The file list just returns the word 'Array'.

Below are three images showing the snippet of the functions.php code where the meta boxes are registered, the code to pull through the meta data in the template file, and the output.

<img width="213" alt="code in functions" src="https://user-images.githubusercontent.com/6866562/40991625-3be54726-68ec-11e8-9892-e12bf39778c6.png">
<img width="403" alt="code in template files" src="https://user-images.githubusercontent.com/6866562/40991626-3c092678-68ec-11e8-9430-2c9e5b44b2db.png">
<img width="565" alt="output" src="https://user-images.githubusercontent.com/6866562/40991627-3c2a3f52-68ec-11e8-98e6-b41036d81958.png">

**Comment by chr0s** [comment]
Hero, thank you. That fixed the wysiwyg, although the file list gallery is still just showing the word "array". I've removed all instances of esc_html - do you know what could be affecting the gallery?

**Comment by tw2113** [comment]
Whenever you see "Array" when you echo a value, that means you're receiving an array back, instead of a string. In those cases, you'll need to do something like a foreach loop on the variable to actually echo out the contents in each array index. I can't recall off the top of my head what the overall structure is for this field type, but I think the array indexes are the attachment ID, and the values stored are either a full `<img>` tag or at least the image URL that you can drop into an `<img src="">` setup to echo that much out.

**Comment by tw2113** [comment]
Closing as not an issue with the plugin itself. We can still discuss as needed in the issue despite the closed status.

**Comment by chr0s** [comment]
Thank you! I found [this page](https://github.com/cmb2/cmb2-snippet-library/blob/master/front-end/output-file-list.php) - if I replace `file_list_meta_key` with my file_list id, will that be on the right track?

**Comment by tw2113** [comment]
That snippet is meant to be used inside the loop. Notice the use of `get_the_ID()` in there. the `$file_list_meta_key` is going to need to be "writing_gallery" from your screenshot above. If you're not already in the loop, then you would need to amend the functions to accept an ID.

However, based on everything shown, you'd just need to do the following and you should get something Make sure to specify the size you want for the image:

```
jt_cmb2_file_list_images( 'writing_gallery', 'full' );
```

**Comment by chr0s** [comment]
Lovely, I've got it working now. Thanks a lot for your help - bit off a little bit more than I could chew I think!

**Comment by tw2113** [comment]
all the while also providing a good learning experience to expand your skills and grow as a developer ;)

**Comment by chr0s** [comment]
Absolutely!
