### ISSUE TITLE
Cannot Set A Static Field Value

### ISSUE THREAD

**Issue by cupcakedream** [CMB2/CMB2#1154]
Hey All - I've combed thru the internet and wiki but it looks like this is (surprisingly) not supported. I have an options page with a hidden field and I want the value to be the current timestamp when saving. It looks like there is no way to set a static value for fields. 

```
$cmb->add_field( array(
		'id'   => 'lc-save-date',
		'type' => 'hidden',
		'value' => strtotime('now'),
	));
```

**Comment by jtsternberg** [comment]
Try this:
```php
$cmb->add_field( array(
	'id'         => 'lc-save-date',
	'type'       => 'hidden',
	'default_cb' => 'time',
));
```

**Comment by cupcakedream** [comment]
Unfortunately that didn't work - this is the initialization if it helps:

```
$cmb = new_cmb2_box( array(
		'id'           => 'lc-notices',
		'title'        => 'Notices',
		'object_types' => array( 'options-page' ),
		'option_key'      => 'lc-notices',
		'parent_slug'     => 'edit.php?post_type=page',
	) );
```

**Comment by jtsternberg** [comment]
Hmm, definitely works for me: 
![](http://b.ustin.co/MDfQY9+)

**Comment by cupcakedream** [comment]
What about after you save it to the DB - is the value set to the old value or the new value?

**Comment by jtsternberg** [comment]
It's set to the old value. That's the way the `default_cb` works... it will only use the default if there is no value saved in the DB. Once that default is saved to the DB, it no longer uses the `default_cb`.

If you don't want it save at all, you can add `'save_field' => false,`.

I definitely recommend checking out the field parameters wiki docs: https://github.com/CMB2/CMB2/wiki/Field-Parameters

**Comment by cupcakedream** [comment]
Thanks for responding - I understand all of that. What i'm looking for is to statically set the field value - even if there is a value saved in the DB - the value would still be the static value.

**Comment by jtsternberg** [comment]
Ah, pardon me for being dense. In the case of many fields, you should be able to override/define the value statically by overriding the `value` attribute. I think this one will accomplish what you're looking to do, if what you are trying to do is to save the current timestamp whenever the cmb data is updated:

```php
$cmb->add_field( array(
	'id'         => 'lc-save-date',
	'type'       => 'hidden',
	'attributes' => array(
		'value' => time(),
	),
));
```

**Comment by cupcakedream** [comment]
Perfect - i'll give this a try - thanks!

**Comment by cupcakedream** [comment]
This worked - thanks again!
