### ISSUE TITLE
Wysiwyg visual tab doesn't save content when Gutenberg is also activated

### ISSUE THREAD

**Issue by LC43** [CMB2/CMB2#1156]
### Expected Behavior:

When saving a post, the contents of the field are saved.

### Actual Behavior:

The changes are not saved. They're only saved when using the tab "text".

 

### Steps to reproduce

I have confirmed I can reproduce this issue on the trunk branch: :heavy_check_mark: 

1. Enable CMB2 & Gutemberg

2. Add wysiwyg field

3. Edit a post and add content to the field wysiwyg 'Content', on the tab "Visual".

4. Refresh and notice that the content is **not saved**.

5. Edit a post and add content to the field wysiwyg 'Content', on the tab "Text".

6. Refresh and notice that the content is **saved**.

### Versions

* CMB2 : 2.4.2
* Gutenberg :  3.4.0
* WP : 4.9.7

### CMB2 Field Registration Code:

```php
add_action( 'cmb2_admin_init', 'yourprefix_register_demo_metabox' );
function yourprefix_register_demo_metabox() {

		$prefix = '_our_info_';

		$cmb = new_cmb2_box( array(
			'id'            => 'test_id',
			'title'         => 'Details',
			'object_types'  => array( 'post' ),
			'context'       => 'normal',
			'priority'      => 'high',
			'show_names'    => true,
		) );

		$cmb->add_field( array(
			'name'        => __( 'Content', 'our-post-types' ),
			'description' => __( 'Has limit space.', 'our-post-types' ),
			'id'          => $prefix . 'description',
			'type'        => 'wysiwyg',
		) );

	// Additional fields...
}
```

**Comment by tw2113** [comment]
@jtsternberg I can confirm saving issues with the Visual tab. Curious if there are errors between Gutenberg's React code and CMB2.

Also something that could trickle its way in to WordPress core since we're using WP api functions for the secondary WYSIWYG sections.

**Comment by LC43** [comment]
hi!

meanwhile, i found this other issue https://github.com/CMB2/CMB2/issues/1112. Later on, i'll try to see if the sanitization is being overwritten somewhere.

**Comment by wpalchemist** [comment]
Confirming that I am running into this issue as well.

**Comment by helena-reshift** [comment]
I have the same problem, Is there any soluton yet?

**Comment by shoelaced** [comment]
Same!

**Comment by geekyposh** [comment]
Also running into this problem.

**Comment by jtsternberg** [comment]
FWIW, I have found it will save if you use the text tab/view or if you toggle to/from the text view before saving. It looks like for some reason it's not always updating the hidden `<textarea>` field when editing.

**Comment by AndreaBarghigiani** [comment]
Same here, anyone have found a better solution that hit the text tab? I can't doploy this to a client site 😞

**Comment by staurand** [comment]
From what I can see, the Tinymce editor updates the hidden `<textarea>` when the parent form is submitted.
However the metabox form is not submitted with Gutenberg.
The code below (pasted in the console) fix the problem.
(update Tinymce editors when the post is saved)
`wp.data.subscribe(function () {
   if (wp.data.select( 'core/editor' ).isSavingPost()) {
     if (window.tinymce && window.tinymce.editors) {
	for (var i = 0; i < tinymce.editors.length; i++) {
	  tinymce.editors[i].save();
	}
    }
  }
});`
Not sure where it should go in CMB2 code or if it should be in CMB2 at all...

The source of the problem is already identified in Gutenberg doc:
https://wordpress.org/gutenberg/handbook/extensibility/meta-box/#common-compatibility-issues
"Here are some common reasons why meta boxes might not work as expected in Gutenberg: [...]  Plugins making updates to their DOM on “submit” or on “save”."

**Comment by jtsternberg** [comment]
Thanks @staurand, fixed!

**Comment by helena-reshift** [comment]
> Thanks @staurand, fixed!

Sorry for the stupid question but how can i get the solution working on my site? I've updated CMB2 plugin to 2.4.2 version - still didn't fix it.

**Comment by helena-reshift** [comment]
> @helena-reshift it's not released yet to say wordpress.org or so yet. You'd need to download and test with a copy of the develop branch for CMB2 here on GitHub.

i see! thanks!
My only small concern is that looks like here on github there is more files than in the plugin. Is there a manual or some tips on how to use dev copy from github? Sorry, i should probably know this but i'm a bit lost.

**Comment by tw2113** [comment]
There definitely are as GitHub here holds all the build tools that are used to compile the final results that you see released on wordpress.org

Should still be able to drop the overall checkout of the repo into a folder into the plugins folder and activate. At least last I checked.
