### ISSUE TITLE
Live previews don't work for oEmbed fields within a repeatable group

### ISSUE THREAD

**Issue by johnbillion** [CMB2/CMB2#1157]
### Expected Behavior:

When an `oembed` field type is present within a repeatable group, it should function as normal.

### Actual Behavior:

The live Ajax-powered embed preview does not function, because the call to `cmb2_ajax()` never triggers, and thus its Ajax handlers are never registered. Ref: https://github.com/CMB2/CMB2/blob/393388b759f4b23cca84b7436543bf11966f12e1/includes/CMB2.php#L1444-L1449

### Steps to reproduce (I have confirmed I can reproduce this issue on the trunk branch):

1. Register a repeatable group and place an `oembed` field type in it.
2. Paste an embed URL into the oEmbed URL input field.
3. Observe that the live preview doesn't function. The Ajax call responds with `0` because there's no registered Ajax handler for the oEmbed preview.

### CMB2 Field Registration Code:

```php
add_action( 'cmb2_init', function() {
	// Meta box
	$cmb_main_box = new_cmb2_box( [
		'id'           => 'main_box',
		'title'        => 'Main Content',
		'object_types' => [
			'post',
		],
	] );

	// Repeatable embed group
	$cmb_embed_group = $cmb_main_box->add_field( [
		'id'         => 'embeds',
		'repeatable' => true,
		'type'       => 'group',
	] );

	// Repeatable field: embed
	$cmb_main_box->add_group_field( $cmb_embed_group, [
		'id'      => 'url',
		'name'    => 'Embed URL',
		'type'    => 'oembed',
	] );
} );
```

**Comment by Fiorinol** [comment]
I'm having this issue as well and I've noticed nobody commented on it in more than a year. Is there a way to register an ajax handler for this?
