### ISSUE TITLE
How to create a default entry for a repeatable group?

### ISSUE THREAD

**Issue by manzoorwanijk** [CMB2/CMB2#1160]
I have a repeatable group for which I want to have a default entry instead of the default values for the group fields. Also, is it possible to make that default entry non-deletable?

**Comment by tw2113** [comment]
Just for my clarity sake, you mean default values set in this?

```
$cmb_group = new_cmb2_box( array(
	'id'           => $prefix . 'metabox',
	'title'        => esc_html__( 'Repeating Field Group', 'cmb2' ),
	'object_types' => array( 'page' ),
) );
```

For that last part, I know I work on a project that prevents deletion of a field by simply hiding the remove button via js/css. Simply uses `jQuery.hide()` on it with the specific field group's selector.

**Comment by manzoorwanijk** [comment]
I mean the value for the [default parameter](https://github.com/CMB2/CMB2/wiki/Field-Parameters#default) of the group field.

Yes, jQuery can be used for that. Thanks

**Comment by tw2113** [comment]
Ah

While I haven't tested anything, I wonder if you could wire up a way to save some post meta upon post creation. It'd be a case, in my mind, of using CMB2 to create an entry the way you want it to be default, then grab the meta value stored for that, and use it for the auto-creation at the start. Biggest challenge I can see with this idea though, is making sure it's shown and available once the page loads. Just throwing some ideas out there, as I don't believe there's anything for that out of box with CMB2.

**Comment by manzoorwanijk** [comment]
I need it for options_page. I tried to look for an appropriate hook to use for setting the defaults for a group field but couldn't find one.

**Comment by manzoorwanijk** [comment]
I finally decided to use ["cmb2_override_{$a['field_id']}_meta_value" hook](https://github.com/CMB2/CMB2/blob/v2.4.2/includes/CMB2_Field.php#L287) this way:
```php
add_filter( 'cmb2_override_my_group_meta_value', function ( $data, $object_id, $args, $cmb ) {

	// If there is no value for the field
	if ( empty( cmb2_options( $args['id'] )->get( $args['field_id'] ) ) ) {

		$my_field1 = get_my_field1();
		$my_field2 = get_my_field2();

		$data = array( compact( 'my_field1', 'my_field2' ) );
	}
	return $data;
}, 10, 4 );

**Comment by tw2113** [comment]
That would definitely be one way to achieve this, yep. Glad to hear something was figured out. :D
