### ISSUE TITLE
textarea_code: disabled attribute doesn't work

### ISSUE THREAD

**Issue by slaFFik** [CMB2/CMB2#1161]
### Expected Behavior:

Disabled `textarea_code` field should not be editable.
So typing there should do nothing AND visually the field should indicate somehow that it's not editable.

### Actual Behavior:

Disabled `textarea_code` field is editable, although data is not saved.

### Steps to reproduce:

- [x] I have confirmed I can reproduce this issue on the trunk branch

1. Add a `textarea_code` field with disabled attribute
2. It is still editable.

### CMB2 Field Registration Code:

```php
add_action( 'cmb2_admin_init', 'yourprefix_register_demo_metabox' );
function yourprefix_register_demo_metabox() {

$main_options = new_cmb2_box(
		array(
			'id'           => 'test_settings_general',
			'title'        => 'Main Options',
			'object_types' => array( 'options-page' ),
			'option_key'   => 'test_main_options',
			'tab_group'    => 'test_main_options',
			'tab_title'    => 'Main',
			'display_cb'   => 'test_options_display_with_tabs',
			'autoload'     => true,
		)
	);
	$main_options->add_field(
		array(
			'name'    => 'Some Text',
			'id'      => 'textarea_code',
			'type'    => 'textarea_code',
			'default' => '<p>Hello</p>',
			'attributes' => [
				'disabled' => true,
			],
		)
	);
}
```

### Solution

Here is how to fix: https://codemirror.net/doc/manual.html#option_readOnly
Just pass the value of `disabled` to `readOnly` option in CodeMirror.

**Comment by tw2113** [comment]
Isn't this type of field a "super textarea" similar to how like the post editor is? Curious if that's playing a part in everything here.

Maybe an alternative solution would be conditional display of the field, using other extensions from CMB2, for the time being.

**Comment by jtsternberg** [comment]
If you're using the the `textarea_code` in its new default codemirror mode, you can tell it to be readonly via the following config:

```php
$main_options->add_field(
	array(
		'name'    => 'Some Text',
		'id'      => 'textarea_code',
		'type'    => 'textarea_code',
		'default' => '<p>Hello</p>',
		'attributes' => [
			'disabled' => true,
			'data-codeeditor' => json_encode( [
				'codemirror' => [
					'mode' => 'css',
					'readOnly' => 'nocursor',
				],
			] ),
		],
	)
);
```

You can also disable codemirror if you prefer. I've added instructions for doing so in the wiki: https://github.com/CMB2/CMB2/wiki/Field-Types#textarea_code

**Comment by slaFFik** [comment]
Works for me, thank you for a detailed answer and wiki update!
