### ISSUE TITLE
How to get the value of an adjacent field (inside a repeatable group) in after_field callback ?

### ISSUE THREAD

**Issue by manzoorwanijk** [CMB2/CMB2#1162]
I have a repeatable group:
```php
$group_field_id = $cmb2->add_field( array(
    'id'            => 'my_group',
    'type'          => 'group',
    'repeatable'    => true,
) );
```
with a few fields
```php
$cmb2->add_group_field( $group_field_id, array(
    'name'              => 'Field 1',
    'id'                => 'field_1',
    'type'              => 'text_medium',
) );

$cmb2->add_group_field( $group_field_id, array(
    'name'              => 'Field 2',
    'id'                => 'field_2',
    'type'              => 'text_medium',
    'after_field'       => 'render_after_field_2',
) );
```
Then I have the callback
```php
function render_after_field_2( $field_args, $field ) {
    $id = $field->_id();

    $field_1 = ''; // How to?

    /**
     * Here I want to display the result of a server-side API call
     * based upon the value of `field_1` of this group entry
     * and same for all the other group entries.
     */
}
```

**Comment by tw2113** [comment]
How are these, thus far, being stored in the database? I assume $id is the post id that you could use to query data with?

**Comment by manzoorwanijk** [comment]
It's for the options-page. The data of the group is obviously stored like this
```
Array
(
    [0] => Array
        (
            [field_1] => some value like value_0_1
            [field_2] => some value like value_0_2
        )

    [1] => Array
        (
            [field_1] => some value like value_1_1
            [field_2] => some value like value_1_2
        )

    [2] => Array
        (
            [field_1] => some value like value_2_1
            [field_2] => some value like value_2_2
        )
)
```
Inside the callback, how do I know which entry is being rendered, 0, 1 or 2? I just need to know the index of the group entry that is currently rendered.

**Comment by tw2113** [comment]
Fun, an array of arrays. Don't have an immediate answer for you, but you'll need to find a way to either do array searching for values you want to compare against, or find a way to specify the accurate array key for the outer array.

**Comment by manzoorwanijk** [comment]
There is `$index` as the `CMB2_Field` attribute, which reads "**Grouped Field's current numeric index during the save process**"

I can do something like this
```php
function render_after_field_2( $field_args, $field ) {

    // get the group index
    $index = $field->group->index;

    // fetch the saved group value
    $group_val = $field->group->value();

    // get the field value
    $field_1 = $group_val[ $index ][ $field->_id() ];

    // use the value
}
```

It does the job, but I want to make sure this is the right way to do it.

**Comment by AhmadRaza9** [comment]
how to get the fields value that is registered with CMB2.....?

**Comment by tw2113** [comment]
@AhmadRaza9 all the post/user/term meta functions should work for you, as we don't store the data somewhere custom. The meta key is going to be the ID value you set for a given field.
