### ISSUE TITLE
Sharing metabox values

### ISSUE THREAD

**Issue by tfont** [CMB2/CMB2#1165]
Is it possible that two metaboxes with the same ID be able to share the same saved values?

```
$cmb_metabox = new_cmb2_box(
[
            'id'           => 'metaboxes,
            'title'        => 'Bottom Content',
            'object_types' => ['page'],
            'show_on'      => ['key' => 'page-template', 'value' => ['page-home.php', 'page-places.php']],
            'context'      => 'normal',
            'priority'     => 'high',
]);

$cmb_metabox->add_field(
[
            'name' => 'Title',
            'id'   =>'title',
            'type' => 'text',
]);
```

When saved on different post edit pages (e.g. page-home vs pages-place) there fields will have different values and not share the same values.

`$dd = get_the_post_meta('title', false);`

Is it possible that page-home.php and page-places.php to share the values? Being updated on either edit page.

**Comment by tw2113** [comment]
To a certain degree, yes. It wouldn't be dependent on metabox ID though, more post numeral IDs.

Override where you grab data from:
https://github.com/CMB2/CMB2/blob/trunk/includes/CMB2_Field.php#L251-L287

Override where you save data to:
https://github.com/CMB2/CMB2/blob/trunk/includes/CMB2_Field.php#L320-L354

You'll need to make one of your pages the primary one, and the other one dependent on that page.

I've used these filters personally to set up a metabox on post types that actually fetch and save data to the wp_options table, and then also a settings page that also saves to the same location. That way updating either spot reflected the same data appropriately.

**Comment by tw2113** [comment]
Closing since this isn't an issue with CMB2 itself. However, you can still comment and discuss, as needed.
