### ISSUE TITLE
Group with blank fields saves empty array

### ISSUE THREAD

**Issue by adamcapriola** [CMB2/CMB2#117]
If a group with unfilled fields is saved, an empty array `array ( )` is stored in the post meta. There should probably be a built-in check for this scenario before saving to prevent a potential buildup of void post meta.

``` php
add_filter( 'cmb2_meta_boxes', 'ac_meta_boxes' );

function ac_meta_boxes( array $meta_boxes ) {

    $meta_boxes['group_testing'] = array(
        'id'           => 'group_testing',
        'title'        => 'Group Testing',
        'object_types' => array( 'post' ),
        'context'      => 'normal',
        'priority'     => 'high',
        'show_names'   => true,
        'fields'       => array(
            array(
                'id'          => 'group_1',
                'type'        => 'group',
                'options'     => array(
                    'group_title'   => 'Group 1',
                    'add_button'    => 'Add',
                    'remove_button' => 'Remove',
                    'sortable'      => true
                ),
                'fields'      => array(
                    array(
                        'name' => 'Field 1',
                        'id'   => 'field_1',
                        'type' => 'text_small'
                    )
                )
            )
        )
    );

    return $meta_boxes;

}
```

WordPress version: 4.0.1
CMB2 version: 2.0.0.3

**Comment by ahm-3d** [comment]
i am getting the same issue but when use it in a created Theme Options page which calls the function below:

    function theme_options_metabox($metabox_id, $key) {

    $prefix = 'theme';
    $cmb_options = new_cmb2_box( array(
        'id'      => $metabox_id,
        'title'   => 'Theme Options',
        'hookup'  => false,
        'show_on' => array(
            'key'   => 'options-page',
            'value' => array( $key )
        )
    ) );

    $group_field_id = $cmb_options->add_field( array(
        'id'          => $prefix . 'demo',
        'type'        => 'group',
        'description' => __( 'Generates reusable form entries', 'cmb2' ),
        'options'     => array(
            'group_title'   => __( 'Entry {#}', 'cmb2' ),
            'add_button'    => __( 'Add Another Entry', 'cmb2' ),
            'remove_button' => __( 'Remove Entry', 'cmb2' ),
            'sortable'      => true,
        ),
    ) );

    $cmb_options->add_group_field( $group_field_id, array(
        'name'       => __( 'Entry Title', 'cmb2' ),
        'id'         => 'title',
        'type'       => 'text',
    ) );
    }

wordpress version: 4.2.2
CMB2 version: 2.0.6

**Comment by vasikgreif** [comment]
Same issue here... Any fix coming for this?
