### ISSUE TITLE
A couple of field types address, widget field, link as plugins

### ISSUE THREAD

**Issue by scottsawyer** [CMB2/CMB2#1171]
## 3rd Party Resources

I needed these for a project this weekend.  There may not be perfect, but I got the site shipped today, so...

## Address field
Basically just the same as the one in the snippet library, just as a separate plugin.  I am sure someone has already done this, but I couldn't find one.

https://github.com/scottsawyer/cmb2-field-address

## Link Field
The link field is cool because it includes some additional fields for various link attributes.  Probably add more attributes over time.

https://github.com/scottsawyer/cmb2-field-link

## Widget Selector
Ok, this one is weird.  I needed a way to reference preconfigured widget instances on content entry forms, similar to how Drupal's Block Reference field works.  This is not obvious to me in WordPress, but I find it can be very useful.  

What I wound up doing is creating a sidebar when it's installed.  You can then drop in Widgets, configure them, then reference them in the metabox.  

https://github.com/scottsawyer/cmb2-field-widget-selector

**Comment by tw2113** [comment]
Just to be certain, are you requesting that these get linked in the resources section of the readme?

**Comment by scottsawyer** [comment]
I just want them to be available to anyone who could use them, adding to the resources section of the readme / wiki would be cool.  I search the issues frequently, so I thought posting here would be good for discovery.

**Comment by jtsternberg** [comment]
@scottsawyer these look to be pretty helpful, but the readmes are pretty sparse. I'd prefer them to have a bit more instruction and possibly screenshots before linking to them from our readme as we don't want people to end up on a dead-end as they aren't sure what to do. Hope that makes sense.

**Comment by scottsawyer** [comment]
@jtsternberg yep, you are totally right.  I will try to update the readmes this weekend.

**Comment by scottsawyer** [comment]
@jtsternberg I updated the readme files, would you mind taking a look and seeing if they are informative enough for now?

**Comment by jtsternberg** [comment]
Looks good, added. Thanks!
