### ISSUE TITLE
Text Date problem

### ISSUE THREAD

**Issue by congthien** [CMB2/CMB2#1181]
Here is my code:
`$cmb_demo->add_field( array(
		'name' => esc_html__( 'Start Date', 'cmb2' ),
		'id'   => $prefix . 'start_date',
		'type' => 'text_date',
		'date_format' => 'd/m/Y'
	) );`

For example,  I set the date is 08/12/2018 ( 08 Dec)
I saved then it shows 12/08/2018 ( 12 Aug )

I used the latest CMB2 plugin.

**Comment by tw2113** [comment]
This is likely going to be the best source for some sort of related issue/sort of answer for you: https://github.com/CMB2/CMB2/issues/1073 It has a stackoverflow link as well for longer explanation of challenges.

One of the biggest challenges, as highlighted below, is dealing with date formats between PHP and JavaScript, as they aren't the most compatible. 

Overall list of various date-based open issues:
https://github.com/CMB2/CMB2/issues/1073
https://github.com/CMB2/CMB2/issues/1019
https://github.com/CMB2/CMB2/issues/986
https://github.com/CMB2/CMB2/issues/765
https://github.com/CMB2/CMB2/issues/678
https://github.com/CMB2/CMB2/issues/646
https://github.com/CMB2/CMB2/issues/518
https://github.com/CMB2/CMB2/issues/378
https://github.com/CMB2/CMB2/issues/343
https://github.com/CMB2/CMB2/issues/300
https://github.com/CMB2/CMB2/issues/378

**Comment by congthien** [comment]
@tw2113 

I changed to text_date_timestamp and it works well.

Thank you!
