### ISSUE TITLE
Date type issue

### ISSUE THREAD

**Issue by harpreet43** [CMB2/CMB2#1182]
Hey,
M new to github. So plz excuse, if my issue reporting format is not according to github.

I have used date type format 'text_date' 5 times in a form repeatedly. But when i view the saved data, only some of the date field shows data, rest are blank?

What are the possibilities???

**Comment by tw2113** [comment]
Can you provide your CMB2 code so that we can see if we can replicate the issue or point out other issues you may have with your configuration?

**Comment by harpreet43** [comment]
Thanks for replying. Plz find  it.

function yourprefix_register_user_profile_metabox() {
	$prefix = 'yourprefix_user_';

	/**
	 * Metabox for the user profile screen
	 */
	$cmb_user = new_cmb2_box( array(
		'id'               => $prefix . 'edit',
		'title'            => __( 'User Profile Metabox', 'cmb2' ), // Doesn't output for user boxes
		'object_types'     => array( 'user' ), // Tells CMB2 to use user_meta vs post_meta
		'show_names'       => true,
		'new_user_section' => 'add-new-user', // where form will show on new user page. 'add-existing-user' is only other valid option.
	) );

	$cmb_user->add_field( array(
		'name'     => __( 'Extra Info', 'cmb2' ),
		'desc'     => __( 'field description (optional)', 'cmb2' ),
		'id'       => $prefix . 'extra_info',
		'type'     => 'title',
		'on_front' => false,
	) );

	$cmb_user->add_field( array(
		'name' => __( 'Qualification', 'cmb2' ),
		//'desc' => __( 'field description (optional)', 'cmb2' ),
		'id'   => $prefix . 'qualification',
		'type' => 'text',
	) );

    $cmb_user->add_field( array(
	'name' => 'Date of Joining',
	'id'   => 'dateofjoin',
	'type' => 'text_date',
	// 'timezone_meta_key' => 'wiki_test_timezone',
	'date_format' => 'd/m/Y',
	'attributes' => array(
		// CMB2 checks for datepicker override data here:
		'data-datepicker' => json_encode( array(
			// dayNames: http://api.jqueryui.com/datepicker/#option-dayNames
			//'dayNames' => array( 'Dimanche', 'Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi' ),
			// monthNamesShort: http://api.jqueryui.com/datepicker/#option-monthNamesShort
			//'monthNamesShort' => explode( ',', 'En,Feb,Mar,Abr,May,Jun,Jul,Ago,Sep,Oct,Nov,Dic' ),
			// yearRange: http://api.jqueryui.com/datepicker/#option-yearRange
			// and http://stackoverflow.com/a/13865256/1883421
			//'yearRange' => '-100:+0',
			// Get 1990 through 10 years from now.
			 'yearRange' => '1950:'. ( date( 'Y' ) + 10 ),
		) ),
	),
    ) );

    $cmb_user->add_field( array(
	'name' => 'Date of Birth',
	'id'   => 'dateofbirth',
	'type' => 'text_date',
	// 'timezone_meta_key' => 'wiki_test_timezone',
	'date_format' => 'd/m/Y',
	'attributes' => array(
		// CMB2 checks for datepicker override data here:
		'data-datepicker' => json_encode( array(
			// dayNames: http://api.jqueryui.com/datepicker/#option-dayNames
			//'dayNames' => array( 'Dimanche', 'Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi' ),
			// monthNamesShort: http://api.jqueryui.com/datepicker/#option-monthNamesShort
			//'monthNamesShort' => explode( ',', 'En,Feb,Mar,Abr,May,Jun,Jul,Ago,Sep,Oct,Nov,Dic' ),
			// yearRange: http://api.jqueryui.com/datepicker/#option-yearRange
			// and http://stackoverflow.com/a/13865256/1883421
			//'yearRange' => '-100:+0',
			// Get 1990 through 10 years from now.
			 'yearRange' => '1950:'. ( date( 'Y' ) + 10 ),
		) ),
	),
    ) );

    $cmb_user->add_field( array(
		'name' => __( 'Desk Phone', 'cmb2' ),
		'desc' => __( 'field description (optional)', 'cmb2' ),
		'id'   => $prefix . 'desk-phone',
		'type' => 'text',
	) );

	$cmb_user->add_field( array(
		'name' => __( 'Residence Phone No.', 'cmb2' ),
		'desc' => __( 'field description (optional)', 'cmb2' ),
		'id'   => $prefix . 'res-phone',
		'type' => 'text',
	) );

	$cmb_user->add_field( array(
		'name' => __( 'Mobile', 'cmb2' ),
		'desc' => __( 'field description (optional)', 'cmb2' ),
		'id'   => $prefix . 'mobile',
		'type' => 'text',
	) );
	
	$cmb_user->add_field( array(
		'name' => __( 'Department', 'cmb2' ),
		'desc' => __( 'field description (optional)', 'cmb2' ),
		'id'   => $prefix . 'dept',
		'type' => 'text',
	) );
	
	$cmb_user->add_field( array(
		'name' => __( 'Designation', 'cmb2' ),
		'desc' => __( 'field description (optional)', 'cmb2' ),
		'id'   => $prefix . 'desig',
		'type' => 'text',
	) );
	
	$cmb_user->add_field( array(
		'name' => __( 'Office Address', 'cmb2' ),
		'desc' => __( 'field description', 'cmb2' ),
		'id'   => $prefix . 'ofc-address',
		'type' => 'textarea_small',
	) );
	
	$cmb_user->add_field( array(
		'name' => __( 'Residential Address', 'cmb2' ),
		'desc' => __( 'field description', 'cmb2' ),
		'id'   => $prefix . 'res-address',
		'type' => 'textarea_small',
	) );

    $cmb_user->add_field( array(
    	'name' => 'Anniversary',
    	'id'   => 'anniversary',
    	'type' => 'text_date',
    	// 'timezone_meta_key' => 'wiki_test_timezone',
    	'date_format' => 'd/m/Y',
    	'attributes' => array(
    		// CMB2 checks for datepicker override data here:
    		'data-datepicker' => json_encode( array(
    			// dayNames: http://api.jqueryui.com/datepicker/#option-dayNames
    			//'dayNames' => array( 'Dimanche', 'Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi' ),
    			// monthNamesShort: http://api.jqueryui.com/datepicker/#option-monthNamesShort
    			//'monthNamesShort' => explode( ',', 'En,Feb,Mar,Abr,May,Jun,Jul,Ago,Sep,Oct,Nov,Dic' ),
    			// yearRange: http://api.jqueryui.com/datepicker/#option-yearRange
    			// and http://stackoverflow.com/a/13865256/1883421
    			//'yearRange' => '-100:+0',
    			// Get 1990 through 10 years from now.
    			 'yearRange' => '1950:'. ( date( 'Y' ) + 10 ),
    		) ),
    	),
    ) );

	$cmb_user->add_field( array(
		'name' => __( 'Spouse\'s Name', 'cmb2' ),
		'desc' => __( 'field description (optional)', 'cmb2' ),
		'id'   => $prefix . 'spouse-name',
		'type' => 'text',
	) );
	
	$cmb_user->add_field( array(
    	'name' => 'Spouse\'s Date of Birth',
    	'id'   => 'spouse-dob',
    	'type' => 'text_date',
    	// 'timezone_meta_key' => 'wiki_test_timezone',
    	'date_format' => 'd/m/Y',
    	'attributes' => array(
    		// CMB2 checks for datepicker override data here:
    		'data-datepicker' => json_encode( array(
    			// dayNames: http://api.jqueryui.com/datepicker/#option-dayNames
    			//'dayNames' => array( 'Dimanche', 'Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi' ),
    			// monthNamesShort: http://api.jqueryui.com/datepicker/#option-monthNamesShort
    			//'monthNamesShort' => explode( ',', 'En,Feb,Mar,Abr,May,Jun,Jul,Ago,Sep,Oct,Nov,Dic' ),
    			// yearRange: http://api.jqueryui.com/datepicker/#option-yearRange
    			// and http://stackoverflow.com/a/13865256/1883421
    			//'yearRange' => '-100:+0',
    			// Get 1990 through 10 years from now.
    			 'yearRange' => '1950:'. ( date( 'Y' ) + 10 ),
    		) ),
    	),
    ) );
    
    //First Child
    
    $cmb_user->add_field( array(
		'name' => __( 'Child Name', 'cmb2' ),
		'desc' => __( 'field description (optional)', 'cmb2' ),
		'id'   => $prefix . 'child1-name',
		'type' => 'text',
	) );
	
	$cmb_user->add_field( array(
    	'name'             => 'Child',
    	'id'               => 'rdb_child1',
    	'type'             => 'radio',
    	'show_option_none' => true,
    	'options'          => array(
    		'Son' => __( 'Son', 'cmb2' ),
    		'Daughter'   => __( 'Daughter', 'cmb2' )
    	),
    ) );
    
    $cmb_user->add_field( array(
    	'name' => 'Date of Birth',
    	'id'   => 'child1-dob',
    	'type' => 'text_date',
    	// 'timezone_meta_key' => 'wiki_test_timezone',
    	'date_format' => 'd/m/Y',
    	'attributes' => array(
    		// CMB2 checks for datepicker override data here:
    		'data-datepicker' => json_encode( array(
    			// dayNames: http://api.jqueryui.com/datepicker/#option-dayNames
    			//'dayNames' => array( 'Dimanche', 'Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi' ),
    			// monthNamesShort: http://api.jqueryui.com/datepicker/#option-monthNamesShort
    			//'monthNamesShort' => explode( ',', 'En,Feb,Mar,Abr,May,Jun,Jul,Ago,Sep,Oct,Nov,Dic' ),
    			// yearRange: http://api.jqueryui.com/datepicker/#option-yearRange
    			// and http://stackoverflow.com/a/13865256/1883421
    			//'yearRange' => '-100:+0',
    			// Get 1990 through 10 years from now.
    			 'yearRange' => '1950:'. ( date( 'Y' ) + 10 ),
    		) ),
    	),
    ) );
    
    
    $cmb_user->add_field( array(
		'name' => __( 'Child Name', 'cmb2' ),
		'desc' => __( 'field description (optional)', 'cmb2' ),
		'id'   => $prefix . 'child2-name',
		'type' => 'text',
	) );
	
	$cmb_user->add_field( array(
    	'name'             => 'Child',
    	'id'               => 'rdb_child2',
    	'type'             => 'radio',
    	'show_option_none' => true,
    	'options'          => array(
    		'Son' => __( 'Son', 'cmb2' ),
    		'Daughter'   => __( 'Daughter', 'cmb2' )
    	),
    ) );
    
    $cmb_user->add_field( array(
    	'name' => 'Date of Birth',
    	'id'   => 'child2-dob',
    	'type' => 'text_date',
    	// 'timezone_meta_key' => 'wiki_test_timezone',
    	'date_format' => 'd/m/Y',
    	'attributes' => array(
    		// CMB2 checks for datepicker override data here:
    		'data-datepicker' => json_encode( array(
    			// dayNames: http://api.jqueryui.com/datepicker/#option-dayNames
    			//'dayNames' => array( 'Dimanche', 'Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi' ),
    			// monthNamesShort: http://api.jqueryui.com/datepicker/#option-monthNamesShort
    			//'monthNamesShort' => explode( ',', 'En,Feb,Mar,Abr,May,Jun,Jul,Ago,Sep,Oct,Nov,Dic' ),
    			// yearRange: http://api.jqueryui.com/datepicker/#option-yearRange
    			// and http://stackoverflow.com/a/13865256/1883421
    			//'yearRange' => '-100:+0',
    			// Get 1990 through 10 years from now.
    			 'yearRange' => '1950:'. ( date( 'Y' ) + 10 ),
    		) ),
    	),
    ) );
    
    
    $cmb_user->add_field( array(
		'name' => __( 'Child Name', 'cmb2' ),
		'desc' => __( 'field description (optional)', 'cmb2' ),
		'id'   => $prefix . 'child3-name',
		'type' => 'text',
	) );
	
	$cmb_user->add_field( array(
    	'name'             => 'Child',
    	'id'               => 'rdb_child3',
    	'type'             => 'radio',
    	'show_option_none' => true,
    	'options'          => array(
    		'Son' => __( 'Son', 'cmb2' ),
    		'Daughter'   => __( 'Daughter', 'cmb2' )
    	),
    ) );
    
    $cmb_user->add_field( array(
    	'name' => 'Date of Birth',
    	'id'   => 'child3-dob',
    	'type' => 'text_date',
    	// 'timezone_meta_key' => 'wiki_test_timezone',
    	'date_format' => 'd/m/Y',
    	'attributes' => array(
    		// CMB2 checks for datepicker override data here:
    		'data-datepicker' => json_encode( array(
    			// dayNames: http://api.jqueryui.com/datepicker/#option-dayNames
    			//'dayNames' => array( 'Dimanche', 'Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi' ),
    			// monthNamesShort: http://api.jqueryui.com/datepicker/#option-monthNamesShort
    			//'monthNamesShort' => explode( ',', 'En,Feb,Mar,Abr,May,Jun,Jul,Ago,Sep,Oct,Nov,Dic' ),
    			// yearRange: http://api.jqueryui.com/datepicker/#option-yearRange
    			// and http://stackoverflow.com/a/13865256/1883421
    			//'yearRange' => '-100:+0',
    			// Get 1990 through 10 years from now.
    			 'yearRange' => '1950:'. ( date( 'Y' ) + 10 ),
    		) ),
    	),
    ) );
    
    
    $cmb_user->add_field( array(
		'name' => __( 'Child Name', 'cmb2' ),
		'desc' => __( 'field description (optional)', 'cmb2' ),
		'id'   => $prefix . 'child4-name',
		'type' => 'text',
	) );
	
	$cmb_user->add_field( array(
    	'name'             => 'Child',
    	'id'               => 'rdb_child4',
    	'type'             => 'radio',
    	'show_option_none' => true,
    	'options'          => array(
    		'Son' => __( 'Son', 'cmb2' ),
    		'Daughter'   => __( 'Daughter', 'cmb2' )
    	),
    ) );
    
    $cmb_user->add_field( array(
    	'name' => 'Date of Birth',
    	'id'   => 'child4-dob',
    	'type' => 'text_date',
    	// 'timezone_meta_key' => 'wiki_test_timezone',
    	'date_format' => 'd/m/Y',
    	'attributes' => array(
    		// CMB2 checks for datepicker override data here:
    		'data-datepicker' => json_encode( array(
    			// dayNames: http://api.jqueryui.com/datepicker/#option-dayNames
    			//'dayNames' => array( 'Dimanche', 'Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi' ),
    			// monthNamesShort: http://api.jqueryui.com/datepicker/#option-monthNamesShort
    			//'monthNamesShort' => explode( ',', 'En,Feb,Mar,Abr,May,Jun,Jul,Ago,Sep,Oct,Nov,Dic' ),
    			// yearRange: http://api.jqueryui.com/datepicker/#option-yearRange
    			// and http://stackoverflow.com/a/13865256/1883421
    			//'yearRange' => '-100:+0',
    			// Get 1990 through 10 years from now.
    			 'yearRange' => '1950:'. ( date( 'Y' ) + 10 ),
    		) ),
    	),
    ) );

}

**Comment by tw2113** [comment]
Looks like similar issues to https://github.com/CMB2/CMB2/issues/1181 in which I reference https://github.com/CMB2/CMB2/issues/1073 which all circles back to the date formatting in the form of "d/m/Y". This trickles all the way down to the PHP level of things. See https://stackoverflow.com/questions/2891937/strtotime-doesnt-work-with-dd-mm-yyyy-format/2891949#2891949

So, while it may not be the most ideal, I did have no issue with setting the format to be "d-m-Y" without the forward slashes as separators. Others have found success with just storing the resulting date as a UTC timestamp.

**Comment by harpreet43** [comment]
Thanks. By making date format 'Y-m-d'. It solved my issue.

**Comment by tw2113** [comment]
Welcome
