### ISSUE TITLE
When adding to options page, option_key is not respected

### ISSUE THREAD

**Issue by davebonds** [CMB2/CMB2#1184]
### Expected Behavior: 
When adding a `new_cmb2_box` using the `object_types => array( 'options-page' )` parameter, the `option_key` value is not respected. The `wp_option` is saved as `options-page` instead of the value for `option_key`

### Actual Behavior:
The `wp_options` key should be the value of the `option_key` parameter.

### Steps to reproduce (I have confirmed I can reproduce this issue on the trunk branch):

1. Register a metabox on an options-page and add a field
2. `wp_options` key is `options-page` instead of what should be the `option_key`

### CMB2 Field Registration Code:

```php
		// Add our CMB2 metabox. Short example.
		$cmb = new_cmb2_box( array(
			'id'           => self::$metabox_id,
			'title'        => $this->title,
			'object_types' => array( 'options-page' ),
			'option_key'   => 'something-else', // This doesn't work.
			'parent_slug'  => 'options-general.php',
			'capability'   => 'manage_options',
			'display_cb'   => array( $this, 'options_page_content' ),
		) );
```

**Comment by tw2113** [comment]
Not managing to recreate on my own at least with what has been provided above Dave,

Can you provide the whole class you're using for this? It's possible it's something else going on.

Attached is a screenshot of what I got and what code I'm using for it. Note I did comment out the display_cb as I don't know what you had in place for that.

![screen shot 2018-11-04 at 4 15 06 pm](https://user-images.githubusercontent.com/484075/47970569-03767a80-e04d-11e8-8339-2e589c7cda25.png)

```
add_action( 'cmb2_admin_init', 'abcmyfunc' );
function abcmyfunc() {
	$cmb = new_cmb2_box( array(
		'id'           => 'mybox',
		'title'        => 'My Title',
		'object_types' => array( 'options-page' ),
		'option_key'   => 'something-else', // This doesn't work.
		'parent_slug'  => 'options-general.php',
		'capability'   => 'manage_options',
		#'display_cb'   => array( $this, 'options_page_content' ),
	) );
	$cmb->add_field( array(
		'name'    => esc_html__( 'Hero Image', 'cmb2' ),
		'desc'    => esc_html__( 'Upload an image.', 'cmb2' ),
		'id'      => 'heroimg',
		'type'    => 'text',
		'options' => array(
			'url' => false, // Hide the text input for the url
		),
	) );
}
```

**Comment by davebonds** [comment]
Michael, after playing around with this a little more, I determined it was my fault. In the `display_cb` callback, I'm using the `cmb2_metabox_form` function to output the form and was incorrectly passing in `options-page` as a param which then overrides the `option_key` param of `new_cmb2_box`. Closing this for now.

**Comment by tw2113** [comment]
Aha! Good to lesson to note for anyone coming around to this in the future.
