### ISSUE TITLE
Colorpicker change event not easy to customize.

### ISSUE THREAD

**Issue by tw2113** [CMB2/CMB2#1189]
Original support thread: https://wordpress.org/support/topic/colorpicker-callback-modification/

https://github.com/CMB2/CMB2/wiki/Field-Types#colorpicker

We show ways to customize the colorpicker as desired but it also has an event callback option that can also be customized.

With stock Iris from core, I hope, but not have confirmed, if the data-attribute method highlighted works. I do know that the data-attributes do get utilized with our customized version that adds the alpha transparency support.

However, from there it gets hairier. The function is not easily passed along to be eventually called. Trying to pass an anonymous callback is going to get mucked up at the json_encode portion. Passing a named function almost works. That version fails once we hit the `$.isFunction` check because it only validates as a string.

Based on some searching, I found that this would be a good check to add:

```
if ( $.isFunction( window[self.options.change] ) ) {
	window[self.options.change].call( this, event, ui );
}
```

Not sure if we want to replace our current if statement or add this alongside it.

Original thread poster found a solution that worked for their case. It can be seen at https://wordpress.org/support/topic/colorpicker-callback-modification/#post-10889992 and below

```
$.widget( 'a8c.iris', $.a8c.iris, {
	_change: function() {
		this._super();

		var self = this,
		el   = self.element;

		console.log('changed color');
		update_chart_colors();
	},
});
```

This feels like more than they should be needing to do to get something to work.

**Comment by staurand** [comment]
@tw2113 I think it feels odd to try to evaluate the change property (could be as you said an anonymous function or a global function but also a function from a global object: MyGlobal.myfunction...)
Maybe we should filter out the color picker change attribute and move it to a script.
Pseudo code:
```
$('#color-picker-id').on('irischange', <?php echo $attributes['color-picker']['change']); ?>);
```

**Comment by tw2113** [comment]
I'm not married to any specific solution, as js isn't my strongest area of knowledge, so the topic is most definitely open to discussion and best solution wins.

**Comment by jtsternberg** [comment]
Since you have to write a callback in javascript anyway, there's no reason to define the callback in php. However, there wasn't previously a good javascript event to hook onto for initiating arguments for colorpickers when added via a repeatable group, so I have pushed up an update (to add [`cmb_init_pickers` event](https://github.com/CMB2/CMB2/commit/d8bab1b5ece0e828effb37d085029fba5fa2557d)). This will allow you to define custom javascript arguments for the pickers just before the pickers are initiated for the field.  Example for color-pickers inside a repeatable group:

```php
<script type="text/javascript">
	$(document).on( 'cmb_init_pickers', function(evt, pickers, cmb) {
		var box = document.getElementById('yourprefix_group_metabox');
		pickers.color.each( function() {
			if ( jQuery.contains( box, this ) ) {
				var $picker = $(this);
				var changeCallback = function(event, obj) {
					console.log('picker changed to:', obj.color.toString());
				};
				var args = $picker.data('colorpicker');
				if ( args ) {
					args.change = args.change || changeCallback;
				} else {
					args = {
						change: changeCallback
					}
				}
				$picker.data('colorpicker', args);

			}
		})
	});
</script>
```

**Comment by jtsternberg** [comment]
And you're dealing with a color-picker that is NOT in a group or repeatable, you can just do this:
```html
<script type="text/javascript">
	$(document).on( 'cmb_pre_init', function(evt, cmb) {
		var $picker = $('#<FIELD_ID>');
		var changeCallback = function(event, obj) {
			console.log('picker changed to:', obj.color.toString());
		};
		var args = $picker.data('colorpicker');
		if ( args ) {
			args.change = args.change || changeCallback;
		} else {
			args = {
				change: changeCallback
			}
		}
		$picker.data('colorpicker', args);
	});
</script>
```

**Comment by tw2113** [comment]
Is this one good to be closed now? or do we want to leave it open a bit longer for visibility and testing purposes?

**Comment by jtsternberg** [comment]
Yah let’s close.
