### ISSUE TITLE
WordPress 5 RC - wysiwyg field type not saved

### ISSUE THREAD

**Issue by dameer** [CMB2/CMB2#1192]
Just as the title says, 'wysiwyg' field type doesn't get saved with Gutenberg.
Tho, it's all right when saving as `'object_types'  => array( 'term' )`

**Comment by jtsternberg** [comment]
This should have been fixed with #1190. Did you test on the trunk branch?

**Comment by dameer** [comment]
Holy guacamole! Sorry for being such a lame ass, I forgot the trunk branch. Thanks for everything!!!

**Comment by jtsternberg** [comment]
🥑
