### ISSUE TITLE
Colour contrast ration of the .cmb2-metabox-description is too low

### ISSUE THREAD

**Issue by rianrietveld** [CMB2/CMB2#1193]
### Expected Behavior:
The colour contrast ratio of text and background needs to be 4.5 or higher according to the [WCAG 2.0 and 2.1 guidelines](https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html). 

This is to ensures that most people can read the text.

### Actual Behavior:
The description (`.cmb2-metabox-description`) has a colour of `#aaaaaa` which results in a contrast ratio against the white background of 2.3, which is too low.

### Steps to reproduce (I have confirmed I can reproduce this issue on the trunk branch):
Check the color contrast with a tool like [Colour Contrast Check by Snook](https://snook.ca/technical/colour_contrast/colour.html#fg=AAAAAA,bg=FFFFFF)

### Suggested improvement:
I suggest changing the `#aaaaaa` in `#757575`, which has a ratio against white of 4.5.

`.cmb2-metabox-description` is defined in a few places in the CSS files.

**Comment by jtsternberg** [comment]
Thank you!

**Comment by rianrietveld** [comment]
Wow, that is fast! Thanks!

**Comment by tw2113** [comment]
Yeah, Justin is like that at times, and it's all good changes to be made. :D
