### ISSUE TITLE
Yoast SEO problem

### ISSUE THREAD

**Issue by wayheming** [CMB2/CMB2#1197]
Hello, there is a problem after your last update with plugin Yoast SEO. I use the standard theme Twenty Nineteen and WordPress version 5.0. The problem is only in the classic editor.
http://prntscr.com/lsygdn
http://prntscr.com/lsygkc

### Steps to reproduce (I have confirmed I can reproduce this issue on the [`develop`](https://github.com/CMB2/CMB2/tree/develop) branch):

1. Add metabox to any post type
2. Instsall Yoast Seo

### CMB2 Field Registration Code:

```php
add_action( 'cmb2_admin_init', 'yourprefix_register_demo_metabox' );
/**
 * Hook in and add a demo metabox. Can only happen on the 'cmb2_admin_init' or 'cmb2_init' hook.
 */
function yourprefix_register_demo_metabox() {
	$prefix = 'yourprefix_demo_';

	/**
	 * Sample metabox to demonstrate each field type included
	 */
	$cmb_demo = new_cmb2_box( array(
		'id'            => $prefix . 'metabox',
		'title'         => esc_html__( 'Test Metabox', 'cmb2' ),
		'object_types'  => array( 'page' ), // Post type
	) );

	$cmb_demo->add_field( array(
		'name'       => esc_html__( 'Test Text', 'cmb2' ),
		'desc'       => esc_html__( 'field description (optional)', 'cmb2' ),
		'id'         => $prefix . 'text',
		'type'       => 'text',
		'show_on_cb' => 'yourprefix_hide_if_no_cats', // function should return a bool value
	) );

}
```

**Comment by itrekkings** [comment]
To follow because I have the same problem

**Comment by xsonic** [comment]
Just ran into the same issue:

Quick fix would be to simply add a if-condition on `cmb2.js line 126`:


			if (wp.data.select('core/editor')) {
				if (wp.data.select('core/editor').isSavingPost() && window.tinyMCE.editors.length) {
					for (var i = 0; i < window.tinyMCE.editors.length; i++) {
						window.tinyMCE.editors[i].save();
					}
				}
			}


Works for me, don't know if it's the right solution. Currently no time to dig in further (olè gutenberg, *sigh*).

**Comment by jtsternberg** [comment]
Thank you. We’ll get a fix out today.

**Comment by wayheming** [comment]
@jtsternberg Thank you!
