### ISSUE TITLE
show_on filter with default page template doesn't work in WordPress 5

### ISSUE THREAD

**Issue by staurand** [CMB2/CMB2#1199]
### Expected Behavior:
We should be able to filter metabox for default page template.
```
'show_on'      => array( 'key' => 'page-template', 'value' => 'default' ),
```

### Actual Behavior:
The metabox does not appear on WordPress > 5.0 on page with the default page template selected.

### Steps to reproduce:

1. Add the metabox config below
2. Create a dummy page template for the page template select dropdown to appear in the page form
3. Create a new page and save it.
4. WordPress >= 5.0: the metabox does not appear
WordPress < 5.0: the metabox appears

### CMB2 Field Registration Code:

```php
define('CMB2_PREFIX', 'wp_test_');
add_action( 'cmb2_admin_init', 'cmb2_page' );
function cmb2_page() {
  /**
   * Initiate the metabox
   */
  $cmb = new_cmb2_box( array(
    'id'            => 'page_metabox',
    'title'         => 'Default page metabox',
    'object_types'  => array( 'page' ), // Post type
    'show_on'      => array( 'key' => 'page-template', 'value' => 'default' ),
  ));

	$cmb->add_field(array(
    'name' => 'Test WP 5.0 & default page template',
    'id'   => CMB2_PREFIX . 'test_page_tempate',
    'type' => 'textarea_small'
  ));
}
```

### Change in WordPress 5.0
Since WordPress 5.0 the default page template value is not "default" but an empty string in the page form select dropdown.
In the wp_post_meta table the "_wp_page_template" is not set the first time the page is saved.
If you change from one template then go back to the default one, the "_wp_page_template" meta value is an empty string.
Ref:
https://core.trac.wordpress.org/browser/branches/5.0/src/wp-admin/edit-form-blocks.php#L153

### Issue to be resolved in CMB2?
CMB2 checks if the "'_wp_page_template" meta value has been set:
```
// Get current template.
$current_template = get_post_meta( $object_id, '_wp_page_template', true );
// See if there's a match.
if ( $current_template && in_array( $current_template, (array) self::get_show_on_value( $meta_box_args ) ) ) {
  return true;
}
```
Should we assume that starting from WordPress 5.0 and empty value for the "_wp_page_template" is equal to the default page template?
```
// Get current template.
$current_template = get_post_meta( $object_id, '_wp_page_template', true );
if ( CMB2_Utils::wp_at_least( '5.0.0' ) && empty($current_template) ) {
  $current_template = 'default';
}
// See if there's a match.
if ( $current_template && in_array( $current_template, (array) self::get_show_on_value( $meta_box_args ) ) ) {
  return true;
}
```

**Comment by tw2113** [comment]
We can definitely consider adding some extra checks and everything here, but for the meantime, it may just be best to provide your own `show_on_cb` that should easily provide everything you're needing for this case. That way, you could return true on the empty string check and have it show in those cases.

**Comment by jtsternberg** [comment]
I would like to deprecate the `show_on` property in favor of the `show_on_cb` property, so I don't think I'll make this change.  Added an example for doing this in the wiki: https://github.com/CMB2/CMB2/wiki/Box-Properties#show_on_cb
