### ISSUE TITLE
Consider about the field dependencies

### ISSUE THREAD

**Issue by anhskohbo** [CMB2/CMB2#1221]
Since [jcchavezs/cmb2-conditionals](https://github.com/jcchavezs/cmb2-conditionals) is abandoned and seem have a lot of bugs. I have implemented a new one in my library (based on CMB2) and it's work perfectly. The js will have a lot of added or changed but I think it's not break anything.

Would be nice if a pull request is welcome!

```php
<?php

$cmb_demo->add_field( array(
	'name' => esc_html__( 'Enable?', 'cmb2' ),
	'id'   => 'enable_searchbox',
	'type' => 'checkbox',
) );

$cmb_demo->add_field( array(
	'name' => esc_html__( 'Enter Value', 'cmb2' ),
	'id'   => 'value',
	'type' => 'text',
        'deps' => ['enable_searchbox', 'is_not_empty'],
        // 'deps' => ['or' => ['checkbox', 'is_not_empty'], ['checkbox', '=', '@some_another_field']]
        // 'deps' => ['and' => ['checkbox', 'is_not_empty'], ['checkbox', '=', '@some_another_field']]
) );
```

**Comment by jtsternberg** [comment]
It's hard to say, as everything we add to CMB2, we'll have to support over the long run. Do you want to submit the PR and we can review?
