### ISSUE TITLE
Svg preview not working

### ISSUE THREAD

**Issue by bilalmalkoc** [CMB2/CMB2#1223]
In file type, i upload svg image, but preview doesn't show it. For allow to upload svg i used [Safe SVG](https://wordpress.org/plugins/safe-svg/) plugin.

    $cmb_services->add_field( array(
        'name'         => esc_html__( 'Navigation Image (Svg)', 'test' ),
        'id'           => $prefix . 'servicesNavigationImageSvg',
        'type'         => 'file',
        'query_args'   => array(
            'type' => array(
                'image/svg',
            ),
        ),
        'preview_size' => 'thumbnail',
    ) );

**Comment by tw2113** [comment]
Until told otherwise, I think this is a detail that needs added as an enhancement for the field type above, if not overall. As is, we just may not have things set to display a preview of sorts, and I don't know offhand how to possibly achieve it as well.

**Comment by andymb** [comment]
Hi, was this change ever committed? I'm using the WordPress CMB2 2.8.0 plugin and SVGs still don't display for a file list:

<img width="777" alt="Screenshot 2021-02-18 at 12 55 37" src="https://user-images.githubusercontent.com/6523473/108360206-d122c400-71e8-11eb-93c9-0500fa9ca423.png">


Latest WP & the SVG Support plugin.

**Comment by jtsternberg** [comment]
This should be good in the latest on the `develop` branch. It will still require the [Safe SVG](https://wordpress.org/plugins/safe-svg/) plugin in order to upload svg's to the site.
