### ISSUE TITLE
[SOLVED] CMB2 wysiwyg field not showing linebreaks

### ISSUE THREAD

**Issue by brothman01** [CMB2/CMB2#1234]
I already solved this issue on my client's site but I wanted to share that fix with the other users and possibly contribute to a bug being fixed:

**Issue:**
My custom CMB2 wysiwyg field is not displaying linebreaks (`<p>` tags or `<br />`) in the output of saved content when displayed with a shortcode so the text is just one long paragraph. (yes I was and am using a fresh clone of the latest version)

**Fix:**
Use `wpautop()` around output in PHP:
`wpautop( get_post_meta( get_the_ID(), 'sa_description', true ) )`

it is an easy fix but it may be indicative of a larger underlying problem.

**Comment by jtsternberg** [comment]
This is not a bug, but rather the documented way that the WP editor works. You can see the notes in the documentation for this field type: https://github.com/CMB2/CMB2/wiki/Field-Types#notes-4

**Comment by Cannacular** [comment]
Basic Paragraph-Text is tricky, In keeping the ease-of-use for the client for delivery I chose to modify an H class to fit my needs and assigned via the drop down in wysiwig (and toot for client to do so).  This will create the line space, but be sure to do this for each paragraph. I too though, can't get a space when using "Paragraph-Text" alone.
