### ISSUE TITLE
REST API CPT returns empty value

### ISSUE THREAD

**Issue by brunoameba** [CMB2/CMB2#1236]
When trying to get a value for a CMB2 meta box from a custom post type post, the retrun value is empty.

If I repeat the process with a normal post (not cpt) the return value appears as expected.
Already set the "'show_in_rest'" attribute to true on the registration of the cpt on functions.php, but still.. no value is returned. empty.

Any suggestions ?
It is clear that the route structure is correct, because it does work for the regular post, but not for my current post type :  

/wp-json/cmb2/v1/boxes/cmb2_info_metabox/fields/ap_office_list_office_images_rest_api/?object_type=post&object_id=375 // Returns the expected value

/wp-json/cmb2/v1/boxes/cmb2_info_metabox/fields/ap_office_list_office_images_rest_api/?object_type=office&object_id=323 // Returns nothing, empty

Then, here it is the cpt definition : 

    /*Offices*/
    register_post_type( 'office',
        array(
            'labels' => array(
            'name' => __( 'Offices' ),
            'singular_name' => __( 'Office' ),
            'add_new_item' => __( 'Add New Office' ),
            'search_items' => __('Search Offices'),
            'edit_item' => __('Edit Office'),
            'new_item' => __('New Office'),
            'all_items' => __('All Offices'),
            'view_item' => __('View Office'),
            'search_items' => __('Search Offices'),
            'not_found' =>  __('No office found'),
            'not_found_in_trash' => __('No offices found in Trash'), 
            'menu_name' => __('Offices')
        ),
            'public' => true,
            'show_in_rest' => true,
            'menu_icon' => 'dashicons-admin-multisite',
            'has_archive' => true,
            'supports' => array( 'title', 'editor', 'author', 'thumbnail', 'excerpt' )
        )
    );

Please, help! I am almost there!

**Comment by jtsternberg** [comment]
Whenever you see `object_type` in the context of CMB2, it refers to the type of object you are dealing with, e.g. `post`, `user`, `term`, `comment`, or `options-page`. Since you're dealing with a post object, your `object_type` would still be `post`.

**Comment by brunoameba** [comment]
Thanks!! That worked!
