### ISSUE TITLE
simple file upload without media modal

### ISSUE THREAD

**Issue by gyrus** [CMB2/CMB2#1243]
Is it possible to have a file upload field which is a simply file upload, i.e. doesn't use the WP media upload/library modal?

I have a front-end form and I need to store files uploaded through it securely. I only need to store files from this field on this form securely. Perhaps there's a way of using a plugin like Download Monitor to do this, but I can't see an obvious way to use that kind of system selectively on the front-end.

I'm guessing my best bet is to build a simple custom system. But I'd need these uploads to live outside the WP uploads system, so I need a simple upload field in a CMB2 form.

**Comment by jtsternberg** [comment]
There's an example using a normal `file` field type in the front-end submit example in the snippet library: https://github.com/CMB2/CMB2-Snippet-Library/blob/master/front-end/cmb2-front-end-submit.php#L38-L46

That example will get you pretty far. Look at the file-handling section too: https://github.com/CMB2/CMB2-Snippet-Library/blob/master/front-end/cmb2-front-end-submit.php#L260-L287

**Comment by gyrus** [comment]
Excellent, many thanks!

**Comment by Bilal-account** [comment]
I used below code for upload file from front end but when I update the form it disappear and not shown on the screen where I am displaying it. Can you help me? I would be very thankful for your valuable time.
"array(
                        'name' => __('Upload Files', 'wp-job-board-pro'),
                        'id' =>  $prefix . 'upload_files',
                        'type' => 'file',
                        'options' => array(
                            'add_upload_file_text' => __('Add or upload files', 'wp-job-board-pro'),
                            'file_list' => true, // Enable multiple file uploads
                            'query_args' => array(
                                'type' => array('image/jpeg', 'image/png', 'application/pdf', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'), // Specify allowed file types
                                'size' => 5242880, // Set maximum file size (5 MB in bytes)
                                'preview_size' => 'thumbnail',
                            ),
                        ),
                    )"

**Comment by tw2113** [comment]
@Bilal-account I have responded on your forum thread over at https://wordpress.org/support/topic/issue-with-cmb2-plugin-field-type-file/ and we can continue discussion there instead of on this old not related GitHub issue.
