### ISSUE TITLE
how to set default for text_date field?

### ISSUE THREAD

**Issue by gyrus** [CMB2/CMB2#1245]
I have the following field definition for a front-end form:

    $cmb->add_field( array(
    	'name'        => 'Date',
    	'id'          => 'date',
    	'type'        => 'text_date',
    	'date_format' => 'j/n/Y',
    	'default'     => date( 'j/n/Y' ),
    	'attributes' => array(
    		'required' => 'required',
    		'data-datepicker' => json_encode( array(
    			'defaultDate' => null
    		)),
    	),
    	'classes'    => array( 'required' ),
    ) );

Neither the 'default' param or the jQuery UI 'defaultDate' param seem to pass anything through ('null' is supposed to default to today: https://api.jqueryui.com/datepicker/#option-defaultDate).

The datepicker works fine, inserts in the right format. And if I just change the type to 'text', the default date appears OK.

**Comment by tw2113** [comment]
What happens if you pass empty string or just leave the default date param not configured at all? Are you not getting what you expect with either of those cases?

**Comment by gyrus** [comment]
Tried empty string, then removing default, then removing defaultDate too - nothing coming through in the field.

Surely default should work with a value passed, in case the default needs to be something other than today? Not that case here, but generally it should work that way.

**Comment by jtsternberg** [comment]
Default callbacks/settings weren't working for for date picker fields, so I fixed that, but do note, you need to set the value with a valid timestamp, not a date string. so in your case, `'default' => time(),` should be sufficient.

**Comment by gyrus** [comment]
`time()` works as default, thanks.
