### ISSUE TITLE
File upload image

### ISSUE THREAD

**Issue by ghost** [CMB2/CMB2#1249]
When I upload an image through a _file_ type, and go to the _upload_ tab to add a new image, the image does not show up on the media library grid. I have to reload the page, and repeat the process to see the image on the media library grid. 

How do I make the image to appear on the media library grid the first time? This is clearly some kind of bug.

![1117631745520650 MdR4sW3HTpkvg1DOHCXG_height640](https://user-images.githubusercontent.com/7514902/55756387-c5c8b400-5a27-11e9-992b-6c5de5036c62.png)

**Comment by tw2113** [comment]
Can you provide your CMB2 configuration code as well as what version of CMB2 and WordPress core you're presently running?

**Comment by brunoameba** [comment]
**CMB2 version :** 2.5.1
**Wordpress version :**  5.1.1

**CMB2 configuration code**

`    /*********************************
    solution 
    *********************************/
    $prefix = 'ap_service_solution_';

    $solution_cmb_main_content = new_cmb2_box(array(
      'id' => $prefix . 'main_content',
      'title' => __('Main Content'),
      'object_types' => array('service'),
      'context' => 'advanced',
      'priority' => 'high',
    ));

    /*Background image*/
    $solution_cmb_main_content->add_field( array(
      'name'    => 'Header Background Image',
      'desc'    => 'Upload an image for the header background (if none present, Featured Image will be selected)',
      'id'      => $prefix . 'mh_background_image',
      'type'    => 'file',
      // Optional:
      'options' => array(
        'url' => false, // Hide the text input for the url
      ),
      'text'    => array(
        'add_upload_file_text' => 'Add Image' // Change upload button text. Default: "Add or Upload File"
      ),
      // query_args are passed to wp.media's library query.
      'query_args' => array(
        //'type' => 'application/pdf', // Make library only display PDFs.
        // Or only allow gif, jpg, or png images
        // 'type' => array(
          'image/gif',
          'image/jpeg',
          'image/png',
        // ),
      ),
      'preview_size' => 'large', // Image size to use when previewing in the admin.
    ) );`

**Comment by brunoameba** [comment]
Haha, you are very polite. 
Thanks :)

**Comment by tw2113** [comment]
Assuming what you have above is exactly what you're trying to work with, I think the issue is the fact that the `'type'` array line is commented out.

You have:

```
'query_args' => array(
    //'type' => 'application/pdf', // Make library only display PDFs.
    // Or only allow gif, jpg, or png images
    // 'type' => array(
      'image/gif',
      'image/jpeg',
      'image/png',
    // ),
  ),
```
it should be:

```
'query_args' => array(
    //'type' => 'application/pdf', // Make library only display PDFs.
    // Or only allow gif, jpg, or png images
    'type' => array(
      'image/gif',
      'image/jpeg',
      'image/png',
    ),
  ),
```

Tried both versions and the first one did fail, the second one is working just fine for me.

**Comment by mehmetsarr** [comment]
I cannot bring the file to the front of the theme. How can I do it.
