### ISSUE TITLE
Including apigen has brought jQuery into your plugin

### ISSUE THREAD

**Issue by Ipstenu** [CMB2/CMB2#1254]
https://github.com/CMB2/CMB2/tree/develop/apigen/theme-bootstrap

I noticed this when someone submitted a plugin and got flagged for jQuery. This is including jQuery which isn't permitted for plugins, but also it;'s an older (out of date) version. Did you mean to do this, or should this be excluded in places?

**Comment by tw2113** [comment]
It got added to GH via https://github.com/CMB2/CMB2/commit/008d9b83263d971d6bd41c27e31113db852d5ef3 but honestly it's one of those things that shouldn't be getting put into other things using the library. It's more meant for us and handling CMB2 documentation.

Chances are this person just dropped everything in, as is. As an extra detail, isn't bundling CMB2 in with other plugins frowned upon now for new plugins, and the recommended thing is to have them recommend installing the base plugin from http://wordpress.org/plugins/cmb2/ ?

**Comment by jtsternberg** [comment]
Yah, this person simply bundled it incorrectly. Probably should have some better docs on that. [This line](https://github.com/CMB2/CMB2/blob/develop/.gitattributes#L10) ensures if you download the zip file from GH, it won't be included. Also, if they download from .org, it won't be included. This person likely cloned it down and included it that way, in which case, they'd get [all these developer-only things](https://github.com/CMB2/CMB2/blob/develop/.gitattributes) in their bundle.

Going to close, but feel free to reopen if you believe there is something else to be done.

**Comment by jtsternberg** [comment]
Added some notes to the docs:
- https://github.com/CMB2/CMB2/wiki/Installation#if-including-the-library-in-your-plugin-or-theme
- https://github.com/CMB2/CMB2/wiki/Basic-Usage#caveats-for-bundling-and-including-cmb2

**Comment by Ipstenu** [comment]
> As an extra detail, isn't bundling CMB2 in with other plugins frowned upon now for new plugins, and the recommended thing is to have them recommend installing the base plugin from http://wordpress.org/plugins/cmb2/ ?

Yes but.

Since y'all SANELY treat it as a library, we've been experimenting with you and ACF, permitting it and seeing if it makes things better or worse over all.

It's still a bit of a wash, as you see with things like jquery and people cloning without thinking :(
