### ISSUE TITLE
class="cmb2-wrap form-table" is rendered as class="cmb2-wrapform-table"

### ISSUE THREAD

**Issue by sharmashivanand** [CMB2/CMB2#1263]
The class="cmb2-wrap form-table" is rendered as class="cmb2-wrapform-table"

(*Missing Space*)

This breaks cmb2-tabs extension: https://github.com/rubengc/cmb2-tabs/issues/6

as of commit rev: https://github.com/CMB2/CMB2/commit/43695336b26fb3c47dd180b58e4aeba7c63aef80

## Steps to reproduce (I have confirmed I can reproduce this issue on the [`develop`](https://github.com/CMB2/CMB2/tree/develop) branch):

1.
2.
3.
4.

## CMB2 Field Registration Code:

```php
add_action( 'cmb2_admin_init', 'yourprefix_register_demo_metabox' );
function yourprefix_register_demo_metabox() {

	$cmb = new_cmb2_box( array(
		// Box Config...
	) );

	$cmb->add_field( array(
		// Field Config...
	) );

	// Additional fields...
}
```

## Your Environment

Browser name and version:
Operating System and version (desktop or mobile):

**Comment by jtsternberg** [comment]
Not able to duplicate.
