### ISSUE TITLE
CMB2 File field and wp 5.1.1 not working!!

### ISSUE THREAD

**Issue by Behzadassadi** [CMB2/CMB2#1265]
i'm trying to add FILE field to the my cpost... 
the meta box added but the button is not functional..!!!

WP 5.1.1

**Comment by tw2113** [comment]
Have you checked your browser's developer tools console for any sort of errors that may be occurring for you?

What is your CMB2 configuration code so that we can potentially attempt recreating with our own installs?

**Comment by Behzadassadi** [comment]
yes... i cheked that and there is no error... button just pressed and nothing happend..
here is my code....

`
      add_action( 'cmb2_admin_init', 'slider_meta_box' );


        function slider_meta_box() {
	$prefix = 'addon_';
	$cmb = new_cmb2_box( array(
		'id'            => $prefix .'meta_box',
		'title'         => __( 'Icon Image', 'cmb2' ),
		'object_types'  => array( 'post_services', ), // Post type
		'context'       => 'advanced',
		'priority'      => 'high',
		'show_names'    => false, // Show field names on the left
		'cmb_styles' => true, // false to disable the CMB stylesheet
		'closed'     => true, // Keep the metabox closed by default
	) );
	$cmb->add_field( array(
		'name'    => 'Icon File',
		'desc'    => 'Upload an image or enter an URL.',
		'id'      => $prefix.'file_icon',
		'type'    => 'file',
		'options' => array(
			'url' => false, // Hide the text input for the url
		),
		'text'    => array(
			'add_upload_file_text' => 'Add File' // Change upload button text. Default: "Add or Upload File"
		),
		'query_args' => array(
			 'type' => array(
			 	'image/gif',
			 	'image/jpeg',
			 	'image/png',
			 ),
		),
		'preview_size' => 'large', // Image size to use when previewing in the admin.
	) );
      }
`

**Comment by tw2113** [comment]
Must be some sort of conflict occurring in your install, as I'm not able to recreate any issues with a pretty standard/bare install. I've had no issues creating new posts and assigning an image with your config, in both classic and gutenberg editors.

If you are on a dev site that you can activate/deactivate things safely, may be worth deactivating plugins until the issue goes away. If/when it does, then we know at least the conflict source and can move forward from there.

**Comment by Behzadassadi** [comment]
yes, i'm on dev.. fresh install, minimal theme only for api..,and no plugin...
i will try and error to find a solution..
Thanks.

**Comment by gemplank** [comment]
@Behzadassadi did you have any luck with finding a solution on this?

**Comment by Behzadassadi** [comment]
> @Behzadassadi did you have any luck with finding a solution on this?

**NO** luck yet,waiting for an update..!
