### ISSUE TITLE
Input field type "switch" not working inside group field

### ISSUE THREAD

**Issue by vikashchauhan64** [CMB2/CMB2#1266]
Hello,

Input field type "switch" is not working inside group field. First group switch field's value is always get replaced by the last group switch field value. It is impossible to have two switch field "on" after updating post/page. I'm working on WordPress version 5.2 and CMB2 version 2.6.0.

Below is my code : 

```
$cmb_demo = new_cmb2_box(array(
        'id' => $prefix . 'metabox',
        'title' => __('Font Settings', 'obdt'),
        'object_types' => array('obdt_fonts'),
        'context' => 'normal',
        'priority' => 'high',
        'show_names' => true,
        'cmb_styles' => true,
        'closed' => false,
    ));
$group_field_id = $cmb_demo->add_field(array(
        'id' => $prefix . 'font_type',
        'type' => 'group',
        'options' => array(
            'group_title' => esc_html__('Font Type {#}', 'cmb2'),
            'add_button' => esc_html__('Add More Font Type', 'cmb2'),
            'remove_button' => esc_html__('Remove Font Type', 'cmb2'),
            'sortable' => true,
            'closed' => false,
        ),
    ));

    $cmb_demo->add_group_field($group_field_id, array(
        'name' => __('Is Default Font', 'obdt'),
       'desc' => '',
       'id' => $prefix . 'default',
       'type' => 'switch',
   ));
```

**Comment by tw2113** [comment]
You may want to first reach out to whoever is providing this `switch` field type, since that's not one that's part of CMB2 core. However, if it's you yourself who has created it, then sharing the code used to create that will be a big help so that we can see what that detail is doing.

**Comment by vikashchauhan64** [comment]
Hi,

Thanks @tw2113 for the hint , I have fixed it.
