### ISSUE TITLE
get_locale() used instead of get_user_locale() in admin area

### ISSUE THREAD

**Issue by abuyoyo** [CMB2/CMB2#1267]
## Behavior:
While in the admin area, metabox titles and description appear in site locale's language, while the rest of the admin page is displayed in the user's locale/language.

I've changed l10ni18n - get_locale() -> get_user_locale() and it solved _my_ problem.
But on my setup I'm not using cmb on the front end (which should still use get_locale() ) so obviously that's not the solution.

**Comment by jtsternberg** [comment]
Try the `develop` branch and let me know if it works as expected.

**Comment by abuyoyo** [comment]
Yes it does!
ty
