### ISSUE TITLE
wordpress version 5.2 cmb2 is not working properly

### ISSUE THREAD

**Issue by Rezaul1300** [CMB2/CMB2#1268]
some filed like:
-------------------------------------------------------------------------------------
**filed type -----------------  problem**
-------------------------------------------------------------------------------------
1. Color picker  ------------- color plate are not coming.
2. file ----------- ----------- only setup by link.. upload option not working
3. Date Picker -------------- Date selecting popup not coming
4. Checkbox ---------------  selecting / deselecting not working.
5. Multi Checkbox --------  selecting / deselecting not working.
6. File list ------------------ Not working
7. group ------------------- Not working 

please check in wordpress latest version

**Comment by pgroot91** [comment]
I haven't checked this out yet. Currently building a new project with cmb2 and latest WP. What kinda branch are you using for CMB2 @Rezaul1300 ?

**Comment by tw2113** [comment]
A lot of these sound like they could be stemming from javascript errors occurring in your editor screen. Have you checked your browser's devtools and console to see if something is showing up there?

Do you presently have a lot of other plugins that add to the editor screen or is this with a stock WP install and only the defaults for everything?

**Comment by Rezaul1300** [comment]
I myself not install any types of plugin..

**Comment by Moumokhtar** [comment]
im having the same issue on a fresh wordpress install with the classical editor plugin only installed i checked the console but no js errors

**Comment by tw2113** [comment]
Can either of you provide your complete CMB2 configuration that you're trying with?

I just used these from the example-functions.php file which ships with CMB2 and encountered no noticeable issues. This has been tested with both the Gutenberg as well as classic editor.

```
$cmb_demo = new_cmb2_box( array(
		'id'           => $prefix . 'metabox',
		'title'        => esc_html__( 'Test Metabox', 'cmb2' ),
		'object_types' => array( 'post' ), // Post type
	) );

	$cmb_demo->add_field( array(
		'name'    => esc_html__( 'Test Color Picker', 'cmb2' ),
		'desc'    => esc_html__( 'field description (optional)', 'cmb2' ),
		'id'      => $prefix . 'colorpicker',
		'type'    => 'colorpicker',
		'default' => '#ffffff',
	) );

	$cmb_demo->add_field( array(
		'name' => esc_html__( 'Test Checkbox', 'cmb2' ),
		'desc' => esc_html__( 'field description (optional)', 'cmb2' ),
		'id'   => $prefix . 'checkbox',
		'type' => 'checkbox',
	) );

	$cmb_demo->add_field( array(
		'name'    => esc_html__( 'Test Multi Checkbox', 'cmb2' ),
		'desc'    => esc_html__( 'field description (optional)', 'cmb2' ),
		'id'      => $prefix . 'multicheckbox',
		'type'    => 'multicheck',
		'options' => array(
			'check1' => esc_html__( 'Check One', 'cmb2' ),
			'check2' => esc_html__( 'Check Two', 'cmb2' ),
			'check3' => esc_html__( 'Check Three', 'cmb2' ),
		),
	) );

	$cmb_demo->add_field( array(
		'name' => esc_html__( 'Test Image', 'cmb2' ),
		'desc' => esc_html__( 'Upload an image or enter a URL.', 'cmb2' ),
		'id'   => $prefix . 'image',
		'type' => 'file',
	) );

	$cmb_demo->add_field( array(
		'name'         => esc_html__( 'Multiple Files', 'cmb2' ),
		'desc'         => esc_html__( 'Upload or add multiple images/attachments.', 'cmb2' ),
		'id'           => $prefix . 'file_list',
		'type'         => 'file_list',
		'preview_size' => array( 100, 100 ),
	) );

	$cmb_demo->add_field( array(
		'name' => esc_html__( 'Test Date Picker', 'cmb2' ),
		'desc' => esc_html__( 'field description (optional)', 'cmb2' ),
		'id'   => $prefix . 'textdate',
		'type' => 'text_date',
	) );

	$group_field_id = $cmb_demo->add_field( array(
		'id'          => $prefix . 'demo',
		'type'        => 'group',
		'description' => esc_html__( 'Generates reusable form entries', 'cmb2' ),
		'options'     => array(
			'group_title'   => esc_html__( 'Entry {#}', 'cmb2' ),
			'add_button'    => esc_html__( 'Add Another Entry', 'cmb2' ),
			'remove_button' => esc_html__( 'Remove Entry', 'cmb2' ),
			'sortable'      => true,
		),
	) );

	$cmb_demo->add_group_field( $group_field_id, array(
		'name' => esc_html__( 'Entry Title', 'cmb2' ),
		'id'   => 'title',
		'type' => 'text',
	) );
```

**Comment by Moumokhtar** [comment]
`

            if ( file_exists( dirname( __FILE__ ) . '/cmb2/init.php' ) ) {
              require_once dirname( __FILE__ ) . '/cmb2/init.php';
            } elseif ( file_exists( dirname( __FILE__ ) . '/CMB2/init.php' ) ) {
              require_once dirname( __FILE__ ) . '/CMB2/init.php';
            }

            // Programs CMB
            add_action( 'cmb2_init', 'programs_metabox' );

            function programs_metabox() {
              $prefix = 'programs_';

              $cmb_activities = new_cmb2_box( array(
                'id'           => $prefix . 'activities_metabox',
                'title'        => esc_html__( 'Activities', 'cmb2' ),
                'object_types' => array( 'programs' ), // Post type
                 'context'      => 'normal',
                 'priority'     => 'high',
                 'show_names'   => true, // Show field names on the left
              ) );

              $group_activities = $cmb_activities->add_field( array(
                'id'          => $prefix . 'activities_group',
                'type'        => 'group',
                'description' => esc_html__( 'Program related activities.', 'cmb2' ),
                'options'     => array(
                  'group_title'    => esc_html__( 'Activity {#}', 'cmb2' ), // {#} gets replaced by row number
                  'add_button'     => esc_html__( 'Add Another Activity', 'cmb2' ),
                  'remove_button'  => esc_html__( 'Remove Activity', 'cmb2' ),
                  'sortable'       => true,
                  //'closed'      => true, // true to have the groups closed by default
                ),
              ) );

              $cmb_activities->add_group_field( $group_activities, array(
                'name'       => esc_html__( 'Title', 'cmb2' ),
                'id'         => 'title',
                'type'       => 'text',
              ) );

              $cmb_activities->add_group_field( $group_activities, array(
                'name'       => esc_html__( 'Title', 'cmb2' ),
                'id'         => 'desc',
                'type'       => 'textarea',
              ) );

            }
`

check both screenshots with classical editor activated and not
regardless the messed up styles nothing at all function, buttons row collapsing .. seems like a js error but im getting nothing in the console

<img width="982" alt="Screen Shot 2019-05-17 at 4 36 55 PM" src="https://user-images.githubusercontent.com/7986441/57935620-7e550380-78c2-11e9-9119-6198afca4cee.png">
<img width="962" alt="Screen Shot 2019-05-17 at 4 37 15 PM" src="https://user-images.githubusercontent.com/7986441/57935621-7eed9a00-78c2-11e9-98a3-756f48f25bc2.png">

**Comment by tw2113** [comment]
Definitely something going on with those screenshots, but I can't say what for certain.

https://cloudup.com/cAdL-IIA13c

Here's my screenshot with the same config above, with 2 changes. I attached it to my "post" post type and I didn't load CMB2 myself since I generally keep the activateable plugin version.

**Comment by Moumokhtar** [comment]
> Definitely something going on with those screenshots, but I can't say what for certain.
> 
> https://cloudup.com/cAdL-IIA13c
> 
> Here's my screenshot with the same config above, with 2 changes. I attached it to my "post" post type and I didn't load CMB2 myself since I generally keep the activateable plugin version.

just tried installing the plugin and removed the bootstrap code from my functions.php and its working now .. so im guessing its something with including files manually tho i prefer the manual way but at least whats causing the problem

**Comment by tw2113** [comment]
Curious if other assets are maybe not being loaded like expected. Worth reverting the manual includes and checking the network tab to see if you're maybe getting some 404 errors.

"develop" branch is considered the "nightly" of sorts, though commits aren't truely nightly. It is where things are merged in first that will be part of a release. "master" i believe is the stable branch without a specific tag number. Otherwise, go with the tagged versions. The wordpress.org copy is always the "stable" release.

**Comment by Moumokhtar** [comment]
> Curious if other assets are maybe not being loaded like expected. Worth reverting the manual includes and checking the network tab to see if you're maybe getting some 404 errors.
> 
> "develop" branch is considered the "nightly" of sorts, though commits aren't truely nightly. It is where things are merged in first that will be part of a release. "master" i believe is the stable branch without a specific tag number. Otherwise, go with the tagged versions. The wordpress.org copy is always the "stable" release.

tried it , all the assets are loaded just fine got no 404s

**Comment by tw2113** [comment]
let me do some digging and I'll see what I can find beyond this.

**Comment by tw2113** [comment]
Looks like https://github.com/CMB2/CMB2/commit/db0e15f11d319d906ca1cce3636568218321d97b is the offending commit that is breaking things.

Before that commit, we would get `cmb2-wrap form-table` while the new version is resulting in `cmb2-wrapform-table` without the space, so it's considered one class.
