### ISSUE TITLE
wysiwyg field stripping the HTML entities code

### ISSUE THREAD

**Issue by tmxxx17** [CMB2/CMB2#1277]
I am using **wysiwyg field** in CMB2 metabox. But unfortunately when i am using the HTML entities there. Its automatically turns into html and my code messed up inside of the editor content.

For example 

      &lt;room number="123"&gt;Conference Room A&lt;/room&gt;

it returning to to following code after saving the post.

      Conference Room A

But its not happening for the post editor. It just happening in CMB2 wysiwyg field. 

I think there have a bug in **wysiwyg field type**

**Comment by tw2113** [comment]
Are you using any custom sanitization callbacks for your field(s) ?

**Comment by tmxxx17** [comment]
No i did not used... Its in the backend.. When i click on visual tab

**Comment by tw2113** [comment]
Can you provide which version of WP you're on, which version of CMB2 you're on, as well as your CMB2 fields configuration code?

**Comment by tmxxx17** [comment]
WP Version : Version 5.2.1
CMB2 : Version 2.6.0
Here is the full config code for cmb2 https://pastebin.com/EjuWLJGZ

Problem is the editor field :

```
        $cmb->add_group_field( $doxy_group_field_id, array(
            'name' =>  esc_html__('Description', 'doxy'),
            'description' =>  esc_html__('Write your doc chapter here', 'doxy'),
            'id'   => $prefix.'doc_chapter',
            'type' => 'wysiwyg',
        ) );
```
If i paste `&lt;room number="123"&gt;Conference Room A&lt;/room&gt;` that code and save the post. First time it shows good and  visual tab also work for the first time. 

But when i edit the post again that time it does not work.
`&lt;room number="123"&gt;Conference Room A&lt;/room&gt; ` code return to plain text,`   Conference Room A  `

though it should show as follows : 
`<room number="123">Conference Room A</room>`

**Comment by tw2113** [comment]
I'll need to tinker and try some things, but I have a feeling that WordPress core isn't recognizing `<room>` as a valid HTML tag. That's my initial take at least

**Comment by tw2113** [comment]
All my tests are proving unsuccessful for how to potentially save your custom HTML tag. I tried adding it + the `number` attribute to the `wp_kses_allowed_html` filter but it was still getting stripped out. That said, I feel that this very much more boils down to WordPress core and not just CMB2. Even the standard editor, not a WYSIWYG field, toggling between visual and text will also strip them out, as per how TinyMCE tends to be. Gutenberg will treat it as code and not actual html.

That said, there's no official `<room>` html tag, so you're going to need to do some work to figure out how to potentially preserve it, or find a different html tag to use.
