### ISSUE TITLE
rest_value_cb not working

### ISSUE THREAD

**Issue by MobinDev** [CMB2/CMB2#1284]
'rest_value_cb' not working on ".../wp-json/wp/v2/posts" and ".../wp-json/wp/v2/posts/<post_id>"
so i changed [this line](https://github.com/CMB2/CMB2/blob/323cca8a15349238a67ee4fe10a62abc00ca8ff3/includes/rest-api/CMB2_REST.php#L413) from :
$values[ $cmb_id ][ $field->id( true ) ] = $field->get_data();
to:
$values[ $cmb_id ][ $field->id( true ) ] = $field->get_rest_value();

**Comment by tw2113** [comment]
how are you specifying your properties and whatnot for your CMB2 instance? You shouldn't be needing to edit CMB2 core unless there's somehow a bug in place. Since this is a custom callback spot, you should be managing to provide your own callback and code in that callback.

**Comment by jtsternberg** [comment]
Good call @MobinDev, I pushed an update.

**Comment by jtsternberg** [comment]
@tw2113 basically, we use `get_rest_value` in the CMB2 REST endpoints, but we weren't using it in the default WP post endpoints when adding CMB2 data, so the update fixes that. `get_rest_value` simply calls `get_data`, and does some filters and such as well as allows a defined callback.

**Comment by tw2113** [comment]
I stand corrected, and am glad @jtsternberg is around for these things :)

Thanks everyone.
