### ISSUE TITLE
updated php version generating warning on page

### ISSUE THREAD

**Issue by emwebber** [CMB2/CMB2#1298]
I"m not using this as a wordpress plugin, though i am using it on my site for custom post types. however i just upgraded my site to the latest version of PHP and now my site (https:thestudio-patrick.com) has this warning:

_Warning: count(): Parameter must be an array or an object that implements Countable in /home/thestu88/.../functions/metabox/init.php on line 740_

I believe i'm using version 1.2.0 of CMB. Would simply updating that fix this issue?

**Comment by tw2113** [comment]
That file name and folder structure has me thinking that you're using the older CMB version at https://github.com/WebDevStudios/Custom-Metaboxes-and-Fields-for-WordPress which is very vastly different than what CMB2 is at by this point.

Chances are there will be a lot of upgrading work needing done, as that old repo is no longer maintained at all.

**Comment by emwebber** [comment]
Ah, makes sense. Thanks for the response!

**Comment by tw2113** [comment]
Welcome.
