### ISSUE TITLE
Feature Request: Wrapper DIV or filter for submit button

### ISSUE THREAD

**Issue by DevinWalker** [CMB2/CMB2#130]
I'm using CMB2 for a plugin settings page, among other things, and I don't like the appearance of the submit button. For styling purposes, it would be super helpful if the submit button had a wrapper DIV or filter to apply a custom wrapper so that I can style it nicer. Also, the submit button text should be customizable with a filter too. Know what I mean? 
![cmb2-submit-btn](https://cloud.githubusercontent.com/assets/1571635/5559556/94c5048c-8d06-11e4-9d6a-c0d2bc6585a7.png)

**Comment by jtsternberg** [comment]
For those who may be lurking on this issue, the snippets from https://github.com/WebDevStudios/CMB2/issues/130#issuecomment-68160722 are now in the [snippet library](https://github.com/WebDevStudios/CMB2-Snippet-Library/tree/master/helper-functions).
