### ISSUE TITLE
Context parameter behave differently for some posts

### ISSUE THREAD

**Issue by paolosax** [CMB2/CMB2#1301]
Hello, 
I'm having a weird behavior about the position of my metabox in admin edit pages.

This is my regular box declared as follow:

`$my_meta = new_cmb2_box(array(
	'id' => $prefix . 'metabox',
	'title' => __('My metabox', 'my-theme'),
	'object_types' => array('post', 'page', 'ctp_one', 'cpt_two'),
	'context' => 'side',
));`

Now, in the admin edit pages of posts, pages and cpt_two I've got the metabox in the sidebar (as intended), while in the cpt_one edit page, I've got the metabox in the "normal" position (NOT in the sidebar).

I've made many attempts to check if I can solve this, changing parameters, deactivating/activating the metabox etc. The only thing I can say is that I've made some experiment during dev, so I've test both the positions, but now it's like it "kept in memory" this one position for this CPT

Ciao
Paolo

**Comment by tw2113** [comment]
If I recall right, you get user meta stored that details the order of metaboxes on a given screen. So, that may be the "kept in memory" detail that you mention.

**Comment by paolosax** [comment]
...in fact, you're right Michael. Thanks for your prompt reply.

Now I just wonder why when I change the context value from normal to side the data does not stores accordingly in the db - need to review my code I think...

**Comment by tw2113** [comment]
probably the user meta takes priority.
