### ISSUE TITLE
WP 5.3 admin css changes

### ISSUE THREAD

**Issue by galengidman** [CMB2/CMB2#1311]
[It was announced on make.wordpress.org](https://make.wordpress.org/core/2019/10/15/report-wp-5-3-admin-css-changes-tested-against-top-20-plugins/) that there are some significant CSS changes coming in 5.3, specifically regarding form styling in an effort to make the admin more accessible. They have 3 specific suggestions regarding making your plugin styles more compatible:

> - remove any fixed heights: flexible heights are the WordPress recommended standard (and one of the main goals of the Admin CSS changes)
> - remove any custom top and bottom padding values
> - remove any custom line-height values

I testing my plugin that uses CMB2 for its options panel and while it's not "broken," the text inputs are a bit too tall, and I imagine there may be a few other imperfections.

I just wanted to put this out there. If I can find some time, I might even be willing to see about a PR myself. Does anyone have any boilerplate code laying around that implements all the fields in various contexts?

**Comment by jtsternberg** [comment]
@galengidman PR would be awesome! The best boilerplate code is the [example-functions.php](https://github.com/CMB2/CMB2/blob/develop/example-functions.php) file.

**Comment by galengidman** [comment]
PR posted: https://github.com/CMB2/CMB2/pull/1314

**Comment by tw2113** [comment]
Closing as PR #1314 was merged in.
