### ISSUE TITLE
Group was disappeared after change baseurl (DB was migrated to new url)

### ISSUE THREAD

**Issue by bahung1221** [CMB2/CMB2#1317]
Hi there,

I facing a problem after change baseurl of wordpress, another data type working fine, but data of group type was disappeared.

I updated url in database by script below:
```
UPDATE wp_options SET option_value = replace(option_value, 'http://localhost:9001', 'http://192.168.1.4:9001') WHERE option_name = 'home' OR option_name = 'siteurl';
UPDATE wp_posts SET post_content = replace(post_content, 'http://localhost:9001', 'http://192.168.1.4:9001');
UPDATE wp_posts SET guid = replace(guid, 'http://localhost:9001', 'http://192.168.1.4:9001');
UPDATE wp_postmeta SET meta_value = replace(meta_value,'http://localhost:9001','http://192.168.1.4:9001');
```

I also try to replace value of group type in `wp_postmeta` table back to `localhost:9001` and then it appeared.

So what is the best way to change the baseurl of wordpress with CMB2?

Thank you for this amazing plugin,
Kind regards

**Comment by tw2113** [comment]
chances are that one of the fields in question is being stored as serialized data, which means every character is important and totals must match.

I'd check out https://wpengine.com/support/wordpress-serialized-data/ which goes over the topic pretty well, even if you're not hosted through WPEngine.

This advice is in no way unique or specific to CMB2, and will apply to WordPress sites in general.

**Comment by bahung1221** [comment]
It got it, thank you very much 😄 @tw2113
