### ISSUE TITLE
This plugin hasn’t been tested with the latest 3 major releases of WordPress.

### ISSUE THREAD

**Issue by RubenMartins** [CMB2/CMB2#1318]
## Expected Behavior:
Support the latest version of WordPress

## Actual Behavior:
This plugin hasn’t been tested with the latest 3 major releases of WordPress.

## Possible Solution
Increase the tag "tested up to" on a v2.6.1 or 2.7.0 release

**Comment by RubenMartins** [comment]
@tw2113 Thank you, when can we expected the update into WP.org?
And can I somehow help you with more regular updates to this plugin as its getting close to 1 year since the last release of 2.6.0 and there is quiet a few updates ready to release from develop branch.

**Comment by tw2113** [comment]
Release time would be a @jtsternberg call for official release time. Thankfully it's been overall pretty stable even if it's been a year.
