### ISSUE TITLE
Problem with file_list output

### ISSUE THREAD

**Issue by levdel** [CMB2/CMB2#1320]
Thank you very much for the plugin.

My problem is the following:
I am trying to list the files I upload from the File_list Metabox, they are not displayed on the page.
If I upload images it works correctly but with files (.pdf and .doc) it doesn't work for me.
This does not happen to me when I use the upload of a single file, it shows it to me without problem.

In the database it does save me correctly, both for one and the other.
The code that I used is the same one that puts in the repository
Thank you!

**Comment by tw2113** [comment]
What code are you using to fetch the saved meta data?

Are you expecting single string values and trying to echo as such? or are you anticipating the fact that you may have arrays returned that need iterated over with a foreach loop or so?

**Comment by alexsoutotalento** [comment]
No problem. I got it! :)

**Comment by levdel** [comment]
No problem. I got it! :)

**Comment by tw2113** [comment]
Sounds good. Thanks for the followup.

**Comment by levdel** [comment]
$file = get_post_meta( get_the_ID(), 'wiki_test_file_list', true );
    foreach ($file as $file => $attachment_url) {

      echo "<a href=".esc_html($attachment_url).">".esc_html($attachment_url)."</a><br>";
    }

**Comment by tw2113** [comment]
Fun little pro tip, the array index number is the attachment ID in the database, in case you need that data for something.

**Comment by missiria** [comment]
I'm asking for the reverse situation update multiple files in file_field ? Any idea ?
