### ISSUE TITLE
Field type file_list and update_post_meta 

### ISSUE THREAD

**Issue by missiria** [CMB2/CMB2#1321]
Hello everyone,
I used the **file_list** for gallery of photos and the problem is when I trying to update the field doesn't update all the images and this is the format of the array i putting : 

`["attach_id" => $attach_id, "attach_url" => $movefile["url"]]`

And this is code for update : 

`update_post_meta( $post_id, 'sinistre_documents', ["attach_id" => $attach_id, "attach_url" => $movefile["url"]] );`

If anyone have a solution for this issue ?

Best regards,
Cordially

**Comment by missiria** [comment]
I got it ! 

the solution is : 

Array :

`$files[$attach_id] = $movefile["url"];`

and update like this : 

`update_post_meta( $post_id, 'sinistre_documents', $files);
`

**Comment by missiria** [comment]
I got it !

the solution is :

Array :

`$files[$attach_id] = $movefile["url"];`

and update like this :

`update_post_meta( $post_id, 'sinistre_documents', $files);`

**Comment by tw2113** [comment]
Glad you got an answer figured out.
