### ISSUE TITLE
Make Fields Uneditable After Post Submission/Update & Only Editable By Certain User(s) After Post Submission/Update

### ISSUE THREAD

**Issue by mike-weiner** [CMB2/CMB2#1323]
**Is your feature request related to a problem? Please describe.**
I have been working on a custom post type that has different sections for different departments (e.g.: Sales, Marketing, Inventory, etc.) within the single post and I need each section to be locked after each manager/employee has entered their information. **All of this information is set up using CMB2 Fields.**

**Describe the solution you'd like**
I am picturing a signature field (ideally a text field for the person to type their name) and a date picker field (to select the date the manger/employee is signing that section) that could be assigned to a section of fields. After filling out their fields, signing, and dating their section (entering their name in the signature field and selecting a date), they would update the post and it would lock their fields and signature from being edited by anyone else. 

The process would look something like this:

- When creating fields, you could assign them to a section. 
- Each section would require a text field to act as a signature box. 
- Each section would require a date field next to the signature box to select the date of signature. 
- If the signature field & date picker had input when the post is updated, it would lock itself and all of the fields in its section from being editable. **I am open to ideas about how this would work. It might be easier to lock the section based on the current user that is signed in as it would be assumed that all users would be required to have an account on the site.**
- I would think it would also need some feature to undo accidental submissions. Maybe any administrators on the site could unlock a locked section if a revision was needed?

**Describe alternatives you've considered**
I have spent significant time looking at other plugins and current features that CMB2 offers, and nothing has what I am looking for. I am open to all opinions and suggestions on how we could get this into CMB2. I think it would be a killer feature with a significant number of applications.

I am open to all ideas about how we can get something like this in the works!

**Additional context**

**Comment by tw2113** [comment]
I wonder if this is technically already possible by way of say the readonly/disabled attribute available for input types, and the https://github.com/CMB2/CMB2/wiki/Field-Parameters#attributes parameter available for CMB2.

My thoughts are conditionally add the parameter(s) to the config based on `current_user_can` checks.

Not outright rejecting this idea, as it's definitely an interesting one, just throwing out ideas of how it may be possible already.

**Comment by mike-weiner** [comment]
That is a possibility. If the conditionality was set-up well, I think it would be a good solution. 

I am still curious if there would be a better way to allow this type of functionality without needing to build out the additional functions that would be needed to handle the conditionality manually for each project. Building it into CMB2 or an add-on plugin would also help more people have access to it.

This is one of the reasons I opened this issue. Try and get some new perspectives on the issue and potential solutions.

**Comment by tw2113** [comment]
Dunno exactly how much extra functions would be needed as it could be as simple as this:

```
$cmb->add_field( array(
	'name'        => 'Extra Small Textarea',
	'id'          => 'wiki_test_xtra_small_textarea',
	'type'        => 'textarea_small',
	'attributes'  => array(
		'disabled' => current_user_can( 'edit_post' ) ? false : true;
	),
) );
```
But like I said in my first reply, leaving this open for other minds to venture in and discuss possibilities.

**Comment by mike-weiner** [comment]
I am circling back to this for anyone else that might want to do this. 

The code below does a couple of things. It grabs the current user's ID# and creates an array of strings containing as few or as many user ids (as strings) as you would like. 

The use case I am working on this for is to restrict certain fields from being editable for those that I don't want to have permission to access this. For example, a sales form might have areas for the customer, office, and supervisor. I only want users who are supervisors to be able to access the field(s) reserved for them. In the code below that is represented as the array `$auth_user_ids`.

For the field(s) that I want to restrict I add the attribute: ` 'disabled'    => (in_array($user_id, $auth_user_ids) ? true : false),`.

This simply checks if the current user's User ID (`$user_id`) is within the array containing the User IDs that have permission to edit those fields (`$auth_user_ids`).

```
$user_id = wp_get_current_user(); // Store current user's ID#
$auth_user_ids = array('1', '2', '3'); // Array to store User IDs that can edit restricted fields

$cmb->add_field( array(
        'name' => 'Publication Date of Resource*',
        'id'   => $maw_prefix . 'resource-publish-date',
        'type' => 'text_date_timestamp',
        'attributes'  => array(
            'required'    => 'required',
            'disabled'    => (in_array($user_id, $auth_user_ids) ? true : false),
        ),
) );
```
Another way to go about this would be creating custom user types such as ("Customer", "Office", "Supervisor") and checking if the current user has that role type. 

I realize that using User IDs and having to manually add new ID numbers to an array is not ideal, however this was created for an environment where once ID#s were added they would not be changed frequently and it provides a wide level of control. 

I would still like to achieve 2 things:

- [ ] Disable Field After Entering Content and Publishing/Updating Post

- Consider a signature field. Once a user were to fill that field in and the post were to be published or updated I would like that to be forever disabled. Anyone have thoughts on this?

- [ ] Disable Field For Every User EXCEPT for User that Filled It In

- For certain fields I want to disable it for every user except for who filled it in on the original publishing of the post or on an update there after. Anyone have thoughts on this?

Thanks to @tw2113 for the initial ideas as a launching point!

**Comment by tw2113** [comment]
**Disable Field After Entering Content and Publishing/Updating Post**

May not be the most straightforward, but I'm thinking this may be able to be done by plucking the post ID out of the current URL, likely via `$_GET` and then checking for "publish" as a post status, using https://developer.wordpress.org/reference/functions/get_post_status/. Perhaps enable for anything but published ? Same setup as your in_array() example above for setting the disabled attribute.

** Disable Field For Every User EXCEPT for User that Filled It In **
It wouldn't necessarily protect against users who can edit other peoples posts and/or admins, but using `current_user_can( 'edit_post' )` capabilities check, I believe would cover you there.

Given all the possible scenarios building up for if a field should or shouldn't be editable, it may be worth creating 1 or 2 functions that check for all these conditions and return a true/false value as a result. If anything, would clean up your field declarations area a little bit.
