### ISSUE TITLE
File frond end problems

### ISSUE THREAD

**Issue by mehmetsarr** [CMB2/CMB2#1325]
Hi, I installed a theme in localhost. I'm coding my own personal theme. I installed CMB2 as an extension. And I've added a file to upload a logo image to the settings page. But I couldn't show the picture on the front of the theme. I have not tried a lot of ways. <?php $image = wp_get_attachment_image (get_post_meta (get_the_ID (), 'wiki_test_image_id', 1), 'medium'); ?>. I never showed a logo picture. Can you help me, please?

**Comment by tw2113** [comment]
Can you provide your CMB2 configuration code as well as any code you're trying for the frontend display?

Chances are, at least as long as something is saving, that the data saved to the custom field is an array, not a string. So you need to be ready to use something like a foreach loop to actually display the information.

**Comment by mehmetsarr** [comment]
I use the file type to upload the logo. with foreach, how can I show the frontend.

**Comment by tw2113** [comment]
If I recall this field type right, it's typically an array of arrays.

For a very basic example.

```
$data = array();

$data[ $attachment_id ] = $attachment_url;
```

So each index key is the attachment ID, and then the value is the url for the attachment.

You could output like so:

```
foreach ( $data as $id => $url ) {
     echo '<img src="' . $url . '" alt="" />'; 
}
```
It would iterate over each file saved and construct an image tag for it.

**Comment by mehmetsarr** [comment]
Function file in this way

<pre>
function menkul_tema_ayarlar() {
	
	$args = array(
		'id'           => 'menkul_tema_ayarlari_duzenle',
		'title'        => 'Tema Ayarları',
		'object_types' => array( 'options-page' ),
		'option_key'   => 'menkul_tema_ana_ayarlar',
		'tab_group'    => 'menkul_tema_ana_ayarlar',
		'tab_title'    => 'Logo & Favicon',
	);
	
	if ( version_compare( CMB2_VERSION, '2.4.0' ) ) {
		$args['display_cb'] = 'menkul_tema_logo_ayarlar_display_with_tabs';
	}
	$menkul_logo_ayarlar = new_cmb2_box( $args );
	
	$menkul_logo_ayarlar->add_field( array(
		'name'    => 'Logo',
		'desc'    => 'Logo yükle',
		'id'      => 'site_logo',
		'type'    => 'file',
	) );
	$menkul_logo_ayarlar->add_field( array(
		'name'    => 'Favicon',
		'desc'    => 'Favicon yükle',
		'id'      => 'site_favicon',
		'type'    => 'file',
	) );
	
	/**
	 * Menü 2
	 */
	$args = array(
		'id'           => 'menkul_genel_tema_ayarlar',
		'menu_title'   => 'Genel Ayarlar', 
		'object_types' => array( 'options-page' ),
		'option_key'   => 'menkul_genel_tema_ayarlar',
		'parent_slug'  => 'menkul_tema_ana_ayarlar',
		'tab_group'    => 'menkul_tema_ana_ayarlar',
		'tab_title'    => 'Genel Ayarlar',
	);
	
	if ( version_compare( CMB2_VERSION, '2.4.0' ) ) {
		$args['display_cb'] = 'menkul_tema_genel_ayarlar_display_with_tabs';
	}
	$menkul_tema_genel_ayarlar = new_cmb2_box( $args );
	$menkul_tema_genel_ayarlar->add_field( array(
		'name'    => 'Test Radio',
		'desc'    => 'field description (optional)',
		'id'      => 'radio',
		'type'    => 'radio',
		'options' => array(
			'option1' => 'Option One',
			'option2' => 'Option Two',
			'option3' => 'Option Three',
		),
	) );
	/**
	 * 3. Menü
	 */
	$args = array(
		'id'           => 'menkul_tema_iletisim_ayarlari',
		'menu_title'   => 'İletişim Ayarları',
		'object_types' => array( 'options-page' ),
		'option_key'   => 'menkul_tema_iletisim_ayarlari',
		'parent_slug'  => 'menkul_tema_ana_ayarlar',
		'tab_group'    => 'menkul_tema_ana_ayarlar',
		'tab_title'    => 'İletişim Ayarları',
	);

	if ( version_compare( CMB2_VERSION, '2.4.0' ) ) {
		$args['display_cb'] = 'menkul_tema_iletisim_ayarlar_display_with_tabs';
	}
	$menkul_iletisim_ayarlar = new_cmb2_box( $args );
	$menkul_iletisim_ayarlar ->add_field( array(
		'name' => 'Test Text Area for Code',
		'desc' => 'field description (optional)',
		'id'   => 'textarea_code',
		'type' => 'textarea_code',
	) );
}
add_action( 'cmb2_admin_init', 'menkul_tema_ayarlar' );


function menkul_ayarlar_display_with_tabs( $cmb_options ) {
	$tabs = menkul_ayarlar_page_tabs( $cmb_options );
	?>
	<div class="wrap cmb2-options-page option-<?php echo $cmb_options->option_key; ?>">
		<?php if ( get_admin_page_title() ) : ?>
			<h2><?php echo wp_kses_post( get_admin_page_title() ); ?></h2>
		<?php endif; ?>
		<h2 class="nav-tab-wrapper">
			<?php foreach ( $tabs as $option_key => $tab_title ) : ?>
				<a class="nav-tab<?php if ( isset( $_GET['page'] ) && $option_key === $_GET['page'] ) : ?> nav-tab-active<?php endif; ?>" href="<?php menu_page_url( $option_key ); ?>"><?php echo wp_kses_post( $tab_title ); ?></a>
			<?php endforeach; ?>
		</h2>
		<form class="cmb-form" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" method="POST" id="<?php echo $cmb_options->cmb->cmb_id; ?>" enctype="multipart/form-data" encoding="multipart/form-data">
			<input type="hidden" name="action" value="<?php echo esc_attr( $cmb_options->option_key ); ?>">
			<?php $cmb_options->options_page_metabox(); ?>
			<?php submit_button( esc_attr( $cmb_options->cmb->prop( 'save_button' ) ), 'primary', 'submit-cmb' ); ?>
		</form>
	</div>
	<?php
}


function menkul_tema_ayarlar_page_tabs( $cmb_options ) {
	$tab_group = $cmb_options->cmb->prop( 'tab_group' );
	$tabs      = array();
	foreach ( CMB2_Boxes::get_all() as $cmb_id => $cmb ) {
		if ( $tab_group === $cmb->prop( 'tab_group' ) ) {
			$tabs[ $cmb->options_page_keys()[0] ] = $cmb->prop( 'tab_title' )
				? $cmb->prop( 'tab_title' )
				: $cmb->prop( 'title' );
		}
	}
	return $tabs;
}
</pre>


the frontend is like this

<pre>

                    <div class="span3 logo">
		<a href="<?php bloginfo('url');?>"><img src="image/logo.png" alt="<?php bloginfo('name'); ?>"></a>
			 
					</div>

</pre>

**Comment by tw2113** [comment]
Will review and get back to you soon.

**Comment by mehmetsarr** [comment]
Teşekkürler ederim

**Comment by tw2113** [comment]
So I just used your code above to set up some options pages, including the 3 tabs. I filled in values for each field.

The content you're setting up is saved in the options table, as 3 individual rows.

First row is getting `menkul_tema_ana_ayarlar` for an option name, and example saved data will be something like:

```
a:4:{s:12:"site_logo_id";s:3:"474";s:9:"site_logo";s:71:"http://wds.test/wp-content/uploads/2019/10/tumblr_ldc6alh2ns1qdzdzs.gif";s:15:"site_favicon_id";s:3:"394";s:12:"site_favicon";s:52:"http://wds.test/wp-content/uploads/2019/05/FdIBM.gif";}
```

Second tab: `menkul_genel_tema_ayarlar` option name and `a:1:{s:5:"radio";s:7:"option2";}` value

Third tab: `menkul_tema_iletisim_ayarlari` option name and `a:1:{s:13:"textarea_code";s:15:"bbjhvbjhbjbm m ";}` value

So for the contents of each tab that you want to fetch, you'll want to use `get_option()` from WordPress core, and pass in the appropriate names from above.

WordPress will handle the potentially funny looking values for you. Each will return an array.

Tab 1 will be an array with 4 indexes. "site_logo_id" which will be the attachment ID, and "site_logo" which will be the image URL that you can use in an example like I provided earlier. "site_favicon_id" will be the ID of the Favicon field set up, and "site_favicon" the image URL for that field.

```
// Only echo's out the URL for the site logo.
$tab1 = get_option('menkul_tema_ana_ayarlar');
echo '<img src="' . $tab1['site_logo'] . '" alt="" />';
```

Tab 2 will be an array with 1 index, specifically "radio" and a value of "option2" based on your code and the option saved from the 3 presented.

```
$tab2 = get_option('menkul_genel_tema_ayarlar');
echo 'You chose ' . $tab2['radio'] . ' for your option';
```

Tab 3 will be an array with 1 index, specifically "textarea_code" and the value typed into the textarea.

```
$tab3 = get_option('menkul_tema_iletisim_ayarlari');
echo $tab3['textarea_code'];
```

**Comment by mehmetsarr** [comment]
Okay done it thank you

**Comment by mehmetsarr** [comment]
Okay done it thank you

**Comment by mehmetsarr** [comment]
Hello, I created a select category field on the back-end as below. I couldn't show this in loop. So when I select the category, it opens as the category I chose on the slides. How can I do this?

back-end code:

`$args = array(
	    'id'           => 'cleanmax_tema_ayarlari_duzenle',
		'title'        => 'Tema Paneli',
		'id'           => 'cleanmax_tema_kategori_sec_ayarlari',
		'menu_title'   => 'Kategoriler',
		'object_types' => array( 'options-page' ),
		'option_key'   => 'cleanmax_tema_kategori_sec_ayarlari',
		'parent_slug'  => 'cleanmax_tema_ana_ayarlar',
		'tab_group'    => 'cleanmax_tema_ana_ayarlar',
		'tab_title'    => 'Kategoriler',
	);

	$cleanmax_kategori_sec_ayarlar = new_cmb2_box( $args );
	$cleanmax_kategori_sec_ayarlar ->add_field( array(
		'name'     => esc_html__( 'Manşet Kategorisi', 'cleanmax' ),
		'desc'     => esc_html__( 'Manşet Kategorisi Seçiniz', 'cleanmax' ),
		'id'       => 'cleanmax_manset_kategorisi',
		'type'     => 'taxonomy_select', 
		'taxonomy' => 'category', 
	) );
	`

front-end code:

`<?php $the_query = new WP_Query( 'showposts=3&post_type=post&category=manset'); ?>
<?php if ( $the_query->have_posts() ) : ?>
    <?php while ( $the_query->have_posts() ) : $the_query->the_post(); ?>
         <?php  if ( has_post_thumbnail()) : ?>
              <li data-transition="curtain-2" data-slotamount="1" data-masterspeed="1000" data-thumb="<?php echo get_the_post_thumbnail_url();?>"  data-saveperformance="off"  data-title="<?php the_title(); ?>"> <img src="<?php echo get_the_post_thumbnail_url();?>"  alt=""  data-bgposition="center top" data-bgfit="cover" data-bgrepeat="no-repeat">
             <?php else: ?>
                                   <?php endif;?>
                <div class="tp-caption sfb sfb tp-resizeme"
                        data-x="center"
                        data-y="center"
                        data-hoffset="0"
                        data-voffset="-65"
                        data-speed="1500"
                        data-start="1000"
                        data-easing="easeInOutQuart"
                        data-splitin="none"
                        data-splitout="none"
                        data-elementdelay="0.01"
                        data-endelementdelay="0.3"
                        data-endspeed="1200"
                        data-endeasing="Power4.easeOut">
                  <h2 class="slider-title-3"><span><?php the_title(); ?></span></h2>
                </div>
               <div class="tp-caption sfb sfb tp-resizeme"
                        data-x="center"
                        data-y="center"
                        data-hoffset="0"
                        data-voffset="-15"
                        data-speed="1500"
                        data-start="1000"
                        data-easing="easeInOutQuart"
                        data-splitin="none"
                        data-splitout="none"
                        data-elementdelay="0.01"
                        data-endelementdelay="0.3"
                        data-endspeed="1200"
                        data-endeasing="Power4.easeOut">
                  <h2 class="slider-title-4"><?php echo get_post_meta(get_the_ID(), "firmaup_slaytlar_kisa_aciklama", true); ?></h2>
                </div>
                <div class="tp-caption sfb sfb tp-resizeme"
                        data-x="560"
                        data-y="320"
                        data-hoffset="0"
                        data-voffset="150"
                        data-speed="1500"
                        data-start="2000"
                        data-easing="easeOutExpo"
                        data-splitin="none"
                        data-splitout="none"
                        data-elementdelay="0.01"
                        data-endelementdelay="0.3"
                        data-endspeed="1200"
                        data-endeasing="Power4.easeIn"><a href="<?php the_permalink(); ?>" class="btn slider-btn-2">DETAYLAR</a></div>
              </li>
             < ?php endwhile; ? >
    < ?php wp_reset_postdata(); ? >
 
< ?php else : ? >
    <p>< ?php _e( 'Üzgünüz, kriterlerinize uygun haber yok.' ); ? ></p>
< ?php endif; ? >`
