### ISSUE TITLE
composer.json is accidentally missing from the the published package

### ISSUE THREAD

**Issue by szepeviktor** [CMB2/CMB2#1327]
See https://github.com/CMB2/CMB2/archive/v2.6.0.zip

The cause is the gitattributes file: https://github.com/CMB2/CMB2/blob/v2.6.0/.gitattributes#L14

A solution could be the following.

- checkout tag v2.6.0
- fork it to a branch - e.g. 2.6.0-fix
- delete the tag
- remove the above line from gitattributes and commit it (maybe exclude the lock file instead)
- tag v2.6.0
- log in to packagist and press "Update"

Thank you.

**Comment by tw2113** [comment]
Closing as 2.7.0 has the composer.json file bundled in

**Comment by szepeviktor** [comment]
Thank you.
