### ISSUE TITLE
Rename CMB2_hookup to CMB2_Hookup

### ISSUE THREAD

**Issue by szepeviktor** [CMB2/CMB2#1328]
Could we rename the `CMB2_hookup` class and the file?

```
viktor@mail:~/cmb2$ grep -rFn CMB2_hookup
includes/CMB2.php:232:          add_action( "cmb2_init_hookup_{$this->cmb_id}", array( 'CMB2_hookup', 'maybe_init_and_hookup' ) );
includes/CMB2_hookup.php:14:class CMB2_hookup extends CMB2_Hookup_Base {
includes/CMB2_Options_Hookup.php:14:class CMB2_Options_Hookup extends CMB2_hookup {
includes/CMB2_Options_Hookup.php:119:                   add_action( "admin_print_styles-{$page_hook}", array( 'CMB2_hookup', 'enqueue_cmb_css' ) );
includes/helper-functions.php:331:              CMB2_hookup::enqueue_cmb_css();
includes/helper-functions.php:335:              CMB2_hookup::enqueue_cmb_js();
bootstrap.php:53:        * Get all created metaboxes, and instantiate CMB2_hookup
```

**Comment by tw2113** [comment]
Any particular reason why, other than consistency in some details? One reason not to at the moment, would be risk of other peoples' extensions and customizations breaking because of the renaming.

**Comment by szepeviktor** [comment]
> Any particular reason why,

I am not a businessman :( I just follow standards.

> breaking because of the renaming

PHP does understand cAse :) https://3v4l.org/UkHiO

**Comment by jtsternberg** [comment]
Classes are case-insensitive so it won’t matter to make this change. If you submit a PR, I’ll be happy to merge.

**Comment by szepeviktor** [comment]
> If you submit a PR, I’ll be happy to merge.

Here you go.
