### ISSUE TITLE
default_cb doesn't seem to work

### ISSUE THREAD

**Issue by davemoz** [CMB2/CMB2#1335]
## Describe the bug
I'm using `default_cb` based on some sparse examples I found Googling the usage. It simply doesn't seem to do anything as I expect it to according to the docs.

I'm using a conditional to show/hide the second(`end_date`) field only if the first(`start_date`) is filled. Then, if `end_date` is saved empty, I'm attempting to use `default_cb` to set it's default value to whatever the `start_date` value is.

## Steps to reproduce
The two fields. I've defined a callback for the second `end_date` field:

    $cmb->add_field( array(
		'desc' => esc_html__( 'Start date', 'og' ),
		'id' => $prefix . 'start_date',
		'type' => 'text_date_timestamp',
		'column' => array(
			'position' => 3,
			'name'		 => 'Start Date',
		),
	) );

    $cmb->add_field( array(
		'desc' => esc_html__( 'End date', 'og' ),
		'id' => $prefix . 'end_date',
		'type' => 'text_date_timestamp',
		'column' => array(
			'position' => 4,
			'name'		 => 'End Date',
		),
		//'date_format' => 'Y-m-d',
		'attributes' => array(
			'data-conditional-id'    => '_og_exhibition_start_date',
		),
		'default_cb' => 'default_end_if_no_start_cb',
		'after_row' => 'after_3_col_grid_cb',
	) );

And the callback:

    /**
     * Sets to same as Start Date if empty
     *
     * @param object $field		Current field object
     * @return array			Array of field options
     */
    function default_end_if_no_start_cb( $field_args, $field ) {
	    $startDate = get_post_meta( $post_id, '_og_exhibition_start_date' );
	    return $startDate;
    }

`end_date` conditionally shows fine when `start_date` is filled, but `end_date` just stays empty if left empty. Am I just not getting `start_date`'s value correctly in the callback? Any other ideas?

**Comment by jtsternberg** [comment]
There's a couple issues with your `default_cb` callback function, but I can understand the frustration for not having proper docs. I have updated the docs, and even included your example for others: https://github.com/CMB2/CMB2/wiki/Field-Parameters#default_cb-example-2

That should help.

**Comment by davemoz** [comment]
Awesome, that's very helpful. Worked great. Thank you!
