### ISSUE TITLE
Add Country, City, Neighborhood Metabox 

### ISSUE THREAD

**Issue by mehmetsarr** [CMB2/CMB2#1336]
How can I add Country, City, Neighborhood metabox. In other words, when the country is selected, cities suitable for it appear in the lower box. When the city is selected, a suitable neighborhood can be found. How can I do that?

**Comment by tw2113** [comment]
May get a bit large overall, just cause of how many possible option combinations there are, but I would recommend something like https://github.com/jcchavezs/cmb2-conditionals to help out with this.
