### ISSUE TITLE
Can't switch between Visual and Text mode on classic editors

### ISSUE THREAD

**Issue by rubengc** [CMB2/CMB2#1338]
## Describe the bug
Can't switch between Visual and Text mode on classic editors on a clean install and only adding the CMB2 library

Error is caused by the call of farbtastic() function ([cmb2.js line 974](https://github.com/CMB2/CMB2/blob/develop/js/cmb2.js#L974))

## Possible Solution
On comment this line issue disappears
Is possible that farbtastic gets removed? a possible solution could be use wpColorPicker instead

**Comment by jtsternberg** [comment]
It’s supposed to use wpColorPicker: https://github.com/CMB2/CMB2/blob/50b898a5471e221a4808c6d39ba0623f5d493e3d/js/cmb2.js#L963

**Comment by rubengc** [comment]
For some reason wp-color-picker script doesn't gets enqueued

I tested it on a clean install with only CMB2 and issue persist

The fix was to manually enqueue it:
```
wp_enqueue_style( 'wp-color-picker' );
wp_enqueue_script( 'wp-color-picker' );
```

I'm checking CMB2_JS.php and there are somethings I found strange

First, wp-color-picker is only enqueue if form is rendered at frontend:
https://github.com/CMB2/CMB2/blob/50b898a5471e221a4808c6d39ba0623f5d493e3d/includes/CMB2_JS.php#L88-L96

But, the frontend equeue function only registers the script, doesn't truly enqueue it:
https://github.com/CMB2/CMB2/blob/50b898a5471e221a4808c6d39ba0623f5d493e3d/includes/CMB2_JS.php#L168-L177

Registering a post type without public access enabled the classic editor, and here is where I found the issue

Is probable that CMB2 requires to register the custom script at frontend but also requires to enqueue it on both ends?

**Comment by jtsternberg** [comment]
Good find. I think WP is starting to be more selective about the things they are enqueueing and when. So we should update line 89 to be:
```php
if ( ! wp_script_is( 'wp-color-picke', 'enqueued' ) ) {
```

**Comment by rubengc** [comment]
PR ready!
