### ISSUE TITLE
Initialize Javascript events on forms added through AJAX

### ISSUE THREAD

**Issue by rubengc** [CMB2/CMB2#1342]
Hi there

I'm trying to get fields dynamically added through AJAX work back again (like wysiwyg, repeatable and groups fields)

I was investigating CMB2 scripts in depth but I can't find a solution for that

Also, I checked the documentation and code snippets and can't find any possible solution

Calling to `window.CMB2.init()` just duplicates JS features (like insert multiples "Check/Uncheck all" buttons on multicheck) on already existent forms but not on the new appended ones

There is someone that have got it done in some way?

Thanks in advance

**Comment by jtsternberg** [comment]
First, the wysiwyg JS is handled separately: https://github.com/CMB2/CMB2/blob/develop/js/cmb2-wysiwyg.js

If I'm understanding you right, you're inserting CMB2 fields via ajax to a page that already has CMB2 fields on it? And you want to initialize the JS for just those new fields?

**Comment by rubengc** [comment]
Hi @jtsternberg 

Yes, exactly, fields get rendered through ajax and I append them on the current screen

I was able to get the CMB2 listeners working using the apply() function like:
```
form.on( 'click', '.cmb-add-group-row', function(e) {
            window.CMB2.addGroupRow.apply(this, [e] );
        });
```

Because this way doesn't work
```
form.on( 'click', '.cmb-add-group-row', window.CMB2.addGroupRow);
```
the `this` context parameter is missed, for that I need to optin for the apply() function way

My main issue right now is with the wysiwyg editor
I've tried the `window.CMB2.wysiwyg.init()` function without so much luck, and I also tried to understand how this function loads the CMB2 editors 

The unique way I was able to solve this is by removing all the html generated by CMB2, place a simple textarea and use the `wp.editor.initialize()` function

But if you could guide me the way CMB2 initialize their single wysiwyg fields will be really helpful!

**Comment by rubengc** [comment]
Already found the way!

**Comment by PayteR** [comment]
> Already found the way!

Hi, what's the way? When this fix will be applied in code? thx
