### ISSUE TITLE
Field type: File_list button unique ID (buggish?)

### ISSUE THREAD

**Issue by pgroot91** [CMB2/CMB2#1345]
## Describe the bug

Not sure if its a bug? But can't seem to figure it out on how to solve the issue. In my project i have multiple file_list but some how the ID and NAME of the buttons come up empty. Warnings in the console that there are no unique IDs for the buttons.

## Screenshots
![image](https://user-images.githubusercontent.com/6934501/79598718-b4a78e00-80e4-11ea-8f45-e5e5ab7ddaf3.png)

## CMB2 Field Registration Code:

```php
add_action( 'cmb2_admin_init', 'amex_media_metabox' );
function amex_media_metabox() {

		/**
		 * Initiate the metabox
		 */
		$amex_media_box_options = array(
			'id'            => 'amex_media_metabox',
			'title'         => __( 'Media', 'cmb2' ),
			'object_types'  => array( 'amex_vehicle', ), // Post type
			'context'       => 'normal',
			'priority'      => 'default',
			'show_names'    => true, // Show field names on the left
			// 'cmb_styles' => false, // false to disable the CMB stylesheet
			// 'closed'     => true, // Keep the metabox closed by default
		);
				
		// Setup meta box
		$cmb = new_cmb2_box( $amex_media_box_options );
		
		$amex_media_tabs = array(
			'config' => $amex_media_box_options,
			'layout' => 'vertical', // Default : horizontal
			'tabs'   => array()
		);
		
		$amex_media_tabs['tabs'][] = array(
			'id'     => 'amex_images_tab',
			'title'  => __( 'Images', 'cmb2' ),
			'fields' => array(
				array(
					'id'      => '_thumbnail', // Saves to WP post thumbnail, allows the_post_thumbnail()
					'name'    => 'Featured Image',
					//'desc'    => 'Upload/Select an image.',
					'type'    => 'file',
					'options' => array(
						'url' => false,
					),
					'text' => array(
						'add_upload_file_text' => 'Add Image'
					),
				), array(
					'name' => 'Gallery',
					'desc' => '',
					'id'   => 'wiki_test_file_list3434',
					'type' => 'file_list',
					// 'preview_size' => array( 100, 100 ), // Default: array( 50, 50 )
					// 'query_args' => array( 'type' => 'image' ), // Only images attachment
					// Optional, override default text strings
					'text' => array(
						'add_upload_files_text' => 'Add Images', // default: "Add or Upload Files"
						'remove_image_text' => 'Remove Image', // default: "Remove Image"
						'file_text' => 'Image:', // default: "File:"
						'file_download_text' => 'Download', // default: "Download"
						'remove_text' => 'Remove', // default: "Remove"
					),
				),
			)
		);
		
		$amex_media_tabs['tabs'][] = array(
			'id'     => 'amex_videos_tab',
			'title'  => __( 'Videos', 'cmb2' ),
			'fields' => array(
				array(
					//'name' => 'Gallery',
					'desc' => '',
					'id'   => 'wiki_test_file_list2',
					'type' => 'file_list',
					// 'preview_size' => array( 100, 100 ), // Default: array( 50, 50 )
					// 'query_args' => array( 'type' => 'image' ), // Only images attachment
					// Optional, override default text strings
					'text' => array(
						'add_upload_files_text' => 'Add Videos', // default: "Add or Upload Files"
						'remove_image_text' => 'Remove Video', // default: "Remove Image"
						'file_text' => 'Video:', // default: "File:"
						'file_download_text' => 'Download', // default: "Download"
						'remove_text' => 'Remove', // default: "Remove"
					),
				),
			)
		);
		
		// set tabs
		$cmb->add_field( array(
			'id'   => '__tabs',
			'type' => 'tabs',
			'tabs' => $amex_media_tabs
		));
		
	}
```

## Your Environment
**CMB2 Master**

**Comment by tw2113** [comment]
Are you using the bundled Tab setup or are you using a different CMB2 extension for this tab setup? I'm not managing to get any field to show up with the code above as is, except a change in the post type.

**Comment by pgroot91** [comment]
@tw2113 not sure if there is a built in tab system in cmb2 itself? 

using the following https://github.com/LeadSoftInc/cmb2-tabs

**Comment by tw2113** [comment]
There is, but I just realized it's just for options pages, not the post editor screen.

Reviewing the rest to see if I can determine anything

Thanks.

**Comment by tw2113** [comment]
I'm thinking this isn't really a bug. I've tested the file list field type both in a tab with the plugin above as we as on its own. I believe due to how everything is set up, we avoid having to process an actual form submission.

**Comment by pgroot91** [comment]
@tw2113 that is fine but the thing is name and id is rendered in the dom throwing the warning about those ids. I have no controle over the id if im right so why is it rendered there?

You will not have the warning i think if you have only 1 file_list since the value is still unique at that point.

I can make the warning go away just by adding a value to the id or removing the id attribute by JS. Therefor i say it must be something within cmb2

**Comment by pgroot91** [comment]
https://github.com/CMB2/CMB2/blob/develop/includes/types/CMB2_Type_File_List.php#L42

The issue is line 42, 43... 

I'm not aware of an option to control the name and id. I would suggest to ditch it otherwise to get rid on the console warnings? @tw2113  what do you think?
