### ISSUE TITLE
Is It Possible to Add a Parameter to Existing Fields?

### ISSUE THREAD

**Issue by davidshq** [CMB2/CMB2#1348]
This isn't really a feature request as much as a question.

Can one (without hacking CMB2 core) add field parameters to a built-in field?

Use Case:
I have a plugin that uses CMB2 for a number of custom post meta. I'm looking to expose this post meta via GraphQL (using WPGraphQL).

If I want to enable REST API integration for a CMB2 field currently I add something like:

`'show_in_rest' => WP_REST_Server::READABLE`

I'd like to be able to add something like this to add support for GraphQL:
`'show_in_graphql' => true`

Then I could use a hook (`"cmb2_init_{$this->cmb_id}"`?) to get the field parameters, check for `'show_ingraphql' => true` and if it exists use WPGraphQL's `register_graphql_field` to add it to the schema...

Before I spend too much time exploring the code, any pointers would be appreciated!

**Comment by jtsternberg** [comment]
It's worth a shot, for sure. It's hard for me to give pointers as I'm not too familiar with the graphql parts. Is there a specific question I can answer? (yes, you can add arbitrary field parameters)

**Comment by davidshq** [comment]
Thanks Justin! My main question at the moment would be how one goes about adding arbitrary field parameters to existing fields?

For example, right now I have a field defined as part of an array of fields like this (this code may look familiar :)):
```
'gc_sermon_video_url' => array(
  'id'  =>  'gc_sermon_video_url',
  'name' =>  __('Video URL', 'lqdm'),
  'desc' => __('Enter an oembed-supported video URL such as YouTube or Vimeo.', 'lqdm'),
  'type' => 'oembed',
),
```

I'd like to do this:
```
'gc_sermon_video_url' => array(
  'id'  =>  'gc_sermon_video_url',
  'name' =>  __('Video URL', 'lqdm'),
  'desc' => __('Enter an oembed-supported video URL such as YouTube or Vimeo.', 'lqdm'),
  'type' => 'oembed',
  'show_in_graphql' => true,
),
```

Once I've done this I can hook into [`register_graphql_field`](https://docs.wpgraphql.com/getting-started/custom-fields-and-meta/) and iterate through all the CMB2 fields and dynamically register them with WPGraphQL's schema (pseudo-ish code):

```
add_action( 'graphql_register_types', 'lqdm_register_graphql_types' );
function lqdm_register_graphql_types(CMB2 object?, langdomain) {
  for each field in CMB2Object
    if (field->show_in_graphql) = true {
      register_graphql_field( field->associated_cpt, field->fieldname, [
        'type' => field->type,
        'description' => __(  field->description, $langdomain ),
        'resolve' => function( $post ) {
           $fieldname = get_post_meta( $post->ID, $fieldname, true );
           return ! empty( $fieldname) ? $fieldname : 'empty';
           }
  ] );
};
```

The one other question would be what the best way to pull in an array of all the fields would be? Whether via a CMB2 object or?

If I can't get this to work I can always register each field individually, but seems it would be faster if I could register them dynamically.

**Comment by nio89** [comment]
@davidshq Did you manage to get this working?

**Comment by davidshq** [comment]
@nio89 Sorry, I never did.
