### ISSUE TITLE
Difference between field id and 'raw' _id?

### ISSUE THREAD

**Issue by gyrus** [CMB2/CMB2#1349]
Could I ask what this difference is?

I've just had an issue on a site where I have 'locked' WYSWIYG fields on a front-end form, which I hook into to replace the field with (1) a hidden input with the field value in, so it's persisted, and (2) a div which shows the content (uneditable).

The problem was that I was using `$field->id()` for the hidden input name / id, and for a field which had the CMB2 id `_prefix_idea-content-2`, this was returning `_prefix_idea_content_2`. This resulted in the 'locked' field content being wiped every time the post was saved.

I seem to have fixed the issue by calling `$field->id( true )` instead to get the 'raw' id (the `_id` property).

However, I've found a few other calls to `$field->id()` in my code, and I'm wanting to properly understand the difference here. I can't find a place in CMB2 code where `_id` is created, with an explanation for replacing dashes with underscores. What context does the id need to have no dashes, and why is non-raw the default for `$field->id()`?

**Comment by gyrus** [comment]
In some of the other calls to `$field->id()`, it doesn't seem to make a difference whether I get the raw value or not - neither have dashes replaced with underscores.

So I don't think this is an urgent 'bug' - however, I'm hoping the answer to this is quick and simple, it would put my mind at rest to understand it! Thanks.

**Comment by jtsternberg** [comment]
`_id` is the raw id that you set in your field, where `id` can be different if it's a sub-field of a group: 
https://github.com/CMB2/CMB2/blob/058085b36fb0d2f3aa134cc82a7af9a36b390fc7/includes/CMB2_Field.php#L1489-L1494

**Comment by gyrus** [comment]
Many thanks!
