### ISSUE TITLE
Retrieve value in "network-options-cmb.php"

### ISSUE THREAD

**Issue by pgroot91** [CMB2/CMB2#1350]
Using the following code:

https://github.com/CMB2/CMB2-Snippet-Library/blob/master/options-and-settings-pages/network-options-cmb.php

i see the data in the wp_sitemeta table.

Probably i'm doing something wrong here but i'm not able to retrieve the value...
```
$value = myprefix_get_network_option("test_text");
var_dump($value);
```
**Result:** path/myfile.php:95:boolean false

```
$value = myprefix_get_network_option("myprefix_network_options", "test_text");
var_dump($value);
```
**Result:** path/myfile.php:95:string 'test_text' (length=9)

Any ideas what could be wrong with the way i'm using this?

**Comment by tw2113** [comment]
At least with these handy helper functions for options, i tend to disregard until i know I have something working, and instead just fetch with get_site_option() and pluck out the value from the indexes. more or less skipping line 72-75. Beyond that, I'd need to remind myself what's inside `cmb2_get_option()` and why things may not be matching up like expected.

**Comment by pgroot91** [comment]
Ok still not sure if it supposed to work like this

`$array = get_site_option('myprefix_secondary_options');
`
returns an array() with all the field keys and values.

and then you use is as `$array["some_field_key"];` and then i will receive the specific value i need.
