### ISSUE TITLE
Can I use all built-in Field types when making a new Field type?

### ISSUE THREAD

**Issue by Vojtechremis** [CMB2/CMB2#1353]
Hi,
can I use all built-in Field types when making a new Field type? Like for example, I tried use File field:

```
function cmb2_render_banner_callback( $field, $value, $object_id, $object_type, $field_type ) {

  echo $field_type->file( array(
    "name" => $field_type->_name( "[background_image]" ),
    "id" => $field_type->_id( "_background_image" ),
    "value" => $value["background_image"],
    "query_args" => array(
      "type" => array(
        "image/jpeg",
        "image/png"
      ),
    ),
    "options" => array(
  		"url" => false,
  	),
  	"text"    => array(
  		"add_upload_file_text" => "Add File"
  	)
  ));

}
```

File upload field shows up, but parameters `query_args`, `type`, `options` and `text` don't work. Am I using `$field_type->file` the wrong way?

Thanks for response. And by the way, this plugin is awesome.

**Comment by tw2113** [comment]
Out of curiosity, what type of field type are you trying to create here? Asking cause it feels potentially a little weird to be trying to use the existing field types inside a callback to render a different field. That may be a good candidate for a field group instead.

**Comment by Vojtechremis** [comment]
> Out of curiosity, what type of field type are you trying to create here? Asking cause it feels potentially a little weird to be trying to use the existing field types inside a callback to render a different field. That may be a good candidate for a field group instead.

I am trying to make banner field, which I would be able to use in different metaboxes. It consists of  Picture, text input and range field.

**Comment by jtsternberg** [comment]
You definitely can use other field types in a custom field, but the file one might be a little tricky since it relies so much on the javascript. The best I can say is to experiment and play with it.
