### ISSUE TITLE
File Front-end Upload Problem

### ISSUE THREAD

**Issue by mehmetsarr** [CMB2/CMB2#1355]
Hello, I made a profile editing page for the front end. meta boxes work fine. I also added a file for the user photo. How can I edit on the front end? The codes are below.

  `$cmb_user->add_field(` array(
		'name' => esc_html__( 'Avatar', 'menkul' ),
		'desc' => esc_html__( 'Avatar Seç', 'menkul' ),
		'id'   => $prefix . 'avatar',
		'type' => 'file',
	) );  `

          < div class="my-2 col-xs-6 p-0" >  
                                        < label class="text-muted" >Image</label > 
                                        < div id="user-profile-image" class="dropzone needsclick" >
                                            < div class="dz-message needsclick text-muted" >    
                                                Drop file here or click to upload.
                                            < /div >
                                        < /div >
                                        < div id="dropzone-preview-template" class="d-none plan-image-template" >
                                            < div class="dz-preview dz-file-preview"  value="" >
                                                < div class="dz-image " >< img src="" data-dz-thumbnail="" alt="prop-image" >< /div >
                                                < div class="dz-details" >
                                                    < div class="dz-size">< span data-dz-size=""></span></div>
                                                    < div class="dz-filename" >< span data-dz-name=""></span>< /div >
                                                < /div >
											
                                                < div class="dz-progress"><span class="dz-upload" data-dz-uploadprogress="" ></span>< /div >
                                                < div class="dz-error-message"><span data-dz-errormessage="" ></span>< /div >
                                                < div class="dz-success-mark" >
                                                    <i class="material-icons mat-icon-xlg">check</i> 
                                                </div>
                                                < div class="dz-error-mark" >
                                                    <i class="material-icons mat-icon-xlg">cancel</i> 
                                                < /div > 
                                            < /div >
											
                                        < /div >  
                                    < /div >

**Comment by tw2113** [comment]
Sorry, not quite sure which aspect you're trying to allow editing.

Also, since I suspect it may help, can you provide the entirety of your CMB2 configuration so that I can see what all you're trying, and potentially at least load some of it in a local install of mine?

**Comment by mehmetsarr** [comment]
`<?php
// Kullanıcı Seç Alanlar Başla
function cmb2_get_user_options( $query_args ) {

    $args = wp_parse_args( $query_args, array(

        'fields' => array( 'user_login' ),

    ) );

    $users = get_users(  );

    $user_options = array();
    if ( $users ) {
        foreach ( $users as $user ) {
          $user_options[ $user->ID ] = $user->user_login;
        }
    }

    return $user_options;
}

// Kullanıcı Seç Alanlar Bitiş



// Kullanıcı Ekstra Alanlar
add_action( 'cmb2_admin_init', 'menkul_register_user_profile_metabox' );

function menkul_register_user_profile_metabox() {
	$prefix = 'menkul_user_';

	$cmb_user = new_cmb2_box( array(
		'id'               => $prefix . 'edit',
		'title'            => esc_html__( 'Kullanıcı Profil Metabox', 'menkul' ), 
		'object_types'     => array( 'user' ), 
		'show_names'       => true,
		'new_user_section' => 'add-new-user', 
	) );
   $cmb_user->add_field( array(
		'name' => esc_html__( 'Avatar', 'menkul' ),
		'desc' => esc_html__( 'Avatar Seç', 'menkul' ),
		'id'   => $prefix . 'avatar',
		'type' => 'file',
	) );

	$cmb_user->add_field( array(
		'name' => esc_html__( 'Cep Telefon Numarası', 'menkul' ),
		'desc' => esc_html__( 'Cep Telefon Numarası giriniz', 'menkul' ),
		'id'   => $prefix . 'danismanceptelefonnumarasi',
		'type' => 'text',
	) );
	$cmb_user->add_field( array(
		'name' => esc_html__( 'Sabit Telefon Numarası', 'menkul' ),
		'desc' => esc_html__( 'Sabit Telefon Numarası giriniz', 'menkul' ),
		'id'   => $prefix . 'danismansabittelefonnumarasi',
		'type' => 'text',
	) );
	
	$cmb_user->add_field( array(
		'name' => esc_html__( 'Facebook URL', 'menkul' ),
		'desc' => esc_html__( 'Facebook Link', 'menkul' ),
		'id'   => $prefix . 'facebookurl',
		'type' => 'text_url',
	) );

	$cmb_user->add_field( array(
		'name' => esc_html__( 'Twitter URL', 'menkul' ),
		'desc' => esc_html__( 'Twitter Link', 'menkul' ),
		'id'   => $prefix . 'twitterurl',
		'type' => 'text_url',
	) );

	$cmb_user->add_field( array(
		'name' => esc_html__( 'İnstagram URL', 'menkul' ),
		'desc' => esc_html__( 'İnstagram Link', 'menkul' ),
		'id'   => $prefix . 'instagramurl',
		'type' => 'text_url',
	) );
	
	$cmb_user->add_field( array(
		'name' => esc_html__( 'Linkedin URL', 'menkul' ),
		'desc' => esc_html__( 'Linkedin Link', 'menkul' ),
		'id'   => $prefix . 'linkedinurl',
		'type' => 'text_url',
	) );
	
  	

} ? >`

**Comment by tw2113** [comment]
Whatever frontend form processing you set up to save the submitted form data will need to save user meta to the id fields with `$prefix` changed out to `menkul_user_`

So like `menkul_user_facebookurl` would be the user meta key you specify.

**Comment by mehmetsarr** [comment]
Thanks
