### ISSUE TITLE
Hi, How can I show shortocode on cmb2 Like contact form 7 shortcoe? Can you please help?

### ISSUE THREAD

**Issue by sagork** [CMB2/CMB2#1363]
Hi, How can I show shortocode on cmb2 Like contact form 7 shortcoe? Can you please help?

**Comment by tw2113** [comment]
I know we have https://github.com/CMB2/CMB2/wiki/Bringing-Metaboxes-to-the-Front-end which is more about displaying the form itself, and not so much anything specific with just outputting the fields saved.

Regarding displaying form values, there's nothing necessarily special needing done as by default CMB2 saves as standard post meta in the wp_postmeta table. So any tutorial showing how to output custom fields/meta data with a shortcode would work, just a matter of determining the keys to use.

**Comment by sagork** [comment]
Still not understand how to show contact form 7 using this

> I know we have https://github.com/CMB2/CMB2/wiki/Bringing-Metaboxes-to-the-Front-end which is more about displaying the form itself, and not so much anything specific with just outputting the fields saved.
> 
> Regarding displaying form values, there's nothing necessarily special needing done as by default CMB2 saves as standard post meta in the wp_postmeta table. So any tutorial showing how to output custom fields/meta data with a shortcode would work, just a matter of determining the keys to use.

**Comment by tw2113** [comment]
Forgive me, are you asking how to integrate Contact Form 7 with CMB2 in some way? For example make their contact form a part of a metabox?

or just how to show CMB2 stuff in a similar way that Contact Form 7 does?
