### ISSUE TITLE
Adding classes to fields

### ISSUE THREAD

**Issue by gyrus** [CMB2/CMB2#1364]
I need to add a custom class to a field. The `classes` parameter adds classes to the row, not the field (input, textarea, etc.). And if I use `attributes` and set classes there, it overrides rather than appends to the default classes, which I don't want.

**Comment by jtsternberg** [comment]
You can modify the element attributes using the element-type specific filters:
```php
add_filter( 'cmb2_input_attributes', function( $args, $type_defaults, $field ) {
	if ( 'your_field_id' === $field->id() ) {
		$args['class'] .= ' your-class' ;
	}

	return $args;
}, 10, 3 );
```

Where `input` in the filter name corresponds to the element type.

**Comment by gyrus** [comment]
I noticed that filter but I wanted to be sure it applied to all possible fields. If that's the only route, I'll just line up a bunch of `add_filter()` calls for each element type. Thanks.
