### ISSUE TITLE
cmb2_metabox_form second parameter is a key or an integer?

### ISSUE THREAD

**Issue by Mte90** [CMB2/CMB2#1365]
## Describe the bug
I have this old snippet https://github.com/WPBP/WordPress-Plugin-Boilerplate-Powered/blob/master/plugin-name/backend/views/settings.php#L258 that use 2 parameter with 2 strings but PHPStan report that the second one is an integer of the Post ID (https://github.com/WPBP/WordPress-Plugin-Boilerplate-Powered/issues/162).

Looking on internet in old articles like https://bigwing.com/blog/create-wordpress-cpt-archive-content-with-cmb2/ the second parameter it was a string.

Looking at the code https://github.com/CMB2/CMB2/blob/e98c1e9e4bbeffb7ab578b149e52ec4b2fea8185/includes/helper-functions.php#L274 it is referring to a integer infact.

But if I configure a string as that parameter is used as key to save the settings.
So I don't know if I am doing it wrong or that parameter accept a string and also a integer.

**Comment by szepeviktor** [comment]
AFAIK `$object_id` is the post ID the metabox is tied to.

**Comment by Mte90** [comment]
Yes but if I set a string as that parameter it is used as option key in the db so there is some issue in the code.

**Comment by jtsternberg** [comment]
`$object_id` is an integer for posts, terms, users, comments, etc. For options, it's a string.

**Comment by szepeviktor** [comment]
😲

**Comment by Mte90** [comment]
So as is now maybe the phpdoc part need to be fixed to support both the type of parameters?

**Comment by Mte90** [comment]
Cool I see the commit with the fix I think that we can close it :-)

**Comment by szepeviktor** [comment]
Thank you.
