### ISSUE TITLE
Taxonomy Select Display Problem in Loop

### ISSUE THREAD

**Issue by mehmetsarr** [CMB2/CMB2#1366]
Hello, I created a category selection field in the backend as below. I couldn't show this in the loop. That's why when I select the category, it doesn't open as the category I chose on the slides. How can I do that?

I am using the admin panel code related to the subject [here](https://github.com/CMB2/CMB2/issues/1325#issuecomment-575704001).

back-end code:
             
            $args = array(
	    'id'           => 'cleanmax_tema_ayarlari_duzenle',
		'title'        => 'Tema Paneli',
		'id'           => 'cleanmax_tema_kategori_sec_ayarlari',
		'menu_title'   => 'Kategoriler',
		'object_types' => array( 'options-page' ),
		'option_key'   => 'cleanmax_tema_kategori_sec_ayarlari',
		'parent_slug'  => 'cleanmax_tema_ana_ayarlar',
		'tab_group'    => 'cleanmax_tema_ana_ayarlar',
		'tab_title'    => 'Kategoriler',
	);

	$cleanmax_kategori_sec_ayarlar = new_cmb2_box( $args );
	$cleanmax_kategori_sec_ayarlar ->add_field( array(
		'name'     => esc_html__( 'Manşet Kategorisi', 'cleanmax' ),
		'desc'     => esc_html__( 'Manşet Kategorisi Seçiniz', 'cleanmax' ),
		'id'       => 'cleanmax_manset_kategorisi',
		'type'     => 'taxonomy_select', 
		'taxonomy' => 'category', 
	) );
	`

front-end code:

```
<?php $the_query = new WP_Query( 'showposts=3&post_type=post&category=manset'); ?>
<?php if ( $the_query->have_posts() ) : ?>
    <?php while ( $the_query->have_posts() ) : $the_query->the_post(); ?>
         <?php  if ( has_post_thumbnail()) : ?>
              <li data-transition="curtain-2" data-slotamount="1" data-masterspeed="1000" data-thumb="<?php echo get_the_post_thumbnail_url();?>"  data-saveperformance="off"  data-title="<?php the_title(); ?>"> <img src="<?php echo get_the_post_thumbnail_url();?>"  alt=""  data-bgposition="center top" data-bgfit="cover" data-bgrepeat="no-repeat">
             <?php else: ?>
                                   <?php endif;?>
                <div class="tp-caption sfb sfb tp-resizeme"
                        data-x="center"
                        data-y="center"
                        data-hoffset="0"
                        data-voffset="-65"
                        data-speed="1500"
                        data-start="1000"
                        data-easing="easeInOutQuart"
                        data-splitin="none"
                        data-splitout="none"
                        data-elementdelay="0.01"
                        data-endelementdelay="0.3"
                        data-endspeed="1200"
                        data-endeasing="Power4.easeOut">
                  <h2 class="slider-title-3"><span><?php the_title(); ?></span></h2>
                </div>
               <div class="tp-caption sfb sfb tp-resizeme"
                        data-x="center"
                        data-y="center"
                        data-hoffset="0"
                        data-voffset="-15"
                        data-speed="1500"
                        data-start="1000"
                        data-easing="easeInOutQuart"
                        data-splitin="none"
                        data-splitout="none"
                        data-elementdelay="0.01"
                        data-endelementdelay="0.3"
                        data-endspeed="1200"
                        data-endeasing="Power4.easeOut">
                  <h2 class="slider-title-4"><?php echo get_post_meta(get_the_ID(), "firmaup_slaytlar_kisa_aciklama", true); ?></h2>
                </div>
                <div class="tp-caption sfb sfb tp-resizeme"
                        data-x="560"
                        data-y="320"
                        data-hoffset="0"
                        data-voffset="150"
                        data-speed="1500"
                        data-start="2000"
                        data-easing="easeOutExpo"
                        data-splitin="none"
                        data-splitout="none"
                        data-elementdelay="0.01"
                        data-endelementdelay="0.3"
                        data-endspeed="1200"
                        data-endeasing="Power4.easeIn"><a href="<?php the_permalink(); ?>" class="btn slider-btn-2">DETAYLAR</a></div>
              </li>
             <?php endwhile; ?>
    <?php wp_reset_postdata(); ?>
 
<?php else : ?>
    <p><?php _e( 'Üzgünüz, kriterlerinize uygun haber yok.' ); ?></p>
<?php endif; ?>`

**Comment by tw2113** [comment]
Any field types that start with `taxonomy` are meant to be used as replacements for the default taxonomy metaboxes and are used to set taxonomy terms on the posts. They don't save as post meta like other field types. As far as I know, those field types don't do anything in regards to option pages like you're using above.

That said, are you trying to offer a field type that is meant to allow choosing 1 to many terms? I'd check out https://github.com/CMB2/CMB2/wiki/Tips-&-Tricks#a-dropdown-for-taxonomy-terms-which-does-not-set-the-term-on-the-post

**Comment by mehmetsarr** [comment]
Thank you for your answer. 
I looked at your link but did not understand anything.
That's how I changed the cycle. But still the category post I selected does not come.

```<?php 
 $the_query = new WP_Query( $args ); 
 	 $mansetkategori = get_option('cleanmax_tema_kategori_sec_ayarlari');
	echo $mansetkategori['cleanmax_manset_kategorisi']; 
 
 if ( $the_query->have_posts() ) : 
   while ( $the_query->have_posts() ) : $the_query->the_post(); 
	 ?>`

**Comment by tw2113** [comment]
It's probably internally failing to save anything because the field is set to save terms to a post, when you're using it on an options page. You need to change your field to a general select input so that it saves as part of the options. The link I gave you is meant to show how to have a general select input, that just happens to be populated with information about taxonomy terms.

**Comment by mehmetsarr** [comment]
> Muhtemelen dahili olarak herhangi bir şey kaydetmekte başarısız oluyor çünkü alan, siz onu bir seçenekler sayfasında kullanırken, bir gönderiye terimler kaydedecek şekilde ayarlanmıştır. Alanınızı, seçeneklerin bir parçası olarak kaydedilmesi için genel bir seçim girişiyle değiştirmeniz gerekir. Size verdiğim bağlantı, genel bir seçme girişine nasıl sahip olunacağını göstermek içindir, bu sadece taksonomi terimleri hakkında bilgilerle doldurulur.

Do you have the opportunity to show it over the code I provided?

**Comment by tw2113** [comment]
The link I provided covers much of it already. What you're seeing there is a new function being defined and then used as the source of the select options. The callback is constructing an array that has the term ID as array keys and then the term name as the array value. Those then get used as the option/value pairs in the dropdown.

**Comment by mehmetsarr** [comment]
> Sağladığım bağlantı zaten çoğunu kapsıyor. Orada gördüğünüz şey, tanımlanmakta olan yeni bir işlevdir ve ardından seçilen seçeneklerin kaynağı olarak kullanılır. Geri çağrı, dizi anahtarları olarak ID terimini ve ardından dizi değeri olarak terim adını içeren bir dizi oluşturur. Bunlar daha sonra açılır menüdeki seçenek / değer çiftleri olarak kullanılır.


I did as you said. The category I selected in the loop on the front end still does not appear.

**Comment by mehmetsarr** [comment]
I used it like this in the loop, but it still doesn't work.

`` `  <?php 
$the_query = new WP_Query( $args ); 

cmb2_get_option( 'cleanmax_tema_kategori_sec_ayarlari', 'cleanmax_manset_kategorisi');
 
 if ( $the_query->have_posts() ) : 
   while ( $the_query->have_posts() ) : $the_query->the_post(); 
	 ?>`

**Comment by tw2113** [comment]
Until you change the "type" field in this part of your code, you're not going to be getting any results:

```
$cleanmax_kategori_sec_ayarlar ->add_field( array(
	'name'     => esc_html__( 'Manşet Kategorisi', 'cleanmax' ),
	'desc'     => esc_html__( 'Manşet Kategorisi Seçiniz', 'cleanmax' ),
	'id'       => 'cleanmax_manset_kategorisi',
	'type'     => 'taxonomy_select', 
	'taxonomy' => 'category', 
) );
```

You're not seeing results because it's not saving to the option because it's trying to treat your current select field like they are taxonomy terms. You need to switch to the standard basic select field type, https://github.com/CMB2/CMB2/wiki/Field-Types#select, and then with the link posted to you previously as an example, fill the options in question with the term information.

```
$cleanmax_kategori_sec_ayarlar ->add_field( array(
	'name'       => esc_html__( 'Manşet Kategorisi', 'cleanmax' ),
	'desc'       => esc_html__( 'Manşet Kategorisi Seçiniz', 'cleanmax' ),
	'id'         => 'cleanmax_manset_kategorisi',
	'type'       => 'select',
	'options_cb' => 'my_custom_select_field_values'
) );

function my_custom_select_field_values( $field ) {
	$terms = get_terms( 'category', $args );
	$term_options = array();
	if ( ! empty( $terms ) ) {
		foreach ( $terms as $term ) {
			$term_options[ $term->term_id ] = $term->name;
		}
	}
	return $term_options;
}
```

This should, if I didn't make any immediate mistakes, store the term ID as the `cleanmax_manset_kategorisi` option overall, and you could then do whatever you need with that ID value afterwards,

**Comment by mehmetsarr** [comment]
> Until you change the "type" field in this part of your code, you're not going to be getting any results:
> 
> ```
> $cleanmax_kategori_sec_ayarlar ->add_field( array(
> 	'name'     => esc_html__( 'Manşet Kategorisi', 'cleanmax' ),
> 	'desc'     => esc_html__( 'Manşet Kategorisi Seçiniz', 'cleanmax' ),
> 	'id'       => 'cleanmax_manset_kategorisi',
> 	'type'     => 'taxonomy_select', 
> 	'taxonomy' => 'category', 
> ) );
> ```
> 
> You're not seeing results because it's not saving to the option because it's trying to treat your current select field like they are taxonomy terms. You need to switch to the standard basic select field type, https://github.com/CMB2/CMB2/wiki/Field-Types#select, and then with the link posted to you previously as an example, fill the options in question with the term information.
> 
> ```
> $cleanmax_kategori_sec_ayarlar ->add_field( array(
> 	'name'       => esc_html__( 'Manşet Kategorisi', 'cleanmax' ),
> 	'desc'       => esc_html__( 'Manşet Kategorisi Seçiniz', 'cleanmax' ),
> 	'id'         => 'cleanmax_manset_kategorisi',
> 	'type'       => 'select',
> 	'options_cb' => 'my_custom_select_field_values'
> ) );
> 
> function my_custom_select_field_values( $field ) {
> 	$terms = get_terms( 'category', $args );
> 	$term_options = array();
> 	if ( ! empty( $terms ) ) {
> 		foreach ( $terms as $term ) {
> 			$term_options[ $term->term_id ] = $term->name;
> 		}
> 	}
> 	return $term_options;
> }
> ```
> 
> This should, if I didn't make any immediate mistakes, store the term ID as the `cleanmax_manset_kategorisi` option overall, and you could then do whatever you need with that ID value afterwards,

I did what she said but it didn't work.

**Comment by mehmetsarr** [comment]
We added the code in the backend. With which code we can make the slideshow according to the category we select in the loop on the front end.

**Comment by tw2113** [comment]
First question is if now when you fetch your options and echo out the `cleanmax_manset_kategorisi` option value, is it the category term ID that you're expecting? 

If yes, then you can use that to do whatever you need to do to fetch the content desired. Looking at this line from earlier:
`new WP_Query( 'showposts=3&post_type=post&category=manset');` you're actually using the category slug, not the ID so to make it easier, we may want to change this `$term_options[ $term->term_id ] = $term->name;` to `$term_options[ $term->slug ] = $term->name;` instead so that it's the slug that gets stored. Then you could just drop that saved option value into your WP_Query args.

**Comment by mehmetsarr** [comment]
> İlk soru, şimdi seçeneklerinizi getirip `cleanmax_manset_kategorisi`seçenek değerini yankıladığınızda, beklediğiniz kategori terimi kimliği mi?
> 
> Cevabınız evet ise, istediğiniz içeriği almak için yapmanız gereken her şeyi yapmak için bunu kullanabilirsiniz. Önceki bu hat baktığımızda:
> `new WP_Query( 'showposts=3&post_type=post&category=manset');`aslında o kadar kolaylaştırmak için değil, kimlik kategorisi slug kullanıyoruz, biz bunu değiştirmek isteyebilirsiniz `$term_options[ $term->term_id ] = $term->name;`için `$term_options[ $term->slug ] = $term->name;`yerine nedenle depolanır sümüklüböcek olduğunu. Daha sonra kaydedilen bu seçenek değerini WP_Query argümanlarınıza bırakabilirsiniz.

I do not want to use this code ('showposts=3&post_type=post&category=manset'). Instead, what code can I use the category we saved on the settings page by writing into the slider on the front end?

**Comment by tw2113** [comment]
That part I can't answer for you because I don't know where the content and images and whatnot that you're wanting to turn into a slider are stored at. All I know for sure is that you have an options page and now you hopefully also have a select field that's saving a desired category to use. I assume use to limit the slider content to a specific category.

**Comment by mehmetsarr** [comment]
> Merhaba, arka uçta aşağıdaki gibi bir kategori seçim alanı oluşturdum. Bunu döngüde gösteremedim. Bu yüzden kategoriyi seçtiğimde slaytlarda seçtiğim kategori olarak açılmıyor. Bunu nasıl yapabilirim?
> 
> [Burada](https://github.com/CMB2/CMB2/issues/1325#issuecomment-575704001) konu ile ilgili yönetici paneli kodunu kullanıyorum .
> 
> arka uç kodu:
> 
> ```
>         $args = array(
>     'id'           => 'cleanmax_tema_ayarlari_duzenle',
> 	'title'        => 'Tema Paneli',
> 	'id'           => 'cleanmax_tema_kategori_sec_ayarlari',
> 	'menu_title'   => 'Kategoriler',
> 	'object_types' => array( 'options-page' ),
> 	'option_key'   => 'cleanmax_tema_kategori_sec_ayarlari',
> 	'parent_slug'  => 'cleanmax_tema_ana_ayarlar',
> 	'tab_group'    => 'cleanmax_tema_ana_ayarlar',
> 	'tab_title'    => 'Kategoriler',
> );
> 
> $cleanmax_kategori_sec_ayarlar = new_cmb2_box( $args );
> $cleanmax_kategori_sec_ayarlar ->add_field( array(
> 	'name'     => esc_html__( 'Manşet Kategorisi', 'cleanmax' ),
> 	'desc'     => esc_html__( 'Manşet Kategorisi Seçiniz', 'cleanmax' ),
> 	'id'       => 'cleanmax_manset_kategorisi',
> 	'type'     => 'taxonomy_select', 
> 	'taxonomy' => 'category', 
> ) );
> `
> ```
> 
> ön uç kodu:
> 
> ```
> <?php $the_query = new WP_Query( 'showposts=3&post_type=post&category=manset'); ?>
> <?php if ( $the_query->have_posts() ) : ?>
>     <?php while ( $the_query->have_posts() ) : $the_query->the_post(); ?>
>          <?php  if ( has_post_thumbnail()) : ?>
>               <li data-transition="curtain-2" data-slotamount="1" data-masterspeed="1000" data-thumb="<?php echo get_the_post_thumbnail_url();?>"  data-saveperformance="off"  data-title="<?php the_title(); ?>"> <img src="<?php echo get_the_post_thumbnail_url();?>"  alt=""  data-bgposition="center top" data-bgfit="cover" data-bgrepeat="no-repeat">
>              <?php else: ?>
>                                    <?php endif;?>
>                 <div class="tp-caption sfb sfb tp-resizeme"
>                         data-x="center"
>                         data-y="center"
>                         data-hoffset="0"
>                         data-voffset="-65"
>                         data-speed="1500"
>                         data-start="1000"
>                         data-easing="easeInOutQuart"
>                         data-splitin="none"
>                         data-splitout="none"
>                         data-elementdelay="0.01"
>                         data-endelementdelay="0.3"
>                         data-endspeed="1200"
>                         data-endeasing="Power4.easeOut">
>                   <h2 class="slider-title-3"><span><?php the_title(); ?></span></h2>
>                 </div>
>                <div class="tp-caption sfb sfb tp-resizeme"
>                         data-x="center"
>                         data-y="center"
>                         data-hoffset="0"
>                         data-voffset="-15"
>                         data-speed="1500"
>                         data-start="1000"
>                         data-easing="easeInOutQuart"
>                         data-splitin="none"
>                         data-splitout="none"
>                         data-elementdelay="0.01"
>                         data-endelementdelay="0.3"
>                         data-endspeed="1200"
>                         data-endeasing="Power4.easeOut">
>                   <h2 class="slider-title-4"><?php echo get_post_meta(get_the_ID(), "firmaup_slaytlar_kisa_aciklama", true); ?></h2>
>                 </div>
>                 <div class="tp-caption sfb sfb tp-resizeme"
>                         data-x="560"
>                         data-y="320"
>                         data-hoffset="0"
>                         data-voffset="150"
>                         data-speed="1500"
>                         data-start="2000"
>                         data-easing="easeOutExpo"
>                         data-splitin="none"
>                         data-splitout="none"
>                         data-elementdelay="0.01"
>                         data-endelementdelay="0.3"
>                         data-endspeed="1200"
>                         data-endeasing="Power4.easeIn"><a href="<?php the_permalink(); ?>" class="btn slider-btn-2">DETAYLAR</a></div>
>               </li>
>              <?php endwhile; ?>
>     <?php wp_reset_postdata(); ?>
>  
> <?php else : ?>
>     <p><?php _e( 'Üzgünüz, kriterlerinize uygun haber yok.' ); ?></p>
> <?php endif; ?>`
> ```

I shared the slider content here.

**Comment by tw2113** [comment]
Yes, which is all based on a WP_Query which from what I can see is based on 3 posts from the "post"  post type, that should have the `manset` category. Since you're using an options page to set a category picker, I assume you want to pluck that choice from the saved options to drop in place for that `manset` category in the WP_Query args. Am I mistaken with that part?

You have the slider output ready, just need to fetch the content to populate it with, which you're doing. Are you needing help getting that saved option value to drop into the args list?

**Comment by mehmetsarr** [comment]
> Evet, bunların hepsi bir WP_Query'ye dayanıyor ve görebildiğim kadarıyla `manset`kategoriye sahip olması gereken "gönderi" yazı türünden 3 gönderiye dayanıyor . Bir kategori seçici ayarlamak için bir seçenekler sayfası kullandığınızdan, bu seçimi `manset`WP_Query argümanlarında o kategori için kaydedilmiş seçeneklerden çıkarmak istediğinizi varsayıyorum . O kısımla yanılıyor muyum?
> 
> Kaydırıcı çıktınız hazır, sadece içeriği doldurmak için getirmeniz gerekiyor, ki bunu yapıyorsunuz. Bağımsız değişkenler listesine düşmek için kaydedilmiş seçenek değerini almak için yardıma mı ihtiyacınız var?

Let the slider be published according to the category I choose in the settings. For example, I chose the 'manset' category, only articles with the 'manset' category should come.

**Comment by tw2113** [comment]
Then all that should be left here is fetching your saved value from this newly constructed dropdown and saved option, and passing that along to the WP_Query args string. Did you amend to have it save the slug or is it still saving the term ID?

**Comment by mehmetsarr** [comment]
> Sonra burada bırakılması gereken tek şey, kaydedilen değerinizi bu yeni oluşturulan açılır menüden ve kaydedilen seçenekten almak ve bunu WP_Query args dizesine aktarmaktır. Bilgi bilgisini kaydetmesi için değişiklik yaptınız mı yoksa hala ID terimini kaydediyor mu?

Normally ' $tab1 = get_option('menkul_tema_ana_ayarlar');
echo '<img src="' . $tab1['site_logo'] . '" alt="" />';' I'm using the code. How can we adapt this to the cycle?

**Comment by tw2113** [comment]
If everything is done and saved on your options page, you should be able to get your chosen category with something like this:

```
$options = get_option( 'cleanmax_tema_kategori_sec_ayarlari' );
echo $options['cleanmax_manset_kategorisi']; //chosen value from your dropdown.
```

**Comment by mehmetsarr** [comment]
> If everything is done and saved on your options page, you should be able to get your chosen category with something like this:
> 
> ```
> $options = get_option( 'cleanmax_tema_kategori_sec_ayarlari' );
> echo $options['cleanmax_manset_kategorisi']; //chosen value from your dropdown.
> ```


I tried but it didn't happen again.

**Comment by mehmetsarr** [comment]
> If everything is done and saved on your options page, you should be able to get your chosen category with something like this:
> 
> ```
> $options = get_option( 'cleanmax_tema_kategori_sec_ayarlari' );
> echo $options['cleanmax_manset_kategorisi']; //chosen value from your dropdown.
> ```

It pulls the ID of the category I selected. But the ID is on the slider. Like 19. In other words, slider articles do not appear according to the category I choose.

**Comment by tw2113** [comment]
See the latter part of my comment here https://github.com/CMB2/CMB2/issues/1366#issuecomment-672872355 . I mention the idea of changing that dropdown from using the term ID as the value like the original example used, to the term slug instead.

**Comment by tw2113** [comment]
I'm closing this as an issue for CMB2, but I can still reply a bit while you work through getting this working. It's more a support task than bug to fix in some way.

**Comment by mehmetsarr** [comment]
> I'm closing this as an issue for CMB2, but I can still reply a bit while you work through getting this working. It's more a support task than bug to fix in some way.

Sorry you closed it. My problem was with the cycle.
I put a code in the loop like this. to call the slides in the category I want, but it didn't work. Could you help?


```<?php
 $options = get_option('cleanmax_tema_kategori_sec_ayarlari');
	echo $options['cleanmax_manset_kategorisi']; 
	
 query_posts( array(
    'category_name'  => $options,
    'posts_per_page' => -1
) );

?>```

**Comment by tw2113** [comment]
Change `'category_name'  => $options,` to `'category_name'  => $options['cleanmax_manset_kategorisi'],`. You're not trying to use ALL of your options, just one of them. My echo line was just to help you visualize and see what values are being saved so that you can use them where you need to, and as appropriate.

**Comment by mehmetsarr** [comment]
> Değişim `'category_name' => $options,`için `'category_name' => $options['cleanmax_manset_kategorisi'],`. Seçeneklerinizin TÜMÜNÜ kullanmaya çalışmıyorsunuz, sadece birini. Yankı hattım sadece hangi değerlerin kaydedildiğini görselleştirmenize ve görmenize yardımcı olmak içindi, böylece bunları ihtiyacınız olan yerde ve uygun şekilde kullanabilirsiniz.

I tried again, it didn't work. Anyway, thank you for your answers.

**Comment by tw2113** [comment]
Check and confirm what you're getting out of your options and variables. Once you know for sure what is getting returned, you can act and use appropriately.

**Comment by mehmetsarr** [comment]
I finally found the solution. as follows,
```
$options = get_option( 'cleanmax_tema_kategori_sec_ayarlari' );
$the_query = new WP_Query( array( 'cat' => $options )  );
```

**Comment by tw2113** [comment]
Awesome to hear, let us know if you need anything else.
