### ISSUE TITLE
CMB2 Custom Field Type - Subject issue

### ISSUE THREAD

**Issue by interlearned** [CMB2/CMB2#1369]
This plugin allowed me to create custom fields in a Job Manager database and those custom field have since disappeared. I am not a coder. Can someone help me with this? The data is not exporting either. 

## CMB2 Field Registration Code:

```php
add_action( 'cmb2_admin_init', 'yourprefix_register_demo_metabox' );
function yourprefix_register_demo_metabox() {

	$cmb = new_cmb2_box( array(
		// Box Config...
	) );

	$cmb->add_field( array(
		// Field Config...
	) );

	// Additional fields...
}
```

## Your Environment

Browser name and version:
Operating System and version (desktop or mobile):

**Comment by tw2113** [comment]
What aspects of the install have changed since it last worked for you? For example did you upgrade to WordPress 5.5? Did you install some other plugin or two for other things, and now this isn't working?

It also sounds like you're using CMB2 to collect and save information to a custom location, as compared to the various meta tables or the options table?

**Comment by interlearned** [comment]
Hello Michael –

I have copied Tonia Meyer, one of my team members who has much more expertise on the web development side than I do to be involved in the discussion.

That said, here is a response to your questions (Tonia, jump in if I fail to cover anything).


  *   We have not upgraded to WordPress 5.5.  We are currently on 4.9.15.
  *   We have not installed any other plugins since the site was originally designed.
  *   Originally, there were a number of checkboxes that were used to collect data from the user.  Specifically, our site is a faculty recruiting site.  I believe the designer used the CMB2 plugin to collect data using checkboxes regarding their lifestyle habits.
  *   It seems like there are several items missing when we view the resumes in the backend on WordPress.  When we do an export of the resumes, the data seems to still be there (though it doesn’t show up in their individual profile).  More importantly, the specific information from those checkboxes that is vital, does not show up in that resume export (it never has) but without it showing up on the individual profile, we have no way of accessing it.

Frankly the site is basically deprecated but we still need to access the data and transfer it over to our CRM.

I hope that helps.

Kind Regards,

     Joshua T. Fischer, Ph.D.
     President & CEO
     InterLearn
     (918) 895-1185
     (918) 517-3002 (fax)
      [facebook-small] <https://www.facebook.com/InterLearnEd>   [twitter-small] <https://twitter.com/InterLearnEd>   [linkedin-small] <https://www.linkedin.com/company/interlearned>
[cid:image004.png@01D67614.45BBB000]<https://calendly.com/interlearn>

**Comment by tw2113** [comment]
So it sounds like, essentially, nothing at all changed, but at the same time things suddenly stopped working. Not a huge amount to go off of from my side, and it still sounds like a very custom implementation of things overall.

**Comment by interlearned** [comment]
That is correct about nothing really changing.


Kind Regards,

     Joshua T. Fischer, Ph.D.
     President & CEO
     InterLearn
     (918) 895-1185
     (918) 517-3002 (fax)
      [facebook-small] <https://www.facebook.com/InterLearnEd>   [twitter-small] <https://twitter.com/InterLearnEd>   [linkedin-small] <https://www.linkedin.com/company/interlearned>
[cid:image004.png@01D67638.90369270]<https://calendly.com/interlearn>

**Comment by tw2113** [comment]
Something somewhere in the overall system had to change because code isn't just going to stop working like that. I don't have any way to provide any sort of leads for this, outside of maybe there's some errors occurring behind the scenes that's preventing things from saving properly?

**Comment by interlearned** [comment]
Michael –

I can appreciate what you’re saying.  It doesn’t make sense to us either.  The site is just about to be deprecated and we’ve not been doing any upgrades or changes to it.

At any rate, I did go into the WP Admin section and download the XML file of all the resume data.  Then I did a search for the specific term I was looking for on the site.  I seem to find the data in the file and am jut working to get it pulled out of there.  However, I could use some help to find what this data means since it was a check box.  Perhaps you could tell me what this means?  In particular, I’m trying to find out whether the box was checked in front of the “I have a personal relationship with Jesus Christ.” item as highlighted below.  Are you able to tell us on this example if the box is checked or not?  Or how the coding works to show checked or unchecked in this data?

<wp:postmeta>
            <wp:meta_key><![CDATA[_ems_history]]></wp:meta_key>
            <wp:meta_value><![CDATA[a:5:{i:0;s:49:"I have a personal relationship with Jesus Christ.";i:1;s:57:"I have not been convicted of or plead guilty to a felony.";i:2;s:21:"I do not use alcohol.";i:3;s:21:"I do not use tobacco.";i:4;s:25:"I have not been divorced.";}]]></wp:meta_value>
</wp:postmeta>


Kind Regards,

     Joshua T. Fischer, Ph.D.
     President & CEO
     InterLearn
     (918) 895-1185
     (918) 517-3002 (fax)
      [facebook-small] <https://www.facebook.com/InterLearnEd>   [twitter-small] <https://twitter.com/InterLearnEd>   [linkedin-small] <https://www.linkedin.com/company/interlearned>
[cid:image004.png@01D67BBD.85010400]<https://calendly.com/interlearn>

**Comment by tw2113** [comment]
I won't be able to say how many options are available, but based on that 1 post meta entry, someone checked and saved these 5 options as part of the post. If there's more options than that, then those not shown were NOT checked. If these are all of the options, then all of them were checked.

"I have a personal relationship with Jesus Christ."
"I have not been convicted of or plead guilty to a felony."
"I do not use alcohol."
"I do not use tobacco."
"I have not been divorced."

**Comment by interlearned** [comment]
Michael –

Thanks for the quick response.  I wondered if that was what was going on.  Thanks for the confirmation!


Kind Regards,

     Joshua T. Fischer, Ph.D.
     President & CEO
     InterLearn
     (918) 895-1185
     (918) 517-3002 (fax)
      [facebook-small] <https://www.facebook.com/InterLearnEd>   [twitter-small] <https://twitter.com/InterLearnEd>   [linkedin-small] <https://www.linkedin.com/company/interlearned>
[cid:image004.png@01D67BC3.B15FC0D0]<https://calendly.com/interlearn>
