### ISSUE TITLE
Agregar un campo de grupo dentro de otro campo de grupo

### ISSUE THREAD

**Issue by Homer1020** [CMB2/CMB2#1375]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tw2113** [comment]
English translation: "Add a group field within another group field".

Regarding nested things, I know we don't have the best support as it's always getting pretty complex at that level.

**Comment by tw2113** [comment]
Closing as very similar to other tickets
