### ISSUE TITLE
Taxonomy Metabox Problem

### ISSUE THREAD

**Issue by mehmetsarr** [CMB2/CMB2#1378]
Hi, my backend code.

```
// Satıcı Ekleme Alanı
function urunler_satici_custom_taxonomy() {

	$labels = array(
		'name'                       => _x( 'Satıcılar', 'Taxonomy Genel Adı', 'piwoox' ),
		'singular_name'              => _x( 'Satıcı', 'Taxonomy Tekil Adı', 'piwoox' ),
		'menu_name'                  => __( 'Satıcılar', 'piwoox' ),
		'all_items'                  => __( 'Tüm Satıcı', 'piwoox' ),
		'parent_item'                => __( 'Ana Satıcı', 'piwoox' ),
		'parent_item_colon'          => __( 'Ana Satıcı:', 'piwoox' ),
		'new_item_name'              => __( 'Yeni Satıcı Adı', 'piwoox' ),
		'add_new_item'               => __( 'Yeni Satıcı Ekle', 'piwoox' ),
		'edit_item'                  => __( 'Satıcı Düzenle', 'piwoox' ),
		'update_item'                => __( 'Satıcı Güncelle', 'piwoox' ),
		'view_item'                  => __( 'Satıcı Gör', 'piwoox' ),
		'separate_items_with_commas' => __( 'Virgül ile ayrı Satıcı', 'piwoox' ),
		'add_or_remove_items'        => __( 'Satıcı ekle veya kaldır', 'piwoox' ),
		'choose_from_most_used'      => __( 'En çok kullanılanlardan birini seçin', 'piwoox' ),
		'popular_items'              => __( 'Popüler Satıcı', 'piwoox' ),
		'search_items'               => __( 'Satıcı Ara', 'piwoox' ),
		'not_found'                  => __( 'Bulunamadı', 'piwoox' ),
		'no_terms'                   => __( 'Satıcı Yok', 'piwoox' ),
		'items_list'                 => __( 'Satıcı Listesi', 'piwoox' ),
		'items_list_navigation'      => __( 'Satıcı Listesi Gezinme', 'piwoox' ),
	);
	$args = array(
		'labels'                     => $labels,
		'hierarchical'               => true,
		'public'                     => true,
		'show_ui'                    => true,
		'show_admin_column'          => true,
		'show_in_nav_menus'          => true,
		'show_tagcloud'              => true,
	);
	register_taxonomy( 'urunlersatici', array( 'piwooxurunler' ), $args );

}
add_action( 'init', 'urunler_satici_custom_taxonomy', 0 );
```

```
// Satıcı Metabox
add_action( 'cmb2_admin_init', 'satici_prefix_register_taxonomy_metabox' );

function satici_prefix_register_taxonomy_metabox() {
	$prefix = 'satici_prefix_';
	
	$cmb_term = new_cmb2_box( array(
		'id'               => $prefix . 'edit',
		'title'            => esc_html__( 'Satıcı', 'piwoox' ), 
		'object_types'     => array( 'term' ), 
		'taxonomies'       => array( 'urunlersatici' ), 
		
	) );


	$cmb_term->add_field( array(
		'name' => esc_html__( 'Satıcı Resmi', 'piwoox' ),
		'desc' => esc_html__( 'Satıcı Resmi Yükleyiniz.', 'piwoox' ),
		'id'   => $prefix . 'satici_avatar',
		'type' => 'file',
		'default' => get_template_directory_uri() . '/image/satici.jpg',
	
	) );
	$cmb_term->add_field( array(
		'name' => esc_html__( 'Facebook Adresi', 'piwoox' ),
		'desc' => esc_html__( 'Facebook Adresi Giriniz.', 'piwoox' ),
		'id'   => $prefix . 'facebook_url',
		'type' => 'text',
		'default' => 'mehmetsarr',
	) );
   $cmb_term->add_field( array(
		'name' => esc_html__( 'Telegram Adresi', 'piwoox' ),
		'desc' => esc_html__( 'Telegram Adresi Giriniz.', 'piwoox' ),
		'id'   => $prefix . 'telegram_url',
		'type' => 'text',
		'default' => 'mehmetsarr',
	) );

}
// Satıcı Metabox
```

my frontend code:

```
 <?php 
 if (have_posts()) :
  while (have_posts()):
   the_post(); 
           ?>
                <div class="col-lg-7 rtl-text">
                    <div class="product-right">
                        <h2><?php the_title(); ?></h2>
                        <h3><?php esc_html_e( 'FİYAT:', 'piwoo' ); ?> <?php echo get_post_meta(get_the_ID(), "piwoox_urun_fiyati", true); ?> <?php esc_html_e( 'TL', 'piwoo' ); ?></h3>
                        
                        <div class="product-description border-product">
                        </div>
                        <div class="product-buttons"><a href="http://m.me/<?php $term= get_term_meta( $term_id, 'satici_prefix_facebook_url', true ); ?>" class="btn btn-normal"><?php esc_html_e( 'MESSENGER', 'piwoo' ); ?></a> <a href="https://t.me/<?php $term = get_term_meta( $term_id, 'satici_prefix_telegram_url', true ); ?>" class="btn btn-normal"><?php esc_html_e( 'TELEGRAM', 'piwoo' ); ?></a></div>
                        <div class="border-product">
                            <h6 class="product-title"><?php esc_html_e( 'Ürün Detayı', 'piwoo' ); ?></h6>
                            <p><?php the_content(); ?></p>
                        </div>
                    </div>
                </div>
				<?php endwhile; endif; wp_reset_query(); ?>
```

I just can't get the taxonomy metadata to the front end. Please help.

**Comment by tw2113** [comment]
You don't have `$term_id` being defined anywhere that I can see, so it's probably `null`. You're going to need to get the associated terms for the given post, and iterate over them to access the term ID that you could then fetch meta for.

**Comment by mehmetsarr** [comment]
> You don't have `$term_id` being defined anywhere that I can see, so it's probably `null`. You're going to need to get the associated terms for the given post, and iterate over them to access the term ID that you could then fetch meta for.

Demo kod?

**Comment by tw2113** [comment]
Something like https://developer.wordpress.org/reference/functions/get_the_terms/ should help get you the current terms that you can iterate over.

**Comment by mehmetsarr** [comment]
> Something like https://developer.wordpress.org/reference/functions/get_the_terms/ should help get you the current terms that you can iterate over.

None of the code I tried works. How can we do?

**Comment by tw2113** [comment]
because i'm still awake...:D

What code have you tried? Do you still have it in your code that you can share?

The too long didn't read is that you need the IDs for the term(s), there are going to be various ways to do that, just a matter of finding one that's working for you.

I'm also re-looking and it doesn't look like you're echo'ing the term meta in your code from earlier, in case you didn't try that with your new code attempts.

**Comment by mehmetsarr** [comment]
I've tried a lot of codes. This is the last time I tried.

``` 
get_the_terms( $post->ID, 'satici_prefix_facebook_url' true); 

```

**Comment by mehmetsarr** [comment]
> çünkü hala uyanığım ...: D
> 
> Hangi kodu denedin? Hala paylaşabileceğiniz kodunuz var mı?
> 
> Çok uzun zamandır okunmamış olan, terim (ler) için kimliklere ihtiyacınız olması, bunu yapmanın çeşitli yolları olacak, sadece sizin için çalışan birini bulma meselesi.
> 
> Ayrıca yeniden bakıyorum ve yeni kod denemelerinizle denememiş olmanız durumunda, daha önce kodunuzda meta terimini tekrarlıyor gibi görünmüyorsunuz.

I've tried a lot of codes. This is the last time I tried.

``` 
get_the_terms( $post->ID, 'satici_prefix_facebook_url' true); 

```

**Comment by tw2113** [comment]
You're mixing your functions, instead of using them in conjunction.

Get your terms on your post:
```
$terms = get_the_terms( $post->ID, 'urunlersatici' );
```

Iterate over the terms, and use the term ID to fetch your term meta
```
$terms = get_the_terms( $post->ID, 'urunlersatici' );
if ( $terms && ! is_wp_error( $terms ) ) : 
	foreach ( $terms as $term ) {
		echo '<div class="product-buttons">';
		echo '<a href="http://m.me/' . get_term_meta( $term->term_id, "satici_prefix_facebook_url", true ) . '" class="btn btn-normal">';
		esc_html_e( "MESSENGER", "piwoo" );
		echo '</a>';
		echo '<a href="https://t.me/' . get_term_meta( $term->term_id, 'satici_prefix_telegram_url', true ) . '" class="btn btn-normal">';
		esc_html_e( "TELEGRAM", "piwoo" );
		echo '</a></div>';
	}
}
```
Adapt as you need.

**Comment by mehmetsarr** [comment]
> foreach ( $terms as $term )

@tw2113 
It gives a warning: A critical error has occurred on your website.

**Comment by tw2113** [comment]
Awesome, progress...get the actual error, not that one has simply occurred, and we can make even more progress.

**Comment by mehmetsarr** [comment]
> Harika, ilerleme ... Asıl hatayı anla, sadece oluştuğunu değil ve daha da fazla ilerleme kaydedebiliriz.

@tw2113 
Thank you very much for your help. I changed the code like this, it worked, but it pulls all meta values. I want him to take one.

```

		$terms = get_terms( 'urunlersatici' );
if ( ! empty( $terms ) && ! is_wp_error( $terms ) ){
    echo '<ul>';
    foreach ( $terms as $term ) {
		echo '<div class="product-buttons">';
		echo '<a href="http://m.me/' . get_term_meta( $term->term_id, "satici_prefix_facebook_url", true ) . '" class="btn btn-normal">';
		esc_html_e( "MESSENGER", "piwoo" );
		echo '</a>';
		echo '<a href="https://t.me/' . get_term_meta( $term->term_id, 'satici_prefix_telegram_url', true ) . '" class="btn btn-normal">';
		esc_html_e( "TELEGRAM", "piwoo" );
		echo '</a></div>';
	}
	}
```

**Comment by mehmetsarr** [comment]
@tw2113 
The main error of the code you provided is:

[09-Oct-2020 04:06:33 UTC] require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/themes/piwoo/single-piwooxurunler.php'), get_terms, WP_Term_Query->query, WP_Term_Query->get_terms tarafından oluşturulan SELECT   FROM wp_terms AS t  INNER JOIN wp_term_taxonomy AS tt ON t.term_id = tt.term_id WHERE tt.taxonomy IN ('urunlersatici') ORDER BY t.name ASC  sorgusu için WordPress veritabanı hatası You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'FROM wp_terms AS t  INNER JOIN wp_term_taxonomy AS tt ON t.term_id = tt.term_...' at line 1

**Comment by mehmetsarr** [comment]
> Awesome, progress...get the actual error, not that one has simply occurred, and we can make even more progress.

@tw2113 

I edited this part of the code you provided, it has been fixed. Thank you very much again :)

```
if ( $terms && ! is_wp_error( $terms ) ){
```

**Comment by tw2113** [comment]
Awesome. Have a good rest of your day :D
