### ISSUE TITLE
metabox fields datas arent being saved

### ISSUE THREAD

**Issue by paponahamed** [CMB2/CMB2#1379]
Hi i have issues on saving the data. The metabox fields are perfectly appearing on the post type but when i update the post the datas on the fields vanishes..

**Comment by tw2113** [comment]
Can you provide your CMB2 configuration code so that we can review/test it out?

**Comment by paponahamed** [comment]
Thanks for getting back to me..i solved it my self..

**Comment by tw2113** [comment]
Awesome to hear. Have a good rest of your day.
