### ISSUE TITLE
add_submenu_page position / order not working

### ISSUE THREAD

**Issue by satindersinghsidhu** [CMB2/CMB2#1380]
There is no option to set position or order a submenu item inside an already exist main menu item.

Currently It is possible via small adjustments:-

1. Add **$this->cmb->prop( 'position' )** inside **add_submenu_page()** inside **CMB2\includes\CMB2_Options_Hookup.php**
2. Also add an extra property - **priority** that we can use inside menu add_action hook. **add_action( $hook, array( $this, 'options_page_menu_hooks' ), $this->cmb->prop( 'priority' ) );**

Hope next version will add some adjustments to order a submenu.

**Comment by tw2113** [comment]
Looks like a good potential new enhancement, thanks for pointing this out.

For those maybe not familiar, the position argument looks like it was added in WordPress 5.3

**Comment by satindersinghsidhu** [comment]
Can I do this without changing inside CMB2 folder inside my plugin now?

It works by changing inside CMB2 but in that way other plugin that also includes CMB2 can again over-ride this.

**Comment by tw2113** [comment]
Unsure how easy it'd be to extend this part of CMB2 to use your own version instead of the version in CMB2 itself for all the appropriate arguments etc.

I do know that CMB2 has some pretty smart loading going on where the latest version will get loaded first and any other version found in the website doesn't get used.

Beyond that, the only way I can think of would be just modifying or forking your own version to use for the time being, until someone decides to actively work on it and get it into the develop branch and/or release.

**Comment by james0r** [comment]
I'm not sure how close of a request this is to what you're asking but I'm trying to make the first submenu item of the options-page a different name than it's parent item.

<img width="456" alt="Screen Shot 2020-12-02 at 7 28 44 PM" src="https://user-images.githubusercontent.com/34731936/100944234-36fa8c00-34d5-11eb-9836-40e47a819301.png">

See the standard Wordpress settings menu item and its children for an example.

**Comment by alfonmaco** [comment]
Hello james0r, to change the name of the submenu itme, you must change the third parameter of the add_submenu_page() function.
  add_menu_page(										
				'Practice Info',				//'page_title'
				'Practice Info',				//'menu_title'
				'manage_options', 			//'capability'
				'practice-info', 				//'menu-slug'
				'practice_info',				//'function'
				 '',						//'icono'											
										//'position'
			);
			add_submenu_page(
				'practice-info',				//'parent_slug'
				'Practice info config',			//'page_title'
				'submenu name',			//'menu_title'
				'manage_options', 			//'capability'
				'practice-config-page', 		//'menu-slug'
				'practice_config_function',		//'function'
										//'position'
			);

**Comment by james0r** [comment]
That's only if I was directly using the Wordpress function correct? 

What about when creating theme options with CMB2? It seems to automatically create this first submenu item and I don't see where I have control over its naming. Maybe there's some perfect combination of arguments I'm supposed two pass in my metabox array but I havn't found it yet. 

`$args = [
    'id'              => 'cmb2_id_box_theme_options',
    'object_types'    => ['options-page'],
    'option_key'      => 'cmb_main_options',
    'menu_title'      => __('Keepers', 'keepers'),
    'position'        => 2,
    'capability'      => 'manage_options', // Cap required to view options-page.
];

$cmb2_options_clinic_info = new_cmb2_box($args);`

that's how I create my metabox for the parent item.

Same thing occurs with this snippet from the snippet library -> https://github.com/CMB2/CMB2-Snippet-Library/blob/master/options-and-settings-pages/theme-options-cmb.php

**Comment by tw2113** [comment]
Does remind me and make me re-realize that this is something we'd need to get support added for to CMB2 still, as it's not at the moment.

Anyone wanting to submit pull requests would be most welcome as well.

**Comment by alfonmaco** [comment]
tray this, you must set capability of menu to 'unknown', and add submenus, when you press on the menu tag is the same as press the first submenu.

$args = [
    'id'              => 'cmb2_id_box_theme_options',
    'object_types'    => ['options-page'],
    'option_key'      => 'cmb_main_options',
    'menu_title'      => __('Keepers', 'keepers'),
    'position'        => 2,
    'capability'      => 'unknown' //'manage_options', // Cap required to view options-page.
];

$cmb2_options_clinic_info = new_cmb2_box($args);
$args = [
    'id'              => 'cmb2_id_box_theme_options_1',
    'object_types'    => ['options-page'],
    'option_key'      => 'cmb_main_options1',
    'menu_title'      => __('Keepers1', 'keepers1'),
    'title'						=> __('Keepers1', 'keepers1'),
    'parent_slug'     => 'cmb_main_options',
    'position'        => 2,
    'capability'      => 'manage_options', // Cap required to view options-page.
];

$cmb2_options_clinic_info = new_cmb2_box($args);
$args = [
    'id'              => 'cmb2_id_box_theme_options_2',
    'object_types'    => ['options-page'],
    'option_key'      => 'cmb_main_options2',
    'menu_title'      => __('Keepers2', 'keepers2'),
    'title'						=> __('Keepers2', 'keepers2'),
    'parent_slug'     => 'cmb_main_options',
    'position'        => 2,
    'capability'      => 'manage_options', // Cap required to view options-page.
];

$cmb2_options_clinic_info = new_cmb2_box($args);

**Comment by alfonmaco** [comment]
![keepers](https://user-images.githubusercontent.com/75403752/101100236-705ef480-35c6-11eb-8108-9ac90899af3d.png)

as you can see, the position set work fine, the problem is if i set a position bigger than the actual number of submenus wordpress append this submenu at last position  not in the position number we set. , for example first submenu position=1, second submenu position=6, and third submenu position=5, then wordpress assign position=1 to submenu 1 position=2 to submenu2 and position=3 to submenu3 .

if you want assign an exact position, the approach maybe can be the follow: you create an array and insert all the submenus in the position you want it, and when all them is ready, the i can run the new_cmb2_box() inside a foreach loop.

$args = [
    'id'              => 'cmb2_id_box_theme_options',
    'object_types'    => ['options-page'],
    'option_key'      => 'cmb_main_options',
    'menu_title'      => __('Keepers', 'keepers'),
    'position'        => 0,
    'capability'      => 'unknown' //'manage_options', // Cap required to view options-page.
];

$cmb2_options_clinic_info = new_cmb2_box($args);
$args = [
    'id'              => 'cmb2_id_box_theme_options_1',
    'object_types'    => ['options-page'],
    'option_key'      => 'cmb_main_options1',
    'menu_title'      => __('Keepers1', 'keepers1'),
    'title'						=> __('Keepers1', 'keepers1'),
    'parent_slug'     => 'cmb_main_options',
    'position'        => 2,
    'capability'      => 'manage_options', // Cap required to view options-page.
];

$cmb2_options_clinic_info = new_cmb2_box($args);
$args = [
    'id'              => 'cmb2_id_box_theme_options_2',
    'object_types'    => ['options-page'],
    'option_key'      => 'cmb_main_options2',
    'menu_title'      => __('Keepers2', 'keepers2'),
    'title'						=> __('Keepers2', 'keepers2'),
    'parent_slug'     => 'cmb_main_options',
    'position'        => 3,
    'capability'      => 'manage_options', // Cap required to view options-page.
];

$cmb2_options_clinic_info = new_cmb2_box($args);
$args = [
    'id'              => 'cmb2_id_box_theme_options_3',
    'object_types'    => ['options-page'],
    'option_key'      => 'cmb_main_options3',
    'menu_title'      => __('Keepers3', 'keepers3'),
    'title'						=> __('Keepers3', 'keepers3'),
    'parent_slug'     => 'cmb_main_options',
    'position'        => 1,
    'capability'      => 'manage_options', // Cap required to view options-page.
];

$cmb2_options_clinic_info = new_cmb2_box($args);


$args = [
    'id'              => 'cmb2_id_box_theme_options',
    'object_types'    => ['options-page'],
    'option_key'      => 'cmb_main_options',
    'menu_title'      => __('Keepers', 'keepers'),
    'position'        => 0,
    'capability'      => 'unknown' //'manage_options', // Cap required to view options-page.
];

$cmb2_options_clinic_info = new_cmb2_box($args);
$args = [
    'id'              => 'cmb2_id_box_theme_options_1',
    'object_types'    => ['options-page'],
    'option_key'      => 'cmb_main_options1',
    'menu_title'      => __('Keepers1', 'keepers1'),
    'title'						=> __('Keepers1', 'keepers1'),
    'parent_slug'     => 'cmb_main_options',
    'position'        => 2,
    'capability'      => 'manage_options', // Cap required to view options-page.
];

$cmb2_options_clinic_info = new_cmb2_box($args);
$args = [
    'id'              => 'cmb2_id_box_theme_options_2',
    'object_types'    => ['options-page'],
    'option_key'      => 'cmb_main_options2',
    'menu_title'      => __('Keepers2', 'keepers2'),
    'title'						=> __('Keepers2', 'keepers2'),
    'parent_slug'     => 'cmb_main_options',
    'position'        => 3,
    'capability'      => 'manage_options', // Cap required to view options-page.
];

$cmb2_options_clinic_info = new_cmb2_box($args);
$args = [
    'id'              => 'cmb2_id_box_theme_options_3',
    'object_types'    => ['options-page'],
    'option_key'      => 'cmb_main_options3',
    'menu_title'      => __('Keepers3', 'keepers3'),
    'title'						=> __('Keepers3', 'keepers3'),
    'parent_slug'     => 'cmb_main_options',
    'position'        => 1,
    'capability'      => 'manage_options', // Cap required to view options-page.
];

$cmb2_options_clinic_info = new_cmb2_box($args);

**Comment by alfonmaco** [comment]
Here you can see an operative sorted menu by position.
```
	$args =array();
$args[] = [
    'id'              => 'cmb2_id_box_theme_options',
    'object_types'    => ['options-page'],
    'option_key'      => 'cmb_main_options',
    'menu_title'      => __('Keepers', 'keepers'),
    'position'        => 0,
    'capability'      => 'unknown' //'manage_options', // Cap required to view options-page.
];

$args[] = [
    'id'              => 'cmb2_id_box_theme_options_1',
    'object_types'    => ['options-page'],
    'option_key'      => 'cmb_main_options1',
    'menu_title'      => __('Keepers1', 'keepers1'),
    'title'	      => __('Keepers1', 'keepers1'),
    'parent_slug'     => 'cmb_main_options',
    'position'        => 2,
    'capability'      => 'manage_options', // Cap required to view options-page.
];

$args[] = [
    'id'              => 'cmb2_id_box_theme_options_2',
    'object_types'    => ['options-page'],
    'option_key'      => 'cmb_main_options2',
    'menu_title'      => __('Keepers2', 'keepers2'),
    'title'	      => __('Keepers2', 'keepers2'),
    'parent_slug'     => 'cmb_main_options',
    'position'        => 3,
    'capability'      => 'manage_options', // Cap required to view options-page.
];

$args[] = [
    'id'              => 'cmb2_id_box_theme_options_3',
    'object_types'    => ['options-page'],
    'option_key'      => 'cmb_main_options3',
    'menu_title'      => __('Keepers3', 'keepers3'),
    'title'	      => __('Keepers3', 'keepers3'),
    'parent_slug'     => 'cmb_main_options',
    'position'        => 1,
    'capability'      => 'manage_options', // Cap required to view options-page.
];

$sortArray = array();

foreach($args as $arg){
    foreach($arg as $key=>$value){
        if(!isset($sortArray[$key])){
            $sortArray[$key] = array();
        }
        $sortArray[$key][] = $value;
    }
}
array_multisort($sortArray["position"],SORT_ASC,$args);

foreach ($args as $arg){
$cmb2_options_clinic_info = new_cmb2_box($arg);
}

```

**Comment by alfonmaco** [comment]
For the solution maybe if you change this function the order work fine. I dont know, how can i propose the change, because i do not know enought about github.

`.

	public function hooks() {
		if ( empty( $this->option_key ) ) {
			return;
		}

		if ( ! $this->cmb->prop( 'autoload', true ) ) {
			// Disable option autoload if requested.
			add_filter( "cmb2_should_autoload_{$this->option_key}", '__return_false' );
		}

		/**
		 * For WP < 4.7. Ensure the register_setting function exists.
		 */
		if ( ! CMB2_Utils::wp_at_least( '4.7' ) && ! function_exists( 'register_setting' ) ) {
			require_once ABSPATH . 'wp-admin/includes/plugin.php';
		}

		// Register setting to cmb2 group.
		register_setting( 'cmb2', $this->option_key );

		// Handle saving the data.
		add_action( 'admin_post_' . $this->option_key, array( $this, 'save_options' ) );

		// Optionally network_admin_menu.
		$hook = $this->cmb->prop( 'admin_menu_hook' );
		
		/*
		*		changes to get working sub_menu position
		*
		*/
		
		
		$parent_slug = $this->cmb->prop( 'parent_slug' );
		$position    = $this->cmb->prop( 'position' );

		if ( $parent_slug ) { 				
			// Hook in to add our sub_menu.
			if ( $position > 0 ){
				// Hook in to add our sub_menu setting position
				add_action( $hook, array( $this, 'options_page_menu_hooks' ), 100 * $position );
			}
			else { 				
				// Hook in to add our sub_menu in a very last position
				add_action( $hook, array( $this, 'options_page_menu_hooks' ), 2000 );
			}
		}
		else{
			// Hook in to add our menu.
			add_action( $hook, array( $this, 'options_page_menu_hooks' ) );
		}

		/*
		*	end of changes
		*
		*/

		// If in the network admin, need to use get/update_site_option.
		if ( 'network_admin_menu' === $hook ) {
			// Override CMB's getter.
			add_filter( "cmb2_override_option_get_{$this->option_key}", array( $this, 'network_get_override' ), 10, 2 );
			// Override CMB's setter.
			add_filter( "cmb2_override_option_save_{$this->option_key}", array( $this, 'network_update_override' ), 10, 2 );
		}
	}
`

**Comment by james0r** [comment]
@alfonmaco Great stuff! Yes, changing the cap to 'unknown' did the trick for me. Almost seems more intuitive IMHO for this to be the default behavior with options-page boxes. 

I'm not having any issues with the position yet but if I do i'll check out your findings here.

Really appreciate it.

**Comment by jtsternberg** [comment]
The [priority box property](https://github.com/CMB2/CMB2/wiki/Box-Properties#priority) is now used for the hook priority for the `add_action` to register the option pages:
https://github.com/CMB2/CMB2/compare/82c3fc844aba8f3c099d7450013e4ff870f58832...develop#diff-7a27804f02c9964249e8fcdfc649140623a59dc2ea8548ad124d35021969dc99
