### ISSUE TITLE
Password field type

### ISSUE THREAD

**Issue by andrewminion-luminfire** [CMB2/CMB2#1385]
**Is your feature request related to a problem? Please describe.**
I’m building a plugin that has some fields for API keys. I’d prefer that they not be visible in a plain `<input type="text">` field, but there seems to be no `<input type="password">` equivalent.

**Describe the solution you'd like**
I’d love to see a password type field.

**Describe alternatives you've considered**
I’ve considered building a plugin to provide this feature, but figured I should open an issue to see if it would be accepted into CMB2 core first. I’m happy to build it and submit a PR if you’re willing to accept it.

**Comment by tw2113** [comment]
It'd actually be easier to make use of the [attributes parameter](https://github.com/CMB2/CMB2/wiki/Field-Parameters#attributes) which allows you to override the type attribute.

The second example at the anchored link shows how to turn a the text field type into number. You could make use of and do "password" instead.

**Comment by andrewminion-luminfire** [comment]
Ah, thanks…mind if I add that as another example in the wiki?

**Comment by tw2113** [comment]
@andrewminion-luminfire go for it, regarding the wiki example addition

**Comment by pgroot91** [comment]
Sorry for bumping this thread! :D

We created a custom field type for this https://github.com/automex/cmb2-hide-show-password-field a while back! It may be useful for others searching for a similar field type.
