### ISSUE TITLE
Multicheck example of how to display just the first three

### ISSUE THREAD

**Issue by TheNewGuy16** [CMB2/CMB2#1388]
Multicheck example of how to display just the first three if they are check out of a 10 checkbox multicheck

**Comment by tw2113** [comment]
Not quite following what you're asking.

**Comment by TheNewGuy16** [comment]
So I have an amenities mutlicheck in the admin area

   -
      -  Kitchen
      -  Balcony
      -  Fireplace
      -  Riverside
      -  Mini Fridge
      -  Wifi
      -  TVs
      -  Coffee Maker
      -  Irons
      -  Humidifier


  and I display all of them with a foreach statement on the front end for
each single room posting page.

foreach (amenities as amenity){
echo $amenitiy
}
which show all of the ones checked


But then on the all rooms listing page we only want to display the first
three if they are checked.  I ended up just pushing all of the checked ones
to an array and then checking if the first second third in the array are
either Kitchen Balcony or fireplace then echoed out the appropriate icon
for each

if($amenities){
$roomAmenity = array();
foreach ($amenities as $amenity){
$roomAmenity[] = $amenity;
}
if($roomAmenity[0]=='Kitchen'){
echo'<span class=\'icon-spoon-knife\'></span>
}
if($roomAmenity[0]=='Balcony'){
echo'<span class=\'icon-sun\'></span>
}
if($roomAmenity[0]=='Fireplace'){
echo'<span class=\'icon-fireplace\'></span>
}
if($roomAmenity[1]=='Kitchen'){
echo'<span class=\'icon-spoon-knife\'></span>
}
if($roomAmenity[1]=='Balcony'){
echo'<span class=\'icon-sun\'></span>
}
if($roomAmenity[1]=='Fireplace'){
echo'<span class=\'icon-fireplace\'></span>
}
if($roomAmenity[2]=='Kitchen'){
echo'<span class=\'icon-spoon-knife\'></span>
}
if($roomAmenity[2]=='Balcony'){
echo'<span class=\'icon-sun\'></span>
}
if($roomAmenity[2]=='Fireplace'){
echo'<span class=\'icon-fireplace\'></span>
}
}

but I feel like there has to be a shorter way to do it . Is there a way to
check if the first three of the multicheck are checked or not and echo
those out?

Thanks

Brian Musinski
Avid Design
P.O. Box 691
vail, CO 81658
t: 970.479.8555
f: 970.479.6007
http://avidonline.com

WEB.PRINT.IDEAS

Follow Avid Design on:
Facebook <https://www.facebook.com/aviddesign> | Twitter
<http://twitter.com/avid_design> | Google+
<https://plus.google.com/103558248328328505381/posts> | Pinterest
<http://pinterest.com/aviddesignvail/> | LinkedIn
<http://www.linkedin.com/company/avid-design-vail>


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by tw2113** [comment]
I'd probably just use `in_array()` or similar for it. It looks like `in_array()` takes arrays for both needle and haystack, so you could save some lines of code there.

**Comment by TheNewGuy16** [comment]
gotcha thanks



Brian Musinski
Avid Design
P.O. Box 691
vail, CO 81658
t: 970.479.8555
f: 970.479.6007
http://avidonline.com

WEB.PRINT.IDEAS

Follow Avid Design on:
Facebook <https://www.facebook.com/aviddesign> | Twitter
<http://twitter.com/avid_design> | Google+
<https://plus.google.com/103558248328328505381/posts> | Pinterest
<http://pinterest.com/aviddesignvail/> | LinkedIn
<http://www.linkedin.com/company/avid-design-vail>
