### ISSUE TITLE
PHP 7.4 warning

### ISSUE THREAD

**Issue by jonathanstegall** [CMB2/CMB2#1389]
## Describe the bug
When running a PHPCS compatibility check for PHP 7.4, the only thing CMB2 seems to report is this, in the file `/cmb2/includes/CMB2_Base.php`:

> Since PHP 7.0, functions inspecting arguments, like func_get_args(), no longer report the original value as passed to a parameter, but will instead provide the current value. The parameter "$message" was used, and possibly changed (by reference), on line 416.

## Steps to reproduce (I have confirmed I can reproduce this issue on the [`develop`](https://github.com/CMB2/CMB2/tree/develop) branch):
1. Set up [PHPCompatibilityWP](https://github.com/PHPCompatibility/PHPCompatibilityWP)
2. In the root of WordPress where composer.json is, run the command `./vendor/bin/phpcs -p . --standard=PHPCompatibilityWP --extensions=php --runtime-set testVersion 7.3-`

## Possible Solution

Possibly, the solution is to move `$args = func_get_args();` before the `if ( is_numeric( $message ) ) {` call.

## Your Environment

Browser name and version:
Operating System and version (desktop or mobile): macOS Catalina.

**Comment by tw2113** [comment]
Definitely likely valid by all means.

I am amused that that line in question, is inside a `deprecated_param()` method :D

**Comment by jonathanstegall** [comment]
Wanted to check on this. I could submit a PR with the line of code I mentioned, although since it's in a deprecated method I'm not really sure how I would test it.

**Comment by jtsternberg** [comment]
Please do submit a PR. To test, set a default callback using the [`default` param](https://github.com/CMB2/CMB2/wiki/Field-Parameters#default) (vs the `default_cb` param), and you should see the deprecated warning.
