### ISSUE TITLE
Not really a Feature Request? Unless it does not exist already. 

### ISSUE THREAD

**Issue by krishangpatney** [CMB2/CMB2#1403]
**Is your feature request related to a problem? Please describe.**
I am trying to add in post meta boxes to be queried with WordPress search features, in particular get_search_query(), within search.php.

**Describe the solution you'd like**
A coded way for me to do this within search,PHP file 

**Describe alternatives you've considered**
 Not been able to find any, hence reaching out here to request for help. 

<if code is needed can provide so, however it is quite standard>

**Comment by tw2113** [comment]
Hi @krishangpatney 

So you're trying to include meta data from some metaboxes, to be considered during a WordPress search, and potentially affect the outcome of the results?

**Comment by krishangpatney** [comment]
yep, so for example, on my WordPress website there are posts with an author metabox, I now want to allow people to use search and have Wordpress also query the author metaboxes for matches. For example, if I were to search for 'krishang', I'd like all posts under my name to come up (from the metabox).

**Comment by tw2113** [comment]
Not really something specific to CMB2 here, as it sounds like potentially a usecase for  [pre_get_posts](https://developer.wordpress.org/reference/hooks/pre_get_posts/) and adding in meta query parameters if currently performing a search query. This spot on the docs page for pre_get_posts has a basic example that you could modify to set meta queries on https://developer.wordpress.org/reference/hooks/pre_get_posts/#exclude-pages-from-search-results Perhaps making use of the queried term as the meta value

If that's not quite right, then the only other alternative at the moment would be needing to have WordPress search meta fields as well as its normal areas, and that's not necessarily the easiest thing to set up from what I've seen.

**Comment by krishangpatney** [comment]
Hey, figured out a way around it kinda by using a plugin, however thanks for your help. :) Shall close this issue.
