### ISSUE TITLE
PHP 8 notice: Required parameter $field_id follows optional parameter

### ISSUE THREAD

**Issue by rubengc** [CMB2/CMB2#1406]
Testing CMB2 in a PHP 8 enviroment causes a notice that alerts about a required parameter that follows an optional one

The notice is:
Deprecated: Required parameter $field_id follows optional parameter $type in cmb2\includes\rest-api\CMB2_REST.php on line 764

The fix only requires to give an initial value to $field_id or make the previous parameters required too

**Comment by jtsternberg** [comment]
It appears you are still on an old version. https://github.com/CMB2/CMB2/blob/fb59d6512b033a44f8f39084c689881e0d75a2d3/includes/rest-api/CMB2_REST.php#L764

**Comment by rubengc** [comment]
Yes, just need to update

Sorry for do not check first for newest versions of CMB2

Thanks @jtsternberg
