### ISSUE TITLE
URLs are sanitized with http, not https

### ISSUE THREAD

**Issue by paulschreiber** [CMB2/CMB2#1412]
## Describe the bug
URLs are sanitized with http, not https. This could lead to privacy loss / redirection / other attacks.

## Steps to reproduce (I have confirmed I can reproduce this issue on the [`develop`](https://github.com/CMB2/CMB2/tree/develop) branch):
1. Create a field of type `text_url`
2. Open a page with that field
3. Enter `google.com` in the field
4. Save the page

## Expected
https://google.com/

## Actual
http://google.com/

## Possible Solution
If the original URL didn't contain a protocol, use `set_url_scheme()` to set it to HTTPS.

**Comment by tw2113** [comment]
Sounds similar to https://github.com/CMB2/CMB2/issues/1391 which didn't really have an actionable resolution, but I have notes in there at https://github.com/CMB2/CMB2/issues/1391#issuecomment-740350116 about CMB2's used internals.

Leaving open for any further discussion needed/desired, but don't have a solution of sorts
