### ISSUE TITLE
woocommerce product data:  Regular price ($) input feild does not save when  CMB2 / CMB2  is active

### ISSUE THREAD

**Issue by Dmwds** [CMB2/CMB2#1414]
when adding a product in woo-commerce , the Regular price ($) field does not save. nor does store data value when CMB2 is active

## CMB2 Field Registration Code:

```php
add_action( 'cmb2_admin_init', 'yourprefix_register_demo_metabox' );
function yourprefix_register_demo_metabox() {

	$cmb = new_cmb2_box( array(
		// Box Config...
	) );

	$cmb->add_field( array(
		// Field Config...
	) );

	// Additional fields...
}
```

## Your Environment

Browser name and version:
Operating System and version (desktop or mobile):

**Comment by jtsternberg** [comment]
I'm going to close the issue, but if you update the description with the requested data, we can re-open.
