### ISSUE TITLE
Deprecation error on CMB2_Type_Multi_Base.php with PHP 8

### ISSUE THREAD

**Issue by isaumya** [CMB2/CMB2#1423]
## Describe the bug
With PHP 8.0.6 the latest version of CMB2 is throwing the following depreciation message:

```
Deprecated: Required parameter $i follows optional parameter $args 
in /example.com/public/wp-content/plugins/seo-by-rank-math/vendor/cmb2/cmb2/includes/types/CMB2_Type_Multi_Base.php 
on line 34
```

I've checked that the Rank Math plugin is using the latest version (v2.9.0) of CMB2 via composer which means this problems still hasn't been resolved in the latest version of CMB2.

**Comment by tw2113** [comment]
https://github.com/CMB2/CMB2/commit/73cd1a34c23c7287fd26710482103736339577cf

We've addressed it enough that it's been committed, but we haven't pushed out a release just yet that includes the fix

Feel free to make the change yourself to confirm the error goes away.
