### ISSUE TITLE
Can not sort fields in repeatable group

### ISSUE THREAD

**Issue by DJMIMi** [CMB2/CMB2#1428]
```php
add_action( 'cmb2_admin_init', function(){
	
	$cmb = new_cmb2_box([
		'id'            => 'metabox_attachment',
		'title'         => 'TEst',
		'object_types'  => [ 'page' ], // Post type
		'priority'      => 'high',
		'show_names'    => true
	] );

	$group_field_id = $cmb->add_field( array(
		'id'          => 'wiki_test_repeat_group',
		'type'        => 'group',
		'description' => __( 'Generates reusable form entries', 'cmb2' ),
		'repeatable'  => true,
		'options'     => array(
			'group_title'       => __( 'Entry {#}', 'cmb2' ), 
			'add_button'        => __( 'Add Another Entry', 'cmb2' ),
			'remove_button'     => __( 'Remove Entry', 'cmb2' ),
			'sortable'          => true,
			'remove_confirm'    => esc_html__( 'Are you sure you want to remove this?', 'cmb2' ),
		),
	) );

	$cmb->add_group_field( $group_field_id, array(
		'name' => 'Entry Title 2',
		'id'   => 'subtitle',
		'type' => 'text',
		 'repeatable' => true,
		 'sortable' => true
	) );

});
```

Step 1
Click to add new group - Add new entry

Step 2.
Click Add Row to add another instance of repeatable|sortable  field inside of last created group

Result 
Drag&drop is not available for repeatable|sortable fields in newly created group

**Comment by tw2113** [comment]
Looks like the sort-ability is determined on page render and not re-calculated with new groups being added afterwards. I created 2-3 groups, and then hit publish, and tried again and all the spots were sortable. However, a 4th group was not, and probably wouldn't be until save and refresh.

So, ideally adding a new row would trigger the jQuery sortable code for that new row.

**Comment by DJMIMi** [comment]
This fixes sortable on adding new row 

https://prnt.sc/13ppkj7
cmb.makeRepeatableSortable( $newRow );

and change function makeRepeatableSortable to accomodate both initial sortable add ing new row by adding optional param $row

`
     cmb.makeRepeatableSortable = function( $row ) {
         var $repeatables = $row ? $row.find( '.cmb-repeat-table .cmb-field-list' ) : cmb.metabox().find( '.cmb-repeat-table .cmb-field-list' );
 
         if ( $repeatables.length ) {
             $repeatables.sortable({
                 items : '.cmb-repeat-row',
                 cursor: 'move',
                 // The default "cancel" attributes are: "input,textarea,button,select,option".
                 // We are appending .CodeMirror.
                 // See https://api.jqueryui.com/sortable/#option-cancel
                 cancel: 'input,textarea,button,select,option,.CodeMirror'
             });
         }
     };
`

**Comment by jtsternberg** [comment]
Thank you for providing the solution. Fixed.
