### ISSUE TITLE
Sortable fields do not maintain their order

### ISSUE THREAD

**Issue by DJMIMi** [CMB2/CMB2#1429]
```
add_action( 'cmb2_admin_init', function(){
	
	$cmb = new_cmb2_box([
		'id'            => 'metabox_attachment',
		'title'         => 'TEst',
		'object_types'  => [ 'page' ], // Post type
		'priority'      => 'high',
		'show_names'    => true
	] );

	$cmb->add_field( array(
		'id'          => 'wiki_test_repeat_group',
		'type'        => 'text',
		'description' => __( 'Generates reusable form entries', 'cmb2' ),
		'repeatable'  => true,
		'sortable'          => true,
	) );
});
```

Step 1
Add couple of text fields and populate them

Step 2 
drag & drop to change their order

Step 3
Update the post/page

Result
Fields are not ordered properly

**Comment by tw2113** [comment]
This one I'm not managing to recreate. The fields are staying in the order they were saved in.

**Comment by DJMIMi** [comment]
Array index is not recalculated on sort complete so the values are not stored in desired sort order https://prnt.sc/13po9w6   https://prnt.sc/13poe6z

**Comment by jtsternberg** [comment]
I also am not able to replicate. It saves in the order it's set for me.

**Comment by DJMIMi** [comment]
Maybe you are testing in version which is not yet released and it was fixed or something. Anyway I've solved it for me like this

Modified makeRepeatableSortable  so it calls new function updateNameAttrSort which will update name of repeatable field based on it's position in the list

`
     cmb.makeRepeatableSortable = function( $row ) {
         var $repeatables = $row ? $row.find( '.cmb-repeat-table .cmb-field-list' ) : cmb.metabox().find( '.cmb-repeat-table .cmb-field-list' );
 
         if ( $repeatables.length ) {
             $repeatables.sortable({
                 items : '.cmb-repeat-row',
                 cursor: 'move',
                 stop: function( event, ui ){
                    cmb.updateNameAttrSort( ui.item.parents( '.cmb-repeat-table' ) );
                 },
                 // The default "cancel" attributes are: "input,textarea,button,select,option".
                 // We are appending .CodeMirror.
                 // See https://api.jqueryui.com/sortable/#option-cancel
                 cancel: 'input,textarea,button,select,option,.CodeMirror'
             });
         }
     };
`

New function:

'
     cmb.updateNameAttrSort = function ( $container ) {
        var counter = 0;
        $container.find( cmb.repeatEls ).each(function(){
            var $this = $(this);
            var name  = $this.attr( 'name' );

            $this.attr( 'name', name.replace(/(.*)\[\d+\]/, '$1[' + counter + ']') );

            counter++;
        });
     };
'

The next one is not related to above

I've also added new function updateIterators which will reduce iterator data by one one row remove ( for all fields bellow removed one ) so it maintain proper incremental value

'
     cmb.updateIterators = function() {
         var $this = $(this);
         var iterator = $this.data('iterator');
         iterator--;

         $this.data( 'iterator', iterator ).attr( 'data-iterator', iterator );
     };
'

and it is being called from removeGroupRow function 

`
 $parent.nextAll( '.cmb-repeatable-grouping' ).each(cmb.updateIterators);
`

here https://prnt.sc/13uz15f

**Comment by tw2113** [comment]
For what it's worth, I had been doing my testing on the 2.9.0 tagged release, not the develop branch which is the "latest greatest" version with all the changes for the next release.

Can you try with a checkout of the develop branch from the repo here on GH? Alternatively, just in case other plugins are causing conflicts, can you try with JUST CMB2 active and no other plugins to see if it goes away?

**Comment by DJMIMi** [comment]
So weird, yesterday I could replicate it today no, so all good.

**Comment by jtsternberg** [comment]
Closing for now.
