### ISSUE TITLE
Sortable fields change their value on save

### ISSUE THREAD

**Issue by DJMIMi** [CMB2/CMB2#1430]
```
add_action( 'cmb2_admin_init', function(){
	
	$cmb = new_cmb2_box([
		'id'            => 'metabox_attachment',
		'title'         => 'TEst',
		'object_types'  => [ 'page' ], // Post type
		'priority'      => 'high',
		'show_names'    => true
	] );

	$cmb->add_field( array(
		'id'          => 'wiki_test_repeat_group',
		'type'        => 'text',
		'description' => __( 'Generates reusable form entries', 'cmb2' ),
		'repeatable'  => true,
		'sortable'          => true,
	) );
});
```

Step 1.
Populate fields for example like this  https://prnt.sc/13op888

Step 2.
Drag & drop 3rd row to 2nd place 

Step 3.
Update post

Result
Row with value 2 is lost and there are two rows with value 1

**Comment by tw2113** [comment]
Same as #1429, not managing to recreate this issue. Possible there's some other plugin js code conflicting? Take a peek at your browser's dev console to see if anything stands out.

**Comment by DJMIMi** [comment]
No plugin only CMB2 and Default WP theme

**Comment by DJMIMi** [comment]
This was browser memorizing input values
