### ISSUE TITLE
How to create a group row via the frontend?

### ISSUE THREAD

**Issue by Msantanna10** [CMB2/CMB2#1432]
Hello! I swear I tried to look for something similar a hundred times but got nothing.

I already know how to edit fields on the frontend, the only thing I couldn't get working is to create group rows and edit their custom fields via the frontend.

I'd be really grateful if someone can point me to the right direction.

Thank you!

**Comment by tw2113** [comment]
Do you have a version that's set up to work on the backend at the moment? If yes, I know we have tutorials and demos available to show CMB2 on the frontend that could be followed and tested.

**Comment by Msantanna10** [comment]
I'll try something later, I just had an idea.

I'd like to know that because I am thinking about creating a private message system using CMB2 group rows, so I can have full control and manage everything easily in case  someone helps me as an admin.

I dont wanna use other plugins for that, I quite like CMB2 and I wonder what could be the smartest way to achieve this goal. 

Thank you!

**Comment by tw2113** [comment]
https://github.com/CMB2/CMB2/wiki/Bringing-Metaboxes-to-the-Front-end would be a good first stop, though the entire Wiki has some pretty great information as well as https://github.com/CMB2/CMB2-Snippet-Library/ for more examples.

**Comment by Msantanna10** [comment]
Perfect! What would you suggest in terms of a private message system? I'd love to find a way to use CMB2

**Comment by tw2113** [comment]
I'd probably consider either a post type or if I'm ambitious enough, a custom table. I know bbPress has post types for forum, topic, and reply, and ties them all together.

**Comment by Msantanna10** [comment]
Post type seems to be a good idea, I already have something in mind. Thank you! You guys are the best!

**Comment by tw2113** [comment]
Welcome.
