### ISSUE TITLE
PHP Deprecated

### ISSUE THREAD

**Issue by Astra-001** [CMB2/CMB2#1440]
PHP Deprecated:  Required parameter $i follows optional parameter $args in D:\xampp\htdocs\latestwordpress\wp-content\plugins\event-registrations-for-the-events-calendar\cmb2\includes\types\CMB2_Type_Multi_Base.php on line 34

**Comment by jtsternberg** [comment]
This was already fixed in 73cd1a34c23c7287fd26710482103736339577cf

**Comment by tw2113** [comment]
@Astra-001 for some extra context, the developer(s) for Event Registrations for The Events Calendar have shipped with a copy of CMB2 bundled with their own plugin. We don't have control over that part, so while we handled the core library itself already, they need to update their shipped copy.
