### ISSUE TITLE
Deprecated: Required parameter $i follows optional parameter $args in D:\Server\htdocs\standard\wp-content\themes\standard\metabox\includes\types\CMB2_Type_Multi_Base.php on line 34

### ISSUE THREAD

**Issue by f-rahim** [CMB2/CMB2#1446]
Deprecated: Required parameter $i follows optional parameter $args in D:\Server\htdocs\standard\wp-content\themes\standard\metabox\includes\types\CMB2_Type_Multi_Base.php on line 34
![image](https://user-images.githubusercontent.com/62511270/151046268-e4ee0fec-a604-42b4-9eee-823216577334.png)

**Comment by jtsternberg** [comment]
Already fixed in #1417

**Comment by tw2113** [comment]
@f-rahim To add some extra clarity, you're going to want to reach out to the theme developer to let them know that there are updates available to CMB2 that they can update their copy to and/or potentially make the same change yourself, found at https://github.com/CMB2/CMB2/commit/c8b29a0779671841906422fe4a38df0831d1a31d
