### ISSUE TITLE
Display gallery and group with elementor

### ISSUE THREAD

**Issue by IselinFox** [CMB2/CMB2#1453]
Can anyone help me with displaying CMB2 image gallery and groups with elementor pro? 

I'm not that good at coding, but giving it a go... 

Created a child theme of Hello Elementor. 
I've created a new post type for products, and want the user to be able to simply put in information. Some products have multiple styles, so I've tried setting up a repeatable group, for display of images and description... 

I've only edited the function.php file. It displays correctly in the backend, but I'm not sure how to display it in the front end... 

Using dynamic tags in the elementor theme builder, I'm able to display 'single' metaboxes containing text, 
But can't manage to display image gallery or group... 

Can anyone help me with the code that I need? And where to place the code? Thank you in advance :) 

Here is the code I've used for the group: 

```
// Custom Fields

add_action( 'cmb2_init', 'cmb2_sample_metaboxes' );

// Define the metabox and field configurations.

function cmb2_sample_metaboxes() {
	
		$cmb = new_cmb2_box( array(
		'id'            => 'produkter_tillegg',
		'title'         => __( 'Tillegg og utførelser', 'cmb2' ),
		'object_types'  => array( 'po_produkter', ), // Post type
		'context'       => 'normal',
		'priority'      => 'high',
		'show_names'    => true, // Show field names on the left
		// 'cmb_styles' => false, // false to disable the CMB stylesheet
		// 'closed'     => true, // Keep the metabox closed by default
	) );


	$group_field_id = $cmb->add_field( array(
	'id'          => 'produkter_repeat_group',
	'type'        => 'group',
	'description' => __( 'Legg til tillegg', 'cmb2' ),
	// 'repeatable'  => false, // use false if you want non-repeatable group
	'options'     => array(
		'group_title'       => __( 'Tillegg {#}', 'cmb2' ), // since version 1.1.4, {#} gets replaced by row number
		'add_button'        => __( 'Legg til ny', 'cmb2' ),
		'remove_button'     => __( 'Fjern tillegg', 'cmb2' ),
		'sortable'          => true,
		// 'closed'         => true, // true to have the groups closed by default
		// 'remove_confirm' => esc_html__( 'Are you sure you want to remove?', 'cmb2' ), // Performs confirmation before removing group.
	),
) );

// Id's for group's fields only need to be unique for the group. Prefix is not needed.
$cmb->add_group_field( $group_field_id, array(
	'name' => 'Tittel/type',
	'id'   => 'tittel_tillegg',
	'type' => 'text',
) );

$cmb->add_group_field( $group_field_id, array(
	'name' => 'Beskrivelse',
	'id'   => 'beskrivelse_tillegg',
	'type'    => 'wysiwyg',
	'options' => array(),
) );

$cmb->add_group_field( $group_field_id, array(
	'name' => 'Bilder',
	'id'   => 'bilder_tillegg',
	'type' => 'file_list',
	'preview_size' => array( 200, 200 ), // Default: array( 50, 50 )
	'query_args' => array( 'type' => 'image' ), // Only images attachment
	// Optional, override default text strings
	'text' => array(
		'add_upload_files_text' => 'Legg til bilder', // default: "Add or Upload Files"
		'remove_image_text' => 'Fjern bildetekst', // default: "Remove Image"
		'file_text' => 'Bilde', // default: "File:"
		'file_download_text' => 'Last ned', // default: "Download"
		'remove_text' => 'Fjern bilde', // default: "Remove"
	),
) );

}
```

**Comment by tw2113** [comment]
I have to suspect that CMB2 is only going to play a small-ish part in this overall solution. Most specifically CMB2 is going to have the role of saving images and information for items in a given gallery. Most specifically as post meta on this "products" post type you've set up.

What remains, at minimum, is in what way is the gallery going to be displayed? Is it going to be a custom module or solution created to work within Elementor? Are there Elementor modules that are able to pull post meta in some way and do something with the information? These are things that CMB2 itself won't be handling, as its focus is go create UI for meta data management on various content types in WordPress.

**Comment by IselinFox** [comment]
I was hoping to use elementor dynamic tags to create templates for the 'products', but I have a feeling the solution is too advanced for my level... Opted to purchase the jetengine plugin that already have the functions I'm looking for working with elementor...

**Comment by tw2113** [comment]
Sounds like you have your next steps now, and I'm rooting for you to achieve what you need here.
