### ISSUE TITLE
DIdn't show Cmb2 metabox  value in font page

### ISSUE THREAD

**Issue by mahmudhasan7** [CMB2/CMB2#1455]
function client_theme()
{
    $client = new_cmb2_box( array(
        'id'           => 'recen',
        'title'        => 'Name',
        'object_types' => array( 'Recent' )
        
    ) );

    $client->add_field( array(
        'name' => 'Name',
        'id'   => 'recents',
        'type' => 'text'
        
    ) );
}
add_action( 'cmb2_admin_init', 'client_theme' );

here is the code font page code :that i cant show value in frontend:

			$recent = new WP_Query([

				'post_type'  => 'Recent'
			] );
			while($recent->have_posts()):$recent->the_post();
				$resents_meta = get_post_meta( get_the_ID(), 'recents', true );
				?>
						 <div class="post-box"> 
						<div class="post-img"><?php the_post_thumbnail(  );?></div>
							<div class="post-cont"> 
								<h2><?php the_title( );?></h2>
								<p><?php echo wp_trim_words( get_the_content( ),20,false );?></p>
								<h1><?php echo $resents_meta; ?></h1>
							</div>
					</div>

**Comment by tw2113** [comment]
Did you find the reasoning why things weren't originally working? would love to see the solution, in case someone else comes in with similar issues.
