### ISSUE TITLE
Update fields in readme

### ISSUE THREAD

**Issue by Mte90** [CMB2/CMB2#1457]
Right now mention my old field https://github.com/CMB2/CMB2-Post-Search-field that I abandoned for https://github.com/rubengc/cmb2-field-ajax-search that is more complete and does also for post and terms.

I am contributing to that field also if the author is not so active now.

**Comment by Mte90** [comment]
Done https://github.com/CMB2/CMB2/pull/1458

**Comment by tw2113** [comment]
Awesome possum! As Justin has already merged, I will close this one out as resolved.

Thanks @Mte90
