### ISSUE TITLE
Default values not applicable in theme option page 

### ISSUE THREAD

**Issue by Mnshawaty** [CMB2/CMB2#1459]
I made an theme option page 
And i have a sample to change the colour of background as like your example
But the default values are not applied
it need to open option page and click on save button tobe applied help me please 

[This is your example ](https://github.com/CMB2/CMB2-Snippet-Library/blob/master/options-and-settings-pages/theme-options-cmb.php)

**Comment by tw2113** [comment]
Closing this issue as you opened up a 2nd issue over at https://github.com/CMB2/CMB2-Snippet-Library/issues/111 and we'll handle there.
