### ISSUE TITLE
add options page as submenu to a post type menu

### ISSUE THREAD

**Issue by greenlevel** [CMB2/CMB2#1464]
Hi I just came across this plugin and wanted to add the options page as submenu to a custom post type in the admin menu.

My custom post type is register_post_type( 'invoice', $args );

Looking at the feedback only added the following parameters to the register_theme_options_metabox function
'parent_slug' => 'invoice',

But it doesn't show up. Do I miss something? Thanks in advance!

I came occurs this lead as well. [https://github.com/CMB2/CMB2/issues/1410](url) 
But it seems fixed? As it's closed.

**Comment by greenlevel** [comment]
Hi I just installed the plugin through wordpress installer, Version 2.10.1

and then put the all the code of the example-functions.php in my functions.php
As for the settings I only added the parent slug to be invoice (invoice is the url for the custom post type)

	$cmb_options = new_cmb2_box( array(
		'id'           => 'yourprefix_theme_options_page',
		'title'        => esc_html__( 'Theme Options', 'cmb2' ),
		'object_types' => array( 'options-page' ),
		'option_key'      => 'yourprefix_theme_options', // The option key and admin menu page slug.
		'icon_url'        => 'dashicons-palmtree', // Menu icon. Only applicable if 'parent_slug' is left empty.
		 'parent_slug'             => 'invoice', // Make options page a submenu item of the themes menu.

	) );

Thanks in advance!

**Comment by tw2113** [comment]
Closing as a non-issue to the plugin itself.

**Comment by greenlevel** [comment]
Thanks very much! It worked.  I didn't know you can just use the standard wordpress functionalities.

**Comment by tw2113** [comment]
Yep yep. We use WP core functions internally to our functions and configuration options.
