### ISSUE TITLE
Image file is not assigned to the correct group item

### ISSUE THREAD

**Issue by alexandrqu** [CMB2/CMB2#1469]
## Describe the bug
The problem occurs in a custom post type with a repeatable group item ('type' => 'group', 'repeatable' => true)

For example, in the custom post type, we have 4 repeatable group items with an image and text in each, after saving the custom post type and after refreshing the page. we delete element[3] and add a new element[4], when adding an image ('type' => 'file') in element[4], the image is assigned to previous item[3]

## Steps to reproduce (I have confirmed I can reproduce this issue on the [`master`](https://github.com/CMB2/CMB2/tree/master) branch):
Case : Have multiple field groups with an image and text in each

| Stage | Description | Screenshot |
|-------|-------------|------------|
| 1 | Delete item[3] |![item1](https://user-images.githubusercontent.com/71935522/197773027-ee6c6be6-4ec9-436f-a50c-d558ccdf0b2e.png) |
| 2 | Add new item[4] |![item2](https://user-images.githubusercontent.com/71935522/197773291-85bf1401-0433-4e3a-be28-42f13ecb5c7e.png) |
| 3 | Add image to item[4] |![item3](https://user-images.githubusercontent.com/71935522/197773709-0a21fd9e-682e-41ef-9df8-87cffed26424.png) |
| 4 | Image is in to the item[3] |![item4](https://user-images.githubusercontent.com/71935522/197774142-ab11af98-c87c-4d98-a989-4ccd9b49f697.png) |

## Additional message
@sergromanenko1 hello, you made a pull request on a similar problem https://github.com/CMB2/CMB2/pull/1371
Do you have the possibility to look for a fix or give us an indication to fix it

**Comment by tw2113** [comment]
Can you provide your CMB2 configuration code so that we can match it up exactly as to what you're seeing this with?

**Comment by alexandrqu** [comment]
You will find below the cmb2 conf of the group and the image (the only two elements necessary to run the bug)

    $slider_group = $slider->add_field(array(
      'id' => $prefix . 'slides',
      'type' => 'group',
      'repeatable' => true,
      'classes' => 'cmb2-width-100',
      'options' => array(
      'group_title' => __('Item {#}', 'cmb2'),
      'add_button' => __('<span class="dashicons dashicons-plus"></span>', 'cmb2'),
      'remove_button' => __('<span class="dashicons dashicons-trash"></span>', 'cmb2'),
      'sortable' => true,
      'closed' => true,
      ),
    ));
    
    $slider->add_group_field($slider_group, array(
      'name' => 'Image',
      'id' => $prefix . 'image',
      'type' => 'file',
      'options' => array(
        'url' => false,
      ),
      'text' => array(
        'add_upload_file_text' => 'Add Image',
      ),
      'query_args' => array(
        'type' => array(
          'image/gif',
          'image/jpeg',
          'image/png',
          'image/svg+xml',
        ),
      ),
      'preview_size' => 'large',
            'attributes' => array(
                'required'               => true, // Will be required only if visible.
                'data-conditional-id'    => $prefix . 'media',
                'data-conditional-value' => 'image',
            ),
    ));

**Comment by tw2113** [comment]
This was bigger than GH allowed, by 2mb

https://cloudup.com/cJI_PvVneUX

@jtsternberg what are your thoughts with this one? I was able to reproduce, but you know the javascript with CMB2 more than I do.

**Comment by davask** [comment]
Hi,
@jtsternberg , it works like a charm, thx
