### ISSUE TITLE
Metabox not going away - cached?

### ISSUE THREAD

**Issue by gyrus** [CMB2/CMB2#1474]
I've no idea if this might be replicable, but I have a metabox that won't go away. It used to be this:

```
$cmb = new_cmb2_box( [
	'title'        => __( 'Page content' ),
	'id'           => 'experience_content_box',
	'object_types' => [ 'experience' ],
	'priority'     => 'high',
	'show_names'   => true,
] );
$cmb->add_field( [
	'name' => __( 'Teaser' ),
	'id'   => '_biro_experience_teaser',
	'type' => 'textarea_small',
] );
$cmb->add_field( [
	'name' => __( 'Main content' ),
	'id'   => '_biro_experience_content',
	'type' => 'wysiwyg',
] );
```

Now it's this:

```
$cmb = new_cmb2_box( [
	'title'        => __( 'Teaser' ),
	'id'           => 'experience_teaser_box',
	'object_types' => [ 'experience' ],
	'priority'     => 'high',
	'show_names'   => false,
] );
$cmb->add_field( [
	'name' => __( 'Teaser' ),
	'id'   => '_biro_experience_teaser',
	'type' => 'textarea_small',
] );
```

Only now the latter 'Teaser' box appears _as well as_ the former 'Page content' box.

- Searching the entire codebase returns nothing for the string 'Page content'
- The 'Teaser' field in both boxes outputs the same value, but the value only updates via the field in the 'Page content' box
- I didn't know CMB2 had any kind of cache, but I found the `$reset_cached` parameter in the `CMB2->get_field()` method. I tried setting the default for this parameter to `true`, and I tried commenting out the bit where it returns the cached version if that parameter is `false`, but no change - 'Page content' still appears.
- Our servers have their own caching mechanism, though AFAIK this is inactive for WP admin pages. And in any case the same issue is happening for me locally, where I've not got any caching set up. Obviously I've completely clear my browser cache and hard refreshed (this is happening for multiple people).

I'm not sure what else to do. Is there a way to nuke whatever caching CMB2 does?

**Comment by gyrus** [comment]
PS. I have left all the meta values for the old content field in the DB, because we've been migrating this into the main content editor, and I'm leaving the data in case the client misses migrating something. I've no idea if or how this might affect the display of the metabox, but let me know if that might be related, we can look at purging the metadata.

**Comment by gyrus** [comment]
Sorry, my bad. Turns out when I renamed the theme file for the custom fields, our gulp.js failed to delete the original file in the public theme :-/

**Comment by tw2113** [comment]
All good
