### ISSUE TITLE
Can't edit content in WYSIWYG field in Visual mode

### ISSUE THREAD

**Issue by pjohanneson** [CMB2/CMB2#1487]
## Describe the bug

I can't see or edit content in WYSIWYG fields using **Visual** mode. The content is visible and editable in the **Text** mode. This seems identical to #1397 but I'm using WordPress 6.1.1 (latest release as I write this). Gutenberg is the editor for the post.

## Steps to reproduce (I have confirmed I can reproduce this issue on the [`develop`](https://github.com/CMB2/CMB2/tree/develop) branch):

1. Add post with title & content.
2. Enter text in the **About BU** field. 
3. Publish post.
4. (later) Go to the editing screen for the post.
5. WYSIWYG field (in **HTML** view) appears empty; can't click into it.
6. Switching to **Text** view allows me to modify and save the field content.

## CMB2 Field Registration Code:

Code for the WYSIWYG meta field:
```php
$cmb = new_cmb2_box(
	array(
		'id' => Core::PREFIX . 'about_bu_meta',
		'title' => __( 'Post-specific "About BU" text', 'bu-news-server' ),
		'object_types' => array( 'post' ),
	)
);
// Adds the main About BU field.
$cmb->add_field(
	array(
		'id'      => $field_id,
		'name'    => __( '"About BU" text', 'bu-news-server' ),
		'type'    => 'wysiwyg',
		'options' => array(
			'teeny'         => true,
			'textarea_rows' => 5,
			'media_buttons' => false,
		),
	)
);
```

## Your Environment

Browser name and version: Firefox 109.0.1
Operating System and version (desktop or mobile): Linux (Xubuntu 20.04)
WordPress 6.1.1

**Comment by pjohanneson** [comment]
Weird: if I remove the `options` array, it works properly. But if I try to pass *any* options, the **Visual** mode locks me out.

`options` set:  
![Screenshot with `options` set](https://user-images.githubusercontent.com/21602/219741534-4315efd8-323e-44a2-9bb7-f60daee12fee.png)

no `options` set:  
![Screenshot with no `options`](https://user-images.githubusercontent.com/21602/219741225-4b3633dd-357a-4547-8644-0c37f9b95d5b.png)

**Comment by tw2113** [comment]
and javascript console errors?

**Comment by pjohanneson** [comment]
Hmm, it looks like it's a conflict with 4 plugins we're hoping to use for user management and the like. If I deactivate those plugins, the **Visual** editor works; if I re-enable any one of them, the **Visual** editor blanks out. I'll approach the other plugin vendor about this.

Thanks for a very, very useful plugin, by the way.

**Comment by tw2113** [comment]
Sounds good, let us know if you need anything else.
