### ISSUE TITLE
Display CMB on TwentyTwentyTwo or Higher Theme

### ISSUE THREAD

**Issue by Rizatzmi** [CMB2/CMB2#1496]
## Expected Behavior:
The goal is to display the CMB to front end expecially in single custom post type page,

## Actual Behavior:
I have read basic usage, in the basic usage give example to display CMB use some php code. Theme from twentytwentytwo onward its use block pattern and templates extension is .html not .php anymore. So the code from basic usage is doesnt work for me. I was trying  change the extension but when i change the extension file, the file dont use anymore. When single.html changed to single.php, wordpress use the index.html dont want to use single.php.

## CMB2 Field Registration Code:

```php
function cmb2_movies() {

	$cmb = new_cmb2_box( array(
		'id'            => 'movies_metabox',
		'title'         => __( 'Movie Detail', 'cmb2' ),
		'object_types'  => array( 'movies' ), 
		'context'       => 'normal',
		'priority'      => 'high',
		'show_names'    => true,
	) );

	// Year
	$cmb->add_field( array(
		'name' => 'Year',
		'id'   => 'year',
		'type' => 'text_date',
		'date_format' => 'Y',
	) );

	// Duration
	$cmb->add_field( array(
		'name' => 'Duration',
		'id'   => 'duration',
		'type' => 'text_time',
    	'attributes' => array(
        'data-timepicker' => json_encode( array(
            'timeOnlyTitle' => __( 'Choose your Time', 'cmb2' ),
            'timeFormat' => 'HH:mm',
            'stepMinute' => 1, // 1 minute increments instead of the default 5
        ) ),
    ),
    'time_format' => 'h:i:s A',
	) );

	// Genres
	$cmb->add_field( array(
		'name'    => 'Genres',
		'desc'    => 'Choose the Genres',
		'id'      => 'genres',
		'type'    => 'multicheck',
		'select_all_button' => false,
		'options' => array(
			'check1' => 'Action',
			'check2' => 'Romance',
			'check3' => 'Comedy',
		),
	) );

}

add_action( 'cmb2_admin_init', 'cmb2_movies' );
```

### Source Code
![carbon](https://github.com/CMB2/CMB2/assets/75655968/edb5a082-0403-4c22-9392-da0a36d2fbd1)

### File Structure
![image](https://github.com/CMB2/CMB2/assets/75655968/bfe8946a-bfd6-46e3-a1f1-d0fd811b44ce)

**Comment by tw2113** [comment]
Whatever methods are available to show meta data with FSE themes are going to need to be used here. CMB2 doesn't store anything in custom places, it's all still the `wp_postmeta`, `wp_termmeta`, `wp_usermeta`, and `wp_options` tables.

**Comment by Rizatzmi** [comment]
@tw2113 Can you give me example? Because im new in here

**Comment by tw2113** [comment]
I haven't attempted anything with post meta and full site editing myself, to be honest. So we'd both end up just googling at the same time.

Unsure if they've gotten to this point with FSE theming as well. They may not be fully done yet.
