### ISSUE TITLE
How to save fields generated by JS?

### ISSUE THREAD

**Issue by cawa-93** [CMB2/CMB2#1498]
My case is a bit complicated. I need to show a `<select>` for a list of posts. When the user selects a post, I need to load the meta fields of the selected post, analyze them, and display an array of additional fields (the exact number is not known) based on the analysis. 
And this process should be repeated every time the user selects a post in the select. Without reloading the page. 

According to the documentation, I could load all the data of all posts on the backend, generate several hundred fields for all existing posts, and on the frontend only switch their visibility depending on the selected post. However, I consider it too time-consuming.

I could use JS to keep track of the `<select>`, load all the data of the selected post only, generate and insert additional text fields. 

However, I don't understand how to make these additional text fields be saved on the backend in the database.

**Comment by tw2113** [comment]
Off the top of my head, I feel like you could register the select input with CMB2, so that all the IDs and name attributes and the like get generated, and then you could just switch out the `<option>`'s in the `<select>` as needed.

**Comment by cawa-93** [comment]
> Off the top of my head, I feel like you could register the select input with CMB2, so that all the IDs and name attributes and the like get generated, and then you could just switch out the `<option>`'s in the `<select>` as needed.

I need to generate not `<option>` inside `<select>`, but additional `<input>`. Something like so:

![image](https://github.com/CMB2/CMB2/assets/1662812/72b81686-0edd-4ac2-8fdf-529b78c17df5)

**Comment by tw2113** [comment]
I know the repo is kind of old, but I'm wondering if https://github.com/jcchavezs/cmb2-conditionals would still work for your usecase. I believe this one would have you registering the fields ahead of time and amount but which get shown is based on the selected value.

**Comment by cawa-93** [comment]
Yeah, it's truly works. 

I need register fields on backend, but not showing it
```php
$group_id = $cmb->add_field( [
	'id'         => 'url-params',
	'type'       => 'group',
	'show_on_cb' => '__return_false', // 👈🏻 never show
	'repeatable' => true,
] );

$cmb->add_group_field( $group_id, [
	'id'   => 'key',
	'type' => 'text',
] );


$cmb->add_group_field( $group_id, [
	'id'   => 'value',
	'type' => 'text',
] );
```

And then, in JS I just need to add some how some where `<input name="url-params[0][key]">` and `<input name="url-params[0][value]">` and after form send backend will save values from this custom inputs. Inportant is `name` attribute.
