### ISSUE TITLE
WP_Query with meta_query on a subfield within a group field CMB2

### ISSUE THREAD

**Issue by hamid7** [CMB2/CMB2#1502]
Hello, how can I use the wp_query to search in custom posts in WordPress and specifically utilize a field from a group in CMB2 during the search?
$args = array(
    'post_type'  => 'your_post_type',
    'meta_query' => array(
        array(
            'key'     => 'myGroup_myField', 
            'value'   => 'subfield_key', 
            'compare' => 'LIKE',
        ),
    ),
);

$query = new WP_Query( $args );

**Comment by tw2113** [comment]
https://wordpress.stackexchange.com/questions/16709/meta-query-with-meta-values-as-serialize-arrays

**Comment by hamid7** [comment]
So, in fact, it's better not to use postmeta grouping for custom post searches in WordPress. Is that correct?

**Comment by tw2113** [comment]
More a case of it's complicated thanks to the serialization aspect of it all, and it's not an issue exclusive to CMB2. The plugin just happens to store data at times in the same way.

**Comment by hamid7** [comment]
Is there a way to use wp_query on postmeta that is grouped, and since it is stored as an array, how can we access the fields within this grouping in CMB2 to use them in wp_query?
But in a plugin like ACF, this task is very easy to accomplish. Please check the link.
https://support.advancedcustomfields.com/forums/topic/quering-group-custom-field-with-user-object-in-post-loop/

**Comment by tw2113** [comment]
That ACF answer is very much like the answers/discussion at the StackOverflow link that I provided.

All that's getting saved to the meta field is a serialized array string, which is going to have both its perks and it's drawbacks. A drawback being how to do a meta query with information saved in the string.

There's nothing preventing you from doing a "LIKE" query compare with your data saved via CMB2, it's all stored the same way way by both CMB2 and ACF...serialized array string
