### ISSUE TITLE
No new releases

### ISSUE THREAD

**Issue by GitHub-Mike** [CMB2/CMB2#1506]
Why are there no more new releases? I couldn't find a reason for this.

**Comment by tw2113** [comment]
Just haven't had reason to just yet, though I believe we're still fully working with the latest WordPress at the moment.

**Comment by GitHub-Mike** [comment]
Thank you for the quick reply. I wasn't sure at first if the repo would continue to be maintained as I was used to the releases. But then I will use the develop branch in the future.
