### ISSUE TITLE
Looking for example about how to add a button that calls a PHP function w/o reloading the page

### ISSUE THREAD

**Issue by dfumagalli** [CMB2/CMB2#1507]
Hello,

I've created a plugin and on its settings page, I need to put a button that performs "PHP stuff" without reloading the page.
Basically, I need to do what many plug-ins do: put buttons in the middle of other settings that don't save settings but launch a custom PHP function.

As added bonus, I'd like that by pressing the button I could provide some visual feedback on-page, for example a string, progress bar or similar.

I know how to do all of this with AJAX without CMB2, but I have no idea about how to do it with this library. I've looked around for examples but there's little stuff (and outdated / very unclear).

I've also looked at CMB2's documentation but all I see are a lot of text fields but zero buttons (much less, with AJAX integration).

**Comment by tw2113** [comment]
There shouldn't be THAT much to adding some AJAX listening and whatnot, and most of the work is going to be done with the Javascript side where you're crafting the javascript to listen to the rendered form, and collect the parts needed.

For example, grabbing the ID on the submit button and doing any amounts of `e.preventDefault()` and then construct your `$.post({})` object, in my example for this reply, using jQuery. Don't forget the `action` property. Then on your PHP side, you'd do the `wp_ajax_` callbacks with that same action and process your PHP handling before returning a result that updates your UI appropriately.

Perhaps the confusion is in how to tie it all together, wherein there's actually nothing that special to be done, and most AJAX tutorials that tie things to a form apply.

**Comment by dfumagalli** [comment]
> There shouldn't be THAT much to adding some AJAX listening and whatnot, and most of the work is going to be done with the Javascript side where you're crafting the javascript to listen to the rendered form, and collect the parts needed.
> 
> For example, grabbing the ID on the submit button and doing any amounts of `e.preventDefault()` and then construct your `$.post({})` object, in my example for this reply, using jQuery. Don't forget the `action` property. Then on your PHP side, you'd do the `wp_ajax_` callbacks with that same action and process your PHP handling before returning a result that updates your UI appropriately.
> 
> Perhaps the confusion is in how to tie it all together, wherein there's actually nothing that special to be done, and most AJAX tutorials that tie things to a form apply.

Hello, I have created 2 CMB2 plugin options pages in my life, so I am not very proficient. Please allow me to explain myself better about this.

I'd have no big issue creating an HTML + PHP script to create a form, attach Javascript to the button and do the whole AJAX stuff.
Instead, I have an issue at how to create that same form with CMB2.

I am in the situation where I have an option page with 3-4 text boxes (with URL, a service port and so on) and it works.

Now, I need to add a button after these text boxes (and followed by others) that should call a PHP function that starts a WP Cron one shot event.

I know how to put the text boxes. I know how to save / load settings. I know how to start the WP Cron event. What I don't know is how to slap that button on the page with CMB2.

**Comment by tw2113** [comment]
Doesn't your creation of option pages output and create save buttons for you, that you could add event listeners to and do all the form field gathering stuff with? What I'm saying is use view source/inspector tools to look into what gets loaded on the options pages for you and use those. The only real difference would be that you're not creating the form markup yourself, the options API in WordPress is doing that part, you just need to handle the rest.

**Comment by dfumagalli** [comment]
I need the save functionality to work. The button would start an operation that does not save or load anything, it just checks a connection.

My option page is coded more or less like this:

`<div id="tabs-1" class="wrap">
			<?php
			$cmb = new_cmb2_box(
				array(
					'id'         => DT_TEXTDOMAIN . '_options-df-tva',
					'hookup'     => false,
					'show_on'    => array( 'key' => 'options-page', 'value' => array( DT_TEXTDOMAIN ) ),
					'show_names' => true,
					)
			);
                          ...
                        if ( function_exists( 'cmb2_get_option' ) ) {
				// Use cmb2_get_option as it passes through some key filters.
				$host_name = cmb2_get_option( 'df-tva-settings', 'df_tva_admin_memcached_host_name', 'localhost' );
				$port_number = cmb2_get_option( 'df-tva-settings', 'df_tva_admin_memcached_port_number', '11211' );
			} else {
                          ...

                        $cmb->add_field( array(
				'name' => __('Memcached host name', 'df-tva'),
				'id'   => 'df_tva_admin_memcached_host_name',
				'type' => 'host_name',
				'desc' => __('Invalid host names will be discarded.', 'df-tva'),
			) );

			$cmb->add_field( array(
				'name' => __('Memcached port number', 'df-tva'),
				'id'   => 'df_tva_admin_memcached_port_number',
				'type' => 'text_number',
				'desc' => __('Invalid port numbers will be discarded.', 'df-tva'),
			) );
                          ...

                        // HERE I NEED THE BUTTON
                        $cmb->add_field(
				array(
					'name' => esc_html__('Memcached active', 'df-tva'),
					'desc' => $memcached_description,
					'id'   => 'df_tva_admin_led_render_row_cb',
					'type' => 'text',
					'render_row_cb' => 'df_tva_admin_led_render_row_cb',
					'host_name' => $host_name,
					'port_number' => $port_number
				)
			);

                        cmb2_metabox_form( DT_TEXTDOMAIN . '_options-df-tva', DT_TEXTDOMAIN . '-settings' );
			?>
		</div>`

**Comment by jtsternberg** [comment]
To add a button, you can create your own custom field type. Lots of examples in the docs: https://github.com/CMB2/CMB2/wiki/Adding-your-own-field-types
and in the snippet library: https://github.com/CMB2/CMB2-Snippet-Library/tree/master/custom-field-types

I just added a sample custom button field type: https://github.com/CMB2/CMB2-Snippet-Library/blob/master/custom-field-types/button-field-type.php

![button-field-type](https://github.com/CMB2/CMB2/assets/1098900/c8e1aa00-1947-480d-8c30-bd58f5e9dcbc)


There's a bunch of ways this could be modified, depending on what you want. I'd encourage you to look through the docs examples and the snippet library if you want more modification.

**Comment by dfumagalli** [comment]
> To add a button, you can create your own custom field type. Lots of examples in the docs: https://github.com/CMB2/CMB2/wiki/Adding-your-own-field-types and in the snippet library: https://github.com/CMB2/CMB2-Snippet-Library/tree/master/custom-field-types
> 
> I just added a sample custom button field type to the snippet library: https://github.com/CMB2/CMB2-Snippet-Library/blob/master/custom-field-types/button-field-type.php
> 
> ![button-field-type](https://private-user-images.githubusercontent.com/1098900/299742402-c8e1aa00-1947-480d-8c30-bd58f5e9dcbc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyMDk5MTksIm5iZiI6MTcwNjIwOTYxOSwicGF0aCI6Ii8xMDk4OTAwLzI5OTc0MjQwMi1jOGUxYWEwMC0xOTQ3LTQ4MGQtOGMzMC1iZDU4ZjVlOWRjYmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjVUMTkwNjU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDJlYjhlOGFjYmI5NjU4NzliNjE0ZmM1ZjY1NzQ3YjA4NzRmZDgwODlhOTVjZjU1NTc5ZWYwYTMyZGVkNDQxMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1c_Gaacmt8XB94oG83mjoESp7fXyPWrJH714soUCGjw)
> 
> There's a bunch of ways this could be modified, depending on what you want. I'd encourage you to look through the docs examples and the snippet library if you want more modification.

Thank you so much! This is **exactly** what I needed. Thank you!
