### ISSUE TITLE
CMB2 plugin not working in Bitnami multiste wordpress instance, 

### ISSUE THREAD

**Issue by Tring-Jagannath** [CMB2/CMB2#1511]
## Describe the bug

We have installed CMB2 in Bitnami wordpress multi site env and network activated it.And then we have created theme options and cmb2 felds, when we open UI and admin page, filed are not working, mean file upload button are not working, group fields are not working. When we inspected the admin panel came to find that cmb2-min.css, cmb2.min.js showing 404 error.

exmaple: 
[http://35.180.52.158.nip.io/bitnami/wordpress/wp-content/plugins/cmb2/css/cmb2.min.css?ver=6.5.2
](url)
we can see that /bitnami/wordpress/ got added in the url, without that the file loads

example: 
[http://35.180.52.158.nip.io/wp-content/plugins/cmb2/css/cmb2.min.css?ver=6.5.2](url)

**Comment by jtsternberg** [comment]
Check out the url troubleshooting doc: https://github.com/CMB2/CMB2/wiki/Troubleshooting#cmb2-urls-issues

**Comment by Tring-Jagannath** [comment]
Thank you very much!, it's perfectly working now.
