### ISSUE TITLE
Issue with Wordpress 6.5

### ISSUE THREAD

**Issue by DenisPitcher** [CMB2/CMB2#1513]
When upgrading to wordpress 6.5.2 the following error message appears.

I have narrowed it down to being related to CMB2 and the localization changes introduced in 6.5

Has anyone else encountered this error?  Any ideas how to resolve it?

Fatal error: Uncaught TypeError: Argument 2 passed to WP_Translation_Controller::load_file() must be of the type string, null given, called in /home/customer/www/21square.com/public_html/wp-includes/l10n.php on line 838 and defined in /home/customer/www/21square.com/public_html/wp-includes/l10n/class-wp-translation-controller.php:101 Stack trace: #0 /home/customer/www/21square.com/public_html/wp-includes/l10n.php(838): WP_Translation_Controller->load_file('/home/customer/...', NULL, 'en_US') #1 /home/customer/www/21square.com/public_html/wp-content/plugins/resQwest/pageTemplate.php(118): load_textdomain(NULL, '/home/customer/...') #2 /home/customer/www/21square.com/public_html/wp-includes/class-wp-hook.php(324): pageTemplate->load_plugin_textdomain('') #3 /home/customer/www/21square.com/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array) #4 /home/customer/www/21square.com/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #5 /home/customer/www/21square.com/public_html/wp-set in /home/customer/www/21square.com/public_html/wp-includes/l10n/class-wp-translation-controller.php on line 101

**Comment by tw2113** [comment]
Not quite sure where CMB2 is factoring in here. From the looks of it, the problematic plugin is resQwest and a pageTemplate.php file.

**Comment by DenisPitcher** [comment]
Apologies, you're correct.  I had done some troubleshooting a few days ago and it was looking like CMB was the issue as the referenced plugin uses it but it looks like I was digging in the wrong direction.
