### ISSUE TITLE
Time picker blank in Chrome

### ISSUE THREAD

**Issue by gyrus** [CMB2/CMB2#1514]
In Chrome (124.0.6367.119) on Mac (14.4.1), when a time picker is clicked, the dialog initially appears blank. Inspecting, the list of times is actually there, it's just not visible until you click. That selects whatever time you clicked. Then, when you click on the field again, the dialog appears correctly.

This doesn't seem to be happening on Firefox or Safari. WP 6.5.3, CMB2 2.11.0. I've searched and can't find mention of this on jQuery UI bug reports.

<img width="699" alt="Screenshot 2024-05-08 at 16 04 18" src="https://github.com/CMB2/CMB2/assets/609161/1c01bffa-2d19-4696-8c50-d2c304d55a68">

**Comment by tw2113** [comment]
Any console errors showing up when you pull up google dev tools?

**Comment by gyrus** [comment]
No, no console errors.

**Comment by tw2113** [comment]
Can you provide your CMB2 configuration code for this, so we can see if we can recreate on our own?

**Comment by gyrus** [comment]
Thanks, hold off on this, I've found some other issues which might be clashing with it.

**Comment by gyrus** [comment]
This is related to a custom timepicker that was implemented some time ago in the project.
