### ISSUE TITLE
Repeater Drag and Drop

### ISSUE THREAD

**Issue by tannerm** [CMB2/CMB2#155]
Hey guys! Thanks for all the hard work here!!

I just wanted to check and see if there are any plans to make the repeater fields support drag and drop re-ordering.

**Comment by jtsternberg** [comment]
That is in the plans for sure, but we're planning on first refactoring the JS. I think once that is complete, adding drag/drop should be pretty straightforward.

**Comment by keepyourreceipt** [comment]
+1

**Comment by carasmo** [comment]
+1

**Comment by StaggerLeee** [comment]
+1

**Comment by carasmo** [comment]
+1

**Comment by aroscoe82** [comment]
+1

**Comment by widoz** [comment]
+1

**Comment by EldonYoder** [comment]
+1

**Comment by antonkor** [comment]
+1

**Comment by kishoresahoo** [comment]
+1

**Comment by JiveDig** [comment]
+1

**Comment by andymb** [comment]
+1

Any news on this? Thanks.

**Comment by tw2113** [comment]
Please use the reaction feature for showing support for this being touched on. Adding comments with "+1" and that's it muddles the issue and details about actual implementation.

**Comment by adriantoll** [comment]
Hi @tw2113 - is there a rough ETA for this? We could really use this feature and are thinking about hacking something together in the interim, but only want to do that if it's not something you guys are actively working on.

**Comment by tw2113** [comment]
Nothing I've heard of. Given Justin's comment above, help getting the javascript refactored would be the best first step to help get this more of a reality.

**Comment by adriantoll** [comment]
@tw2113 OK, thanks. It was because Justin's comment was 2.5 years old that I thought progress may have been made on that side of things - we'll see what we can do.

**Comment by rogerlos** [comment]
I have a small jQuery plugin which allows drag and drop sorting of repeatable fields. Not thoroughly tested just yet, but seems to work OK in my local build:

https://github.com/rogerlos/cmb-daggable-repeater

It does need to be invoked from another script:

```JavaScript
$( '.cmb-repeat' ).cmbDraggableRepeater();
```

**Comment by angelorocha** [comment]
+1 👍

**Comment by lipemat** [comment]
I submitted a [pull request](https://github.com/CMB2/CMB2/pull/1142) just now which adds this support. ^

**Comment by angelorocha** [comment]
Wow!!!! Great Job!

**Comment by tw2113** [comment]
From my end, I'd love to get various people testing this to make sure it's not getting any js console errors or issues with saving data at the end, before it gets merge in at all.
