### ISSUE TITLE
Feature Request - Taxonomy Radio / Check

### ISSUE THREAD

**Issue by estin1985** [CMB2/CMB2#322]
I would love to see an option to hide empty terms for the taxonomy field types.  It would be a real simple addition, and if you are open to it I will create a pull request.

**Comment by tw2113** [comment]
Closing as won't fix, despite some tinkering by myself late last week. The reason being is that it's already possible with current field arguments. See the following links. 

https://github.com/CMB2/CMB2/wiki/Field-Parameters#query_args

Example usage: https://github.com/CMB2/CMB2/wiki/Field-Types#taxonomy_select
