### ISSUE TITLE
Text Money Bug: if a text money field is left empty, when a post is saved it returns 0,00 as the value

### ISSUE THREAD

**Issue by monecchi** [CMB2/CMB2#457]
I've set up a repeatable group which is consisted of 4 fields, one of them is a  <strong>text money</strong> field and I've encountered what seems to be a bug, not sure though if anything on my set up or theme might be affecting the way the field should work.

I use a localized pt-BR (Brazilian Portuguese) language wp install, and initially I thought it could be something related to it. Could anyone confirm that the way the <strong>`function text_money()` - CMB2_Sanitize.php</strong> in the plugin's latest stable version will not reproduce this bug on a localized wordpress install? I've come across wordpress `function number_format_i18n` that can be seen here: https://core.trac.wordpress.org/browser/tags/4.3/src/wp-includes/functions.php#L172, but as I'm not a developer I simply can't read it to conclude if it is that which is causing the bug or not.

CMB2 is integrated within my theme and I've just updated to version 2.1.0. Everything works as expected, all field types seems to be working fine, but the <strong>text money</strong> field insists to return <strong>`0,00`</strong> as its value if the field is left empty when saving the post. I've tried to manually delete the value from the text money field and save the post again, but somehow the <strong>`0,00`</strong> pops up again as its default value.

It turns out that if I leave all the text money field blank, my site still echoes the  <strong>`0,00`</strong>...

Any chances to use an ordinary text field and have it formatted as number? Any help is really appreciated.

This is how I've set up my repeatable group:

```
 $cmb_group = new_cmb2_box( array(
      'id'            => $prefix . 'food_price_box',
      'title'         => __( 'Pricing Options', 'cmb' ),
      'object_types'  => array( 'food_menu' ),
      ) );

    // Parent
    $group_field_id = $cmb_group->add_field( array(
      'id'          => $prefix . 'food_price_group',
      'type'        => 'group',
      'options'     => array(
      'group_title'   => __( 'Price Box {#}', 'pivot' ), 
      'add_button'    => __( 'Add New Price Box', 'cmb' ),
      'remove_button' => __( 'Remove Price Box', 'cmb' ),
      'sortable'      => true, // beta
    ),

      ) );

    // Price Label
    $cmb_group->add_group_field( $group_field_id, array(
      'name' => __( 'Price Legend', 'cmb'),
      'desc' => __( 'Set a short legend for the price. e.g Small, Large, 4 slices, 500ml etc.', 'cmb'),
      'id'   => 'price_title',
      'type' => 'text_small',
      'repeatable' => true, // Repeatable fields are supported w/in repeatable groups (for most types)
      'options' => array( 'add_row_text' => __( 'Add New Legend', 'cmb' ) ),
      ) );

    // Price Label Description
    $cmb_group->add_group_field( $group_field_id, array(
      'name' => __( 'Price Description', 'pivot' ),
      'desc' => __( 'A very short description for the price legend.', 'cmb'),
      'id'   => 'price_desc',
      'type' => 'text_medium',
      'after_field'  => __( '<p><b>E.g.</b> "Serves up to 4 people", "Made with Premium Cheese" etc.</p>', 'cmb'),
      //'repeatable' => true, 
      ) );          

    // Price Amount
    $cmb_group->add_group_field( $group_field_id, array(
      'name' => __( 'Product Price', 'cmb' ),
      'desc' => __( 'Set the price for the item. Use , to separate decimals.', 'cmb'),
      'id'   => 'price_tag',
      'type' => 'text_money',
      'before_field' => 'R$', // override '$' symbol if needed
      //'repeatable' => true, 
      ) );

    $cmb_group->add_group_field( $group_field_id, array(
      'name' => __( 'Display Promotional Price?', 'cmb' ),
      'desc' => __( 'If you check yes it will be displayed on the price box.', 'cmb'),
      'id'   => 'check_promo',
      'type' => 'multicheck',
      'options' => array(
          'no' => 'Yes',
          'yes' => 'No',              
      ),
      ) );
```

**Comment by tw2113** [comment]
I'm going to close as tenatively fixed or limited in scope. We can revisit in the future, as needed.

It would/should be possible to provide a custom sanitization callback for the field as well, and roll your own version of money formatting, if really needed
