### ISSUE TITLE
Button Label for file meta type

### ISSUE THREAD

**Issue by widoz** [CMB2/CMB2#503]
Hi,

First of all thank you for the amazing plugin. 
I noticed that there is no way to change the button label for the file meta type when the post meta exists.

Currently the only label that appear is for upload an image/file even for change it. I know I can set a label like "Upload or Change" but will be more usable having two labels. One to upload an image/file if the post meta doesn't exists and another otherwise.

**Comment by tw2113** [comment]
Years later, I'm going to mark this as a closed issue. The reason being is that at the time of this posting, there is a `label_cb` parameter that is under-documented that can be used in replacement of the `name`  parameter. This allows for setting a function callback that can be used for conditional return values.

Example code below:

```
$cmb->add_field( array(
	'label_cb' => 'example_label_callback',
	'desc'      => esc_html__( 'Upload an image or enter a URL.', 'cmb2' ),
	'id'           => $prefix . 'image',
	'type'       => 'file',
) );
```

```
function example_label_callback() {
        // If we're adding new, just return a default
	if ( empty( $_GET['post'] ) ) {
		return 'Create';
	}

	// Otherwise we're going to have an ID in the URL.
	$post_id = absint( $_GET['post'] );

	$saved_value = get_post_meta( $post_id, 'image', true );

	if ( empty( $saved_value ) ) {
		return 'Create';
	}

	return 'Update';
}
```

This would allow for customizing the label based off of current meta data status, as per the original request. Beyond that, it's pretty much ready to be customizable in however one sees fit ways.
