### ISSUE TITLE
Dynamically created fields and saving them.

### ISSUE THREAD

**Issue by Daronspence** [CMB2/CMB2#568]
So I have a rather unique problem that may or may not be a problem with CMB2. If this is by design, then I have no issues using my solution if this isn't natively supported via the core plugin, but I don't think it is.

I have a CPT, and for each taxonomy term attached to the current post, I want to generate a field.

I have hacked this together using the below code...

``` php
if ( isset( $_REQUEST['post'] ) || isset( $_REQUEST['post_ID'] ) ) :

        $postID = isset( $_REQUEST['post'] ) ? intval($_REQUEST['post']) : false;
        $post_id = isset( $_REQUEST['post_ID'] ) ? intval($_REQUEST['post_ID']) : false;

        if ( $postID )
            $post = $postID;
        elseif ( $post_id )
            $post = $post_id;
        else
            return;

        $terms = wp_get_post_terms( $post, 'pwdynamic' );

        /**
         * Initiate the metabox
         */
        $cmb_dynamic = new_cmb2_box( array(
            'id'            => 'pwdynamic_' . get_post_type( $post ),
            'title'         => __( 'Dynamic Page Info', 'cmb2' ),
            'object_types'  => array( 'pwproperty' ), // Post type
            'context'       => 'normal',
            'priority'      => 'low',
            'show_names'    => true, // Show field names on the left
        ) );

        if ( $terms ) :
            foreach ( $terms as $term ){
                $cmb_dynamic->add_field( array(
                    'name'      => __( $term->name . ' WYSIWYG', 'cmb2' ),
                    // 'desc'   => 'field description (optional)',
                    'id'        => $prefix . 'dynamic_' . $term->term_id,
                    'type'      => 'wysiwyg',
                    'options'   => array()
                ) );
            }
        endif;
endif;
```

In terms of rendering, this works fine (though admittedly I wish it wasn't so hacky as CMB2 is initialized before the global `$post` object is present). 

I can type in the WYSIWYG. However, when I click save, the WYSIWYG is empty when the page reloads.

I believe this is happening because the `foreach` loop generating the fields isn't running when the page saves, so CMB2 is ignoring those fields.

In the meantime, I've utilized my own `save_post` function.

``` php
add_action( 'save_post', function(){
    global $post;

    if ( $post->post_type !== 'pwproperty' )
        return;

    foreach ( $_REQUEST as $key => $value ){
        $start = strpos( $key, 'pwproperty_dynamic_' );
        if ( $start !== false ){
            update_post_meta( $post->ID, $key, wp_kses_post( $value ) );
        }
    }
});
```

Since CMB2 fills the initial field value from a `get_post_meta()` call, the fields are now populated when the page reloads since the value exists in the database.

What I'm curious about is if there is a better way to go about this, or if this is functionality present in CMB2 already and I just missed it while reading the WIKI? I really have tried, but I can't find anything relevant :cry: 

Thanks for the great work you guys have done! It works great for 99.99% of people I'm sure! ;)

**Comment by rogerlos** [comment]
If you dynamically add non-wysiwyg fields, do they get saved?

**Comment by nclslbrn** [comment]
Same bugg occurs on checkbox field type, I try to generate metaboxes with an array of properties and a foreach loop, metaboxes are rendered well on the edit post page, values of these checkbox is on the global $_POST variable but nothing is stored in the database.

**Comment by jtsternberg** [comment]
Please review #805.

**Comment by jtsternberg** [comment]
Another similar issue: #395.

**Comment by nclslbrn** [comment]
Thank you, I will read this

**Comment by nclslbrn** [comment]
It seems that this bugg was caused by the function product_formula_td() (called by the 'render_row_cb' option) with deactivating it, the metabox values are stored in the database.

Thank you again

**Comment by jtsternberg** [comment]
Ok, 👍

**Comment by gitgrupoift** [comment]
I got the same problem and managed by hooking the CMB2 fields also on pre_get_posts, in addition to cmb2_init
