### ISSUE TITLE
Enhancements to color picker field

### ISSUE THREAD

**Issue by cluke009** [CMB2/CMB2#60]
I have a need for rgba color with my usage of this field and I would imagine others may need additional color spaces as well. It would be nice if could choose the format to use for colors in the options as well as alpha level.

So (hex, rgb, hsv) + alpha (are there others people regularly use?)

This field should probably be using the html5 input=[color] as well. 
There is a jquery plugin http://bgrins.github.io/spectrum/ it looks pretty robust. 

I would be willing to work on this if there is interest. Until then I will be adding this in as a custom field type for my project.

**Comment by jjessica** [comment]
I just stumbled upon your blog and wanted to say that I have really enjoyed reading your blog posts. Any way I’ll be subscribing to your feed and I hope you post again soon.<a href="http://www.design3i.com/school-web-design-uk/">web design for schools uk</a>
