### ISSUE TITLE
Programmatically adding a new value to a repeatable / group field?

### ISSUE THREAD

**Issue by dreiacht** [CMB2/CMB2#69]
Hello,

first of all thanks for this great plugin, I've used it in a lot of projects!

This is the first problem i've encountered that I just can't seem to figure out.

I have a group field with a repeatable text field and have to programmatically add new values to this group via PHP. Adding them via the admin panel is not an option. On normal fields it works great with add_user_meta / add_post_meta but how can I do this on a group field? I think I somehow will have to add the new value the group array but I have no Idea how to do that, I hope you can help me out!

Thanks in advance and sorry for the bad english, I hope you understand my problem.

**Comment by jimboobrien** [comment]
Thank you so much for posting this! Really helped me out a lot!

- Jim
