### ISSUE TITLE
Localize or apply_filters the jQuery UI date format.

### ISSUE THREAD

**Issue by tw2113** [CMB2/CMB2#73]
This is in regards to the `cmb2_l10` object and the `'dateFormat'      => __( 'mm/dd/yy', 'cmb2' ),` field. Setting a `date_format` for a field saves and initially displays the right format on load, but once a user invokes the datepicker again, it goes back to the hardcoded version.

It'd be awesome if we could provide this in the user's chosen date format if possible, or at least provide a filter around it for users to change.

**Comment by jhit** [comment]
Why not use the jQuery default translation mechanism here?
Add a language dependent JS file and set the datepicker.regional = 'de'
see http://api.jqueryui.com/datepicker/#option-dateFormat

As far as I understand the jQuery documentation it should be enough to include the regional JS file and set to *regional* property on the datepicker JS object.

You would still need the filter for the dateFormat, but setting all the translation strings could be skipped from the cmb2 filter.

**Comment by ajuliano** [comment]
Hi,

I had a similiar problem when language was set to Swedish. The month of september was set as undefined. I used the following to solve the problem:

`function ajuliano_custom_cmb2_date_format( $data ) {
	$data['defaults']['date_picker']['monthNamesShort'] = array( 'Jan', 'Feb', 'Mar', 'Apr', 'Maj', 'Jun', 'Jul', 'Aug', 'Sep', 'Okt', 'Nov', 'Dec' );

	return $data;
}
add_filter( 'cmb2_localized_data', 'ajuliano_custom_cmb2_date_format' );`
