### ISSUE TITLE
Sorting column Field Parameter

### ISSUE THREAD

**Issue by gorirrajoe** [CMB2/CMB2#831]
Is there a way to make the `column` field parameter (https://github.com/WebDevStudios/CMB2/wiki/Field-Parameters#column) sortable?

It'd be similar in functionality to the "Title" and "Date" table headers.

**Comment by tw2113** [comment]
I have to imagine it would be, but not necessarily through CMB2 itself. It'd be more akin to tutorials that have multiple parts. One part would be getting it added to the column list, the next part being making it sortable. CMB2 looks like it has the firs part covered, but not the second.

**Comment by jtsternberg** [comment]
It's not built in but something I'd like to eventually add, especially for certain field types which make sense to do so (date fields, checkboxes, text fields, etc).

**Comment by RubenMartins** [comment]
Hi, do you have update on this feature? Thanks

**Comment by tw2113** [comment]
Don't believe there's been any traction on this one yet.
