### ISSUE TITLE
Leading zero values not respected

### ISSUE THREAD

**Issue by gyrus** [CMB2/CMB2#869]
If a select is populated with, say, months, where leading zeros are added to numeric values (e.g. December is `12` but January is `01`) the correct value should be selected after saving.

However, this isn't the case. I think it's these lines in 2.2.4, `includes/types/CMB2_Type_Multi_Base.php:77`:

		if ( is_numeric( $value ) ) {
			$value = intval( $value );
		}

Is there a reason for this?

**Comment by jtsternberg** [comment]
Is there a particular field configuration that causes this for you?

**Comment by gyrus** [comment]
This is the field definition:

	$month_options = array( '00' => '[No month]' );
	for ( $m = 1; $m <= 12; $m++ ) {
		$month_options[ str_pad( $m, 2, '0', STR_PAD_LEFT ) ] = date("F", mktime(0, 0, 0, $m, 10));
	}
	$cmb->add_field( array(
		'name'				=> __( 'Written - month' ),
		'id'				=>  '_pilau_written-month',
		'type'				=> 'select',
		'options'			=> $month_options,
		'on_front'			=> false,
	) );

**Comment by timothyjensen** [comment]
I am having a related issue with the code that @gyrus referred to: https://github.com/CMB2/CMB2/blob/trunk/includes/types/CMB2_Type_Multi_Base.php#L81-L83.

My issue is that I'm dynamically populating the select options with Gravity Forms field IDs, so sometimes the value is a float, such as `1.3` (for example, the first-name field in a Gravity Form).  However, the code above converts the value from, say `1.3` to `1`.  CMB2 already does a good job of escaping the data before this point, so perhaps it's safe to remove the `intval()` function call on line 82.

**Comment by jtsternberg** [comment]
@timothyjensen since you have the optimal testing scenario, can you test by changing those lines to this:
```php
if ( is_numeric( $value ) ) {
	$value = is_float( $value ) ? floatval( $value ) : intval( $value );
}
```

**Comment by timothyjensen** [comment]
@jtsternberg Thanks for addressing this.  Unfortunately the code you suggested doesn't quite fix the issue.  I should have been more accurate in my previous description; the option value is saved as a string in the database. Because of that `is_float( $value )` returns false when retrieving the meta value.  Here's a screenshot of what I'm talking about: http://cloud.timj.us/0Q1r152U0u2d.

**Comment by jtsternberg** [comment]
Can you please test #1013?

**Comment by timothyjensen** [comment]
Works perfectly!

**Comment by timothyjensen** [comment]
Also tested #1013 with a leading zero value like @gyrus originally reported, and that issue is now resolved as well.

**Comment by jtsternberg** [comment]
I added some leading zero unit tests as well: https://github.com/CMB2/CMB2/commit/c2c4d4757f3f1657f493d2ef9e860ea5291975ca

Thanks for testing, i'll merge it in now.
