### ISSUE TITLE
Adding a field group below title moves Publish, Format etc metaboxes down to below default editing box

### ISSUE THREAD

**Issue by wpfan1000** [CMB2/CMB2#871]
### Expected Behavior:

Publish, Format etc metaboxes should be displayed in normal (top right) position on editing screen.

### Actual Behavior:

Adding a field group below title moves Publish, Format etc metaboxes down to below default editing box

With custom fields:
![cmb2 issue screen cap 1 - with custom fields](https://cloud.githubusercontent.com/assets/13694708/23467145/3ab81c8a-fe6b-11e6-9821-d1546a490d4c.jpg)
![cmb2 issue screen cap 2 - with custom fields](https://cloud.githubusercontent.com/assets/13694708/23467141/39c6b7f0-fe6b-11e6-8c0a-dacc7acd1cb6.jpg)

Without custom fields:
![cmb2 issue screen cap 3 - without custom fields](https://cloud.githubusercontent.com/assets/13694708/23467144/3aa9c856-fe6b-11e6-961b-b1c7e9ea45fb.jpg)

### Steps to reproduce (I have confirmed I can reproduce this issue on the trunk branch):

1.  Paste code below into a plugin
2.  Activate plugin

### CMB2 Field Registration Code:

```php
    $cmb = new_cmb2_box( array(
        'id'            => 'cmb2_content_fields',
        'title'         => __( 'CMB2 fields', 'cmb2' ),
        'object_types'  => array( 'page','post' ), // Post types
        'context'       => 'after_title', 
        'priority'      => 'high',
        'show_names'    => true, // Show field names on the left
        // 'cmb_styles' => false, // false to disable the CMB stylesheet
        // 'closed'     => true, // Keep the metabox closed by default
    ) );



    // ----------- Add text area fields


    $cmb->add_field( array(
        'name' => 'Test',
        'desc' => 'Test descrip',
        'id' => 'cmb2_content_writing_helper_field_mission',
        'type' => 'textarea'
    ) );

```

**Comment by jtsternberg** [comment]
Do you see the issue occurring for the other locations above the editor?  [`form_top`](https://developer.wordpress.org/reference/hooks/edit_form_top/), or [`before_permalink`](https://developer.wordpress.org/reference/hooks/edit_form_before_permalink/)?

**Comment by wpfan1000** [comment]
With form_top (no issue):
![form_top](https://cloud.githubusercontent.com/assets/13694708/23467802/012a03e6-fe6d-11e6-80a3-3a1d1b3da95e.jpg)

With before_permalink - exact same behaviour as after_title

**Comment by wpfan1000** [comment]
I am a complete amateur compared to you guys but as a possibility I have noticed this happening to me sometimes when I have an incomplete html closing tag eg </div (the > is missing) when modifying templates......

**Comment by jtsternberg** [comment]
hmm, that DOES look like a missing closing tag. Ok, i'll look into it.

**Comment by wpfan1000** [comment]
I just realized - regarding before_permalink - I had not saved the post and so no permalink field had yet been displayed - so it may look a little different then - sorry but at the moment I don't have the time to test.....

**Comment by proweb** [comment]
Same issue.
With textarea field `after_title`
```
function islam_speakers_metaboxes() {

	$prefix = '_kfuislam_';


	$cmb_demo = new_cmb2_box( array(
		'id'           => $prefix . 'metabox',
		'title'        => esc_html__( 'Информация по докладчику', 'cmb2' ),
		'object_types' => array( 'speakers', ), // Post type
		'context'       => 'after_title',
		'priority'      => 'high',
		'show_names'    => true, // Show field names on the left
	) );

	$cmb_demo->add_field( array(
		'name'       => esc_html__( 'Должность', 'cmb2' ),
		'id'         => $prefix . 'text',
		'type' => 'textarea',

	) );

}
```
![_008](https://cloud.githubusercontent.com/assets/680073/24138256/95f067c0-0e28-11e7-85b9-85a275ae8434.png)

**Comment by tw2113** [comment]
Can you test with a copy of the trunk branch from here on GitHub? If it's already been addressed , then it's going to be in that branch. Otherwise, a fix is still in the works.

**Comment by proweb** [comment]
@tw2113 downloaded trunk branch - bug still present 
https://www.useloom.com/share/fe990195610a4eabbf3387ac7e6988e8

**Comment by tw2113** [comment]
Noted, it's still an open issue pending fixed then. :) Keep an eye on this ticket for fixes that you could apply yourself when the time comes.

**Comment by jtsternberg** [comment]
This has been fixed (in trunk).
