### ISSUE TITLE
A way to add content before/after field based on field arg

### ISSUE THREAD

**Issue by rubengc** [CMB2/CMB2#876]
Revising documentation about how to create a custom fields and CMB2 code I am trying to setup a plugin that renders html before and after of a field if this has a parameter(s) defined

I am trying to do the same that wordpress publishing actions form (before publish button) with any CMB2 field, the workflow is really easy but I need to find a way to add content before/after any field

The problem is there is any hook before/after a field, so at this moment is impossible to make work correctly this plugin

Can someone with more deep knowledge with CMB2 help me?

**Comment by tw2113** [comment]
Just out of curiosity, have you tried providing some of these, in case they're applied to custom field types by users?

https://github.com/WebDevStudios/CMB2/wiki/Field-Parameters

I can't say for certain if they're always included regardless of source, but worth a try. Alternative thought would be to check the default field types and see how they implement these parts.

**Comment by rubengc** [comment]
I got this done using before/after parameters but I want to build a plugin where you get the html needed from a single parameter

**Comment by rubengc** [comment]
I see CMB2 has the actions `cmb2_before_form` and `cmb2_after_form`, exists the posibility to add similar actions for each field row? (`cmb2_before_field_row` and `cmb2_after_field_row`)

**Comment by tw2113** [comment]
Unless I'm mistaken, that would be covered in https://github.com/WebDevStudios/CMB2/wiki/Field-Parameters#before-after-before_row-after_row-before_field-after_field and `before_row`, `after_row`

**Comment by rubengc** [comment]
Yes, I know this parameters but I want to access this from a plugin and output html when user specifies a parameter in this fields, something like:

```php
// Field definition by an user that has my plugin and want to use on this field
$cmb->add_field( array(
    'name' => __( 'Field name', 'cmb2' ),
    'id'   => '_testing_a_plugin',
    'type' => 'text',
    'parameter_from_a_plugin' => true,
) );

// My plugin
add_action( 'cmb2_before_field_row', 'before_row', 10, 2 );
function before_row( $field_args, $field ) {
    if( isset( $field_args['parameter_from_a_plugin'] ) && (bool) $field_args['parameter_from_a_plugin'] ) {
        // Output html from plugin before row output
    }
}

add_action( 'cmb2_after_field_row', 'after_row', 10, 2 );
function after_row( $field_args, $field ) {
    if( isset( $field_args['parameter_from_a_plugin'] ) && (bool) $field_args['parameter_from_a_plugin'] ) {
        // Output html from plugin after row output
    }
}
```

**Comment by tw2113** [comment]
Is the field(s) being declared in its own plugin? Perhaps you could do an apply_filters in those parameter spots so that things can be added from the other plugin. Just throwing a quick idea out there. Otherwise I think your needs would need to be addressed in a future version.

**Comment by rubengc** [comment]
Check the plugin here: https://github.com/rubengc/cmb2-field-js-controls

I want to output this plugin content if user define `js_controls` parameter as bool true or as array not using `before_row` and `after_row` like in plugin example

Is possible to do this in current version of CMB2?

**Comment by tw2113** [comment]
Yeah, not seeing anything in the core code for php hooks that you could use or a way to provide custom field parameters like that, so until told otherwise, I think you may be out of luck with it at the current version.

**Comment by rubengc** [comment]
Oh, so, Is posible to add this filters? If you are ok with this hooks I can PR the changes

**Comment by tw2113** [comment]
I definitely encourage PRs for enhancements, but I don't have the final say for what will or won't get accepted. That's pretty much up to @jtsternberg here as he's the lead developer of CMB2 still.

**Comment by bradp** [comment]
Feel free to open a PR @rubengc, thanks.

**Comment by rubengc** [comment]
Nice! I will PR this changes this afternoon

**Comment by rubengc** [comment]
Both PRs has been merged, so let's close this issue
