### ISSUE TITLE
Call to undefined function cmb2_get_option() !

### ISSUE THREAD

**Issue by jimmyphong** [CMB2/CMB2#94]
im using cmb2 to creat admin theme option page with step
1. copy CMB2 folder to /wp-content/my-theme/inc/CMB2
2. creat option.php in /wp-content/my-theme/inc/option.php

3 in option.php code

if ( file_exists(  **DIR** .'/cmb2/init.php' ) ) {
    require_once  **DIR** .'/cmb2/init.php';
} elseif ( file_exists(  **DIR** .'/CMB2/init.php' ) ) {
    require_once  **DIR** .'/CMB2/init.php';
}

and code like this tutorial 
http://arushad.org/how-to-create-a-tabbed-options-page-for-your-wordpress-theme-using-cmb/

with call get option function
function myprefix_get_option( $key = '' ) {
    global $myprefix_Admin;
    return cmb2_get_option( $myprefix_Admin->key, $key );
}

and in my theme function.php request option.php;

all thing work fine , so when i call myprefix_get_option('my_field');

i get Call to undefined function cmb2_get_option() !

any help ? Thanks

**Comment by piya23300** [comment]
I found the same issure.
