### ISSUE TITLE
Date is not going to update in meta

### ISSUE THREAD

**Issue by baikaresandeep** [CMB2/CMB2#945]
Hi, 
I'm using `text_datetime_timestamp`  field type for date format but I want date as `DD/MM/YYYY` and time in 24 hrs format. But these fields are not updating in database. But before some days ago I was able to update it, don't know suddenly what happened?

```php
$inspection_option_page->add_field( array(
				'name' => __( 'Date of visit ', 'cmb' ),
				'desc' => __( 'Enter Date of visit(DD/MM/YYYY).', 'cmb' ),
				'id'   => '_ins_visit_date',
				'type' => 'text_datetime_timestamp',
				'time_format' => 'H:i',		
				'date_format' => 'd/m/Y',
			) );
```

 Can you just tell me the reason behind that? Can't I write both the format means `time_format` and `date_format`??

**Comment by tw2113** [comment]
Hi @baikaresandeep,

Can you please start a thread for this over at https://wordpress.org/support/plugin/cmb2 ? We're really trying to leave initial support for questions/issues there, and when we confirm bugs, we'll move things here to the issues list.

I am not aware of any sort of updates that were released in the pas few days, but any updates that you applied to your install may be playing a part. So any information you can add there for what was recently updated, could help out.

Thanks.

**Comment by baikaresandeep** [comment]
Thanks @tw2113 for reply. I have fixed this issue.

**Comment by tw2113** [comment]
Would you be willing to post the solution you found, in case someone stumbles across this GH issue with the same problem?

**Comment by baikaresandeep** [comment]
I was using the both format for date and time, I think that was issue. But when I removed `'time_format' => 'H:i',` it works for me.

I think both the format is not working with this field.

**Comment by tw2113** [comment]
gotcha, thanks :)
