### ISSUE TITLE
How to Call only 3 field in my form

### ISSUE THREAD

**Issue by Lekinio** [CMB2/CMB2#950]
### Expected Behavior:

hello

how to call only 3 field (image,album and map) in my front-end form??

**Comment by tw2113** [comment]
Hi @Lekinio,

Can you please start a thread for this over at https://wordpress.org/support/plugin/cmb2 ? We're really trying to leave initial support for questions/issues there, and when we confirm bugs, we'll move things here to the issues list.

With the thread you make, can you provide your CMB2 configuration code as well, and we'll proceed from there.
