### ISSUE TITLE
Repeatable group using cmb2_metabox_form saves only the first group

### ISSUE THREAD

**Issue by contactashish13** [CMB2/CMB2#951]
If I use a repeatable group on the "options-page" using cmb2_metabox_form, it is able to display/add/remove the groups but on saving it only saves the first group. 

I've checked the $_POST data in helper-functions.php cmb2_print_metabox_form method and it contains only the first group.

### Steps to reproduce (I have confirmed I can reproduce this issue on the trunk branch):

1. register cmb2 as per the code below
2. In a separate page, show the form using

```
cmb2_metabox_form("images", "images", array( 'cmb_styles' => true ) );
```
3. Add more than 1 group and Save
4. The page is reloaded with only the first group's values. The others are discarded/not saved.

### CMB2 Field Registration Code:

```php
add_action( 'cmb2_admin_init', 'yourprefix_register_demo_metabox' );
function yourprefix_register_demo_metabox() {

	$cmb = new_cmb2_box( array(
        'id'      => 'images',
        'hookup'  => false,
        'show_on' => array(
            // These are important, don't remove
            'key'   => 'options-page',
            'value' => array( 'images' )
        ),
	) );

	$group_id = $cmb->add_field( array(
		// Field Config...
	) );
$cmb->add_group_field( $group_id, ....);


	// Additional fields...
}
```

**Comment by tw2113** [comment]
@contactashish13 can you please start a thread over at https://wordpress.org/support/plugin/cmb2 and we'll get you taken care of there for initial support. We are striving to leave GitHub issues for confirmed bugs or enhancement ideas, while using the WordPress.org forums for initial support and general questions.

When you start the thread, please provide the entirety of the CMB2 config setup you're using, as well as all the code used elsewhere for this specific functionality. It'll help make sure we have all the information.

Thanks.
