### ISSUE TITLE
Putting boxes below title and above editor

### ISSUE THREAD

**Issue by riverofjanuary** [CMB2/CMB2#958]
Any way to do that with the `new_cmb_box` declaration? I know there are crazy hacks but I'm trying to implement the CMB2 framework in a plugin and I'd like a way to easily declare that a metabox sit *above* the main content editor.

**Comment by tw2113** [comment]
I'd check out this portion of the wiki https://github.com/CMB2/CMB2/wiki/Box-Properties#context Should cover what you're looking for.
