### ISSUE TITLE
Allow only image in file_list field

### ISSUE THREAD

**Issue by vucumbra** [CMB2/CMB2#959]
Hi
it's possibile to limit the upload only for image? and not for attachment too?
I have search in documentation but not found.

This feature is implemented or no?
Thx 
Regards

**Comment by anhskohbo** [comment]
Yes, you can do that by pass `query_args` option:

```php
$cmb->add_field( array(
	'name' => 'Test File List',
	'id'   => 'wiki_test_file_list',
	'type' => 'file_list',
        'query_args' => array( 'type' => 'image' )
```

**Comment by vucumbra** [comment]
Ah! Perfect
Have you a document where can i find the list with all query_args?
thx for your work This FRAMEWORK IS AMAZING!

**Comment by anhskohbo** [comment]
I read the source code and found that, actually `query_args` is passed on `wp.media` object in js: https://github.com/CMB2/CMB2/blob/trunk/js/cmb2.js#L207

I thinks it's should be list at here: https://github.com/CMB2/CMB2/wiki/Field-Types#file_list

And pls close the topic.

**Comment by vucumbra** [comment]
thx
