### ISSUE TITLE
frontend form and upload featured image

### ISSUE THREAD

**Issue by vucumbra** [CMB2/CMB2#960]
Hi
i have read your great documentation abount new form in frontend
https://webdevstudios.com/2015/03/30/use-cmb2-to-create-a-new-post-submission-form/

But only i have not understand how upload the featured image
Of course when i submit the form, that return this error becouse i not have this function

> Fatal error: Call to undefined function wds_frontend_form_photo_upload() 

In documentation you write

> You can see we’re using a helper function, wds_frontend_form_photo_upload, (which is just a wrapper for media_handle_upload). It’s not directly related to CMB2, so I won’t go over it here, but I’ll include it in the final code snippet.

But in the final code snipped i can't find

**Comment by tw2113** [comment]
You can find it here: https://github.com/CMB2/CMB2-Snippet-Library/blob/master/front-end/cmb2-front-end-submit.php#L234-L267 right at the very end.

Hope you're enjoying using CMB2.
