### ISSUE TITLE
easy way for customize css in form frontend? Bootstrap grid helper?

### ISSUE THREAD

**Issue by vucumbra** [CMB2/CMB2#961]
Hi
Witch is the easy way for customize css in form frontend?
I can put the shortcode's form but i like customize too field by field

i need to use the bootstrap grid for correctly place the fields in some responsive divs

thx

**Comment by tw2113** [comment]
Hey @vucumbra could you start a support thread over at https://wordpress.org/support/plugin/cmb2 for this. We strive to use that forum for the general support/questions and leave GitHub here for confirmed bugs and enhancements.

Thanks.

**Comment by vucumbra** [comment]
but this is general support.....i can't customize the field in frontend, but just put in shortcode.....please can u help me? exist some way for do this?
