### ISSUE TITLE
form in frontend problem with bootstrap and modal mode

### ISSUE THREAD

**Issue by vucumbra** [CMB2/CMB2#964]
hi
i have try to put a form from shortcode in a modal windows from boostrap
and there was some problem
1-textare in wysiwyg mode not work
2- upload single featured image not work type: file
3- upload multiple images not work

there was a bug/incompatiility
or is my error?
thx

if i put the same shortcode in normal post, they show correctly form and work as well

**Comment by tw2113** [comment]
Responding at https://wordpress.org/support/topic/form-in-frontend-and-modal-bootstrap-little-bug/

Will re-open if any confirmed bugs show up.
