### ISSUE TITLE
How install cmb_field_map?

### ISSUE THREAD

**Issue by vucumbra** [CMB2/CMB2#968]
Hi i have read in olderpost exist a way for include google map with cmb2
https://github.com/mustardBees/cmb_field_map/

but i have not understand how integrate/installation  this. Just put the folders into cmb2 directory?

thx

**Comment by tw2113** [comment]
Looks like that repo houses its own plugin, so download a copy of it and drop it into your plugins folder. Then it'll be activateable like every other plugin
