### ISSUE TITLE
Asset URLs incorrect in some circumstances

### ISSUE THREAD

**Issue by leewillis77** [CMB2/CMB2#980]
### Expected Behavior:
JS and CSS files loaded correctly. 

### Actual Behavior:
JS and CSS files produce 404s due to incorrect URL. 

### Steps to reproduce (I have confirmed I can reproduce this issue on the trunk branch):

I have the following folder structure:

- repo-wp-content
    - plugins
        - lookbooks
            - cmb2
- webroot
    - WordPress files
    - wp-content
        - plugins
            - lookbooks -> ../../../repo-wp-content/plugins/lookbooks

That is - cmb2 is installed under a plugin (lookbooks), which has been symlinked into the wp-content/plugins directory. Under this setup CMB_utils::get_url_from_dir() fails to produce the right path for cmb2 assets, e.g. 

http://example.com/www/sites/example/repo-wp-content/plugins/lookbooks/cmb2/css/cmb2.min.css
http://example.com/www/sites/example/repo-wp-content/plugins/lookbooks/cmb2/js/cmb2.min.js?ver=2.2.4

get_url_from_dir() is passed /www/sites/example/repo-wp-content/plugins/lookbooks/cmb2/ which is the absolute path to the files.

It tries to turn this into a URL but is unable to as it does not find WP_PLUGIN_DIR (/www/sites/example/webroot/wp-content/plugins) in the path to replace with WP_PLUGIN_URL leading to the file path being output as a URL.

**Comment by tw2113** [comment]
Please review this and let us know if it helps resolve your issue: 
https://github.com/CMB2/CMB2/wiki/Troubleshooting#cmb2-urls-issues

**Comment by leewillis77** [comment]
Hi; 

Yes, I can fix it with a filter. I only raised it to see if it was something that could be fixed "properly" without people having to override the behaviour in a filter. From the history (sorry those issues never came up for my search!) it looks like it's been agreed that there's no way CMB2 can always get this right. 

Happy to close & thanks for the quick reply!

**Comment by tw2113** [comment]
Nature of the beast with it being able to be from potentially many different sources. Glad this will work well enough for your though. Thanks Lee.
