### ISSUE TITLE
CMB2 strips too many slashes

### ISSUE THREAD

**Issue by leewillis77** [CMB2/CMB2#981]
### Expected Behavior:
Data is saved, and retrieved as entered

### Actual Behavior:
If the following data is entered into a text field:

```[{"content":"This is a \"some\" content"}]```

What will be saved, and retrieved out of the database when accessed is:

```[{"content":"This is a "some" content"}]```

Note that slashes have been over-zealously removed. The data should be retrieved as-is without modification. 

### Steps to reproduce (I have confirmed I can reproduce this issue on the trunk branch):

1. Register a standard text field, e.g. as per the example.

```
$cmb_demo->add_field( array(
	'name'       => esc_html__( 'Test Text', 'cmb2' ),
	'desc'       => esc_html__( 'field description (optional)', 'cmb2' ),
	'id'         => $prefix . 'text',
	'type'       => 'text',
) );
```

2. Enter the following into the field:

```[{"content":"This is a \"some\" content"}]```

3. Save the entity. Note that what gets stored, and retrieved is:

```[{"content":"This is a "some" content"}]```

instead of

```[{"content":"This is a \"some\" content"}]```

*Note:* While I've reported this as an issue with the "text" type, the original bug I observed was with a custom field, within a repeatable group, so any fix probably needs to be generic across all field types, not just text.

**Comment by leewillis77** [comment]
I looked at #655 before I raised this which seems related - although opposite :)

**Comment by leewillis77** [comment]
The issue seems to be that CMB2_Sanitize strips slashes from the data - https://github.com/CMB2/CMB2/blob/trunk/includes/CMB2_Sanitize.php#L40

However, when fields are saved the (already stripped) value is passed to update_metadata which expects slashed, not unslashed data:

Ref:
https://github.com/CMB2/CMB2/blob/trunk/includes/CMB2_Field.php#L368
https://core.trac.wordpress.org/browser/tags/4.7.3/src/wp-includes/meta.php#L163 

Presumably (from the comments on #655) there's a difference between fields which are going into options (which expects raw data), and those which are going into metadata (which expects slashed data). 

Calling wp_slash() on the value before calling add/update_metadata in CMB2_Field::update_data() resolves the issue for me but I don't know the codebase well enough to determine if that's a better approach that not unslashing it in the first place until we know where it's going?

**Comment by leewillis77** [comment]
To clarify - here's the changes I'm running locally which "WorkForMe"[tm]

https://gist.github.com/leewillis77/55ac1e12b53b367f1009a0f38a0071ad

**Comment by jtsternberg** [comment]
To be clear, this is not a specific issue with CMB2, and can be reproduced by simply calling update_post_meta with your value:

```php
$meta_val = '[{"content":"This is a \"some\" content"}]';
update_post_meta( get_the_ID(), 'some_meta_key', $meta_val );

$meta = get_post_meta( get_the_ID(), 'some_meta_key', true );
echo '<xmp>$meta: '. print_r( $meta, true ) .'</xmp>';

// Prints: [{"content":"This is a "some" content"}]
```

This is because WordPress itself calls `wp_unslash` inside of `update_meta_data`: https://github.com/WordPress/WordPress/blob/master/wp-includes/meta.php#L167 

So I'm a bit hesitant to make this change across the board, as I am not positive of what unintended consequences there may be. Any thoughts on that?

**Comment by leewillis77** [comment]
Hi Justin; 

I'm afraid it *is* a CMB2 issue.

Your example is flawed since you're manually assigning an unslashed value to `$meta_val`. Essentially reproducing the fault with what CMB2 is doing. If you pulled the data from `$_POST` then it would be slashed, e.g.

```[{\"content\":\"This is a \\\"some\\\" content\"}]```

not

```[{"content":"This is a \"some\" content"}]```

As an example, if I manually create a metabox with the following code then it works as expected.

```
<?php

class Test {

	public function run() {
		add_action( 'add_meta_boxes', array( $this, 'add_meta_boxes' ) );
		add_action( 'save_post', array( $this, 'save_info' ) );
	}

	public function add_meta_boxes() {
		add_meta_box(
			'input-test',
			'Input test',
			array( $this, 'input_test' ),
			'post',
			'side',
			'low',
			null
		);
	}

	public function input_test( $post ) {
		if ( ! empty( $post->ID ) ) {
			$cur = get_post_meta( $post->ID, 'my-input-test', true );
		} else {
			$cur = '';
		}
		?>
		<input type="text" name="my-input-test" value="<?php echo esc_attr( $cur ); ?>">
		<?php
	}

	public function save_info( $post_id ) {
		if ( empty( $_POST['my-input-test'] ) ) {
			return;
		}
		update_metadata( 'post', $post_id, 'my-input-test', $_POST['my-input-test'] );
	}
}
```

I understand the hesitancy to make these sort of changes, however I do think they're necessary. The changes I gave in https://gist.github.com/leewillis77/55ac1e12b53b367f1009a0f38a0071ad work for me - although it seems inefficient to unslash everything, and then re-slash it if it's going to a _metadata() call. It may be the least impactful fix though.

**Comment by jtsternberg** [comment]
Also, I understand this is a question/issue/bug report regarding CMB2 core, but if you are looking to correct this for a single field, you can do so with the `'sanitization_cb'` field parameter: 

```php
$cmb->add_field( array(
	'name'            => __( 'Test Text', 'cmb2' ),
	'id'              => '_yourprefix_demo_text',
	'type'            => 'text',
	'sanitization_cb' => 'sanitize_text_field',
) );
```
Which means it's bypassing the `CMB2_Sanitize` stuff. So yah, it might make sense to move the `stripslashes_deep` from `CMB2_Sanitize::__construct()` to `CMB2_Options::set()` instead so that it only applies to non-meta data.

**Comment by jtsternberg** [comment]
Ok, can you test trunk?

**Comment by jtsternberg** [comment]
Looking at the commit history, @clifgriffin introduced this in 337874f46dd70dd43e7b29a9d8faa10501e0f48f to address something with magic quotes, it looks like? Clif, do you recall what the issue was?

**Comment by leewillis77** [comment]
Hey Justin; 

Trunk WorksForMe[tm] after your change. Note - I'm only dealing with postmeta values here, I can't verify it works properly for other items.

**Comment by clifgriffin** [comment]
@jtsternberg I don't remember the specifics, but essentially WordPress core forces magic slashes for all form data. This is to provide consistency. 

So stripping slashes universally should be safe.

However, if the data is pre-slashed I could see an issue. This is obviously a non-standard use case. 

Perhaps we just need a filter that lets people override this behavior for specific scenarios?

**Comment by leewillis77** [comment]
> So stripping slashes universally should be safe.

That's the point. It's not. The _metadata() functions expect to receive slashed data from a FORM, not unslashed data. So if your form data is going to end up in one of the _metadata() functions you either need to not unslash it yourself, or re-slash it before calling those functions. 

> However, if the data is pre-slashed I could see an issue. This is obviously a non-standard use case.

I'm not sure how it's non-standard?

**Comment by clifgriffin** [comment]
@leewillis77 It appeared you were entering pre-slashed serialized data into a text field. That's what seems non-standard.

Your note on the `_metadata()` functions is really interesting. It makes me wonder why this change was necessary in my implementation as it was certainly being stored in post meta or the like. 

(I wish my memory of two years ago was better)

**Comment by jtsternberg** [comment]
@clifgriffin i think we got the slash puzzle worked out. I mainly pulled you in as your commit message referenced magic quotes, not slashes. So I am hoping that rings a bell for you and maybe you recall something specific to that.

**Comment by leewillis77** [comment]
Aha. I get you.

It's actually JSON-encoded rather than slashed, so I guess that is a bit unique-to-me, but the bug could affect anything where slashes were important (struggling to think of an example!!)

**Comment by clifgriffin** [comment]
@jtsternberg How did you fix it out of curiosity?

Sounds like we need some unit tests. NOT IT.

**Comment by jtsternberg** [comment]
@leewillis77 the most important example: `¯\_(ツ)_/¯`
@clifgriffin see https://github.com/CMB2/CMB2/issues/981#issuecomment-307113546 and https://github.com/CMB2/CMB2/commit/c325d63aee8c36095c66564d56d24c40f96ccd99
Also, we have a ton of unit tests, and they all pass with both solutions (which means I should create a test that fails using the old method...), but I guess we'll have to wait and see if anyone runs into a magic quotes issue.
