### ISSUE TITLE
file_list Insert from URL

### ISSUE THREAD

**Issue by rubengc** [CMB2/CMB2#983]
Wordpress media frame has an optional menu to insert media from URL (oembed), to make it possible you need to set up `wp.media` instance with parameter `frame: 'post'`

CMB2 does not pass any parameter so frame has his default value `frame: 'select'` which is impossible to access to the "add from URL" option

One problem I found setting `frame: 'post'` is the addition on three new menus (image gallery. audio playlist and video playlist) which is possible to someone do not want to add this option

To take the full control of how the wp.media frame will work, is possible to extend from some of this frames (select or post) and customize it exactly in the way we want

There is a post talking about this (custom frames) on stackexchange:
https://wordpress.stackexchange.com/a/94326

**Comment by rubengc** [comment]
Digging on CMB2 internals I found there is an javascript event to override the `media` frame

A new issue appears with a wrong asignment of the javascript variables 

I am trying to change a specific field modal with the parameter `frame: 'post'` to enable the option "Insert from URL" but modal var is not well assigned and makes the first time the media modal is opened with the default paratemers instead with my own (the second time, modal has been updated successfully)

Explanation:

At cmb2.js, in `_handleMedia` function there is where the problem comes:
```javascript
	cmb._handleMedia = function( formfield, isList ) {
                // code code code ...

		// Create the media frame.
		media.frames[ media.field ] = modal = wp.media( {
			title: cmb.metabox().find('label[for="' + media.field + '"]').text(),
			library : media.fieldData.queryargs || {},
			button: {
				text: l10n.strings[ isList ? 'upload_files' : 'upload_file' ]
			},
			multiple: isList ? 'add' : false
		} );

		cmb.trigger( 'cmb_media_modal_init', media );

		// code code code ...

		// Finally, open the modal
		modal.open();
	};
```

In `cmb_media_modal_init` event I am able to modify `media` variable, but not `modal`

A way to fix it and keep backward compatibility is:
```javascript
	cmb._handleMedia = function( formfield, isList ) {
                // code code code ...

		// Create the media frame.
		media.frames[ media.field ] = wp.media( {
			title: cmb.metabox().find('label[for="' + media.field + '"]').text(),
			library : media.fieldData.queryargs || {},
			button: {
				text: l10n.strings[ isList ? 'upload_files' : 'upload_file' ]
			},
			multiple: isList ? 'add' : false
		} );

		cmb.trigger( 'cmb_media_modal_init', media );

                // Assign modal after trigger cmb_media_modal_init event
		modal = media.frames[ media.field ];

		// code code code ...

		// Finally, open the modal
		modal.open();
	};
```

**Comment by jtsternberg** [comment]
In chrome, I am not seeing that issue. If I do the following, it sets the object property on both variables, `media.frames[ media.field ]` _and_ `modal` as they are both simply references to the object.

```js
jQuery( function( $ ) {
	$( document ).on( 'cmb_media_modal_init', function( evt, media, cmb ) {
		media.frames[ media.field ].test = 'testing';
	} );
});
```

I suppose it's possible it may work differently in different browsers?

But if you're looking to pre-init a frame instance, you can already do that manually via something like this:

```js
jQuery( function( $ ) {
	$( document ).on( 'cmb_init', function( evt, cmb ) {
		var fieldId   = '_yourprefix_demo_image'; // The ID of the field whose frame you want to modify.
		var fieldData = $( '#' + fieldId ).data();
		var isList    = true; // true if 'file_list', false if 'file'

		// Pre-init our specific frame
		cmb.media.frames[ fieldId ] = wp.media( {
			title: cmb.metabox().find('label[for="' + fieldId + '"]').text(),
			library : fieldData.queryargs || {},
			button: {
				text: window.cmb2_l10.strings[ isList ? 'upload_files' : 'upload_file' ]
			},
			multiple: isList ? 'add' : false
		} );
	} );
});
```

**Comment by jtsternberg** [comment]
The 2nd solution I posted is the only way you'll be able to modify the `frame` attribute, because that attribute is used within the `wp.media` function to determine which type of frame object to create. You could also just stomp out the existing object with your own created frame.

**Comment by jtsternberg** [comment]
Ok, after playing with this even more, it became apparent what you were saying/asking for. As of 229213a241a1c049c5ba1c47aa176823ea6a9b21, this should be good.

**Comment by rubengc** [comment]
Thanks @jtsternberg you rocks

**Comment by mclblock** [comment]
Hi
Sorry to bring this one back but I'm struggling to get this to work. When I try to overwrite `media.frames[media.field].frame` to 'post' it doesn't change the view of the modal as `media.frames[media.field]` was already instantiated to an object with a call to `wp.media`. 
In my case running the suggested code won't enable the 'Import from URL' feature.

Here's my JS:
````
jQuery(function ($) {
	$(document).on('cmb_media_modal_init', function (evt, media, cmb) {
		media.frames[media.field].modal.frame = 'post';
	});
});
jQuery(function ($) {
	$(document).on('cmb_media_modal_init', function (evt, media, cmb) {
		media.frames[media.field].modal.frame = 'post';
	});
});
````
Any pointers would be greatly appreciated.
Thanks
