### ISSUE TITLE
Should taxonomy_select work with $cmb->get_sanitized_values using cmb2 in front end form?

### ISSUE THREAD

**Issue by yeahsmaggy** [CMB2/CMB2#988]
### Expected Behavior:

doing   $sanitized_values = $cmb->get_sanitized_values( $_POST );

recognises my taxonomy related fields.

### Actual Behavior:

doing   $sanitized_values = $cmb->get_sanitized_values( $_POST );

on  a $_POST with

```
(
    [object_id] => fake-object-id-edit-user-profile-form
    [nonce_CMB2php_cmb_page_edit_user_profile] => 67a843e229
    [_cmb_page_edit_user_profile_salutation_select] => miss
    [_cmb_page_edit_user_profile_first_name_text] => Andrew1
    [_cmb_page_edit_user_profile_last_name_text] => Welch
    [_cmb_page_edit_user_profile_email_text] => awelch@asdf
    [_cmb_page_edit_user_profile_job_role_text] => Developer
    [_cmb_page_edit_user_profile_business_phone_number_text] => 234
    [_cmb_page_edit_user_profile_mobile_phone_number_text] => 234
    [_cmb_page_edit_user_profile_summary_textarea] => adsfasd fasd fas da a fsdaf sd
    [_cmb_page_edit_user_profile_skills_autocomplete_multi] => 
    [_cmb_page_edit_user_profile_team_taxonomy_select] => all-staff
    [_cmb_page_edit_user_profile_team_taxonomy_radio] => all-staff
    [_cmb_page_edit_user_profile_test_name_text] => ddd
    [submit-cmb] => Update Your Details
)



```
only returns array:
```
(
    [_cmb_page_edit_user_profile_salutation_select] => miss
    [_cmb_page_edit_user_profile_first_name_text] => Andrew1
    [_cmb_page_edit_user_profile_last_name_text] => Welch
    [_cmb_page_edit_user_profile_email_text] => awelch@asdf
    [_cmb_page_edit_user_profile_job_role_text] => Developer
    [_cmb_page_edit_user_profile_business_phone_number_text] => 234
    [_cmb_page_edit_user_profile_mobile_phone_number_text] => 234
    [_cmb_page_edit_user_profile_summary_textarea] => adsfasd fasd fas da a fsdaf sd
    [_cmb_page_edit_user_profile_test_name_text] => ddd
)

```

### Steps to reproduce (I have confirmed I can reproduce this issue on the trunk branch):

1. use the code here https://webdevstudios.com/2015/03/30/use-cmb2-to-create-a-new-post-submission-form/ 
2. add a taxonomy_select field 
3. compare $_POST to   $sanitized_values = $cmb->get_sanitized_values( $_POST );

**Comment by tw2113** [comment]
Hi @ yeahsmaggy.

My biggest question here is if you're expecting the field type to save the taxonomy information as if it was meta data for the post. Looking things over, that almost feels like the case. The taxonomy_* field types are meant to be replacements for the WordPress default meta boxes for categories/tags/taxonomies. Thus, I'm wondering if that's playing a part in expected return vs actual.

Also, just in case needing to dig in more, can you please provide all the code you're using for this? I know and realize you said "use the code from our frontend submission" post, but you also added more after that, that I'd want to have that part exactly as is for you where it's not returning as expected.

**Comment by yeahsmaggy** [comment]
@tw2113 thanks for the reply and thanks for the awesome code and hard work. Yes you are absolutely correct which is something I worked out. It does actually make sense for me to save the taxonomy on the user object anyway rather than as meta. Either I could do and I can also use the standard select with an option_cb to load the taxonomy terms. 

The only difference is that I am using the code for an edit profile page. I'll clean it up and post it somewhere.

**Comment by tw2113** [comment]
Sounds good. For what it's worth, for initial feeling things out and such, let's use https://www.wordpress.org/support/plugin/cmb2. I monitor that area as well, and offer support the best I can. We try to keep GitHub for confirmed bugs or new enhancement ideas.

Thanks.

**Comment by yeahsmaggy** [comment]
Absolutely mate will do.
