### ISSUE TITLE
Changelog shows wrong event name

### ISSUE THREAD

**Issue by JiveDig** [CMB2/CMB2#991]
https://github.com/CMB2/CMB2/blob/trunk/CHANGELOG.md#enhancements-16

Shows `cmb_add_row` and `cmb_remove_row` when they are really `cmb2_add_row` and `cmb2_remove_row`. Was hitting a wall during development until I realized I was using the wrong event!

**Comment by tw2113** [comment]
@jtsternberg thoughts on this one? Given that it's 3 years old at this point?

**Comment by jtsternberg** [comment]
Well, the changelog entry is accurate, as that feature was introduced pre-cmb2, and so those hook/event names were accurate. See https://github.com/CMB2/CMB2/commit/f6e320f.

Ideally, we need a wiki page about interacting w/ the JS stuff, and the available events.

**Comment by jtsternberg** [comment]
Closing though, as issue is not actually an issue.

**Comment by JiveDig** [comment]
Wiki would be great. I was doing all custom JS then thought maybe I should see if CMB has any events built in, and sure enough there is! The only way I found was a search that returned the changelog. Either way, those events are super helpful 👍

**Comment by jtsternberg** [comment]
It's a start!
https://github.com/CMB2/CMB2/wiki/Javascript-API
