### ISSUE TITLE
Problem width Group Field and wysiwyg editor

### ISSUE THREAD

**Issue by all2aller** [CMB2/CMB2#992]
I've created field verses in a group, but I know that problems with the wysiwyg editor in the front end do not show the < p > paragraphs but only the < ul > tags and other tags.

I've added the wpautop feature but still does not show the paragraphs.

How can I fix it?

**Comment by tw2113** [comment]
Hey @all2aller can you please start a support thread for this over at https://wordpress.org/support/plugin/cmb2 and we'll get things looked at there?

Also if you could provide all relevant config and template code that you're using, that'll help out a lot more.

We strive to leave the GitHub issues area for confirmed bugs or enhancement ideas, and use the support forum for initial support.
