### ISSUE TITLE
problem display metabox in template page

### ISSUE THREAD

**Issue by harabidi** [CMB2/CMB2#997]
hello, 
i have a problem with displaying group metabox, my template page ="test.php" exist in the same functions.php folder 
this is my code :

```
add_action( 'cmb2_init', 'domaine_register_repeatable_group_field_metabox' );
function domaine_register_repeatable_group_field_metabox() {
  global $post;  
  $pageTemplate = get_post_meta($post->ID, '_wp_page_template', true);
  $prefix = 'domaine_';

  if($pageTemplate == 'test.php' ){
    $cmb_group = new_cmb2_box( array(
        'id'           => $prefix.'cmb_demo',
        'title'        => esc_html__( 'Repeating Field Group', 'cmb2' ),
        'object_types' => array( 'page', ),
	  	'show_on'      => array( 'key' => 'pageTemplate', 'value' => 'test.php' ),
		 
		'context'      => 'normal', //  'normal', 'advanced', or 'side'
		'priority'     => 'high',  //  'high', 'core', 'default' or 'low'
		'show_names'   => true, // Show field names on the left
    ) );
    $group_field_id = $cmb_group->add_field( array(
        'id'          => $prefix . 'demo',
        'type'        => 'group',
        'description' => esc_html__( 'Generates reusable form entries', 'cmb2' ),
        'options'     => array(
            'group_title'   => esc_html__( 'Dossier de compétence {#}', 'cmb2' ), // {#} gets replaced by row number
            'add_button'    => esc_html__( 'Add Another Entry', 'cmb2' ),
            'remove_button' => esc_html__( 'Remove Entry', 'cmb2' ),
            'sortable'      => true, // beta
            // 'closed'     => true, // true to have the groups closed by default
        ),
    ) );
    $cmb_group->add_group_field( $group_field_id, array(
        'name'       => esc_html__( 'Entry Title', 'cmb2' ),
        'id'         => 'title',
        'type'       => 'text',
    ) );
    $cmb_group->add_group_field( $group_field_id, array(
        'name'       => esc_html__( 'Votre Métier', 'cmb2' ),
        'id'         => 'title2',
        'type'       => 'text',
    ) );
    $cmb_group->add_group_field( $group_field_id,array(
        'name'     => esc_html__( 'Selectionner votre domaine', 'cmb2' ),
        'desc'     => esc_html__( 'field description (required)', 'cmb2' ),
        'id'       => $prefix . 'taxonomy_select',
        'type'     => 'taxonomy_select',
        'taxonomy' => 'job_listing_category', // Taxonomy Slug
    ) );
    $cmb_group->add_group_field( $group_field_id, array(
        'name'        => esc_html__( 'Description', 'cmb2' ),
        'description' => esc_html__( 'Write a short description for this entry', 'cmb2' ),
        'id'          => 'description',
        'type'        => 'textarea_small',
    ) );
    $cmb_group->add_group_field( $group_field_id, array(
        'name' => esc_html__( 'Entry Image', 'cmb2' ),
        'id'   => 'image',
        'type' => 'file',
    ) );
}  }
```

**Comment by tw2113** [comment]
Hey @harabidi can you please start a forum thread over at http://wordpress.org/support/plugin/cmb2 with this same information? We strive to leave Github for confirmed bugs and enhancements, while using WordPress.org for the initial support questions.

Thanks.

**Comment by mamunur105** [comment]
This is Working well 


$value = isset($_GET['post']) ? get_post_meta($_GET['post'], '_wp_page_template', true ) : '';

// $value = get_post_meta($post_id, '_wp_page_template', true ); 
if ($value == 'page-templates/weekend.php') {
	// echo "string";
	add_action( 'cmb2_admin_init', 'slider_metabox' );
	function slider_metabox(){
		$cmb = new_cmb2_box( array(
			'id'           => 'thingsto-do',
			'title'        => 'Menual Slider',
			'object_types' => array( 'page' ), // post type
			'context'      => 'normal', //  'normal', 'advanced', or 'side'
			'priority'     => 'high',  //  'high', 'core', 'default' or 'low'
			'show_names'   => true, // Show field names on the left
		) );
		$group_field_id = $cmb->add_field( array(
			'id'          => 'cat_slider_group_field',
			'type'        => 'group',
			'description' => __( 'Menual Page Slider', 'cmb2' ),
			
			'options'     => array(
				'group_title'   => __( 'Entry {#}', 'cmb2' ), 
				'add_button'    => __( 'Add Another Entry', 'cmb2' ),
				'remove_button' => __( 'Remove Entry', 'cmb2' ),
				'sortable'      => true, // beta
				
			),
		) );
		// Id's for group's fields only need to be unique for the group. Prefix is not needed.
		$cmb->add_group_field( $group_field_id, array(
			'name'    => 'Slider Image',
			'desc'    => 'Upload an image or enter an URL.',
			'id'      => 'things_slider__image',
			'type'    => 'file',
			'options' => array(
				'url' => false, // Hide the text input for the url
			),
			'text'    => array(
				'add_upload_file_text' => 'Upload/Select Slider Image' // Change upload button text. Default: "Add or Upload File"
			),
			// query_args are passed to wp.media's library query.
			'query_args' => array(
				// 'type' => 'application/pdf', // Make library only display PDFs.
				// Or only allow gif, jpg, or png images
				'type' => array(
					'image/gif',
					'image/jpeg',
					'image/png',
				),
			),
			'preview_size' => 'large', // Image size to use when previewing in the admin.
		) );
		$cmb->add_group_field( $group_field_id, array(
			'name' => 'Title ',
			'id'   => 'slider_section_title',
			'type' => 'text',
		) );
	
		 
	}

	
}
